### ISSUE TITLE
Not able to download certain stories from ffn and ao3 due to utf8 error 

### ISSUE THREAD

**Issue by klackerz** [JimmXinu/FanFicFare#100]
These are the url

https://www.fanfiction.net/s/8379655/1/Hogwarts-Battle-School

The error codes are 

Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.jobs", line 180, in do_download_for_worker
  File "calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer", line 227, in writeStory
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 369, in getStory
  File "calibre_plugins.fanficfare_plugin.fanficfare.htmlcleanup", line 83, in removeEntities
  File "encodings/utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xef in position 3936: invalid continuation byte

I am also getting the same error codes for certain other stories both from ffn and ao3.  For eg this fic does not even start the job. 'https://www.fanfiction.net/s/7287278/49/Harry-Potter-and-the-Forests-of-Valbon%C3%AB' 

These are certain other urls for which I am not able to download.
https://www.fanfiction.net/s/7354757/1/
https://www.fanfiction.net/s/11115934/1/
https://www.fanfiction.net/s/11120132/1/
https://www.fanfiction.net/s/11027086/1/

Using calibre 2.27, fanficfare 2.24, Linux Mint

**Comment by JimmXinu** [comment]
I'm not able to duplicate this problem with calibre on Win8 or with CLI on CentOS6.  I don't have a Linux Mint available to test with.

I've seen at least one report that ffnet was having problems with their service yesterday/last night.

Is this an ongoing problem that you can duplicate?

**Comment by klackerz** [comment]
Yes this is a ongoing problem for me. I can download the stories from the website and update the metadata using the plugin. But the metadata update will fail if the story title has some special characther like in Harry Potter and the Forests of Valbonë.

I just installed fanficfare cli version and it's working without any issues while downloading the above fic,  So this seems to be a problem with the plugin or my calibre install.

**Comment by JimmXinu** [comment]
I've tried these stories on Linux Mint 17.1 with calibre 2.27(64bit) and FanFicFare 2.2.5.  They all worked fine for me.

Also, you describe the problem in the first post and in your later post quite differently.  First you said it was failing during the metadata collection phase preventing download.  Then you later said you could download, but it failed updating calibre's metadata.

There's nothing I can find to fix with what I know so far.  

Do you use calibre in a language other than English?  Additional debug logs (from running calibre in debug mode while downloading) may help.

**Comment by klackerz** [comment]
I meant I could download the stories when I use the fanficfare website or the cli version,then add it to calibre and then update the metadata. This will only work if there are no special characters in the metadata.  I am not able to download these story using the plugin probably because it contains some special character somewhere in the story text.

For the other stories, I am able to download them using website or the cli, but updating metadata fails in the plugin. Eg For any Pokémon fics.

I will add the calibre debug soon.

**Comment by klackerz** [comment]
Here is the pastebin of the  debug while trying to download a story.
http://pastebin.com/xGTFX04c

**Comment by JimmXinu** [comment]
I've posted a [test version](http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025) that might help with your problem by catching an additional exception.

Let me know if works any better for you.

**Comment by klackerz** [comment]
It's working perfectly now without any issues. Tried with a variety of stories which are downloading fine.

Thanks for the fix.

**Comment by JimmXinu** [comment]
Great, but I actually a branch version with some extra stuff that's not ready yet.  I've updated it now.  Would you mind getting the current [test version](http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025) again and making sure it still works?  
Thanks.

**Comment by klackerz** [comment]
This version is also working for me without any trouble. Thanks again.

**Comment by JimmXinu** [comment]
Excellent.  Thanks for helping figure this out.
Fixed in d59a1bda1a9b8ad6444d4658c065f6ebd4f88b5a
Will be included in next release.
