### ISSUE TITLE
Updating Stories with sequel stories instead of creating a new one

### ISSUE THREAD

**Issue by slyferrain** [JimmXinu/FanFicFare#1000]
When downloading at least two different stories from Literotica, the URL and story was updated instead of creating a new story. 

An example: https://www.literotica.com/s/quaranteam-ch-01-10 is adding the Book 2 and putting the chapters before the first story. 
Second is https://www.literotica.com/s/just-the-six-of-us-ch-01

**Comment by JimmXinu** [comment]
For Literotica, there isn't a separate story URL or page, so FFF uses the first chapter URL as the story URL.

Those authors have chosen to insert a "second book" *at the start* of an existing story.  

As far as the Literotica site and FFF are concerned, there's no difference between that and adding a Prologue or Preface chapter at the start after the fact.  You'd have to take it up with the authors.

I would suggest turning on FFF's `mark_new_chapters` feature.
```
## If true, when updating an epub that already has old chapters, new
## chapters will be marked in the TOC and chapter header by using
## chapter_title_new_pattern and chapter_title_addnew_pattern to set
## the chapter title.
## If set to latestonly, only new chapters downloaded this time will
## be marked (new) and existing chapters will have any (new) marks
## removed.
##
## mark_new_chapters can be true, false or latestonly
mark_new_chapters:true
```
