### ISSUE TITLE
Can't get 'Updated' column to work

### ISSUE THREAD

**Issue by Victor239** [JimmXinu/FanFicFare#1001]
In this issue https://github.com/JimmXinu/FanFicFare/issues/915 I saw the 'Updated' column method mentioned, but I can't seem to replicate it. 

This is my 'Updated' custom column:
![image](https://github.com/JimmXinu/FanFicFare/assets/12621257/a86ff07c-125c-41ed-b7ff-f910027c77de)

But the column stays blank, except for one single book which has today's date.

I also tried to update some entries to see if that would get others to update. I kept `Update Calibree Metadata` blank as I didn't want it changing my tags,  and the new checkbox `Background Metadata` doesn't seem to have any more info about it in the [wiki page](https://github.com/JimmXinu/FanFicFare/wiki/UpdateModes) so I left it blank also.

![image](https://github.com/JimmXinu/FanFicFare/assets/12621257/8ec523eb-24ad-4838-9170-c9ebee5998b5)

I did get an error message when updating these entries, and none of their 'Updated' columns changed. 

![image](https://github.com/JimmXinu/FanFicFare/assets/12621257/37527b83-a38a-4ec2-8645-78e7545aee57)

**Comment by JimmXinu** [comment]
1. If you have `Update Calibre Metadata` unchecked, FFF doesn't update your Calibre metadata--including custom columns such as the `#updated` column.  You can check the 'New Only` option for Tags on the Standard Columns tab to not change those.
2. You tried to do `Update EPUB if Newer Chapters`, presumably none of those books had more chapters.  Do 'Update EPUB Always' or 'Update Calibre Metadata Only` instead.

As a general rule, GitHub issues are for problems with the software.  Questions like this are best posted to the [Mobile Read FFF Plugin thread](https://www.mobileread.com/forums/showthread.php?t=259221).

**Comment by Victor239** [comment]
Ah, I see. Thanks, with these changes it's now working as expected :)

Apologies, it's been some time since I used this plugin so I wasn't aware.
