### ISSUE TITLE
[Fiction.live] Error downloading images

### ISSUE THREAD

**Issue by Jemeni11** [JimmXinu/FanFicFare#1004]
If a Fiction.live image has a URL starting with `https://cdn3.fiction.live/images/` or `https://ddx5i92cqts4o.cloudfront.net/images/`, downloading that image fails. 
It looks like they've switched to `https://cdn6.fiction.live/file/fictionlive/images/` as their new image hosting path.

So something like this should work:
```py
elif url.startswith("https://cdn3.fiction.live/images/") or url.startswith("https://ddx5i92cqts4o.cloudfront.net/images/"):
    logger.warning("Converting url to cdn6. This might fail.")
    url = f"https://cdn6.fiction.live/file/fictionlive/images/{url.split('/images/')[-1]}"
```

I would have made a pull request but I'm wary of breaking anything 😐

**Comment by JimmXinu** [comment]
Example story URL?  I don't read that site.

**Comment by JimmXinu** [comment]
After poking at the site's javascript a while, I think I've isolated the cdn URL replacement code:
```
(e=e.replace(/(\w+)\.cloudfront.net/g,"cdn6.fiction.live/file/fictionlive")
 .replace(/www\.filepicker\.io\/api\/file\/(\w+)/g,"cdn4.fiction.live/fp/$1"),
 e=e.replace(/cdn4.fiction.live\/(.+)/g,"cdn6.fiction.live/file/fictionlive/$1")
 .replace(/cdn3.fiction.live\/(.+)/g,"cdn6.fiction.live/file/fictionlive/$1"))
```
There's some more complexity related to `thumb` images that looks for a half dozen specific image widths that I'm going to ignore because we don't know the image sizes.

Test versions posted.

**Comment by JimmXinu** [comment]
FYI, this should also address #933.

**Comment by JimmXinu** [comment]
Assumed fixed.
