### ISSUE TITLE
ScribbleHub download broken

### ISSUE THREAD

**Issue by anotherwaytolive** [JimmXinu/FanFicFare#1005]
When attempting to download story from ScribbleHub calibre pops up with "None of the 1 URLs/stories can be/need to be downloaded", with error log saying "HTTP error in FFF '403 Client Error: forbidden for url: scribblehub link"

**Comment by JimmXinu** [comment]
My notes show that it's not uncommon to need to use the [Proxy Feature](https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures) and flaresolverr to download from ScribbleHub now.

**Comment by anotherwaytolive** [comment]
> My notes show that it's not uncommon to need to use the [Proxy Feature](https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures) and flaresolverr to download from ScribbleHub now.

Will check it out. Thanks.
