### ISSUE TITLE
use_flaresolverr_proxy:directimages 403 cover Failures

### ISSUE THREAD

**Issue by Funtime60** [JimmXinu/FanFicFare#1009]
I've had a few cases where use_flaresolverr_proxy:directimages on scribblehub fails for the covers, but as far as I can tell all other images do work as one of them is used in place of the cover.

Here is an example that failed for me.
https://www.scribblehub.com/series/121448/giant-robot-reincarnation/

This one worked first try though.
https://www.scribblehub.com/series/852237/azure-orphans/

I'm wondering if perhaps the first image fails occasionally, which just happens to be the cover image? I which case attempting to load an image multiple times might resolve it? I'm not sure how to confirm this theory though.

**Comment by JimmXinu** [comment]
Scribblehub story cover images are hosted on cdn.scribblehub.com.  Embedded images are generally hosted on some other site and linked by the author in the story text.

The main point of the `use_flaresolverr_proxy:directimages` is to allow download of those images on other sites when using flaresolverr to access scribblehub for the story text. Cover images from cdn.scribblehub.com working at all is a bonus and honestly not something I expected to work.

That said, I get the cover image for that first story to download--after first accessing the story in browser.  I suspect that cdn.scribblehub.com runs a lower level of blocking than the story chapters etc.  We've seen other sites where viewing something in the site in browser first will allow downloading to work.

So: if it works, great.  If it doesn't, I don't know of anything else that could be done about it.

**Comment by Funtime60** [comment]
I see, thanks for the explanation. Makes perfect sense. I'll see if I can come up with a work around myself before I make another issue.
