### ISSUE TITLE
Storiesonline.net/n/

### ISSUE THREAD

**Issue by xOverbaked** [JimmXinu/FanFicFare#1016]
ran into a story starting with storiesonline.net/n/ today really odd have not seen any other stories using /n/ yet but something to watch out for. all the other stories in that series starts with /s/
https://storiesonline.net/n/25243/variation-on-a-theme-book-5

**Comment by JimmXinu** [comment]
Already addressed in 893345dc335eb872caa7e6d70becdb58940c383e  Test versions are up in the usual places.
