### ISSUE TITLE
[Bug] Specific SpaceBattles Thread Giving NoneType Object Decompose Error

### ISSUE THREAD

**Issue by dastrdly6585** [JimmXinu/FanFicFare#1017]
OS: Windows 10
FFF: Latest test version
Calibre: 7.0

I am getting an odd error message for the below specific SpaceBattles thread and it is refusing to update. I was able to successfully pull the fic just two days ago.

Status: Error
Title: It's an Abyss, not bottomless
Author: DisgruntledJaeger
Comment: 'NoneType' object has no attribute 'decompose'
URL: https://forums.spacebattles.com/threads/its-an-abyss-not-bottomless-kancolle-si.1064792/

**Comment by JimmXinu** [comment]
Looks like a site change.  Test versions up in the [usual places](https://github.com/JimmXinu/FanFicFare#test-versions).
