### ISSUE TITLE
Less than signs in threadmark titles on Sufficient Velocity not being escaped.

### ISSUE THREAD

**Issue by HowardJeng** [JimmXinu/FanFicFare#1019]
Possibly related to #863.

With 4.29.0, a less than sign in a chapter title for the thread https://forums.sufficientvelocity.com/threads/brocktons-celestial-forge-worm-jumpchain.70036/ on Sufficient Velocity isn't being escaped properly in the generated xhtml. Chapter title is `The Biggest D#<k Move (Setbyrust)` at post https://forums.sufficientvelocity.com/threads/brocktons-celestial-forge-worm-jumpchain.70036/post-18093348. The generated xhtml leaves the unescaped less than in the title and meta fields.

Another chapter in the same thread has a paired less than and greater than sign (`<AGREEMENT> (Ziggrrauglurr)`, https://forums.sufficientvelocity.com/threads/brocktons-celestial-forge-worm-jumpchain.70036/post-25114890) and that seems to be interpreted as a tag which gets removed. Ex: in the toc.ncx the text for the navpoint is `Apocrypha -  (Ziggrrauglurr)` stripping out the `<AGREEMENT>` entirely.

**Comment by JimmXinu** [comment]
I see what's happening here, and it is basically the same problem as #863.  I think I've done a better job of addressing it this time.  Test versions in the usual places.
