### ISSUE TITLE
No connection to flaresolverr

### ISSUE THREAD

**Issue by sdiehl1966** [JimmXinu/FanFicFare#1024]
FFF v4.30.0
FFF doesn't connect to flaresolverr anymore.
Error is always:
`Connection to flaresolverr proxy server failed.  Is flaresolverr started?`
flaresolverr ist running and responding via cli

**Comment by JimmXinu** [comment]
Works fine for me with [FlareSolverr v3.3.12](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.12) on win10.  Nothing in FFF's FlareSolverr support has changed anytime recently.

I would speculate that you have a firewall blocking the connection, or a mismatch on the connection IP.  

By default, FlareSolverr listens to all addresses and FanFicFare looks for it on `localhost` aka 127.0.0.1.

**Comment by sdiehl1966** [comment]
Ah, sorry for this. I forgot to check the Flaresolverr logs. It seems to have been a bug there (was still v3.3.11, when I tested yesterday) or CF changed something again. It received the requests but timed out afterwards. After updating to 3.3.12 it works again.
What threw me off was the error-message about 'Connection failed'.
Btw Flaresolverr is running in a Docker container on a virtual machine, so no localhost unfortunately, but no firewall problems between Calibre and the Docker host and it works quite well (until it doesn't) ;-).
