### ISSUE TITLE
Cannot download from Royal Road

### ISSUE THREAD

**Issue by Shaitan051** [JimmXinu/FanFicFare#1025]
'NoneType' object has no attribute 'text'

**Comment by JimmXinu** [comment]
Story URL?  Debug output?

**Comment by Shaitan051** [comment]
https://www.royalroad.com/fiction/41760/the-quest-of-words

[tmp5950s668.txt](https://github.com/JimmXinu/FanFicFare/files/13806948/tmp5950s668.txt)

**Comment by JimmXinu** [comment]
I'm not seeing that error.  

Probably because your version of FanFicFare is a test version from May 2022.  There have been site changes since, then.  Please update to the latest version.
