### ISSUE TITLE
browsercache_blockfile(Chromium) SuperFastHash Wrong for Some Keys

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#1026]
Opening issue to record the details of this issue and fix.  

We've had occasional reports of certain URLs not working with BrowserCache for sometime, but I've never been able to isolate the problem before.

From this [initial problem report](https://www.mobileread.com/forums/showthread.php?p=4387708&postcount=9178) I was able to isolate that the SuperFastHash implementation we were using wasn't correctly hashing 
`1/0/_dk_https://fanfiction.net https://fanfiction.net https://www.fanfiction.net/s/14295569/20/Devil-May-Cry-The-Lightning-Thief` to `0x16403ce8`, arriving at `0xe7f02702` instead.

Why it was wrong for that one value but not any other chapter URLs in the story, or indeed, the vast majority of URLs used with it, I couldn't say.  My knowledge of bit manipulation in Python isn't up to the task.

But swapping in a different SuperFastHash implementation appears to work.  Now using https://github.com/vperron/python-superfasthash

This problem and fix only apply to Chromium browsers, and only those using blockfile cache.

**Comment by rajeshbalan** [comment]
This has fixed the issue with this story.. Thanks! :-)
