### ISSUE TITLE
RoyalRoad Inserting Invisitext Into Chapters

### ISSUE THREAD

**Issue by Chirishman** [JimmXinu/FanFicFare#1028]
Some time in the last week or so Royal Road started inserting "this work has been stolen" paragraphs with what looks like some kind of randomly generated alphanumeric class tag to hide them with CSS.

I've seen authors manually slip these into their works before when they're having issues but as far as I'm aware this is the first time I'm seeing it inserted **by the site itself**. I twigged that this was the site and not the authors when I noticed that the message was word-for-word identical in new chapters of stories by different authors. Interestingy the location where the watermark message appears in a given chapter seems to be deterministic even if the class tag value is randomized.

It's irritating when listening to the stories via TTS especially since it occurs at least once in every chapter but it's not unusable if nothing is changed. I'm not sure if you'll want to write a defeat for this or just mark it as known but either way here's what I've found:

As viewed in a normal browser

![image](https://github.com/JimmXinu/FanFicFare/assets/7658840/80e37a0e-bbf6-4a44-b00e-449a99f5c8a8)

As seen when inspecting the source of an individual chapter in a browser

![image](https://github.com/JimmXinu/FanFicFare/assets/7658840/417f0798-a720-4c5e-a4ea-158a12840798)

![image](https://github.com/JimmXinu/FanFicFare/assets/7658840/18fef8b1-77fe-45d5-a467-2f02bab7cf65)

and the source of the same snip of the resulting ebook

![image](https://github.com/JimmXinu/FanFicFare/assets/7658840/5bd83bf4-a2d4-491b-a43b-a811fdca73d4)

**Comment by JimmXinu** [comment]
Story URL so I can see it?

**Comment by Chirishman** [comment]
> Story URL so I can see it?

Those screenshots are from [this story](https://www.royalroad.com/fiction/65765) but like I said it appears to be sitewide. It is present in every new chapter that I've downloaded in the last 24 or 48 hours including all of these:

https://www.royalroad.com/fiction/77821
https://www.royalroad.com/fiction/63759
https://www.royalroad.com/fiction/77820
https://www.royalroad.com/fiction/47826
https://www.royalroad.com/fiction/63762

All by different authors, all with identical injected text with a randomized class name in the `<p>` tag that rolls over every time the page is loaded fresh.

**Comment by JimmXinu** [comment]
I'm reluctant to implement a solution for this because I agree that authors shouldn't have their works published by others.  And as such things go, this is very innocuous.

Technologically, finding all paragraphs containing a fixed string and removing them is easy.  Until that string or tag is changed, that is.  Then it could become an escalating race of change and counter change.

FYI, in my TTS reader, that paragraph is read aloud even with `display:none` on the tag.

**Comment by Chirishman** [comment]
I agree on all points. I feel ambivalent a solution here too given the relative innocuousnes.

On a technical level I don't expect it to actually achieve much in the way of stopping the content theft in the long term, especially since the actual content of the message isn't randomized in any way so it's super easy for a bad actor to find and replace.

Mostly what it's going to do for my personal reading workflow is cause me to start tracking the copies of stories on SpaceBattles and Scribblehub instead of RR for the ones that are crossposted.

I mostly wanted to bring it to your attention so that there would be a record of it here so it's clear it's a `[Known Issue/Won'tFix]` when other people notice it. It's also worth being aware of as a possible start of a trend of RR changes that might follow, and if they increased the frequency of the insertion to more times per chapter or something the decision might need to be revisited.

And yes, TTS still reading it even when hidden by CSS has been my experience too.

**Comment by JimmXinu** [comment]
Fair enough.

I'm going to leave this issue open, for the increased visibility.

**Comment by MrTyton** [comment]
Just an FYI, there are multiple strings that they are adding with it - it's not the exact same text every time. I am weird about this as well - it is definitely _annoying_ to me, but it's probably healthier for the ecosystem.

**Comment by LDShadowLord** [comment]
Agreed with @MrTyton - It's most likely healthier for those authors using the platform, but it's highly irritating.
And they enter the scenario where thieves will still find a way around it, so it just begins to harm "regular" users.

I've noticed that beside increasing the variability of the messages, they are also now putting a class onto every single <p> tag in the code, to make it more difficult. Currently it can be curated out as only 1 of those <p> tags has a class within the <head> style tag that says "display:none".

**Comment by grenskul** [comment]
All this does is irritate the people using tts and other accessibility function .
I say that if this does turn into a game of cat and mouse we should go as often as they do . I very much doubt they'll go nuclear and this causes a significantly worse experience specially to the disabled.
As of right now you have a solution to the current implementation . I say merge it ( or remake it and merge cause my code is pretty terrible) and if they change how it works , just keep patching fixes.

**Comment by Edocsil** [comment]
Or just ignore it? It's not the end of the world to have that one line in
the chapters, you can easily clean them up yourself after downloading if
you really care, there's no reason for FFF to fight RR over this.

And if this is affecting people with a disability while reading on the
website, then it should be reported to RR. That's it.

**Comment by Chirishman** [comment]
They are now inserting text inline in existing paragraphs and without spaces after periods, making the accessibility/TTS impact worse 🙄

![image](https://github.com/JimmXinu/FanFicFare/assets/7658840/b15294b3-cf57-4240-bf22-c63c445af5f7)

![image](https://github.com/JimmXinu/FanFicFare/assets/7658840/9c9740a9-b865-4c51-a2a3-809a61d92fc3)

**Comment by grenskul** [comment]
> They are now inserting text inline in existing paragraphs and without spaces after periods, making the accessibility/TTS impact worse 🙄
> 
> ![image](https://private-user-images.githubusercontent.com/7658840/299398632-b15294b3-cf57-4240-bf22-c63c445af5f7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTkxMTIsIm5iZiI6MTcwNjExODgxMiwicGF0aCI6Ii83NjU4ODQwLzI5OTM5ODYzMi1iMTUyOTRiMy1jZjU3LTQyNDAtYmYyMi1jNjNjNDQ1YWY1ZjcuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE3NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNWRiYjY3OGJlNTg2OWU3NzRhOGEwMzU4YzRiMTdiYjkxYzExMTY0ZjI3ODJmZGIzMmU2MjE0MTQzNTNjMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Utoa2FckpVoKViF2DyfGis8vbGtJY7Zwmc1b4nqj8g)
> 
> ![image](https://private-user-images.githubusercontent.com/7658840/299398733-9c9740a9-b865-4c51-a2a3-809a61d92fc3.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTkxMTIsIm5iZiI6MTcwNjExODgxMiwicGF0aCI6Ii83NjU4ODQwLzI5OTM5ODczMy05Yzk3NDBhOS1iODY1LTRjNTEtYTJhMy04MDlhNjFkOTJmYzMuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE3NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYTg1ZDIwNTc0MTQ4YjA2MDZlYjYzZjE4NTgyYzZmOWQzOTA1ZDIyMDM1NmU1ZGIxNDhjZmMzNWM5YjVkMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PlGKQg4hNIVUtC3zr9dWKP7JsIpWxHCCCCS4X_t87Lg)

The pr in limbo still catches these btw.

**Comment by JasonGross** [comment]
> I'm reluctant to implement a solution for this because I agree that authors shouldn't have their works published by others. And as such things go, this is very innocuous.
> 
> Technologically, finding all paragraphs containing a fixed string and removing them is easy. Until that string or tag is changed, that is. Then it could become an escalating race of change and counter change.
> 
> FYI, in my TTS reader, that paragraph is read aloud even with `display:none` on the tag.

What about (at least) a middle road of keeping enough information around that it's possible for users who want to do post-processing to handle this?  Right now, it seems that `display: none` is stripped from the css styling, and so there's no way to inspect the resulting epub and determine which blocks were hidden.  Could the plugin at least keep all the `display: none` mappings in the css file it generates for the epub?  (Or am I mistaken and it's just that "update epub" does not regenerate the css file, but if I redownloaded the book from scratch I'd get an updated css?)

**Comment by JimmXinu** [comment]
As a general rule, FFF discards site styling in favor of consistent styling (as customized by the user) for all stories and sites.

Since this has been stable for a week, I've merged @grenskul's PR(#1031) and uploaded test versions in the usual places.

**Comment by MrTyton** [comment]
The fix isn't working for me - Tested with https://www.royalroad.com/fiction/61228/i-will-touch-the-skies-a-pokemon-fanfiction


```
python3.9 -m fanficfare.cli -u "royalroad.com/fiction/61228" --update-cover --non-interactive

```
```
python3.9 -m fanficfare.cli --version
Version: 4.30.6
```

**Comment by JimmXinu** [comment]
Hmm.  I don't read RoyalRoad, so I didn't test it myself.  

Probably has to do with that CSS class also containing `speak: never;` now.  @grenskul?

**Comment by grenskul** [comment]
Changed the regex for the new style . I made it thinking about possible minor changes so anything they do using this style method can be beaten within minutes by anyone that knows basic regex.
Made the PR

**Comment by JimmXinu** [comment]
#1033 merged in, test versions posted again.

**Comment by MrTyton** [comment]
Test version seems to work now. Thanks.

**Comment by TheOne320** [comment]
So this appears to still happen.
I just downloaded this series:
https://www.royalroad.com/fiction/78230/magical-girl-platinum

and in the the downloaded file it keeps repeating the text:
"This work was stolen from Magical Girl Platinum on Royal Road. Please message me there."

The text is not there in the normal browser page.
