### ISSUE TITLE
[Feature request] Add support for literotica series

### ISSUE THREAD

**Issue by tholley7** [JimmXinu/FanFicFare#1029]
In the list of supported sites, literotica is listed but the URL examples are all for individual stories. I would like to add series as one book to Calibre.

**Comment by JimmXinu** [comment]
The FanFicFare Calibre plugin already has a feature to make an Anthology book from multiple story URLs.

CLI users can use [EpubMerge](https://github.com/JimmXinu/EpubMerge/blob/main/epubmerge.py) to the same effect.  EpubMerge can be use CLI directly, I haven't packaged it into PyPi.

**Comment by JimmXinu** [comment]
See #1032 #666 & #253
