### ISSUE TITLE
Possible DeviantArt Site Change has broken fetching stories

### ISSUE THREAD

**Issue by boomcpg** [JimmXinu/FanFicFare#1030]
Story previously downloaded 3 weeks ago using FanFicFare . Now get the below error when trying to refetch the same story. This also has occurred on a few other stories as well from DeviantArt.

OS: Windows 10
FanFicFare Version: 4.30.0 on both retrievals
Calibre Version: 7.3
Error: 'NoneType' object has no attribute 'decompose'
[Story URL=https://www.deviantart.com/auraguardianhadou/art/The-magical-Draik-plushie-37009366](https://www.deviantart.com/auraguardianhadou/art/The-magical-Draik-plushie-37009366)

**Comment by JimmXinu** [comment]
[FanFicFare plugin test version is always posted here](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).

**Comment by boomcpg** [comment]
Can confirm this and other DeviantArt stories are downloading correctly with test branch
