### ISSUE TITLE
[Feature Request] Allow to download fics from AO3 Series URL, Or Allow for Multiple URL extractions for a single URL. 

### ISSUE THREAD

**Issue by ffuentesm** [JimmXinu/FanFicFare#1032]
Something that urks me is that some authors post their fics are a series of oneshots instead of a single fic with short chapters. 
So I normally need to download them one by one. Could you make it so that FFF can take an Ao3 Series URL and extract the fics from that single URL? 

Like, this series has 16 URLs https://archiveofourown.org/series/2630311
the way things are now, I need to download each one individually. It would be a huge QoL if I could just input a single URL. 

Or maybe, some form of "URL fetcher" from a single URL? Like if I give the URL to my bookmarked fics page, this would then check for any valid URLs from that URL and use those on the download queue.
I can makeshift something like that by using this code when inspecting the FFN favourite page. 

> var x = document.querySelectorAll("a");
var myarray = []
for (var i=0; i<x.length; i++){
var nametext = x[i].textContent;
var cleantext = nametext.replace(/\s+/g, ' ').trim();
var cleanlink = x[i].href;
myarray.push([cleantext,cleanlink]);
};
function make_table() {
var table = '<table><thead><th>Name</th><th>Links</th></thead><tbody>';
for (var i=0; i<myarray.length; i++) {
table += '<tr><td>'+ myarray[i][0] + '</td><td>'+myarray[i][1]+'</td></tr>';
};

var w = window.open("");
w.document.write(table);
}
make_table()

**Comment by JimmXinu** [comment]
It's come up a before: #666 #253. Short answer: 
- The FanFicFare Calibre plugin already has that feature.  Look for the Anthology options.  Requires EpubMerge plugin, too.
- I've never added it for CLI for various reasons.  I assume anyone using CLI can script [epubmerge.py](https://raw.githubusercontent.com/JimmXinu/EpubMerge/master/epubmerge.py) themselves.
