### ISSUE TITLE
include_images false, but still download cover images?

### ISSUE THREAD

**Issue by emrys90** [JimmXinu/FanFicFare#1037]
Not super important, but I disabled include_images as it can be slow downloading some ebooks that include lots of images per chapter. This also stopped downloading cover images though, which I would ideally still like to have. Is there a way to accomplish that?

**Comment by JimmXinu** [comment]
Not currently.  But it's not a terrible idea.

There's several [different places](https://github.com/JimmXinu/FanFicFare/wiki/Cover-Settings-Calibre-Plugin#where-do-epub-covers-come-from) a cover image can come from depending on the story and your settings.  

Looking at the code, it should be possible to add an additional setting for `include_images` to allow cover types other than `first` without collecting images in the chapter texts.  But I'll need to do some testing first.

**Comment by JimmXinu** [comment]
Test versions with `include_images:coveronly` option posted in the usual places.

**Comment by emrys90** [comment]
Great, thank you!

**Comment by JimmXinu** [comment]
Give it a try and make sure it does what you want.
