### ISSUE TITLE
Python 2 CLI does not output custom metadata or a title page

### ISSUE THREAD

**Issue by praschke** [JimmXinu/FanFicFare#1041]
I tested this on AO3 stories to be confident of the results.

Getting the CLI in a runnable state on Python 2 was difficult, as there is no longer a setup.py, which pip2 requires, but I wanted to try running with the vendored dependencies as they are older. I linked `fanficfare` and copied `cli.py` into `included_dependencies` and was able to run it from there.

- When printing metadata using CLI options, custom metadata is never displayed.
- The setting `include_titlepage: true` in the default INI is ignored and a title page is not output unless I put `include_titlepage: true` in a personal INI.
- When the titlepage is included, the div below the title and author heading is empty.

I verified by printing the cached metadata at the end of `extractChapterUrlsAndMetadata` that all custom metadata is collected, but everything downstream of that is broken.

**Comment by JimmXinu** [comment]
I only support py2 in the calibre plugin at this point.  Removing official CLI support for py2 was deliberate.

I would suspect from your issues that you're using an outdated or damaged `defaults.ini`, or you have a `personal.ini` that sets those somewhere.  For example, if you're on linux, somebody insisted I support ini files in `$XDG_CONFIG_HOME` at one point.
