### ISSUE TITLE
DeviantArt Adapter: Failure to Download Story

### ISSUE THREAD

**Issue by boomcpg** [JimmXinu/FanFicFare#1042]
All nine stories report the same error message. 

OS Tested: Windows 10 and Linux Mint
Calibre Version: 7.5.1
Error: 'NoneType' object is not subscriptable
Story Gallery url: [Maid for Slimes](https://www.deviantart.com/corpulency/gallery/88534814/maid-for-slimes) tested by "Make Anthology Epub from We Page". Also tested first story individually with same result

**Comment by JimmXinu** [comment]
Test versions up in the usual places.
