### ISSUE TITLE
Wrong number of threadmarks being reported for Sufficient Velocity

### ISSUE THREAD

**Issue by HowardJeng** [JimmXinu/FanFicFare#1043]
FanFicFare v4.32.0 on Calibre 7.6

When updating some epub files on Sufficient Velocity, the number of threadmarks reported are off for some threads. For example when trying to download https://forums.sufficientvelocity.com/threads/a-darker-path-worm-fanfic.107715/ it reports "Existing epub contains 109 chapters, web site only has 79. Use Overwrite or force_update_epub_always to force update." I don't know where the number 79 is coming from as the main threadmark category has 82 threadmarks at the moment.

Other threads having this problem include

https://forums.sufficientvelocity.com/threads/project-gamer-ver-2-young-justice-gamer-multicross-oc.92217/
"Existing epub contains 386 chapters, web site only has 134. Use Overwrite or force_update_epub_always to force update."

and

https://forums.sufficientvelocity.com/threads/brocktons-celestial-forge-worm-jumpchain.70036/ 
"Existing epub contains 579 chapters, web site only has 181. Use Overwrite or force_update_epub_always to force update."

But some threads are reporting the correct number of threadmarks like

https://forums.sufficientvelocity.com/threads/harry-potter-and-the-skittering-spouse.108358/
"Already contains 39 chapters."

This appears to have started some time in the last week.

**Comment by JimmXinu** [comment]
Should be addressed in d1c5847a586b2d60917108d2193bd07ca4b56037 and c60b296bc9a36547481b2615ac1b1e58c51bb72c.  Test versions in the usual places.

This announcement ([Threadmarks - Pagination](https://forums.sufficientvelocity.com/threads/threadmarks-pagination.128132/)) says it happened the evening before I released last--but after I ran tests.

I'll release a point version in a day or two.
