### ISSUE TITLE
fanficfare linux vs windows speed difference

### ISSUE THREAD

**Issue by nerdguy1338** [JimmXinu/FanFicFare#1050]
For whatever reason, the linux version of the calibre plugin of FFF is much faster when getting metadata. I specifically used a new windows calibre install, and copied the personal ini file out of linux calibre into the windows version.

windows is at least twice as fast.

**Comment by JimmXinu** [comment]
There are multitudes of variables at play in such a comparison.  FanFicFare and parts of Calibre are probably the only code that is the same in both.  Of course they're going to run differently.

And as the only part that is the *same*, I don't think it's on FFF to account for the difference.
