### ISSUE TITLE
Errors fetching information on the plugin now generate modal error boxes instead of just reporting on the job log like before

### ISSUE THREAD

**Issue by jherazob** [JimmXinu/FanFicFare#1051]
In the past, if fetching metadata or a story generated an error (the story got deleted from the site, Flaresolverr proxy timed out, something raised an exception, etc.), the plugin used to just show you information that the operation failed, at the end, aggregated for all stories, as part of the log for the job. 

Now, since the latest plugin version, it shows a modal dialog box *for each single error*, independent of the job log at the end. Having a long collection gathered over time means that for each check I'll have now to deal with several modal error dialog boxes every time, instead of just showing me the error log like it has done before. 

Is this something that the FanFicFare plugin changed, or Calibre itself? More importantly, is it behavior that can be disabled?

**Comment by JimmXinu** [comment]
You are seeing the same thing as #1048 and #1044.  Fix is out in the test version.  The latest [FanFicFare plugin test version is always posted here](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).

Leaving open this time for higher visibility.
