### ISSUE TITLE
browser cache path for fanfiction.net doesn't work

### ISSUE THREAD

**Issue by PHBN1964** [JimmXinu/FanFicFare#1055]
i followed the instructions for browser cache path for fanfiction.net but it still doesn't resolve the error 403, and even the use of proxies does not work. hat can i do to resolve this problem

**Comment by JimmXinu** [comment]
This has been reported many times, most recently in #1036 #1047

ffnet has been using a heightened state of Cloudflare 'protection' for years now.  Support for it is now ['limited'](https://github.com/JimmXinu/FanFicFare/wiki/SupportedSites#limited-support-sites).

Pretty much everything I know that can help is documented in the wiki pages:
https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature
https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures

You could also search the [FanFicFare maillist](https://groups.google.com/group/fanfic-downloader) and the [Calibre plugin thread](https://www.mobileread.com/forums/showthread.php?t=259221) for past discussions.

**Comment by LoisGNS** [comment]
It's been working for me. I'm on ver 4.20.0 of FFF and 6.14.1 (portable) of Calibre, in case that matters.  Make sure you have this line included in your personal.ini, in the [defaults] section:

open_pages_in_browser:true

**Comment by mhussaincov93** [comment]
hi,

this works for me also.

just wish when the page is opened in browser it would open the page in
the same window, and not spawn a new tab for every chapter/opened page.

could something be done about that?

Majid

**Comment by JimmXinu** [comment]
No,unfortunately. I remembering looking for a way to do that when implementing `open_pages_in_browser`.  

I'm honestly a little bit surprised any and all apps are still allowed to open URLs like this.  Convenience and functionality won out over security in this case.

**Comment by PHBN1964** [comment]
> It's been working for me. I'm on ver 4.20.0 of FFF and 6.14.1 (portable) of Calibre, in case that matters. Make sure you have this line included in your personal.ini, in the [defaults] section:
> 
> open_pages_in_browser:true

it worked, thanks
but when i update a epub it give errors even if i go to the first and last chapter of the fanfic, having to go to all new chapters for it to work fine

is there something i'm doing wrong

**Comment by LoisGNS** [comment]
> No,unfortunately. I remembering looking for a way to do that when implementing `open_pages_in_browser`.
> 
> I'm honestly a little bit surprised any and all apps are still allowed to open URLs like this. Convenience and functionality won out over security in this case.

Any way to make it not grab focus when it opens the URLs? I can close the tabs when done, but the focus-grabbing is inconvenient.

**Comment by JimmXinu** [comment]
I could not find one.  I would be interested if someone else could--but only if it a) works on Windows, Mac and Linux, b) still works in Calibre 2.48 (on python2), and c) doesn't add large additional dependencies that need to be bundled.

I suggest looking at this section about [WebToEpub](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature#webtoepub) if `open_pages_in_browser` is too onerous.

Honestly, if it was any smaller fanfic site, I never would have bothered with browser cache and just dropped the site.

**Comment by mhussaincov93** [comment]
make sure that all cloudflare captures are passed.

move your browser windows to another workspace

this seembs to work for me.

using mate desktop

simply moveing all chrome windows to say workspace 4 does the job.

I hope this works.

Majid

**Comment by LoisGNS** [comment]
> I suggest looking at this section about [WebToEpub](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature#webtoepub) if `open_pages_in_browser` is too onerous.

I do remember using WebToEpub before the open_pages_in_browser was developed, and found opening in browser to be much preferable, even with the focus issue. I should add that I'm just happy that it continues working despite FFnet's doing its best to make life difficult.

Often, I just go away from the computer for several minutes (to minimize having to deal with focus being grabbed) while FFF does its thing. It's a small inconvenience compared to what I'd need to do otherwise.
