### ISSUE TITLE
Existing story produces 'Story does not exist' error

### ISSUE THREAD

**Issue by WinterPhoenix-602** [JimmXinu/FanFicFare#1059]
The following error is produced when attempting to download the story 'The Dungeon Without a System'. 

Story does not exist: (https://forums.sufficientvelocity.com/threads/the-dungeon-without-a-system.97590/)
https://forums.sufficientvelocity.com/threads/the-dungeon-without-a-system.97590/

The thread can only be viewed when logged into an account on Sufficient Velocity, but adding login credentials to personal.ini did not solve the issue.

**Comment by JimmXinu** [comment]
Some stories are hidden when you aren't logged in, so there's no way for FFF to tell that it actually exists.

But you can tell FFF to always login before trying to download.  Add to `personal.ini`:
```
# for all SV stories, use your existing section if you have one:
[forums.sufficientvelocity.com]
username:XXX
password:XXX
always_login:true

# for only that story:
[https://forums.sufficientvelocity.com/threads/the-dungeon-without-a-system.97590/]
always_login:true

```
