### ISSUE TITLE
[literotica.com] Download all Story from User

### ISSUE THREAD

**Issue by mcj130101** [JimmXinu/FanFicFare#1060]
Downloading all the writer's stories at once has stopped working since the new UI change on the website. Hope you can find a fix for it soon

**Comment by mcj130101** [comment]
Update /  I think that the new change has completely stopped fanficfare from working properly .

Error: 
..Traceback (most recent call last):

  File "/home/mcj130101/.local/pipx/venvs/fanficfare/lib/python3.11/site-packages/fanficfare/adapters/adapter_literotica.py", line 189, in extractChapterUrlsAndMetadata
    raise exceptions.FailedToDownload("Couldn't find story <%s> on author's page <%s>" % (self.url, authorurl))
fanficfare.exceptions.FailedToDownload: Couldn't find story <https://www.literotica.com/s/friends-with-benefits-pt-11> on author's page <https://www.literotica.com/stories/memberpage.php?uid=7768740&page=submissions>

**Comment by JimmXinu** [comment]
Pretty sure this is the same as #1058 

I said there:

> I'm not seeing that site change. However, I also don't have an account on literotica; is it a member only change?

I continue to not see this change when I look at the site.

**Comment by JimmXinu** [comment]
Closing as duplicate, continue discussion in #1058
