### ISSUE TITLE
QuestionableQuesting.com Site Changed

### ISSUE THREAD

**Issue by Wasuregusa** [JimmXinu/FanFicFare#1067]
I'm getting a `HTTP Error in FFF '400 Client Error: Bad Request for url: https://forum.questionablequesting.com/login/login'(400)` whenever I try to update a story.

The site recently migrated to "Xenforo 2" as their new forum engine, which looks like the most likely cause of the problem.

**Comment by JimmXinu** [comment]
XF2 change already addressed in 5b443d43638fec3cbf1c9e31f6ce06123a196e81.  Test versions up in the usual places.

I'm not seeing this.  Story URL?

**Comment by Wasuregusa** [comment]
My bad. I forgot to mention I was using FFF as a Calibre plugin, and the version they have (v4.34.1) doesn't have yet the correction for QuestionableQuesting.

I manually patched `fanficfare/adapters/adapter_forumquestionablequestingcom.py` inside the file `~/.config/calibre/plugins/FanFicFare.zip` as in [5b443d4](https://github.com/JimmXinu/FanFicFare/commit/5b443d43638fec3cbf1c9e31f6ce06123a196e81) and everything worked fine.

**Comment by JimmXinu** [comment]
Or you can pick up the [posted test version from the usual places](https://github.com/JimmXinu/FanFicFare#test-versions).

I'm going to leave this open for now for higher visibility.

**Comment by Wasuregusa** [comment]
Got it. Thanks a lot!
