### ISSUE TITLE
get urls for anthology epub miising stories on ao3

### ISSUE THREAD

**Issue by kyoam** [JimmXinu/FanFicFare#1081]
i tried to update an epub for this https://archiveofourown.org/series/3944911 which as 3 stories :
 https://archiveofourown.org/works/49516933
https://archiveofourown.org/works/53149204
https://archiveofourown.org/works/54685789

but when i use either the get urls from web page or the update anthology epub option it only lists 2 links of the 3:

https://archiveofourown.org/works/49516933
https://archiveofourown.org/works/54685789

what do I have to do to fix this?

my personal ini is the default one if that helps and https://archiveofourown.org/works/53149204 has the lock symbol on it if that helps.

**Comment by JimmXinu** [comment]
> my personal ini is the default one if that helps and https://archiveofourown.org/works/53149204 has the lock symbol on it if that helps.

That lock indicates a Restricted story.  AO3 pretends those stories don't and hides them if you aren't logged in.  

If you configure your username/password in personal.ini, FFF will attempt to login before getting series like that.
```
[archiveofourown.org]
username:YourName
password:yourpassword
```

**Comment by kyoam** [comment]
the weird part was i tried it with another series that had a restricted story https://archiveofourown.org/series/2835628 and it came up with that one...

i did edit the personal ini and the problem has solved itself so thanks.
