### ISSUE TITLE
Suggestion: Add an option to download the entire thread when downloading from QQ, SB, SV, etc. (CLI)

### ISSUE THREAD

**Issue by NTaya** [JimmXinu/FanFicFare#1082]
I use the command line interface. I want to download the entire thread on QQ because I want to read both the story and the discussion after each chapter. However, FanFicFare is smart, which in my case is a bad thing, and only goes through the Threadmarks. I didn't find an option to download everything in defaults.ini or in the CLI flags.
Thanks in advance.

**Comment by JimmXinu** [comment]
This has been requested before.  I decided that a 'download all posts' feature was a) too difficult/expensive to update--FFF depends on a chapter list paradigm, b) outside FFF's mission of story download, and c) too open to abuse.
