### ISSUE TITLE
Spacebattles Story Does Not Exist

### ISSUE THREAD

**Issue by Mamoth112** [JimmXinu/FanFicFare#1085]
I've been using FFF for a while now without issues, but today as I was trying to download a fic from forums.spacebattles.com it responded with Story does not exist.

I'm using the Calibre plugin.

I have also tried downloading other fics from spacebattles and got the same result.

I have also checked other sites such as sufficient velocity and they all worked fine.

**Comment by JimmXinu** [comment]
I am able to download from SB.  Without knowing the story URL, I can't tell you anything more for sure.

If it's a user-restricted story, you may need `always_login:true` with user/pass settings.
