### ISSUE TITLE
Support for https://www.inkitt.com

### ISSUE THREAD

**Issue by bichitoxxx** [JimmXinu/FanFicFare#1087]
Could you please consider adding support for https://www.inkitt.com While some of the stories are available on supported sites, many of them are not. 

After the new Wattpad rules, many translators and authors have decided to move to this platform

Thank you.

**Comment by bichitoxxx** [comment]
I apologize, I think I'm a bit clumsy with this topic, I don't download it properly, because it won't let me install it in calibre
![Screenshot_1](https://github.com/JimmXinu/FanFicFare/assets/29169926/9bd59a5b-d2ca-4c12-8746-98afc700e17a)

**Comment by bichitoxxx** [comment]
I downloaded it like this and then I went to caliber and and clicked install plugin. I guess I did it wrong-
![Screenshot_1](https://github.com/JimmXinu/FanFicFare/assets/29169926/05c7021f-e71d-4bae-b3a8-3fe45e3ddcec)
![Screenshot_2](https://github.com/JimmXinu/FanFicFare/assets/29169926/9cd0ca36-00f0-44d7-9906-4195d4a30d82)

**Comment by bichitoxxx** [comment]
I have installed the file that you gave me last. Now it recognizes the URL of the page but gives an error

![Screenshot_3](https://github.com/JimmXinu/FanFicFare/assets/29169926/f4c83ce0-1106-401e-b05e-91f82ad930ac)
![Screenshot_6](https://github.com/JimmXinu/FanFicFare/assets/29169926/2d2c1d69-07f9-4d13-9040-bb518b725304)
![Screenshot_5](https://github.com/JimmXinu/FanFicFare/assets/29169926/f19430aa-c1ba-4b38-ad0b-9e05192e0682)

**Comment by bichitoxxx** [comment]
Thank you very much for your help, I feel quite clumsy. I'll try

**Comment by bichitoxxx** [comment]
> Este sitio requiere que inicie sesión para ver historias que tengan más de 4 capítulos. Puedes hacerlo añadiendo esta sección a tu personal.ini
> 
> ```
> [www.inkitt.com]
> username:username
> password:password
> ```
> 
> Y si desea instalar la extensión desde el código descargado de github, debe extraer el zip, abrir una terminal allí y ejecutar el comando `python ./makeplugin.py` ![2](https://private-user-images.githubusercontent.com/167717232/346304039-55689817-0240-4212-9f9b-645ee9f77295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzY3NTgsIm5iZiI6MTcyMjU3NjQ1OCwicGF0aCI6Ii8xNjc3MTcyMzIvMzQ2MzA0MDM5LTU1Njg5ODE3LTAyNDAtNDIxMi05ZjliLTY0NWVlOWY3NzI5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNTI3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjYxODUyZTNjMDZlYjNhOGM4OTBhYjFjZmQ1YzhkODNkMjQ2MGZiMDBmNjA5ODRlMzk4ZWExNmVmNzIxM2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n45I7YqCb2Wg4bT_eBX_ugRfaUjEpj2WtT_u9LSOQj8) ![3](https://private-user-images.githubusercontent.com/167717232/346304044-f1907fc6-87aa-4566-95bf-4f9f9d74566f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzY3NTgsIm5iZiI6MTcyMjU3NjQ1OCwicGF0aCI6Ii8xNjc3MTcyMzIvMzQ2MzA0MDQ0LWYxOTA3ZmM2LTg3YWEtNDU2Ni05NWJmLTRmOWY5ZDc0NTY2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNTI3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGE0NWNkYTYzMTM4MzhhN2YxODNhNWY2NzRhMTAxZmEyOGQwNTBmYTM0ZGQ3MTU2MTk5NjY1NmM2NzcwMjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CMHpsVYA3gCLxqKGke05tX81AkWkrck6ulrOhx7jhWs)

I never managed to open the terminal because my capabilities do not reach that Therefore it was never able to install the test version, I tried to add the line

[www.inkitt.com]
username:username
password:password

It still never worked but it does detect the URL. With the new update it again does not detect the URL and now this appears every time I try to modify the personal.ini

![Screenshot_4](https://github.com/user-attachments/assets/245e8116-81d6-4267-aa91-fe9ad3a42d94)
![Screenshot_5](https://github.com/user-attachments/assets/13136614-b402-440d-9089-754b528be644)
![Screenshot_6](https://github.com/user-attachments/assets/7354b63b-4f9d-4456-ba2c-208cb1f9e014)

**Comment by bichitoxxx** [comment]
Hello, I solved the problem by adding the lines.

[www.inkitt.com]
username:username
password:password

What you suggested to me, this solved the problem, and I could now download the stories. but after updating to the latest version 4.37.0 the same problem occurred again, you do not detect the inkitt URLs and the personal.ini appears like this with that error

![Screenshot_2](https://github.com/user-attachments/assets/295c4f06-c65c-4c23-b3e6-49f1ef066a5c)
![Screenshot_3](https://github.com/user-attachments/assets/effaedb3-06a3-45ad-880a-0e2d496335cf)

**Comment by bichitoxxx** [comment]
At the moment I have not tested the current official version, as soon as I saw that it did not work on that website I went back to the previous version so I did not test it to find out if there were errors. I am going to install the version that you gave me now and if there are errors I will inform you. Thank you very much for all your work.

**Comment by bichitoxxx** [comment]
I have a question: today I got a new update, 4.38, in Calibre. If I update, will I lose the ability to download Inkitt again?

**Comment by JimmXinu** [comment]
Correct.  These changes haven't been submitted for inclusion in the official version.

As @dbhmw said last month:
> After updating to a newest version you will lose the version that supports the website. I haven't made a pull request so for now the website isn't supported in the main release of the plugin. I will send an updated plugin here. I didn't test this plugin much so i rather not try to get this merged for now. Have you encoutered any bugs?

**Comment by bichitoxxx** [comment]
then I will continue with the previous version, and will not update so as not to lose them. Thank

**Comment by bichitoxxx** [comment]
Hello, I did not update to the latest version so as not to lose the Inkkit downloads, but today this appears and it does not let me add or update, I did not change anything, everything remains the same.
![Screenshot_2](https://github.com/user-attachments/assets/219c019e-d361-4b82-9bb2-90bc1685e930)
![Screenshot_3](https://github.com/user-attachments/assets/11532883-93fc-4e41-baff-33f80a68a007)

**Comment by bichitoxxx** [comment]
> Hola, no actualicé a la última versión para no perder las descargas de Inkkit, pero hoy aparece esto y no me deja agregar ni actualizar, no cambié nada, todo sigue igual. ![Screenshot_2](https://private-user-images.githubusercontent.com/29169926/365334436-219c019e-d361-4b82-9bb2-90bc1685e930.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NzcwMTgsIm5iZiI6MTcyNTY3NjcxOCwicGF0aCI6Ii8yOTE2OTkyNi8zNjUzMzQ0MzYtMjE5YzAxOWUtZDM2MS00YjgyLTliYjItOTBiYzE2ODVlOTMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAyMzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZTA1MzdhNmU3MGE4ODM0YTNiZjdhZTVlZWZjNGQ3OWFjMzcyZTNlN2NjYmQxOGJhMWI4MTliN2FiNjkzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R20zH_rfib36s3MW8NWpNf_tDYztl3EghHA6sRTRrjg) ![Screenshot_3](https://private-user-images.githubusercontent.com/29169926/365334438-11532883-93fc-4e41-baff-33f80a68a007.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NzcwMTgsIm5iZiI6MTcyNTY3NjcxOCwicGF0aCI6Ii8yOTE2OTkyNi8zNjUzMzQ0MzgtMTE1MzI4ODMtOTNmYy00ZTQxLWJhZmYtMzNmODBhNjhhMDA3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAyMzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NGM4MTFiOGM0OGQ2M2U3NjI5NjE0OTcxZjQ1OWUyYWE0ZDNiZjM1ODY5MWFiZWUyOWQ2ZWJlNGI4YTBkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lY0-Bf1e1Tb9LBWikD-RuDgBcvcaMV2kgApeKvd5jQU)

I've been reading the bugs posted by other users and one of the answers you gave seems to work for now.
[www.fimfiction.net]
use_cloudscraper:true
slow_down_sleep_time:3

I just had to modify the personal.ini

[www.inkitt.com]
use_cloudscraper:true
slow_down_sleep_time:3

and downloaded again

**Comment by JimmXinu** [comment]
Decided against supporting this site due to primarily being for-pay content.  [Discussion](https://github.com/JimmXinu/FanFicFare/pull/1109#issuecomment-2365228349) on #1109
