### ISSUE TITLE
Literotica update if newer Doesn't update stories....

### ISSUE THREAD

**Issue by Saii36** [JimmXinu/FanFicFare#1088]
Hi Xinu,

Thank you soo much you saved me a lot of time with this plugin.

Whenever I try to update(overwrite if never) a story in my library it doesn't update, even though there are new chapters on the site. It worked fine on June 23.

I've tried updating each story individually but it still doesn't work. However, if I overwrite the entire story(overwrite always) or delete it and then try downloading then it captures all the newer chapters. I'm using version 4.36.0

**Comment by Saii36** [comment]
Hi again... I just noticed that this issue only occurs with series that do not have a new update date in the series info section but do have newer chapter links.

These series without a newer update date does not work:
https://www.literotica.com/series/se/the-dragon-king
![Screenshot 2024-07-07 at 11-46-03 The Dragon King - Story Series - Literotica com](https://github.com/JimmXinu/FanFicFare/assets/139146851/f85fb93d-b157-4c83-be25-a72db0eede3a)

![Screenshot 2024-07-07 at 11-49-26 Stories by girlfred - Literotica com](https://github.com/JimmXinu/FanFicFare/assets/139146851/69e06a28-2141-4ea9-8e35-2d03df678a49)


https://www.literotica.com/series/se/the-soul-refiner
![Screenshot 2024-07-07 at 11-46-45 The Soul Refiner - Story Series - Literotica com](https://github.com/JimmXinu/FanFicFare/assets/139146851/76449bd8-558f-452b-8245-b089d1845967)

![Screenshot 2024-07-07 at 11-47-50 Stories by Maltry - Literotica com](https://github.com/JimmXinu/FanFicFare/assets/139146851/e3b2aa15-9d0a-495c-a03d-94ffe648f1eb)



Series with a newer update date work fine:
https://www.literotica.com/series/se/a-little-harmess-exhibitionism
https://www.literotica.com/series/se/493583987

**Comment by JimmXinu** [comment]
> Hi again... I just noticed that this issue only occurs with series that do not have a new update date in the series info section but do have newer chapter links.

FFF can't parse the author page, so if the site is giving the wrong date, it's just wrong until the site catches up.
