### ISSUE TITLE
Issue creating anthology from paginated series on AO3

### ISSUE THREAD

**Issue by jessctanugi** [JimmXinu/FanFicFare#1091]
I have a paginated series that seems to be breaking a few of the functions in the latest version of FanFicFare (and the previous version; I updated today to see if it fixed the issue and it didn't). In the past, these functions have worked perfectly on my machine with other very long series on AO3, but today [this series](https://archiveofourown.org/series/1669567) and others by the same author are breaking it. 

I suspect it's the pagination -- I also tried the multi-page series you linked to on a previous closed issue ([this series](https://archiveofourown.org/series/1891810)) and it also wasn't working. I tried to get around it by going page by page (adding ?page=2 to the URL) but that didn't work either.

Both "get URLs from webpage" and "make anthology epub from webpage" aren't working with these URLs, and this is the summary of the error I'm getting:
> calibre, version 7.15.0
> ERROR: Unhandled exception: <b>ValueError</b>:invalid literal for int() with base 10: '2&amp;view_adult=true'

Thanks for making such an amazing tool -- it's been so amazingly helpful in putting together and updating these long series!!

**Comment by JimmXinu** [comment]
Looks like the site started adding an additional URL parameter to the page URL.  I've added better URL parsing and posted test versions in the usual places.
