### ISSUE TITLE
Outlook/Microsoft Email Connection issue

### ISSUE THREAD

**Issue by M3We** [JimmXinu/FanFicFare#1093]
I think Outlook/Microsoft have changed the way they connect via IMAP, and I do vaguely remember getting a popup from them saying they were changing it.

All good if I just have to deal with it, if its a Microsoft isolated issue.

I've changed nothing (except for manually putting in the pwd everytime confirming this is correct) and now am getting this error every time:

```
calibre, version 7.15.0
ERROR: Unhandled exception: <b>error</b>:b'LOGIN failed.'

calibre 7.15  embedded-python: True
macOS-14.5-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.5.0', 'Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.5', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Count Pages (1, 13, 6) && EpubMerge (3, 1, 0) && FanFicFare (4, 36, 0) && Manage Series (1, 5, 2) && Reading List (1, 15, 4) && Smashwords Metadata (1, 0, 2) && Walk Search History (1, 5, 4)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 592, in get_urls_from_imap_menu
    url_list = get_urls_from_imap(prefs['imapserver'],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<User>/Library/Preferences/calibre/plugins/FanFicFare.zip/fanficfare/geturls.py", line 189, in get_urls_from_imap
    status = mail.login(user, passwd)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "imaplib.py", line 612, in login
imaplib.IMAP4.error: b'LOGIN failed.'
```

**Comment by JimmXinu** [comment]
I've never used it with any service but Gmail. 

Gmail started requiring 2FA, but gave an option called Google App Passwords for unique-per-app passwords.  Maybe Outlook has something similar?

> WARNING There's very little data protection in Python--once you've given FanFicFare your password, any plugin or other part of Calibre could potentially read it if it knows to look for it. Alternatively, if you use 2FA on Gmail you can use [Google App Passwords](https://support.google.com/accounts/answer/185833#app-passwords).

I'll leave this open for the moment, but I don't have a way to address it beyond Google.

**Comment by M3We** [comment]
Update: followed [this](https://support.microsoft.com/en-au/account-billing/how-to-get-and-use-app-passwords-5896ed9b-4263-e681-128a-a6f2979a7944) and still doesn't work

**Comment by nekogecko2** [comment]
I'm having the same issue. I've been using a Outlook email account that I auto forward fanfic update emails to from my main gmail account. Worked fine a month ago but doesn't work anymore.

**Comment by bichitoxxx** [comment]
> Tengo el mismo problema. He estado usando una cuenta de correo electrónico de Outlook a la que reenvío automáticamente los correos electrónicos de actualización de fanfics desde mi cuenta principal de Gmail. Funcionó bien hace un mes, pero ya no funciona.

I had the same problem with Microsoft and Google accounts, and I had to create an account at mail.gmx.com, that's the only thing I could do to continue using it.

**Comment by nekogecko2** [comment]
> I had the same problem with Microsoft and Google accounts, and I had to create an account at mail.gmx.com, that's the only thing I could do to continue using it.

Good news! I decided to randomly try the "get story urls from email" button again and now it looks like Outlook emails are working again! I was being too lazy to final another email service and set up auto forwarding again. 😅

**Comment by M3We** [comment]
Worked yesterday again, back to not working
