### ISSUE TITLE
SufficientVelocity Story Does Not Exist Error

### ISSUE THREAD

**Issue by deep-bhattacharya** [JimmXinu/FanFicFare#1097]
The thread gives an error: Story does not exist, when trying to download as epub in FanFicFare.

Not sure if this is due to how long the URL is, maybe?

https://forums.sufficientvelocity.com/threads/my-absolutely-incredible-astonishing-super-amazing-life-as-someone-in-another-world-is-absolutely-and-unquestionably-beyond-reproach-it-sucks.68737/

**Comment by JimmXinu** [comment]
That's in the Unlisted Original Fiction subforum which is only viewable by logged in users.  You can tell FFF to `always_login` for that particular story:
```
[https://forums.sufficientvelocity.com/threads/my-absolutely-incredible-astonishing-super-amazing-life-as-someone-in-another-world-is-absolutely-and-unquestionably-beyond-reproach-it-sucks.68737/]
always_login:true
```
Or for all SV stories using the site section instead.  This is most convenient if you also configure `username` and `password`, but that's up to you.  You will be prompted for them otherwise.

**Comment by deep-bhattacharya** [comment]
The credentials are already present in personal.ini

[forums.sufficientvelocity.com]
username:****
password:********

I appended the line to the section;

always_login:true

But still getting the same issue.

Other relevant configs:

[base_xenforoforum]
always_reload_first_chapter:true
skip_threadmarks_categories:Staff Post,Apocrypha, Voting
order_threadmarks_by_date_categories:Threadmarks
threadmark_category_order:Sidestory,Omake,Media,Informational

**Comment by deep-bhattacharya** [comment]
Okay, the issue has fixed itself. I suddenly got an alert about possible password compromise, changed it, also updated it in the the ini, and the download just went through.

Maybe some security measure, I dunno.

Thanks for your help.
