### ISSUE TITLE
replace_metadata assumes True when preventing recursion

### ISSUE THREAD

**Issue by EtorixDev** [JimmXinu/FanFicFare#1098]
[Line 923](https://github.com/JimmXinu/FanFicFare/blob/2666164c5be1415a99e8cb9d3d4e652d2087eb79/fanficfare/story.py#L923) of `story.py` sets `doreplace=True`.

Directly below it, the conditional `if cond_match and cond_match.key() != key:` is checked.

In my case, I was attempting to replace one category based on the content of another category. 

`category=>match=>replacement&&category=~content`

Unknowingly, this is blocked for some recursion reason which I don't fully understand. Regardless, instead of cancelling the replacement, the current implementation continues on. In my opinion if the replacement has to be aborted such as preventing recursion, the condition should be assumed false. Preventing false positives should take priority.

Something along the lines of:
```py
if cond_match:
    if cond_match.key() != key: # prevent infinite recursion.
        new_seen_list = dict(seen_list)
        new_seen_list[repl_line]=True
        condval = self.getMetadataForConditional(cond_match.key(),seen_list=new_seen_list,doreplacements="_LIST" not in cond_match.key())
        doreplace = condval != None and cond_match.is_match(condval)
    else:
        doreplace = False
```

I managed to get my use case working with both `category` and `category_LIST` (though with unknown potential side effects) by modifying some things but I'll be making a second issue for that because I believe there's some unintended behavior there (before my changes).

**Comment by JimmXinu** [comment]
Do you have an example of this code misbehaving?  Or is this purely an optimization suggestion?

**Comment by EtorixDev** [comment]
> Do you have an example of this code misbehaving? Or is this purely an optimization suggestion?

The example would be in #1099 

In there I tried to replace a category based on other categories, but since that is blocked by recursion protection it always triggers no matter what.

**Comment by JimmXinu** [comment]
The idea is basically: If the conditional is obviously recursive, ignore the conditional clause entirely.

I have a vague recollection that I chose to leave it that way as being more visible--and obviously broken--than the conditional clause never being met.  One could certainly argue for other approaches.  

But I'm not inclined to touch the replacement code if I don't absolutely have to.  You would not believe the size and complexity of replacement setups some users have.
