### ISSUE TITLE
replace_metadata does not evaluate in-order as the wiki suggests

### ISSUE THREAD

**Issue by EtorixDev** [JimmXinu/FanFicFare#1099]
It's possible I have misunderstood the wiki, how replace_metadata works in general, or this just an edge case, but here is my use case.

Fandoms: `Spider-Man (Tom Holland Movies), The Avengers (Marvel Movies), Deadpool - All Media Types, Daredevil (TV)`

For simplicity, anything I consider main marvel I replace to `Marvel`, and then if any extended marvel is found, replace `Marvel` with `Marvel+` followed by replacing the extended fandoms with blank, effectively erasing them.

Basic Example:
```ini
replace_metadata:
	category=>Iron Man.*=>Marvel
	category=>Captain America.*=>Marvel
	category=>Marvel=>Marvel+&&category=~Daredevil.*|Deadpool.*
	category=>Daredevil.*=>
	category=>Deadpool.*=>
```

This fails due to a recursion block on checking a category while replacing a category. I do not understand the reason behind this as there is a lot of code to look at, but I was able to get it to work simply by removing the recursion check and setting `doreplacements` to `False` (the main issue here explained below).

I also tried `category_LIST` as such:
```ini
replace_metadata:
	category=>Iron Man.*=>Marvel
	category=>Captain America.*=>Marvel
	category=>Marvel=>Marvel+&&category_LIST=~Daredevil.*|Deadpool.*
	category=>Daredevil.*=>
	category=>Deadpool.*=>
```

This fails because during the evaluation of the `Marvel+` line, `getMetadataForConditional` is called on [line 928](https://github.com/JimmXinu/FanFicFare/blob/2666164c5be1415a99e8cb9d3d4e652d2087eb79/fanficfare/story.py#L928). Then `getMetadata` and `getList` default to `True`. `getMetadata` eventually calls `getList` [here](https://github.com/JimmXinu/FanFicFare/blob/2666164c5be1415a99e8cb9d3d4e652d2087eb79/fanficfare/story.py#L1073) which as just stated defaults to `True` for `doreplacements`.

So, in essence the returned value for `category` or `category_LIST` is a completely processed version of the categories, and since I clear the fandoms being checked right after, they're not there and the check fails. This doesn't feel like the intended behavior based on this sentence in the wiki:
> Replacements are applied in order--so plan accordingly.

I tried just setting `doreplacements` to `False` in `getList` but then the replacement succeeded even on stories it shouldn't have, so I assume there's multiple other places along the way which use the value and effect the output but I'm unsure. 

My solution to this was to just add a `doreplacements` kwarg to `getMetadataForConditional`, pass the value on to `getList` and `getMetadata`, and in `doreplacements()` on [line 928](https://github.com/JimmXinu/FanFicFare/blob/2666164c5be1415a99e8cb9d3d4e652d2087eb79/fanficfare/story.py#L928) pass `False`.

```py
def getMetadataForConditional(self,key,seen_list={},doreplacements=True):
    if self.getConfig("conditionals_use_lists",True) and not key.endswith("_LIST"):
        condval = self.getList(key,seen_list=seen_list,doreplacements=doreplacements)
    else:
        condval = self.getMetadata(key.replace("_LIST",""),seen_list=seen_list,doreplacements=doreplacements)
    return condval

def doReplacements(self,value,key,return_list=False,seen_list={}):
    ...
    if cond_match and cond_match.key() != key: # prevent infinite recursion.
        new_seen_list = dict(seen_list)
        new_seen_list[repl_line]=True
        # print(cond_match)
        condval = self.getMetadataForConditional(cond_match.key(),seen_list=new_seen_list,doreplacements=False)
        doreplace = condval != None and cond_match.is_match(condval)
```

I'm not sure what exactly this would break as it works for me both for `category` and `category_LIST`, but I'm open to other ideas as I'm sure it's broken *something*.

Edit: I have `include_in_category:fandoms` set if that wasn't clear.

**Comment by EtorixDev** [comment]
I was doing all of my testing with the command line. Despite my fixes working there, I can't seem to get them to work in the plugin by running `makeplugin.py` and manually installing it.

**Comment by JimmXinu** [comment]
Removing the recursion checks is not an option.  We can get stuck in an infinite loop when replacements reference each other.

The standard answer for replacements to refer to the same metadata entry is to make a `NOREPL` copy of the metadata entry.  Something like:
```
add_to_extra_valid_entries:,categoryorig
include_in_categoryorig:category.NOREPL

replace_metadata:
	category=>Iron Man.*=>Marvel
	category=>Captain America.*=>Marvel
	category=>Marvel=>Marvel+&&categoryorig=~Daredevil.*|Deadpool.*
	category=>Daredevil.*=>
	category=>Deadpool.*=>
```

**Comment by EtorixDev** [comment]
I see! I didn't actually want to or have a need to change how it works. I was just trying to find a solution to my checks failing. I wasn't aware NOREPL was an available option.

**Comment by EtorixDev** [comment]
Just tested it and the NOREPL method works! I would recommend updating the wiki for [ReplaceMetadata](https://github.com/JimmXinu/FanFicFare/wiki/ReplaceMetadata) explaining how it works as it currently is only mentioned once at the very end of [InExcludeMetadataFeature](https://github.com/JimmXinu/FanFicFare/wiki/InExcludeMetadataFeature) and offhandedly in [MetadataManagement](https://github.com/JimmXinu/FanFicFare/wiki/MetadataManagement) in-code without explanation. Thanks for the help!
