### ISSUE TITLE
Archive of our own.  Unable to download via calibre

### ISSUE THREAD

**Issue by roon0** [JimmXinu/FanFicFare#1102]
Since the afternoon of 2 September 2024 I have been unable to download from AO3 on to calibre, when I have tried I get the following for example on [
](https://archiveofourown.org/works/56895805/chapters/144670894)Status

I get 
Error
Unknown
Unknown
HTTP Error in FFF '403 Client Error: Forbidden for url: https://archiveofourown.org/works/56895805/navigate?view_adult=true'(403)

Status
Title
Author
Comment
URL
Error
Unknown
Unknown
HTTP Error in FFF '403 Client Error: Forbidden for url: https://archiveofourown.org/works/56895805/navigate?view_adult=true'(403)
https://archiveofourown.org/works/56895805

**Comment by danielw97** [comment]
According to AO3_Status on twitter/X, there are some additional protections in place currently due to ongoing maintenance.
Hopefully these will be relaxed when everything is synced up again.
Hth.

**Comment by LoisGNS** [comment]
I also couldn't download tonight, but could view the site.  When viewing the site, however, it briefly flashes a message that suggests something security-related (goes by  too fast to capture)

**Comment by roon0** [comment]
I guess we just wait it out.  Thanks for looking.

**Comment by kolbdog323** [comment]
It seems that archiveofourown is still giving out this error 
Status
Title
Author
Comment
URL
Error
Book Club
megamatt09
HTTP Error in FFF '403 Client Error: Forbidden for url: https://archiveofourown.org/works/37712317/navigate?view_adult=true'(403)
https://archiveofourown.org/works/37712317
and this is for any story not just adult only

**Comment by JimmXinu** [comment]
Working again for me.  Cloudflare blocking may be regional.

**Comment by roon0** [comment]
It appears to be working for me.
