### ISSUE TITLE
[Suggestions] Option for FFF fics to be affected by Calibre Tag Rules when downloaded. 

### ISSUE THREAD

**Issue by ffuentesm** [JimmXinu/FanFicFare#1106]
Is it possible to have FFF download from URL to be affected by the "Adding book" Rules? 
Due to how some tags are updated in AO3, fics with older tags are not updated unless the author does it manually. 
So I made some rules so I do not have to manually merge them together. But it seems that FFF is not affected by it when downloading fics.

Here are some examples of rules that I have. The ones that mostly bother me are how Avatar has now been updated to have the 2005 cartoon tag. Others are how some animes have anime and manga separated to be later merged into one. 

![image](https://github.com/user-attachments/assets/dd57bb26-e3fa-4212-8d3e-6796688c4965)

**Comment by JimmXinu** [comment]
I believe [this post](https://www.mobileread.com/forums/showthread.php?p=3757905&postcount=2961) from 2018 is the last time the topic came up.  I think the comments then still apply:

> I did look at this, both applying one of the existing rule sets and re-using the infrastructure (aka tag_mapper) to create additional rule sets. These are my observations:
> - Applying the existing add book or download metadata rule sets is problematic. Which? When? FFF configures everything by library, those rules do not.
> - Creating new rule sets using tag_mapper/author_mapper are possible per library. But for just tags/authors? For custom columns? For each custom column?
> - Pro: The tag_mapper a nice GUI solution for filtering and modification of tags.
> - Con: It's not as flexible and capable as FFF's ini text solution. For example, conditionals have no equivalent.
> - Pro: Aside from GUI-ness, the biggest advantage I see to the tag_mapper is that it uses the Tag Editor, which knows what tags are already in the library, making it easy to limit incoming tags to those already in the library.
> - Con: When I created a rule containing all my tags (1867), I wasn't able to edit that rule again reliably. Double clicking it only occasionally worked.
> - Con: Redundancy of features: I couldn't remove replace_metadata from FFF even if I wanted to because CLI and web service still need it. Troubleshooting complex setups with both is daunting.

I continue to hesitate adding this to FFF largely because of redundancy and increased troubleshooting issues.  But I will at least think about it again since it's been a while.

**Comment by ffuentesm** [comment]
Well, if there is an alternative way, other than incorporating the native Calibre Rules, I would accept a FFF version of that same function (automatically replacing tags). Does that already exist in the FFF ini settings and I did not notice? 

It's just frustrating that every few weeks I need to manually merge tags due to the metadata updating to the old version and Calibre filtering out 50% of fics due to a fandom tag change.

**Comment by JimmXinu** [comment]
Yes, FFF has a ton of existing features for manipulating the collected metadata and setting Calibre custom columns.  But the documentation is admittedly a bit scattershot.  

The primary discussion point for FFF plugin is the [Plugin FanFicFare Thread](https://www.mobileread.com/forums/showthread.php?t=259221) on mobileread.com.  There's [another user thread](https://www.mobileread.com/forums/showthread.php?t=352403), but it's not one I routinely read.

Look in the plugin `defaults.ini` (there's a button on the personal.ini tab of FFF plugin config, or see [the source](https://github.com/JimmXinu/FanFicFare/blob/main/calibre-plugin/plugin-defaults.ini).  Read the comments around `replace_metadata`, `include_metadata_pre`(et al) and `custom_columns_settings`.  `defaults.ini` comments are the primary doc for a lot of features.

There are also some wiki pages:
https://github.com/JimmXinu/FanFicFare/wiki/ReplaceMetadata
https://github.com/JimmXinu/FanFicFare/wiki/InExcludeMetadataFeature
https://github.com/JimmXinu/FanFicFare/wiki/MetadataManagement
