### ISSUE TITLE
Scribblehub images not downloading?

### ISSUE THREAD

**Issue by defendurname** [JimmXinu/FanFicFare#1107]
Hello, I am using the calibre plugin and have tried using these commands in personal.ini but still cant seem to get images downloaded. It used to work at some point last year I think but not sure if something changed in the last few weeks/months.

[epub]
## download as epub and use Calibre to convert.
include_images:true
force_img_self_referer_regexp:gelbooru.com|photobucket.com

I also use this in case it affects things:

[www.scribblehub.com]

use_cloudscraper:true

The story url is https://www.scribblehub.com/series/623932/on-astral-tides-from-humble-freelancer-to-astral-emperor/

Thanks for any help you can provide.

**Comment by JimmXinu** [comment]
If you wrap your ini sections in ``` markers, github will display them properly.
```
# Like this
```

I only see one image in the first 10 chapters of that story.  It's an imgur link that is serving an HTML page full of javascript including:
> If you're seeing this message, that means <strong>JavaScript has been disabled on your browser</strong>, please <strong>enable JS</strong> to make Imgur work.

FFF doesn't have a javascript engine, so it cannot download such an image.  I don't really see away around that.

**Comment by defendurname** [comment]
Ah I see...thanks for your help :(
