### ISSUE TITLE
Fimfiction fetch failing to strip <script>

### ISSUE THREAD

**Issue by Xaquseg** [JimmXinu/FanFicFare#111]
The Fimfiction fetch module is failing to strip out `<script>` tags from the fetched body, which is causing some site formatting logic to end up in the file the user gets, which is confusing/weird.

I would suggest either adding logic to strip `<script>` blocks, or using our download_chapter endpoint with the html parameter to fetch chapters instead of loading the regular user-visible page, as that endpoint should generally avoid issues like this in the future.

**Comment by JimmXinu** [comment]
Stripping out `<script>` tags across the board is probably a good idea.

Is the Fimfiction API documented anywhere?  All I've found is this [FAQ](https://www.fimfiction.net/faq#site).

**Comment by Xaquseg** [comment]
There is currently no API that can be used to perform these functions, however we hope to have a usable API at some point soonish. At the moment you will have to continue to use your existing fetch logic. Do take a look at the download_chapter URLs if you get a chance though, the pages returned by that endpoint are much simpler (= less load on our server, smaller/faster download for your plugin) and should also be much easier to process due to their lack of any unrequired tags.

The API is planned to support returning entire chapter contents, and probably in client-choice of bbcode, html, and plaintext. (= strip bbcode) Does that sound like it would be usable for your purposes? I assume that plus something like "list stories in this bookshelf" and "list user's bookshelves" would be enough to perform the functions you require?

We do have documentation of currently-planned API functionality: http://www.fimfiction.net/api-docs (clearly there are a lot of missing calls still, and a lot of the listed ones are documented but not implemented... but it should give you an idea of what we're planning on.)

**Comment by JimmXinu** [comment]
Are the download_chapter URLs you mentioned not part of the API?  And if not, are they documented somewhere?

**Comment by Xaquseg** [comment]
They're returned as part of the story detail page, or a browse page in "full" mode. On the regular site while browsing, if you hover over the cloud icon on the right side of each listed chapter, there are two icons, one returns plaintext, the other returns html. They're technically possible to construct yourself, but w/o the API there's no good way to get chapter IDs, unfortunately :(. If it's an issue, don't worry about it too much, just adding strip logic for `<script>` should solve the problem users are seeing. I'll make a note that you're interested in logged-in use of our API, for when those functions become usable.

**Comment by JimmXinu** [comment]
Change: bc57c2cadad3ed909ad5aa746c8468b4a41485df
