### ISSUE TITLE
Support for webnovel?

### ISSUE THREAD

**Issue by Kimberlyrios1111** [JimmXinu/FanFicFare#1113]
It's almost impossible to find a downloading option for that website i would really appreciate it if you could add it to the website support list 

used to be supported when it was gravitytales.com thanks!

**Comment by JimmXinu** [comment]
Webnovel's WebNovel Author Benefit link specifically says that they pay the authors.  FanFicFare is for freely available content.  For legal and moral reasons, I'm not interested in adding paid sites.  

See past discussions #1109 #440
