### ISSUE TITLE
error ficbook.net

### ISSUE THREAD

**Issue by Alla183** [JimmXinu/FanFicFare#1114]
![image](https://github.com/user-attachments/assets/150e90c1-385b-43d5-8b7f-2d44d5e19120)

**Comment by Alla183** [comment]
FlareSolverr don't work(

**Comment by JimmXinu** [comment]
FlareSolverr works for me with ficbook.net--at least for one small download.

You could try `use_cloudscraper:true` instead of FlareSolverr, but generally FlareSolverr works better.

There isn't really much I can do about cloudflare issues.

**Comment by Voblaa** [comment]
### 

> Статус
> Название
> Автор
> Комментарий
> URL
> Ошибка
> Дом по соседству
> Пайсано
> 'NoneType' object has no attribute 'find'
> https://ficbook.net/readfic/13022823
> 

New error :(

**Comment by JimmXinu** [comment]
There are been recent site changes addressed in #1123 & #1125.  Try updating to the [latest test version](https://github.com/JimmXinu/FanFicFare/#test-versions).
