### ISSUE TITLE
syosetu.com site changed?

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#1115]
There's [a report](https://www.mobileread.com/forums/showthread.php?p=4457243#post4457243) that syosetu.com may have changed.  I'm seeing that error, too.

@praschke, would you have time and interest to look into this?

**Comment by praschke** [comment]
yes, i can look into it.

**Comment by praschke** [comment]
sorry, looking closer, it seems new chapters are not correctly extracted. it isn't throwing an error for some reason.
