### ISSUE TITLE
Deviantart: Certain Stories Produce No Text

### ISSUE THREAD

**Issue by GoAwayNow** [JimmXinu/FanFicFare#1118]
Just gonna warn you right off the bat, this is a pregnancy fetish story. Thus far, it's the only story I've found that produces this error, but it's also the most recently posted thing I've tried to download, so that might be related, possibly a format change on the site or something.

Status: Error
Title: Breeding Balloon: Prolog
Author: madigascar9
Comment: Could not find story text. Please open a bug with the URL https://www.deviantart.com/madigascar9/art/Breeding-Balloon-Prolog-1105725636
URL: https://www.deviantart.com/madigascar9/art/Breeding-Balloon-Prolog-1105725636

**Comment by JimmXinu** [comment]
Looks like a site change.  I've posted test versions in the [usual places](https://github.com/JimmXinu/FanFicFare#test-versions).

I don't read that site, so my testing is fairly limited.

**Comment by GoAwayNow** [comment]
Yep, that did it, imports no problem now. Thank you!
