### ISSUE TITLE
ERROR https://ncode.syosetu.com/

### ISSUE THREAD

**Issue by Agile-Bite** [JimmXinu/FanFicFare#1120]
![Screenshot 2024-10-08 182415](https://github.com/user-attachments/assets/8fd590f6-2da2-451c-a2aa-0bb7d9d13edf)

**Comment by JimmXinu** [comment]
Previously reported in #1115 and fixed in #1116 & #1117.

If you still see the problem using [the test version](https://github.com/JimmXinu/FanFicFare#test-versions), reopen this issue.

**Comment by Agile-Bite** [comment]
It was actually working tomorrow but today it's don't
