### ISSUE TITLE
ERROR https://ncode.syosetu.com/

### ISSUE THREAD

**Issue by Agile-Bite** [JimmXinu/FanFicFare#1121]
![Screenshot 2024-10-08 182415](https://github.com/user-attachments/assets/0a43b04f-dd6f-4036-be8a-20c183bdcc03)
It was actually working tomorrow but when I try today it's showing Error

**Comment by JimmXinu** [comment]
Can you paste the story URL?

I'm not seeing this happen with a random test story.  @praschke?

**Comment by praschke** [comment]
this looks like the same error that was recently fixed. i can't replicate it from the main branch, logged in or out.

the current tagged release doesn't include the fix. the test version should work?

**Comment by JimmXinu** [comment]
Using the current test version, I'm also able to download both of those.  (Admittedly, I only downloaded 5 chapters.)

@Agile-Bite, are you sure you're using [the test version](https://github.com/JimmXinu/FanFicFare#test-versions) as previously mentioned?

It would help if you also tried while running in debug mode (Calibre Preferences dropdown) and post the debug log.

**Comment by Agile-Bite** [comment]
I checked once more try removing and re enabling the plugin from the file and then realised that the one I have been enabling all this time was actually an older version of it. And the latest test version was actually download with some other name. Which cause the confusion.

Sorry guys for all this commotion and wasting all you  precious time.
Truly I am sorry 🙇🙇🙇
