### ISSUE TITLE
[FiMFiction] flaresolverr incompatibility

### ISSUE THREAD

**Issue by luna-best** [JimmXinu/FanFicFare#1122]
Related to https://github.com/JimmXinu/FanFicFare/issues/1100 and the comment `Expecting value: line 1 column 1 (char 0)` in https://github.com/JimmXinu/FanFicFare/issues/1100#issuecomment-2329465365_

This is caused by the assumption the request will work at https://github.com/JimmXinu/FanFicFare/blob/869686f3631a1a495131de0e483a3b700974cce1/fanficfare/adapters/adapter_fimfictionnet.py#L291C13-L291C50

However, flaresolverr can't [get JSON documents in a simple way](https://github.com/FlareSolverr/FlareSolverr/issues/165), which is the type of data returned by `https://www.fimfiction.net/ajax/stories/%s/groups`. Please try/except lines 290-292 as they can all fail for different reasons. The plugin works consistently if the groups section referenced is commented out, the original issue was closed incorrectly blaming rate limiting from CloudFlare.  It is inconsistent because not all stories have groups.

**Comment by JimmXinu** [comment]
Thanks for this pointing out.  I was hasty in dismissing the `Expecting value: line 1 column 1 (char 0)` problem as just CF being CF.

As a general rule, I prefer to error out rather than catch and ignore problems.  I've seen too much time spend trying to figure out 'what am I doing wrong' when it's not the user's fault.

I think a better solution is to strip off the HTML when it's JSON in a flaresolverr response--there are other adapters that use JSON.  But with an off switch in case it causes other problems.

I've coded and posted test versions with such a fix.  It does rely on the string `<div class=\"json-formatter-container\">` being the JSON response identifier, which could potentially change.

**Comment by JimmXinu** [comment]
Interesting.  For me, this fix works on your example, as well as the three examples from the [other issue](https://github.com/JimmXinu/FanFicFare/issues/1100#issuecomment-2323505394).

Considering 'groups'  are the only metadata collected from JSON, and that I can't even find where a story's groups are shown on the site, I'm inclined to remove that code entirely if it's unreliable.

**Comment by JimmXinu** [comment]
Sorry, I assume people are familiar with [where I post test versions](https://github.com/JimmXinu/FanFicFare/#test-versions).

I'm using FlareSolverr 3.3.21 windows binary.  Unless the docker version uses a different browser, I would expect it to be the same.

But if you tell me it still doesn't work in general with stories with "groups", I will remove that.

**Comment by JimmXinu** [comment]
A column labeled 'Featured In' 3 PgDn's from the top did not leap out at me as 'groups'.  And not having examples of both initially, I assumed the non-JSON groups code was for backward compatibility, not short groups lists.

I've gone ahead with your suggestion of just catching any exceptions in the JSON processing.

There's a good chance I will regret it some day when someone wants to know why they don't get all the groups and have forgotten why.  But the hope that perhaps one day CF will stop interfering convinced me to not just tear it out entirely.

Test versions in [the usual places](https://github.com/JimmXinu/FanFicFare/#test-versions).

**Comment by JimmXinu** [comment]
It's site specific metadata that isn't anywhere in Calibre's metadata unless you configure it to be.  There's tons of options.  

You probably want `custom_columns_settings` or `include_subject_tags` settings.  

It's been discussed many times in the [plugin thread](https://www.mobileread.com/forums/showthread.php?t=259221).
