### ISSUE TITLE
Invalid credentials error on fetch from IMAP same as#437

### ISSUE THREAD

**Issue by Perseus1702** [JimmXinu/FanFicFare#1127]
Same issue as #437 I have tried everything including CLI but it is not working. I don't have any proxy or antivirus, tried restarting calibre and rebooting computer, tried disabling firewall as well, I have no idea what a DNS cache is. Google has removed the Less secure app access settings completely. The email works on Outlook(new). I haven't used any other IMAP client. 
Here is the full log:

calibre, version 7.20.0
ERROR: Unhandled exception: <b>error</b>:b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

calibre 7.20  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: D:\Devanshu\Calibre\calibre.exe
Successfully initialized third party plugins: Count Pages (1, 13, 6) && FanFicFare (4, 39, 0) && Generate Cover (2, 3, 4)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 592, in get_urls_from_imap_menu
  File "C:\Users\user\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\geturls.py", line 189, in get_urls_from_imap
  File "imaplib.py", line 612, in login
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

Similar error from CLI as well

**Comment by JimmXinu** [comment]
Are you using an outlook email account?    It sounds alot like #1093.

I'm [told that outlook, et al](https://www.mobileread.com/forums/showthread.php?p=4457927&postcount=10025) don't allow third party app logins anymore.  

I'm not aware of anyone finding a workaround.  Best suggestion has been to use a GMX or Gmail account.  And you need to use 2FA and  [Google App Passwords](https://support.google.com/accounts/answer/185833#app-passwords) with Gmail.

If you aren't using an outlook account, if you have an `%` signs in your username or password, they need to be escaped in INI files as `%%`.

**Comment by Perseus1702** [comment]
No I am using a Gmail account, I can't use GMX in my country. No `%` signs in username or password. I am not using 2FA. I will try it out.

**Comment by Perseus1702** [comment]
Thank you very much. 2FA with App Passwords worked.

**Comment by nekogecko2** [comment]
> I'm not aware of anyone finding a workaround. Best suggestion has been to use a GMX or Gmail account. And you need to use 2FA and [Google App Passwords](https://support.google.com/accounts/answer/185833#app-passwords) with Gmail.

Thank you! This worked for my gmail account! Now I can use my old gmail account again that I made just for forwarding fanfic update emails to.

**Comment by bpothier** [comment]
Sadly it is not super easy/obvious to do, but for the adventurous you can use - https://github.com/simonrob/email-oauth2-proxy/ to act as an IMAP (not IMAPS, well not easily) proxy to OAUTH2 servers (gmail, outlook, yahoo, others).
