### ISSUE TITLE
Add support for https://www.furaffinity.net

### ISSUE THREAD

**Issue by Waterspark63** [JimmXinu/FanFicFare#1129]
I don't know if it's been asked before, as searching 'fa' or 'furaffinity' doesn't return any issues, but is there any possibility for FA to be added as a supported site? I understand if it's a bit to.. inconsistent to add as a site, but thought I'd ask just to have a definite answer.

**Comment by JimmXinu** [comment]
That looks like it's an image site with a minor side line in textual works.  I don't see any support for multi-chapter works beyond including the work 'Chapter' in titles.  And it isn't fanfiction.

Sorry, I'm not interested in adding this.
