### ISSUE TITLE
Add support for https://www.webnovel.com

### ISSUE THREAD

**Issue by tr13dm03** [JimmXinu/FanFicFare#1133]
It seems that whatever difficulties once existed with that domain (old closed issues) may have been reverted, I can pull chapters from it with curl from my terminal.

Chapter listing is also present as a JSON blob in said curl output, among other places.

**Comment by JimmXinu** [comment]
It's not a technical issue at this point.  In #1113 [I said before](https://github.com/JimmXinu/FanFicFare/issues/1113#issuecomment-2438408885):

> Webnovel's Author Benefit link specifically says that they pay the authors. FanFicFare is for freely available content. For legal and moral reasons, I'm not interested in adding paid sites.
> 
> See past discussions #1109 #440
