### ISSUE TITLE
Can the download option for Inkitt be added? 

### ISSUE THREAD

**Issue by ohlala94** [JimmXinu/FanFicFare#1134]
Hello! 

I just discovered FanficFare today and I'm in love, since I can save my favorite stories from Wattpad and read them offline! However, many authors I love have moved to Inkitt and I'm unable to download their works. 

I know nothing about coding, so if anyone can tell me of adding Inkitt is possible, I'd be the happiest person ever! 

Thanks in advance

**Comment by JimmXinu** [comment]
This has been discussed before and rejected as part of main stream FFF.  I don't want to add any new sites that are paid author content.  See #361 #1087 #1109 ([Discussion](https://github.com/JimmXinu/FanFicFare/pull/1109#issuecomment-2365228349))
