### ISSUE TITLE
Download from fimfiction.net failing with FlareSolverr

### ISSUE THREAD

**Issue by EtorixDev** [JimmXinu/FanFicFare#1135]
I downloaded the Docker image and started it. Opening `http://localhost:8191/` shows `"FlareSolverr is ready!"`. I tried adding `use_flaresolverr_proxy:true` to the website specific settings as well as to the global settings separately. I also tried specifying the address, port, and protocol settings as the Wiki says (despite not changing the defaults). But every time FanFicFare just opens up a login prompt 2 times in a row and then fails with `Failed to Login for URL: (...) with username: (...)`. 

The details I'm inserting are correct, I logged in with them in a browser to check. I also changed my password to not include any special characters at all. Also, I specify the exact same credentials in the `personal.ini` file under `username` and `password`, but it seems `use_flaresolverr_proxy` ignores them.

I'm on the latest stable FFF version, latest stable Flaresolverr version, and am trying to download from Fimfiction which I know recently has been having Cloudflare issues, which is why I'm trying to use FlareSolverr.

**Comment by JimmXinu** [comment]
Downloading using FlareSolverr still works for me for stories that don't require login.

It looks like FimF has added an additional POST step to login--sometimes.  I think it may also something from CloudFlare.  It might be possible to automate it, but since it's a deliberate auto-automation feature...

On the other hand, FimF has its own download feature, so you are not dependent on FFF to download and read stories from there.

**Comment by EtorixDev** [comment]
Can you share which FlareSolverr version you're using or any config you've changed? I have tried many stories off of the front page and every single one prompts for a login inside of Calibre with Fanficfare but none prompt for a login in an incognito tab to download. It just lets me download no questions asked. This is true across all ratings from everyone to mature.

Also I use Calibre as a library to keep track of progress and FFF to look for updates. I don't use it to read. I can and do read in the browser just fine.

**Comment by JimmXinu** [comment]
flaresolverr-v3.3.21, which is just what I had handy--not sure it's most recent.

Do you have `always_login:true` in personal.ini?  That would require password every time.

**Comment by EtorixDev** [comment]
I don't have `always_login` set at all, no.

3.3.21 does seem to be the most recent, it's what I downloaded. Interestingly I downloaded 1.2.9 as linked in the Wiki and it didn't prompt me to login. FlareSolverr got challenged (it didn't seem to with 3.3.21) and completed the challenge, but FFF errored with "This story does not exist" on every link provided.

**Comment by EtorixDev** [comment]
I tried *removing* my `username` and `password` fields and that worked. It now downloads just fine, even mature stories which I don't understand. It doesn't prompt me to login either.

**Comment by JimmXinu** [comment]
It looks like, unlike most site adapters, for FimF FFF always tries to login in if there are `username` & `password` settings.  I've implemented a change to honor `always_login` instead.  

I'm not really interested in trying to figure out the login issue for the few stories it would apply to right now.
