### ISSUE TITLE
Minor: has_key is deprecated

### ISSUE THREAD

**Issue by fitzmorrispr** [JimmXinu/FanFicFare#116]
On some stories from some sites, i get a warning from beautiful soup that has_key is deprecated, and should be replaced with has_attr
(Indeed, in site-packages/bs4/element.py:1527, you can see that has_key just passes everything through to has_attr)

While it turns out there's a bunch of instances of has_key to replace, mostly in the code for generating plaintext ebooks, the one that I notice during my day-to-day use is in utf8FromSoup, base_adapter.py:576

**Comment by JimmXinu** [comment]
34333a1c480dae51f43fbc4583b5ddfe33beeac5
