### ISSUE TITLE
 Each story part should have a label like this "Session A62:" but it is lost on import.

### ISSUE THREAD

**Issue by Kurt001** [JimmXinu/FanFicFare#119]
When importing this story http://www.mcstories.com/NoMoreLimits/index.html
Each part should have a label like this "Session A62:" but it is lost on import.

**Comment by JimmXinu** [comment]
Fixed in next release.
047a03c61c90276eb707f5688f8716128a0ea72a
Some mcstoriescom stories include <h3> tags that aren't title/chapter/byline.
