### ISSUE TITLE
I installed FanFicFare but can't see it in Calibre

### ISSUE THREAD

**Issue by skuttan97** [JimmXinu/FanFicFare#122]
Hi
My problem is that I can't see fanficfare at all in calibre - I can install and uninstall it but nothing else. It's like fanficfare doesn’t even exist other than in the list of my "add-ons” or the list of possible "add-ons" to install. I have tried to uninstall both fanficfare and calibre and then installing them again (I have done this separately and at the same time). I have also tried to restart my computer. Nothing of this have worked. How can I fix this? I used to really love using fanficfare!

Hope someone can help me!

**Comment by JimmXinu** [comment]
If FanFicFare is appearing on your list of installed User Plugins, it's installing, it's just not appearing where you expect it.  

When you go into Calibre's Preferences, Toolbar, there's a drop down 'Click to choose menu or toolbar to customize'.  It's not uncommon for users not to realize that there are different versions for when a device is connected.  So if you put it on one toolbar, but not the other, or on a context menu instead of toolbar, you might not see it where you expect.

If that doesn't help, restart Calibre in debug mode (Calibre Preferences dropdown), then quit again to get the debug log and see what it says.  You can post it here if you need help figuring it out.

**Comment by skuttan97** [comment]
FanFicFare doesn't appear here "Click to choose menu or toolbar to customize" ether, (in any toolbar).

Here is the debug log:
calibre Felsökningslogg
calibre 2.45  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: ADLIBRIS_SE && Find Duplicates && FanFicFare
Starting up...
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 152, in __init__
  File "site-packages\calibre\gui2\ui.py", line 166, in init_iaction
  File "calibre_plugins.fanficfare_plugin.__init__", line 107, in load_actual_plugin
  File "site-packages\calibre\customize\__init__.py", line 582, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 95, in <module>
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.fanficfare_plugin.config", line 1239, in <module>
ValueError: incomplete format
Started up in 17.83 seconds with 1743 books
SMART_DEV (   0.08:  0.083) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.59:  0.829) startup_on_demand listening on port 9090
SMART_DEV (   1.94:  0.034) _attach_to_port try ip address "" on port 54982
SMART_DEV (   2.25:  0.001) startup_on_demand broadcast socket listening on port 54982
SMART_DEV (   3.66:  1.131) run All IP addresses {'{AEEB8052-750B-45C7-8B52-CAB56B8F5AB1}': [{'netmask': '255.255.255.0', 'broadcast': '192.168.0.255', 'addr': '192.168.0.102'}], '{85F27125-8569-4223-ABC5-DC72B32509B9}': [{'addr': '169.254.215.49'}], '{140FEAEB-9079-412D-A709-B40C34AB5C42}': [{'addr': '169.254.108.175'}], '{C6EC40D9-D2F9-44C4-B7A7-95AB588E5298}': [{'addr': '169.254.36.106'}], '{BBED3E08-0B41-11E3-8249-806E6F6E6963}': [{'netmask': '255.0.0.0', 'broadcast': '127.255.255.255', 'addr': '127.0.0.1'}]}

**Comment by skuttan97** [comment]
Here is the debug report for Version: 2.57.1:
calibre Felsökningslogg
calibre 2.57.1  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: Find Duplicates && ADLIBRIS_SE && FanFicFare
Registering with default programs...
Starting up...
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 152, in __init__
  File "site-packages\calibre\gui2\ui.py", line 166, in init_iaction
  File "calibre_plugins.fanficfare_plugin.__init__", line 107, in load_actual_plugin
  File "site-packages\calibre\customize\__init__.py", line 603, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 95, in <module>
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.fanficfare_plugin.config", line 1239, in <module>
ValueError: incomplete format
Registered with default programs in 15.0 seconds
SMART_DEV (   0.01:  0.014) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.82:  0.931) startup_on_demand listening on port 9090
SMART_DEV (   2.28:  0.024) _attach_to_port try ip address "" on port 54982
SMART_DEV (   2.71:  0.000) startup_on_demand broadcast socket listening on port 54982
SMART_DEV (   4.28:  1.176) run All IP addresses {'{C6EC40D9-D2F9-44C4-B7A7-95AB588E5298}': [{'addr': '169.254.36.106'}], '{140FEAEB-9079-412D-A709-B40C34AB5C42}': [{'addr': '169.254.108.175'}], '{85F27125-8569-4223-ABC5-DC72B32509B9}': [{'addr': '169.254.215.49'}], '{AEEB8052-750B-45C7-8B52-CAB56B8F5AB1}': [{'broadcast': '192.168.0.255', 'netmask': '255.255.255.0', 'addr': '192.168.0.102'}], '{BBED3E08-0B41-11E3-8249-806E6F6E6963}': [{'broadcast': '127.255.255.255', 'netmask': '255.0.0.0', 'addr': '127.0.0.1'}]}
Started up in 28.89 seconds with 1743 books

**Comment by JimmXinu** [comment]
There's an error in the Swedish translation file that causes that problem.

Attached is a version with a quick fix.  I need to get the translation fixed in Transifex for a long term fix, but it will be functionally identical.

[FanFicFare.zip](https://github.com/JimmXinu/FanFicFare/files/288890/FanFicFare.zip)

**Comment by skuttan97** [comment]
Thank you so much for the very quick help! It works great!
