### ISSUE TITLE
[Calibre] Ultra-long fics seem to break after a certain length

### ISSUE THREAD

**Issue by jayands** [JimmXinu/FanFicFare#123]
[The Chase - kudzuhaiku.epub.zip](https://github.com/JimmXinu/FanFicFare/files/334285/The.Chase.-.kudzuhaiku.epub.zip)

Specifically, the fic in question is [The Chase][the chase] by kudzuhaiku on FimFiction. I know it's not FimFiction, because other files update. I was considering just removing it and starting over, but I already have this much, and I'm somewhere in the 710s, chapter-wise, so it doesn't *immediately* affect me, but it is a possible issue. The log says, in the comment column, "File is not a zip file."

Furthermore, it's a FFF-produced epub; Fimfiction strips all the styling from their native epubs, for some reason, so I've always preferred your output to theirs.

[the chase]: http://www.fimfiction.net/story/185272/

**Comment by JimmXinu** [comment]
I was able to download that story (it took +2 hours...), 'update' it to 923 chapters, then update to add chapter 924 and it all worked.

However, I did see that error when trying to update _your_ epub.  I don't know how it would have happened, but there appears to be some minor corruption with your epub file that is preventing FFF from reading it to see how many chapters it has.  

Calibre's tools use a modified ZipFile class that is apparently more forgiving.  I was able to use Calibre's Edit Book tool to open, minimally edit (delete an extra newline) and save your epub and then FFF could update it.  I suggest you do that.

Unless you can show FFF is outputting epubs that it can't read back again regularly, I'm going to assume this is a one time fluke.

(BTW, You don't need to put epubs inside zip files--they're already zipped.  If you rename an epub to .zip, you can view the contents like any zip file.)
