### ISSUE TITLE
July 18th Django 1.2 removal deadline (Web Service only)

### ISSUE THREAD

**Issue by botmtl** [JimmXinu/FanFicFare#124]
(just in case you missed the memo - I think the app is going to blow up in 10 days from today.)

Support for versions 1.2 and 1.3 of the Django packaged libraries will be removed on **July 18, 2016**. We recommend that you move to newer versions of Django, such as Django 1.4 or later.  [ref](https://cloud.google.com/appengine/docs/deprecations/django).

**Comment by cryzed** [comment]
@JimmXinu, do you have any usage statistics regarding the web application? Are people really using it? I would have assumed nearly all users use the Calibre plugin.

**Comment by botmtl** [comment]
I truly have no idea.  I made a duplicate for myself, but it's not as if I ever use it.

**Comment by cryzed** [comment]
I'd suggest possibly removing it if it turns out that no one is using it anymore. Let's wait what Jimm has to say.

**Comment by hawkrives** [comment]
I use it occasionally to download a story directly to my phone, but that's maybe once every few months. I wouldn't be terribly put out if it was shut down.

**Comment by JimmXinu** [comment]
FanFicFare doesn't use Django.  It included Django in app.yaml to shut up a warning 'way back when'.  And even that seems to have been commented out some time ago (from main.py):
```
## Just to shut up the appengine warning about "You are using the
## default Django version (0.96). The default Django version will
## change in an App Engine release in the near future. Please call
## use_library() to explicitly select a Django version. For more
## information see
## http://code.google.com/appengine/docs/python/tools/libraries.html#Django"
## Note that if you are using the SDK App Engine Launcher and hit an SDK
## Console page first, you will get a django version mismatch error when you
## to go hit one of the application pages.  Just change a file again, and
## make sure to hit an app page before the SDK page to clear it.
#os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'
#from google.appengine.dist import use_library
#use_library('django', '1.2')
```
But thanks for the heads up, I'll remove it before then.

As for the web service itself, yes there are people who use it.  Enough that the daily free quota is still exhausted everyday as far as I can tell with a couple minutes of looking.

As long as it's low effort for me, I'll keep updating the web service version for those that use it.  But I'm on record as not being interested in spending money on it or running donations collection for it.
