### ISSUE TITLE
Broken in Termux

### ISSUE THREAD

**Issue by tidux** [JimmXinu/FanFicFare#126]
![screenshot_20160718-000706](https://cloud.githubusercontent.com/assets/1330562/16907889/1accc052-4c7c-11e6-8158-ee69f9463fd7.png)

[Termux](http://termux.com) is a vaguely Debian like environment for Android.  Installing via `pip2 install fanficfare` worked but attempting to use the script resulted in the pictured stack trace.

**Comment by JimmXinu** [comment]
That's a bug in the BeautifulSoup4 / html5lib interactions.  It looks like it was [reported and fixed](https://bugs.launchpad.net/beautifulsoup/+bug/1603299), but I don't know how long it will take for the update to get down to you.

I've seen reference to it working again with a forced downgrade of html5lib, like so:
`pip install --upgrade html5lib==1.0b8`

Regardless, this isn't a problem with FanFicFare itself, so I'm closing the issue.
