### ISSUE TITLE
KeyError: u'tags' after trying to update an anthology

### ISSUE THREAD

**Issue by DarkDeyus** [JimmXinu/FanFicFare#131]
calibre, version 2.65.1
ERROR: Unknown Exception: <b>KeyError</b>:u'tags'

calibre 2.65.1 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 0, 8) && FanFicFare (2, 3, 6) && EpubSplit (2, 1, 2) && Kindle Collections (1, 7, 17) && Find Duplicates (1, 6, 2) && EpubMerge (2, 0, 13)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\proceed.py", line 206, in do_ask_question
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1759, in do_download_merge_update
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 2473, in merge_meta_books
KeyError: u'tags'

This is what i got after letting this plugin update my anthology. This error occures after the confirmation of updating the file.

**Comment by JimmXinu** [comment]
What are the story URLs (or series URL) you're seeing this with?

I'm trying to duplicate the problem and so far, I can't.

**Comment by JimmXinu** [comment]
2 weeks without response to request for more info.
