### ISSUE TITLE
Issue with Import Image

### ISSUE THREAD

**Issue by MrTyton** [JimmXinu/FanFicFare#135]
When installing fanficfare on a blank system, I ran into import errors when using cli.py, at line [305](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/cli.py#L305). This is because the line `import Image` is only allowed with PIL, which has depreciated into Pillow, which requires the line `from PIL import Image` instead. If a user has PIL installed on their system, there should be no difference, but if they have Pillow then this line is required.

**Comment by JimmXinu** [comment]
I confess I don't test image processing in CLI often, so thanks for the heads up.

"Add support for Pillow (vs PIL) image lib in CLI." in c4153ac
