### ISSUE TITLE
Issue in the CLI version

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#136]
In the CLI version I have set it up so that in gets the urls from a txt file using the --infile option

The new update though seems to demand to include a url during execution of the exe file.

If i just run the command prompt I have been using it gives me a message like:

> Usage: fanficfare [options] [STORYURL]...
> 
> Options:....

If I add a story url though it works properly (it downloads both the url I gave in command prompt as well as the urls in the txt file)

**Comment by JimmXinu** [comment]
I thought I'd tested all those cases.  Sorry about that.  I've pushed out a pip version 2.4.3 (99e4ea9) to fix it.  You should be able to update to it now.
