### ISSUE TITLE
New versions are not tagged

### ISSUE THREAD

**Issue by eli-schwartz** [JimmXinu/FanFicFare#138]
When releasing a CLI-only update, please tag the new version. :smiley: 

My [ArchLinux package](https://aur.archlinux.org/packages/fanficfare) pulls directly from GitHub, partly because attempting to programmatically download from PyPI is [kind of painful](https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package) unless you use pip...

Without having an actual tagged release for a release, it becomes harder to update the package. :disappointed:

**Comment by JimmXinu** [comment]
I've added a [tag for v2.4.3](https://github.com/JimmXinu/FanFicFare/releases/tag/v2.4.3) as requested.

**Comment by eli-schwartz** [comment]
Thanks!
