### ISSUE TITLE
CLI Error using input TXT

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#140]
Ok I have 2 bug's to mention

This is the first one:

When downloading stories using a txt, depending on the last character of the input, the CLI might not download the correct story.
Specificaly if the last line of the input txt has the url:

> http://archiveofourown.org/works/4833515

the cli will instead try to download 

> http://archiveofourown.org/works/483351

Similarly if the last line is the url:

> https://www.fanfiction.net/s/11515678

it will try to download

> https://www.fanfiction.net/s/1151567

and fail since that story does not exist.

On the other hand urls like 

> https://www.fanfiction.net/s/11515678/1/This-Bites
> https://www.fanfiction.net/s/11515678/1/
> https://www.fanfiction.net/s/11515678/

and

> http://archiveofourown.org/works/4833515/chapters/11070479
> http://archiveofourown.org/works/4833515/

are fine because in those cases the url to be downloaded basically becomes

> https://www.fanfiction.net/s/11515678/1/This-Bite
> https://www.fanfiction.net/s/11515678/1
> https://www.fanfiction.net/s/11515678

and

> http://archiveofourown.org/works/4833515/chapters/1107047
> http://archiveofourown.org/works/4833515

and those redirect to the correct stories.

**Note:** The above obviously applies if the file does _not_ end in a newline. If there _is_ a newline then obviously that newline is the last character in the txt and it is that newline that is deleted

**Comment by JimmXinu** [comment]
One could argue that that [all lines in text files require newlines](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206), even the last one.

But since I can trivially create such a file with MS Notepad, clearly not everyone agrees.

Fixed in 8a84043d294dd720332e3614fcd5f2906238b4e7
