### ISSUE TITLE
CLI Error using post_process_cmd

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#141]
Ok I have 2 bug's to mention

This is the second one:

First of all I should mention that I am not sure if this a FanficFare error or a python error or a microsoft cmd error. However it _is_ something that _could_ be dealt with by FanficFare.

I have mentioned this before in another issue (#137) but I am currently using post_process_cmd to post 

> Downloaded Story: "${title}" by "${author}"

when a story is downloaded using CLI.

However when I tried to download 

> https://www.fanfiction.net/s/10752206/

I instead get the following error message

> Traceback (most recent call last):
>   File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "c:\python27\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "c:\Python27\Scripts\fanficfare.exe\__main__.py", line 9, in <module>
>   File "c:\python27\lib\site-packages\fanficfare\cli.py", line 237, in main
>     passed_personalini)
>   File "c:\python27\lib\site-packages\fanficfare\cli.py", line 383, in do_download
>     call(string.Template(adapter.getConfig('post_process_cmd')).substitute(metadata), shell=True)
>   File "c:\python27\lib\subprocess.py", line 522, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "c:\python27\lib\subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "c:\python27\lib\subprocess.py", line 928, in _execute_child
>     args = '{} /c "{}"'.format (comspec, args)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 51: ordinal not in range(128)

I have checked and **encode character u'\u2026'** is referring to the character **…** in the story's title "Beyond the Outer Gates Lies… A high school library?"
So the problem is because the character … (and probably others) can not be printed.
Like I said this might be an issue of Python or of the command prompt

On the other hand the resulting epub created has the filename:
Xavon Wrentaile - Beyond the Outer Gates Lies_ A high school library_-ffnet_10752206.epub
So the **…** character (as well as the **?** character) have been replaced with **_** since windows does not accept those characters as valid in filenames.

So even if the above error is not caused by FanficFare, it might be possible to parse the output of  post_process_cmd through a similar function and replace characters like **…** and **?** with **_** just like in the filename output

**Comment by JimmXinu** [comment]
Change f115d68e524d1acc7d2f205c8bc1996a0abd7833 adds a new `post_process_apply_filename_safepattern` setting to apply the same `output_filename_safepattern` to `post_process_cmd` metadata.

I originally was going to set `post_process_apply_filename_safepattern:true` by default, but testing shows it isn't necessary for my Linux system, so I'm making it `false` by default so the behavior doesn't change for other users. c7bbb765b29b6ecfed97d3b92f06804c4a6af2be
