### ISSUE TITLE
fanfiction.net https certificate error

### ISSUE THREAD

**Issue by Pheoxy** [JimmXinu/FanFicFare#142]
Been getting this a lot. Sometimes it works sometimes just this.

`<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>`

**Comment by JimmXinu** [comment]
There's an [FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#im-having-ssl-certificate-errors--help) on that.

If it doesn't solve your problem, you can reopen in the issue.
