### ISSUE TITLE
Adult-Fanfiction Issue

### ISSUE THREAD

**Issue by xd1986k** [JimmXinu/FanFicFare#145]
Hello. 
Receiving this error on a few fics.
http://hp.adult-fanfiction.org/story.php?no=600022799 Story does not exist: (Did not find story in author story list: http://members.adult-fanfiction.org/profile.php?no=1296851847&view=story&zone=hp&page=1)

**Comment by gcomyn** [comment]
I have worked this out, but am having a problem sending in the pull request... *sigh*... working on it right now, hopefully will be done tonight.

**Comment by JimmXinu** [comment]
Fixed in 1e0cc699c2b2c555e6ca7a459c202092dd10bbf4
Thanks gcomyn!
