### ISSUE TITLE
CLI bug using post_process_cmd

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#151]
I have been using post_process_cmd and posting a custom message.
There was an error with some unprintable characters (#141) but it has since been fixed using the new command post_process_apply_filename_safepattern:true in the ini file

However I have noticed that among the unsafe characters is **:** 
Which is correct since the **:** is not acceptable for a windows filename.

However some metadata like the date the fic has been updated last is printed like:

> 2016-11-24 11_00_35

instead of the normal:

> 2016-11-24 11:00:35

Trying to add **:** as a safe character in output_filename_safepattern would not work since output_filename_safepattern applies to both the output_filename and the post_process_cmd.

Is it possible to find some way to separate those 2 cases.
Like adding a variable output_cmd_safepattern which is the same as output_filename_safepattern by default and have each process using a different one.
That way if the user wants he can edit output_cmd_safepattern and add **:** as a safe-to-print character while still replacing it on the filename

**Comment by JimmXinu** [comment]
Okay, but I'm not going to maintain backward compatibility:

Replace post_process_apply_filename_safepattern with post_process_safepattern so it can have its own pattern. 34ec12ea1e8f89174b49b52633bb0c39574191fc

This will be in the next release.
