### ISSUE TITLE
tthfanfic went ssh, breaks fanficfare

### ISSUE THREAD

**Issue by thgrendel** [JimmXinu/FanFicFare#155]
I get the Bad Story URL error.

Is that something that can be hacked locally?

**Comment by JimmXinu** [comment]
Already fixed, but not yet released.  And I see that hadn't pushed the changeset yet.  Sorry about that.

e229a3b3a0860b1bb9dbfcf53b7921ec0dced9d4

There's a [test version of the plugin](http://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2) posted.

**Comment by thgrendel** [comment]
Thanks. That was easy :)
 I patched my local version as I use the cli for my homebuilt toolchain and it works just fine.
