### ISSUE TITLE
CLI: Fanfiction.net check_next_chapter breaking

### ISSUE THREAD

**Issue by MrTyton** [JimmXinu/FanFicFare#159]
So I'm posting this here, I'll try and figure out what's wrong:

If you set in personal.ini the following

```
[www.fanfiction.net]
check_next_chapter:true
```

then the following happens

`MrTyton@Ryouzanpakuto:~/Scripts/Fanfiction/fanficdownload$ fanficfare "www.fanfiction.net/s/12105910"
Traceback (most recent call last):
  File "/usr/local/bin/fanficfare", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/fanficfare/cli.py", line 237, in main
    passed_personalini)
  File "/usr/local/lib/python2.7/dist-packages/fanficfare/cli.py", line 327, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/local/lib/python2.7/dist-packages/fanficfare/adapters/base_adapter.py", line 451, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/local/lib/python2.7/dist-packages/fanficfare/adapters/adapter_fanfictionnet.py", line 143, in doExtractChapterUrlsAndMetadata
    except e:
UnboundLocalError: local variable 'e' referenced before assignment
`

The same output occurs if you try to do `fanficfare -u --update-cover "www.fanfiction.net/s/12105910"`, which is my usual case, but the previous case seems more prone as to why.

This occurs if there is no epub that it is updating. I currently don't have a test case to see what happens if there is an epub that it is trying to update.

This is likely because of the code [here](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/adapters/adapter_fanfictionnet.py#L143), I don't think you're allowed to just do `except e`, I'm pretty sure it just has to be `except Exception as e`.

**Comment by JimmXinu** [comment]
Agreed--that line needs to be fixed. (c4e10b6)

But it only happens when some other error has occurred, and I don't see it happening for me.

**Comment by MrTyton** [comment]
Again, I think that it's tied to the flag check_next_chapter, since when that's set to True it throws the error. I'll do more testing to see if there's actually anything that needs fixing.

**Comment by JimmXinu** [comment]
Obviously--the entire try/except structure is inside the check_next_chapter if clause.

But that except clause is only called if there's some exception (other than HTTPError), and I'm not seeing it.

However, while testing it more thoroughly, I did see it still had another problem that I've now fixed. (21fa480)
