### ISSUE TITLE
xenforoforum adapter issue

### ISSUE THREAD

**Issue by sarf** [JimmXinu/FanFicFare#161]
Hi!

I am trying to download Taylor Varga (a surprisingly good slice-of-life Worm fanfiction with giant lizards), and have been getting the same error consistently with it. Note that the Taylor Varga fanfiction is very very long (400+ pages) and I can download other stories on spacebattles without problems.

Taylor Varga URL: https://forums.spacebattles.com/threads/taylor-varga-worm-luna-varga.398991/
Error: 'NoneType' object has no attribute 'find'
`Download 1 FanFiction Book(s)
FFF: INFO: 2017-01-29 22:31:32,677: calibre_plugins.fanficfare_plugin.jobs(50): FanFicFare v2.8.0
FFF: INFO: 2017-01-29 22:31:32,677: calibre_plugins.fanficfare_plugin.jobs(54): Adding jobs for URLs:
FFF: INFO: 2017-01-29 22:31:32,677: calibre_plugins.fanficfare_plugin.jobs(56): https://forums.spacebattles.com/threads/398991/
FFF: INFO: 2017-01-29 22:32:02,529: calibre_plugins.fanficfare_plugin.jobs(92): Logfile for book ID 71 (Taylor Varga)
FFF: INFO: 2017-01-29 22:32:02,530: calibre_plugins.fanficfare_plugin.jobs(93): url:(https://forums.spacebattles.com/threads/398991/) id:(71)
FFF: INFO: 2017-01-29 22:31:33,767: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(199): url: https://forums.spacebattles.com/threads/398991/
FFF: DEBUG: 2017-01-29 22:31:33,767: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter(278): #####################################
pagecache HIT: https://forums.spacebattles.com/threads/398991/
FFF: INFO: 2017-01-29 22:31:33,769: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(204): use useurl: https://forums.spacebattles.com/threads/taylor-varga-worm-luna-varga.398991/
FFF: DEBUG: 2017-01-29 22:31:34,227: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter(278): #####################################
pagecache HIT: https://forums.spacebattles.com/threads/taylor-varga-worm-luna-varga.398991/threadmarks
FFF: INFO: 2017-01-29 22:31:45,058: calibre_plugins.fanficfare_plugin.jobs(268): Do update - epub(159) vs url(162)
FFF: INFO: 2017-01-29 22:31:45,058: calibre_plugins.fanficfare_plugin.jobs(269): write to C:\Users\Anders\AppData\Local\Temp\calibre_xk1me_\fanficfare_vepl8b\Taylor Varga-mp3.1415player-ys6pbz.epub
FFF: INFO: 2017-01-29 22:31:45,059: calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer(179): Save directly to file: C:\Users\Anders\AppData\Local\Temp\calibre_xk1me_\fanficfare_vepl8b\Taylor Varga-mp3.1415player-ys6pbz.epub
FFF: DEBUG: 2017-01-29 22:31:47,296: calibre_plugins.fanficfare_plugin.fanficfare.story(92): image used unchanged
FFF: DEBUG: 2017-01-29 22:31:47,299: calibre_plugins.fanficfare_plugin.fanficfare.story(92): image used unchanged
FFF: DEBUG: 2017-01-29 22:31:47,301: calibre_plugins.fanficfare_plugin.fanficfare.story(92): image used unchanged
FFF: DEBUG: 2017-01-29 22:31:47,302: calibre_plugins.fanficfare_plugin.fanficfare.story(92): image used unchanged
FFF: DEBUG: 2017-01-29 22:31:47,303: calibre_plugins.fanficfare_plugin.fanficfare.story(92): image used unchanged
FFF: DEBUG: 2017-01-29 22:31:49,638: calibre_plugins.fanficfare_plugin.fanficfare.story(92): image used unchanged
FFF: INFO: 2017-01-29 22:31:52,493: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: INFO: 2017-01-29 22:31:52,494: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: DEBUG: 2017-01-29 22:31:52,496: calibre_plugins.fanficfare_plugin.fanficfare.story(92): image used unchanged
FFF: INFO: 2017-01-29 22:31:52,496: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: INFO: 2017-01-29 22:31:52,499: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: INFO: 2017-01-29 22:31:56,793: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: INFO: 2017-01-29 22:31:56,795: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: INFO: 2017-01-29 22:31:56,796: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: INFO: 2017-01-29 22:31:56,801: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: INFO: 2017-01-29 22:31:57,743: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: DEBUG: 2017-01-29 22:31:57,747: calibre_plugins.fanficfare_plugin.fanficfare.story(92): image used unchanged
FFF: INFO: 2017-01-29 22:31:57,749: calibre_plugins.fanficfare_plugin.fanficfare.story(1141): Failed to load or convert image, skipping:
failedtoload
Exception: Previously failed to load
FFF: DEBUG: 2017-01-29 22:31:57,950: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(340): Getting chapter text from: https://forums.spacebattles.com/posts/30855757/ index: 159
FFF: DEBUG: 2017-01-29 22:31:57,950: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(351): USE READER MODE
FFF: DEBUG: 2017-01-29 22:31:57,950: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(361): Reader URL to: https://forums.spacebattles.com/threads/398991/reader?page=16
FFF: DEBUG: 2017-01-29 22:31:57,950: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter(288): #####################################
pagecache MISS: https://forums.spacebattles.com/threads/398991/reader?page=16
FFF: DEBUG: 2017-01-29 22:32:02,278: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(367): anchorid: post-30855757
FFF: INFO: 2017-01-29 22:32:02,309: calibre_plugins.fanficfare_plugin.jobs(318): Exception: {u'author': [u'mp3.1415player'], u'outfile': u'C:\\Users\\Anders\\AppData\\Local\\Temp\\calibre_xk1me_\\fanficfare_vepl8b\\Taylor Varga-mp3.1415player-ys6pbz.epub', u'title': u'Taylor Varga', u'tags': [u'Worm', u'Worm Altpower', u' Luna Varga', u'Worm Crossover', u'FanFiction', u'Worm Au'], u'url': u'https://forums.spacebattles.com/threads/398991/', u'good': False, u'added': False, u'epub_for_update': u'C:\\Users\\Anders\\AppData\\Local\\Temp\\calibre_xk1me_\\fanficfare_vepl8b\\old-71-dh4dx0.epub', u'username': 'NoneGiven', u'timestamp': datetime.datetime(2017, 1, 29, 22, 31, 33, 761000, tzinfo=SafeLocalTimeZone()), u'comment': u"'NoneType' object has no attribute 'find'", u'password': '', u'pubdate': datetime.datetime(2016, 7, 10, 17, 59, tzinfo=SafeLocalTimeZone()), u'site': 'forums.spacebattles.com', u'calibre_columns': {}, u'showerror': True, u'comments': u'<div class="messageText SelectQuoteContainer ugc baseHtml"> <span>This introduction may change as time goes on, as I will answer common questions and address issues here, as well as announce the status of the story should it change. So if you get puzzled, read it again to see if it\'s been updated.</span><br>\n<br>\nSince all the cool kids seem to be doing it these days I thought I might take a stab at a Worm fic. Actually I have three started for various reasons, but this </div></html>', u'icon': u'dialog_error.png', u'end': None, u'status': u'Error', u'updatedate': datetime.datetime(2017, 1, 27, 15, 57, tzinfo=SafeLocalTimeZone()), u'calibre_id': 71, u'publisher': u'forums.spacebattles.com', u'all_metadata': {'description': u'<div class="messageText SelectQuoteContainer ugc baseHtml"> <span>This introduction may change as time goes on, as I will answer common questions and address issues here, as well as announce the status of the story should it change. So if you get puzzled, read it again to see if it\'s been updated.</span><br/>\n<br/>\nSince all the cool kids seem to be doing it these days I thought I might take a stab at a Worm fic. Actually I have three started for various reasons, but this </div>', 'authorHTML': u"<a class='authorlink' href='https://forums.spacebattles.com/members/mp3-1415player.322925/'>mp3.1415player</a>", 'seriesUrl': '', 'authorId': u'mp3-1415player.322925', 'title': u'Taylor Varga', 'langcode': '', 'formatext': '', 'characters': u'', 'tagsfromtitle': u'Worm, Luna Varga', 'storyUrl': u'https://forums.spacebattles.com/threads/398991/', 'siteabbrev': u'fsb', 'version': u'FanFicFare v2.8.0', 'formatname': '', 'numWords': '', 'authorUrl': u'https://forums.spacebattles.com/members/mp3-1415player.322925/', 'ships': u'', 'numChapters': u'162', 'category': u'', 'dateUpdated': u'2017-01-27 15:57', 'extratags': u'FanFiction', 'storyId': u'398991', 'site': u'forums.spacebattles.com', 'cover_image': '', 'words_added': '', 'language': '', 'seriesHTML': '', 'author': u'mp3.1415player', 'forumtags': u'Worm Altpower, Worm Au, Worm Crossover', 'status': '', 'lastupdate': u'Last Update Year/Month: 2017/01, Last Update: 2017/01/27', 'genre': u'', 'warnings': u'', 'series': '', 'output_css': '', 'dateCreated': u'2017-01-29 22:31:27', 'datePublished': u'2016-07-10 17:59', 'rating': ''}, u'series': '', u'author_sort': [u'mp3.1415player'], u'listorder': 0, u'begin': None, u'is_adult': False}:'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.jobs", line 272, in do_download_for_worker
  File "calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer", line 198, in writeStory
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 394, in getStory
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 385, in getChapterTextNum
AttributeError: 'NoneType' object has no attribute 'find'

FFF: INFO: 2017-01-29 22:32:02,532: calibre_plugins.fanficfare_plugin.jobs(102): 
Download Results:
https://forums.spacebattles.com/threads/398991/ 'NoneType' object has no attribute 'find'

FFF: INFO: 2017-01-29 22:32:02,532: calibre_plugins.fanficfare_plugin.jobs(104): 
Successful:

FFF: INFO: 2017-01-29 22:32:02,532: calibre_plugins.fanficfare_plugin.jobs(105): 
Unsuccessful:
https://forums.spacebattles.com/threads/398991/
`

**Comment by JimmXinu** [comment]
This is a [known](https://www.mobileread.com/forums/showthread.php?p=3464268#post3464268) [issue](https://www.mobileread.com/forums/showthread.php?p=3466297&postcount=1786) with SB's implementation of Reader mode--for some stories they don't consistently put the same number of posts per page.  

So far, only a few stories have the issue.  I'm trying to come up with something, worst case FFF will just not use reader mode for SB in the next version.

In the meantime, you can either add this to your personal.ini:
```
[forums.spacebattles.com]
use_reader_mode:false
```

Or download it from [SV instead](https://forums.sufficientvelocity.com/threads/32119/).  (That's what I do.)
