### ISSUE TITLE
missing charset

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#168]
When downloading HTML with
```bash
fanficfare -f html 'https://archiveofourown.org/works/601124/chapters/1083962'
```
I get perfect HTML (which is awesome!, thank you), but without some character encoding indication. However, when I look at the HTML source of the page itself, I can see that it has
```html
<meta charset="utf-8"/>
```
in its ``<head>`` element. Could you please add it as well? Otherwise, I have plenty of characters corrupted because Firefox uses as default (correctly, it is according to W3C HTML standard) ``ISO 8859-1`` encoding, which leads to corrupted characters.

**Comment by JimmXinu** [comment]
Good point.  I didn't realize it wasn't.

I'll add that change(7b98e41) in the next release.

In the meantime, you could customize your output to add it, if you don't want to wait:
```
[html]
# metadata
file_start:<!DOCTYPE html>
 <html>
 <head>
 <meta charset="UTF-8">
 <title>${title} by ${author}</title>
 <style type="text/css">
 ${output_css}
 </style>
 </head>
 <body>
 <h1><a href="${storyUrl}">${title}</a> by ${authorHTML}</h1>
```
[Customize Output](https://github.com/JimmXinu/FanFicFare/wiki/CustomOutput#html)
