### ISSUE TITLE
Some kind of progress indication for CLI version

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#169]
I know you probably don’t want to include yet another dependency, but even the simplest of indicators (something like ``04/15 chapters downloaded") would be better than:
```
matej@mitmanek: epubs$ time fanficfare 'https://www.fanfiction.net/s/11858501/1/Aftershocks'

real	2m39.098s
user	0m5.705s
sys	0m0.081s
matej@mitmanek: epubs$ 
```
Really? A program which doesn’t make any noise for two minutes feels broken to me and ``Ctrl-C`` is not that far from my mind.

**Comment by hawkrives** [comment]
I add the `-v` flag when I use the fanficfare cli, personally.

**Comment by mcepl** [comment]
> I add the -v flag when I use the fanficfare cli, personally.

you mean ``-d``, right (``-v`` just prints the version)? Yeah, but that is really *debugging* output, too much for normal use, IMHO.

**Comment by hawkrives** [comment]
@mcepl Yes, you are correct. I apologize; I was working from memory.

**Comment by JimmXinu** [comment]
10aadfb907331843ffd54b9c6c4ba6341225df85
