### ISSUE TITLE
Support for http://gravitytales.com/

### ISSUE THREAD

**Issue by eFrysTon** [JimmXinu/FanFicFare#175]
Please consider adding support for http://gravitytales.com/

**Comment by gcomyn** [comment]
I'll look into... looks to be like webnovel and wuxia in html coding...

**Comment by eFrysTon** [comment]
More like webnovel than wuxiaworld. 

The TOC pages on gravity seem to be software generated, so they are consistent in format and always directly reflect newly posted chapters.

The TOC pages on wuxiaworld seem to be manually created/updated. They are inconsistent, get only sometimes updated, often contain wrong links, and some of them contain links to chapters which haven't been posted yet. Which means that they are unfortunately pretty useless for creating epubs and then updating them in the future (because either they only get updated every few weeks and you have to wait for new chapters to show up, or, worse, they referenced chapters which didn't exist yet, which got downloaded already with "nothing here" pages, and which don't get recognized as updated once posted).

**Comment by gcomyn** [comment]
I've seen that about wuxia, and there really isn't anything I can do about it code wise...

About gravity tales... since it is a script that generates the chapter lists, I can't see anyway for me to get the chapter list using FFF... unless Jimm knows how to run the script within the adapter...

This is the line that generates the chapter list:

`<script>ReactDOM.render(React.createElement(Components.ChapterGroupList, { novelId: 21, novelSlug: 'Chaotic-Lightning-Cultivation' }), document.getElementById("chapters"))</script>
`

So, it doesn't look like I can get this to work at this time... Sorry.

**Comment by eFrysTon** [comment]
Using the novelId (21), that seems to result in a request for http://gravitytales.com/api/novels/chaptergroups/21

which returns JSON encoded information about the chapter groups, with a ChapterGroupIdID listed for each.

Using that ChapterGroupID with http://gravitytales.com/api/novels/chaptergroup/82

then returns a JSON encoded list of chapters, with a title and url (fragment) for each.

**Comment by gcomyn** [comment]
Ok... I'll look into that... I'm going to do a little work for money, but I'll be back tomorrow to go over it.

**Comment by eFrysTon** [comment]
Thanks, very much appreciated (I would try my hand myself, being a software developer, but python isn't a language I'm all that familiar with).

**Comment by gcomyn** [comment]
yeah... I just started learning it when I started using FFF, myself... so I'm not an expert in anyway... but I'm learning.  And since I don't have a 'real' job... (I drive for lyft right now)... I usually have some time... maybe *gryn*.  I'll start looking at it now... may have something tonight.

**Comment by JimmXinu** [comment]
There are a couple adapters already that pull data from JSON: adapter_fimfictionnet.py(directly from a URL) and adapter_fictionpadcom.py(from elements in the HTML).  That should help.

And I learned Python when I first got involved with the project, too.

**Comment by gcomyn** [comment]
Ok... I've got everything worked out, except the synopsis... *sigh*... I'm getting Unidecode errors... I've sent an email to Jim for help... so we'll see what we can do.

**Comment by gcomyn** [comment]
This is being tested with the CLI.... once I get it working there, I'll test it with Calibre...

**Comment by gcomyn** [comment]
Ok... I've sent the "final" version to Jim (he helped alot). I've tested it with the CLI and Calibre plugin, and it works for me.

There is a default.ini section, because I capture the Translator, which is not a default title page element... also, I've kept the synopsis html, but that can be overwritten in the ini.

**Comment by eFrysTon** [comment]
Thanks a lot!

**Comment by xd1986k** [comment]
Getting the following error on a few stories.
```
Bad
Unknown
Unknown
local variable 'synopsis' referenced before assignment
http://gravitytales.com/novel/dungeon-hunter
```

**Comment by JimmXinu** [comment]
@xd1986k -- @gcomyn has already gotten me the fix for that, new test version should be up today.

**Comment by eFrysTon** [comment]
Something seems to be broken, with this. When I try to update any book from this site I almost always end up with an entry like this in the log:

Bad
King of Gods
Thunder
IncompleteRead(4517 bytes read)
http://gravitytales.com/novel/king-of-gods

If I keep trying to update the book, it *may* succeed 1 time out of ten or so.

I can access the site just fine in the browser and don't have any other connection problems, so I don't think it's my internet connection.

**Comment by JimmXinu** [comment]
We saw an [extremely similar problem before](https://www.mobileread.com/forums/showthread.php?p=3336369&highlight=IncompleteRead#post3336369).  It was being caused by overzealous firewall/AV.  Please give that a try.

**Comment by eFrysTon** [comment]
That worked, thanks a lot.

**Comment by eFrysTon** [comment]
Some (not all, and not always, but e.g. http://gravitytales.com/novel/peerless-battle-spirit and http://gravitytales.com/novel/hedonist-sovereign  ) of the stories on gravity tales list a teaser chapter as last entry in their list of chapters. That is, it's only a small fraction of the chapter, and the word "teaser" shows up either in the title (but only in the chapter page itself, not in the main list with chapter links) or somewhere in the few lines below the title.

Makes the "update epub" function in fanficfare useless with these stories, as when the teaser chapter gets updated to the full chapter and a new teaser chapter is added at the end, it leaves the already downloaded teaser chapter alone, and just downloads the new chapters (again ending in a teaser which will stick around on the next update).

Is there any way the adapter could be modified so that if the last chapter it downloads contains the word "teaser" it's ignored and not added to the epub?

**Comment by JimmXinu** [comment]
That appears to be something the authors are doing, not a feature of the site.  While both have the word 'Teaser' near the top, it isn't presented the same way, nor is it in the chapter list title.  

What I personally do with such cases is use calibre's Edit book and remove the chapter.
