### ISSUE TITLE
New site request - alternatehistory.com forum

### ISSUE THREAD

**Issue by Pheoxy** [JimmXinu/FanFicFare#178]
alternatehistory.com now use xenfero and threadmarks.

Thought I'd pass that one for people.

**Comment by JimmXinu** [comment]
This was [requested earlier in the year](https://www.mobileread.com/forums/showthread.php?p=3452849&postcount=1704).  I said:

>... [alternatehistory.com] seems to lack the standing conventions that makes it possible to pick out stories from threads on the other forums. 

I went and looked at it again now, and I couldn't actually find any story threads to evaluate.  So I think my point stands. :-)

If there's a creative subforum or something that I missed, let me know.

**Comment by Pheoxy** [comment]
For example:
https://www.alternatehistory.com/forum/threads/the-hour-of-the-wolf-asoiaf-au.391094/

**Comment by JimmXinu** [comment]
That thread requires a user account--which is why I couldn't see it before.  (That's the sort of info that's would be useful to include...)

And after creating an account, clicking that link I get:
> You do not have permission to view this page or perform this action. 

So I can't say anything about that one.

I _can_ now see the subforum "Finished Timelines and Scenarios", which does contain prose stories.  And the half dozen threads I've looked at don't have threadmarks or chapter links in the first post.

So I'm not moved from my original assessment.

**Comment by Pheoxy** [comment]
Hmm, seems user registration needs admin verification now due to spam. Sorry didn't know they had changed that I'm always logged in.

I'm on my phone at the moment but would the FanFicFare login options in the .ini allow for xenfero login to allow for it?

![screenshot_20170429-003313](https://cloud.githubusercontent.com/assets/6779172/25538005/78a8d850-2c73-11e7-8041-e0eab0ef5d6c.png)

**Comment by JimmXinu** [comment]
Now that my alternatehistory.com account is 'approved', I can see that there is a subforum [Fandom AH](https://www.alternatehistory.com/forum/forums/fandom-ah.248/)--hidden away from the uninitiated--containing a significant number of story threads.  And while not all, a majority of recent threads there do appear to have threadmarks or index links.

I've code support for this (3e897e7).  It will be bit before there's a test version released, I want to use the base_xenforoforum changes for a bit first; make sure nothing else broke.

**Comment by Pheoxy** [comment]
Awesome! I look forward to the test release when it comes.

**Comment by JimmXinu** [comment]
Test version is up.
