### ISSUE TITLE
FiMfiction.net has updated their site, no longer compatible with FanFicFare 2.12.0

### ISSUE THREAD

**Issue by zontargs** [JimmXinu/FanFicFare#186]
Error log:

Status: Bad
Title: Unknown
Author: Unknown
Comment: 'NoneType' object has no attribute 'find'
URL: https://www.fimfiction.net/story/373432/

**Comment by JimmXinu** [comment]
Hmmm.  They've changed a lot.  It may be a bit to get it all fixed.

**Comment by JimmXinu** [comment]
I've pushed some changes(9275858d687359aeccd6d9f881061f2972491b52) that I think fix everything.  

New test versions will probably be published tomorrow.

**Comment by JimmXinu** [comment]
[Test version posted](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).

 FYI, there's still work to be done on FimF with user/pass.  FaceDeer is looking into that.

**Comment by JimmXinu** [comment]
FYI, user/pass protected stories on FimF appear to be very rare.  The next release is going to go ahead without it.
