### ISSUE TITLE
QuestionableQuesting regression and url

### ISSUE THREAD

**Issue by tr13dm03** [JimmXinu/FanFicFare#189]
I found a regression for [QuestionableQuesting](https://forum.questionablequesting.com) affecting all build outputs (plugin, cli, etc). It causes any attempt to download a thread to throw an "index out of range". Bisecting result:

   ```git
   84dc04bb151abb729e3fc82a2b312ca3a821a2fa is the first bad commit
   commit 84dc04bb151abb729e3fc82a2b312ca3a821a2fa
   Author: Jim Miller <retiefjimm@gmail.com>
   Date:   Sun Jun 11 13:20:01 2017 -0500
   
   Extend base_xenforoforum_adapter Reader Mode to other Threadmark Categories.
   
   :040000 040000 fa49567db2128355cb50ad3274fa0503ff3e0874 e98fbb825ea898fd0dbf0ee32c70cf73b38b3099 MANIFEST.in fanficfare
   ```

One also cannot download from https://questionablequesting.com/threads/your-title-here only https://forum.questionablequesting.com/threads/your-title-here at the moment.

**Comment by JimmXinu** [comment]
I believe 9e378b7 fixes QQ support.  I want to test it a bit more with SV & SB before putting out a new test version.

I don't have a huge level of sympathy for `questionablequesting.com` vs `forum.questionablequesting.com`--the code used to be for questionablequesting.com and it stopped working requiring the change to `forum.qq` (897976b4bdccb478b57e7639f7d5e19b8dc8a0aa).

**Comment by tr13dm03** [comment]
I'll check the fix a bit later,

As for the url part, with the added context you mention, I would be inclined to agree with the sentiment. Maybe an error message in case someone accidentally uses the wrong form? That's actually how I found out.

**Comment by JimmXinu** [comment]
[Test version posted](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).
