### ISSUE TITLE
Downloads from Fimfiction.net no longer includes author's notes

### ISSUE THREAD

**Issue by marktaiwan** [JimmXinu/FanFicFare#196]
Stories from Fimfiction.net may includes author's notes at the beginning or end of each chapter ([example](https://www.fimfiction.net/story/346172/3/discord-doesnt-even-want-a-cult/and-they-bequeathed-unto-him-clocks-books-and-disguises)).
Following the June 2017 site changes, and the subsequent update to FanFicFare, those are no longer included in the downloads. Is it possible to have them back please?

**Comment by JimmXinu** [comment]
@FaceDeer - Do you have any interest in looking into this?  

adapter_archiveofourownorg shows one way it can be done with configurable options for different types of notes.  My problem is that I don't know what notes are available on fimf.

**Comment by marktaiwan** [comment]
Only two types of notes are available on fimf. One places the notes before `<div id="chapter-body">` and one after. So I guess that makes them `chapterheadnotes` and `chapterfootnotes`.
Unfortunately there are no class or id to mark the two apart, besides their position in relation to the chapter text.

**Comment by JimmXinu** [comment]
Can you provide a few story URLs that demonstrate both types of notes?  Ideally, one each of top only, bottom only and both in the same chapter.

**Comment by marktaiwan** [comment]
Fimfiction only allows the notes to either be at the top or at the bottom, but not both at the same time.

Bottom:
https://www.fimfiction.net/story/346172/3/discord-doesnt-even-want-a-cult/and-they-bequeathed-unto-him-clocks-books-and-disguises

Top:
I couldn't find a published example right now, and Fimfic doesn't seem to let non-users see unpublished stories, so I attached the [webpage as a file](https://github.com/JimmXinu/FanFicFare/files/1100767/Author.s.note.at.the.top.-.Test.Article.-.Fimfiction.zip).

**Comment by FaceDeer** [comment]
Just did some tinkering with my personal test story and it looks pretty straightforward. Inside <div id="chapter" class="chapter"> there is a <div class="authors-note bbcode"> and a <div id="chapter-body" class="chapter-body double-spaced"> (the presence of the "double-spaced" class is optional, and there's also an "indented" class that can be here. Likewise, I noticed that the bbcode class in the author-note div wasn't consistently present.)

The author's note can be before the chapter-body or after the chapter-body, but not both - the editor only allows one author note and you can pick where it goes.

I'll crack open the adapter and see about adding this later tonight. My instance of Calibre is busy on a multi-hour task right now that I'd rather not interrupt and start over. :)

Kicking myself a bit, I remember thinking "I should test author notes" back when Fimfiction first updated but I guess I never did.

**Comment by JimmXinu** [comment]
[Fixed by FaceDeer](https://github.com/JimmXinu/FanFicFare/pull/197).  Thanks!

**Comment by marktaiwan** [comment]
Thank you!
