### ISSUE TITLE
CLI Update 

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#202]
I got the message that FanficFare updated when I opened Calibre, so I updated it there.
But when I tried to update it in the CLI version it does not upgrade.

Is there something wrong or is there something else that applies to the CLI version?
Like, does it check the date or something and will it upgrade tomorrow?

**Comment by JimmXinu** [comment]
It looks like the pypi site has changed their upload API.  My upload script failed rather quietly, so I missed it.

I'll need to figure that out.

**Comment by JimmXinu** [comment]
Okay, that was easier than I feared.  It's fixed now.

Thanks for pointing this out.
