### ISSUE TITLE
[bug] Spacebattles and SufficientVelocity don't seem to be working

### ISSUE THREAD

**Issue by ATotalGit** [JimmXinu/FanFicFare#203]
If you try to download a fic from either, it will only give you the first chapter, and seems to view this as the entire work. However, if you try to update a fic in your library that's already up to date, it will correctly tell you that no new contributions have been made.

Fics I tried it out on:
https://forums.sufficientvelocity.com/threads/miracles-of-ancient-wonder-rwby-exalted.28772/
https://forums.spacebattles.com/threads/damned-if-i-do.431653/
https://forums.spacebattles.com/threads/a-white-knight-for-a-dark-day-galahad-in-westeros.540523/
https://forums.spacebattles.com/threads/exitium-doom-4-mass-effect.530347/

**Comment by JimmXinu** [comment]
There were site changes on SB/SV a few weeks ago that changed how threadmarks appeared.  Changes have already been made to FanFicFare to account for those.

I'm able to download those stories fine using the latest version.  Please make sure that you are using v2.14.0.
