### ISSUE TITLE
Spacebattles and SufficientVelocity broken

### ISSUE THREAD

**Issue by Blank99** [JimmXinu/FanFicFare#213]
Not sure when this happened, but today FanficFare is failing to download anything from forums.Spacebattles.com and forums.SufficientVelocity.com, both the web and calibre versions. This wasn't an issue a 1~2 weeks ago.

**Comment by Blank99** [comment]
To update on this, if I use the address of the thread, ie:
https://forums.spacebattles.com/threads/stacked-deck-or-colin-wallis-vs-single-parenting-worm-persona.459689/
It doesn't work, but if I scroll down (on the thread) and grab a link to the first post, ie:
https://forums.spacebattles.com/threads/stacked-deck-or-colin-wallis-vs-single-parenting-worm-persona.459689/#post-28320806

Then it downloads that specific post just fine (just not the whole story).

**Comment by JimmXinu** [comment]
This is both duplicate (#207) and already fixed (f39c9d49f8eb179e82b76f776981fe081b6f7537).
