### ISSUE TITLE
Error while getting metadata for webnovel.com ebooks

### ISSUE THREAD

**Issue by kestrel404** [JimmXinu/FanFicFare#214]
Get error message: 'NoneType' object has no attribute 'find_next_sibling'
Happens on both current & previous versions of Calibre plugin & HTML page. Happens for all books I've tried (i.e. https://www.webnovel.com/book/7141974606000205/)

I've used the plugin to download these ebooks previously,.

**Comment by JimmXinu** [comment]
Already fixed in a2ea915aa5e25ee078f14567dfb89c969a0acc6f

Test versions are up for [calibre](https://www.mobileread.com/forums/showthread.php?t=259221) and [web service](https://2-15-7-dot-fanficfare.appspot.com/).
