### ISSUE TITLE
unable to update the webnovel

### ISSUE THREAD

**Issue by blacksheep19** [JimmXinu/FanFicFare#218]
the following is the bugreport
Status
Title
Author
Comment
URL
Bad
The Strongest System
Xinfeng
'NoneType' object has no attribute 'find_next_sibling'
https://www.webnovel.com/book/7817013305001305

**Comment by JimmXinu** [comment]
Duplicate issue(#214) and already fixed in a2ea915.

Test versions are up for [calibre](https://www.mobileread.com/forums/showthread.php?t=259221), CLI and [web service](https://2-15-9-dot-fanficfare.appspot.com/).

**Comment by blacksheep19** [comment]
thank you , after i installed the latest version manually the error was
solved. i think something was wrong with calibre plugin update.
