### ISSUE TITLE
Spacebattles and Sufficient Velocity links not working

### ISSUE THREAD

**Issue by darnessfalls** [JimmXinu/FanFicFare#220]
Spacebattles and Sufficient Velocity links with multiple threadmark categories are not working. It shows an href error.
Eg: https://forums.spacebattles.com/threads/worm-dc-comics-fear.537310/
https://forums.sufficientvelocity.com/threads/building-faith-dresden-files-si.28419/

**Comment by JimmXinu** [comment]
This is both multiply duplicate (#207, #213, #215, #217) and already fixed (f39c9d49f8eb179e82b76f776981fe081b6f7537).

**Comment by darnessfalls** [comment]
But I just checked it and it didn't work.
