### ISSUE TITLE
XenForoForum Sites with multiple threadmark categories

### ISSUE THREAD

**Issue by darnessfalls** [JimmXinu/FanFicFare#226]
Recently, the XenForoForum sites have added the concept of threadmark categories. Since then, I haven't been able to download the stories with multiple threadmark categories. How should I change the personal.ini file to I resolve this issue?

**Comment by JimmXinu** [comment]
Fixed in the last release.  Please update to latest version before reporting Issues.

If you are still seeing a problem after that, reopen this including a story URL that shows the problem.
