### ISSUE TITLE
Exporting Metadata Only JSON

### ISSUE THREAD

**Issue by jcc10** [JimmXinu/FanFicFare#228]
So this is probably a bit of a feature creep but since you already have the metadata only mode, could you add a mode so it exports the metadata as JSON? It would really help with connecting to other programs. (and remove the need for me to re-write metadata scrapers for most of these sites)

Basically it would take the data I think you are already storing in a list or dictionary and run json.dumps to generate the json string of the object.

I would make the modification myself but I don't have the patience to dig through the project to find the code for exporting. (and ensuring it can only export as json while in metadata mode.)

**Comment by JimmXinu** [comment]
I can add an option for that to the CLI pretty easily.

I'm not particularly interested in adding it to the plugin or web service.

**Comment by jcc10** [comment]
Ok, Yah. my fault forgetting there is also a plugin and web service.

I was actually talking about the CLI...

**Comment by JimmXinu** [comment]
I've put out a CLI test version that adds a `--json-meta` option.

You can get it with:
`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare `

You can try it with:
`fanficfare --meta-only --json-meta 'test1.com?sid=5'`

If you also want to make sure you don't over write any existing output files or get warnings about not doing so, you can add `output_filename` and `always_overwrite` settings:
`fanficfare --meta-only --json-meta 'test1.com?sid=5' -o output_filename=/dev/null -o always_overwrite=true`

While experimenting, you can reduce network traffic by using test1.com story URLs or `--save-cache` option with real site URLs.

**Comment by jcc10** [comment]
So, that seems to just output the json in the shell without saving it. Which while not necessarily bad is also not ideal. (although certainly workable.)

Is it possible to make it save as a .json when using --json-meta?

**Comment by JimmXinu** [comment]
You mean other than piping to a file? ;-)

If you'd like something more complex, you can see where [cli.py](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/cli.py#L410) does it now.

**Comment by jcc10** [comment]
Thanks for the reference link!
