### ISSUE TITLE
Use of JSON API instead of HTML scraping for fimfiction.net

### ISSUE THREAD

**Issue by TBBle** [JimmXinu/FanFicFare#229]
I've just discovered that fimfiction.net has a [JSON API](https://www.fimfiction.net/developers/api/v2/docs).

Would it be worth changing FanFicFare's fimfiction.net adaptor to use that API?

It _seems_ to me on brief examination that such a change wouldn't need to affect anything outside the adaptor itself, but it's possible that this is either incorrect, or the whole idea has already been considered and rejected.

**Comment by TBBle** [comment]
Looking at it, it requires [OAuth 2](https://www.fimfiction.net/developers/api/v2/docs/oauth), and I'm not sure how well that integrates with an open-source project like this, particularly for anonymous users.

**Comment by JimmXinu** [comment]
Back in 2012-3, we did use FimF's JSON APIs more.  There were a number of issues, including story summaries given in BBCode.  Eventually it was just less work to page scrape again for most things.

Unless there are specific reasons to reconsider it, I'm not very interested in trying again--especially if OAuth2 is involved.

**Comment by TBBle** [comment]
The main things that prompted me to look at this were:
* Performance
* Functionality to push things like the 'read' status back-and-forth
* Functionality to integrate better with the various lists

My particular use-case is that I only want to pull stories into Calibre when they are Complete, and I'd also like to auto-pull stories in my To Read list that have become Completed, and vice-versa, update FimFiction with 'Read' for stories I've read, and then remove them from my local Calibre.

There's no strong need for such to be part of FanFicFare, so I'll probably try and put something together to deal with this use-case separately, building on the metadata that FanFicFare stores when it pulls an epub.
