### ISSUE TITLE
Weird Questionable Questing Error (CLI)

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#230]
I am downloading:

> https://forum.questionablequesting.com/threads/history-strongest-cultivator-hsdk-xianxia.6135/

in the CLI.

It's a NSFW story and needs my username/password which I have on my settings ini-file

However it gives the error:

> FFF: WARNING: 2017-09-19 21:08:27,236: configurable.py(1103): Caught an exception reading URL: https://forum.questionablequesting.com/threads/history-strongest-cultivator-hsdk-xianxia.6135/  Exception HTTP Error 403: Forbidden.
> FFF: ERROR: 2017-09-19 21:08:27,239: configurable.py(1109): Giving up on https://forum.questionablequesting.com/threads/history-strongest-cultivator-hsdk-xianxia.6135/

but the story is downloaded correctly

The same thing happens if I use:

> https://forum.questionablequesting.com/threads/6135/

which is the same thread

**Comment by JimmXinu** [comment]
The QQ NSFW area is the only part of any supported xenforo site that uses user/pass login and it's detected by the 403 error that's thrown.  It does, as you noticed, go on past those log outputs.

So in the interests of not showing errors when life goes on, I've changed those to debug level output.
4ad6d02
