### ISSUE TITLE
Forcing default format to be other than epub in .ini files?

### ISSUE THREAD

**Issue by l8gravely** [JimmXinu/FanFicFare#233]
I've read the docs, the .ini file examples and even the code.  It's not clear how to force the default output format to be something other than epub.

**Comment by JimmXinu** [comment]
Hmmm.  Good point, that's not controllable from personal.ini.

Are you talking about CLI, web service or calibre plugin?

**Comment by l8gravely** [comment]
>>>>> "Jim" == Jim Miller <notifications@github.com> writes:

Jim> Hmmm. Good point, that's not controllable from personal.ini.
Jim> Are you talking about CLI, web service or calibre plugin?

cli mostly, but ideally from everywhere.  I'd also suggest that the
.ini files have all possible options for each section listed, even if
commented out.

Just to clarify what's possible.

**Comment by JimmXinu** [comment]
I've thought about this some more and it's not as simple as I initially thought.  

The issues are: first, that the output format dictates (in part) which sections of the .ini files are used, and; second, that the existing code is all designed for format to be available *before* the .ini is parsed and used.

Also, I assumed we were talking about web service.  CLI output format option can be passed with a wrapper script or alias trivially.

For CLI, the overhead in making the change vs a simple alias or wrapper script isn't worth it, IMO.  But I'll happily look at a PR to do it.  I would be more inclined to add a default format setting for web service outside personal.ini.

As for all possible options in every section, I'm not interested in doing that.  There are a ton of settings and over 100 sites.  It would be hugely redundant and a nightmare to maintain when they change.
