### ISSUE TITLE
Retrieval from fimfiction.net stopped workin

### ISSUE THREAD

**Issue by kephas** [JimmXinu/FanFicFare#236]
When I try to either update or download from fimfiction.net, I get the following error in Calibre:

Status: Bad
Title: Unknown
Author: Unknown
Comment: 'NoneType' object has no attribute 'find'
URL: (url of the story)

To have a timeline, it still worked in April.

**Comment by JimmXinu** [comment]
Working fine for me.  

Are you using the most recent version of FanFicFare?  What is a story URL that shows the problem for you?  Are you using CLI, web service or Calibre plugin?

**Comment by kephas** [comment]
I was using FFF 2.6.0 in Calibre. I installed FFF CLI with pip and 2.17.0 was able to get the books so I updated the Calibre plugin to 2.17.1 and it works too.
