### ISSUE TITLE
Downloading metadata for stories should happen in the background

### ISSUE THREAD

**Issue by JasonGross** [JimmXinu/FanFicFare#241]
"Downloading metadata for stories" should not be a modal dialog box that blocks input to calibre.  This is extremely annoying when I have a few hundred stories to download metadata and thus cannot do anything else with calibre for an hour or two.

**Comment by JimmXinu** [comment]
When downloading by URL FFF sometimes needs to be able to gather user input.  Calibre doesn't provide any way for background jobs to do that.

If you are doing updates of existing books, there is a option to download metadata in the background.

In either case, downloading hundreds of stories at a time is not recommended.  This [FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-shouldnt-i-just-select-my-entire-library-and-use-fanficfare-plugin-to-check-for-updates) is about updates, but the same reasoning applies.
