### ISSUE TITLE
harrypotterfanfiction.com not retrieving anymore

### ISSUE THREAD

**Issue by milford833** [JimmXinu/FanFicFare#243]
I went to download a few fan fictions from harrypotterfanfiction.com today and it does not even register them in download from URLs.  It was working a few weeks ago.  I made sure I was upgraded to the latest versions.

**Comment by JimmXinu** [comment]
They've changed from defaulting to http to https.  It will still work if you change the https urls to http.

Next version will allow both http/https for that site and default to https. 5989d1d06bf2604ec542cb42a10f62cf356af582
