### ISSUE TITLE
output_filename - way to replace spaces with underscores?

### ISSUE THREAD

**Issue by l8gravely** [JimmXinu/FanFicFare#245]
Playing around with trying to automate writing txt files from downloads.  I've got the following line in my personal.ini file:

output_filename: ${author}:${title}${formatext}

but when it writes the file, it keeps the spaces in the title field (and possibly author, but haven't checked yet) so I'd like to try and replace the white space with underscores before the file gets written.

It should be pretty simple, but I couldn't make it work.  I tried to define a new variable called mytitle and then work on replacing this, but I suspect I can't do that:

mytitle: ${title}
replace_metadata:
  mytitle=>\s+=>_

output_filename: ${author}:${mytitle}${formatext}

Any suggestions?

**Comment by l8gravely** [comment]
Ok, so I'm a moron and didn't understand the:

output_filename_safepattern:(^\.|/\.|[^a-zA-Z0-9_\.\[\]\(\)&-]+)

in the docs until I read the source code in more detail.  Really need to learn python better.  But!!

I still think it would be nice to have multiple patterns if possible, so that I could have:

output_filename_safepattern:(^\.|/\.|[^a-zA-Z0-9_ \.\[\]\(\)&'-]+)
output_filename_replacepatterns:
  '=>
 \s=>_

or something like that.  Right now I can survive by even just using rename after-the-fact on the generated files.

**Comment by JimmXinu** [comment]
You can already control the output file name to that resolution, but it is a bit round-about.

`extra_valid_entries` lets you add new metadata entries.
`include_in_X` lets you include existing metadata entries in the new ones you create.
`replace_metadata` lets you do that sort of replacement on metadata entries.
`output_filename` lets you define the output path name using metadata entries.

So you can use something like:
```
[epub]
add_to_extra_valid_entries:,filetitle,fileauthor
include_in_filetitle:title
include_in_fileauthor:author
add_to_replace_metadata:
 filetitle,fileauthor=>'=>
 filetitle,fileauthor=>[ ]=>_
 # space should be replaced with '_' by output_filename_safepattern, but that's how you'd do it, not \s.
output_filename: ${fileauthor}:${filetitle}${formatext}
```

**Comment by l8gravely** [comment]
Thanks!
