### ISSUE TITLE
fanficfare non-interactive mode

### ISSUE THREAD

**Issue by arisboch** [JimmXinu/FanFicFare#246]
Could you please add an option to let fanficfare run really non-interactive (such as answering questions such as "are you old enough" and the like with a "yes")?

**Comment by JimmXinu** [comment]
This has been discussed before in PR#192 but was never incorporated due to me missing/not getting a notification.  I've merged that change in now and posted test versions.  Assuming no other problems, it will be in the next release.

**Comment by arisboch** [comment]
When I use -o is_adult:true --non-interactive, I get the following error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare==2.18.3', 'console_scripts', 'fanficfare')()
  File "/usr/local/lib/python2.7/dist-packages/FanFicFare-2.18.3-py2.7.egg/fanficfare/cli.py", line 267, in main
    passed_personalini)
  File "/usr/local/lib/python2.7/dist-packages/FanFicFare-2.18.3-py2.7.egg/fanficfare/cli.py", line 314, in do_download
    output_filename)
  File "/usr/local/lib/python2.7/dist-packages/FanFicFare-2.18.3-py2.7.egg/fanficfare/cli.py", line 517, in get_configuration
    (var, val) = opt.split('=')
ValueError: need more than 1 value to unpack
```

**Comment by JimmXinu** [comment]
The text is a little off.  Use `-o "is_adult=true" --non-interactive` instead.

**Comment by arisboch** [comment]
Awesome, thanks! Could you add the order of the arguments to the readme file, too, please, so that other users wouldn't have the same problem?

**Comment by JimmXinu** [comment]
Which readme?  And what isn’t clear from the cli help text?

**Comment by arisboch** [comment]
You're right, I should've meant the cli help text and it is not really clear from the help text, as the order in which arguments given on the cli don't matter in many programs.

**Comment by JimmXinu** [comment]
FFF doesn't care about option order either, and the CLI help text already says to put options before URLs.  So I'm not sure what you think it is that needs to be added...

**Comment by arisboch** [comment]
@JimmXinu
Sry, it was a misunderstanding, all works well. Thanks, it helped me very much with my wrapper script!
