### ISSUE TITLE
tolkienfanfiction.com errors

### ISSUE THREAD

**Issue by eavrunin** [JimmXinu/FanFicFare#248]
If given a story url (e.g., http://www.tolkienfanfiction.com/Story_Read_Head.php?STid=1034) it creates an epub with the correct metadata, but the author's page in place of the text.  If given a chapter url (e.g., http://www.tolkienfanfiction.com/Story_Read_Chapter.php?CHid=4945) the download fails with the log showing "cannot concatenate 'str' and 'NoneType' objects".

**Comment by JimmXinu** [comment]
Looks like the site made a few changes.  Fixed in 96418426785531e41a45c76f921b26aa2459938a, changes will be in the next test version.

Thanks for pointing out the problem.

**Comment by eavrunin** [comment]
Great, thank you!
