### ISSUE TITLE
Consider support for tenprintcover.py in cli

### ISSUE THREAD

**Issue by Nothorse** [JimmXinu/FanFicFare#251]
It would be good to be able to generate covers in the cli version.

tenprintcover.py (https://github.com/mgiraldo/tenprintcover-py) makes pretty neat covers very fast and would be a good addition if it were possible to call it via personal.ini 

Currently you can only specify an existing file, which precludes that option.

**Comment by JimmXinu** [comment]
Have you tried the [`post_process_cmd`](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/defaults.ini#L199) feature?

**Comment by Nothorse** [comment]
The post_process_cmd is already used to add the finished epub to a library database and directory structure.

And of course I want the cover embedded, I don't see an option to add a cover image to an epub afetr the download and packaging. If I've missed something, just point me to the right spot.

Thanks!

**Comment by JimmXinu** [comment]
I'm busy with the US Thanksgiving holiday this week, but I'll looking into maybe making a `pre_process_cmd` when I get time.

**Comment by Nothorse** [comment]
Very cool, thank you!

**Comment by JimmXinu** [comment]
I've posted a test version with a new `pre_process_cmd` feature you can try.  Let me know how it works for you.

> Test version of CLI for pip install:  You'll have to get it from the testpypi repository.  This works for me on Debian:
>
> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

Copy and uncomment as appropriate.
```
## For use only with CLI version--run a command 3*before* the output
## file is written.  All of the titlepage_entries values are
## available, (but not output_filename).  Can be used to generate
## cover images that are then included in the output ebook using
## default_cover_image.
#pre_process_cmd:tenprintcover.py --author "${author}" --title "${title}" --cover cover.png

## Some operating systems and command shells have problems with some
## characters.  When set, pre_process_safepattern will be applied to
## each metadata item passed to pre_process_cmd before it's called.
#pre_process_safepattern:(^\.|/\.|[^a-zA-Z0-9_\. \[\]\(\)&'-]+)
```

**Comment by Nothorse** [comment]
Just tried it.

Cover generation works nicely but for some reason I can't seem to make the default_cover_image work. The cover is there, but is not included into the epub.

Config:

pre_process_cmd:tenprintcover.py --author "${author}" --title "${title}" --cover /Users/[redacted]/.fanficfare/cover.png
pre_process_safepattern:(^\.|/\.|[^a-zA-Z0-9_\. \[\]\(\)&'-]+)
include_images:true
keep_summary_html:true
make_firstimage_cover:true
is_adult:true
default_cover_image:file:///Users/[redacted]/.fanficfare/cover.png
always_overwrite: true

**Comment by JimmXinu** [comment]
Hmm.  A bit of code I added to help fix a common class of mistaken image URLs was also affecting `file:///`.  I've uploaded a new CLI test version, do the pip update again and give it a try.

`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by Nothorse** [comment]
Sorry, but nope. I upated and tried it again, but no joy.

The cover is generated and available at the location, but it's not included in the epub.

I have no idea what's wrong.

(I also tried to generate the cover in my docroot and access it via http://localhost/ but that doesn't work either.)

I have grepped through all available configs and explicitly set never_make_cover: false
but it doesn't work. 

Do you have a size limit for covers somewhere in the code? Maybe I generate them too large?

**Comment by JimmXinu** [comment]
Are you getting any kind of error message?  What do you get if you run with `--debug`?

I didn't install tenprintcover.py, but I am able to run a `pre_process_cmd` command that makes an image file and then include it using `default_cover_image`.

**Comment by Nothorse** [comment]
OK. Got something:

FFF: INFO: 2017-11-29 20:26:30,415: story.py(1177): Failed to load or convert image, 
parent:None
skipping:file:///Users/thomas/Sites/cover.png
Exception: cannot identify image file <StringIO.StringIO instance at 0x104c211b8>

Should I attach the image file?

**Comment by JimmXinu** [comment]
It might help.  That error suggests that it's finding the image, but failing to process it.  

You could also try `no_image_processing: true` to turn off all image processing.

**Comment by Nothorse** [comment]
That works now. Thanks for the command and the help getting it to work!

**Comment by JimmXinu** [comment]
Okay.  I'll close this issue again.
Troubleshooting the image processing is really a separate problem, go ahead and open another issue if you decide you want to pursue it.
