### ISSUE TITLE
Support for AO3 series

### ISSUE THREAD

**Issue by kephas** [JimmXinu/FanFicFare#253]
I encountered a story on AO3 where the author publishes each chapter as a work in a series, but this is not yet supported by FanFicFare (I tried with 2.17.0)

https://archiveofourown.org/series/551686

**Comment by JimmXinu** [comment]
The calibre plugin can already create an ebook anthology from an AO3 series, but only when downloading as epub.

Look for the 'Make Anthology Epub from Web Page' option on the FFF dropdown.

While FFF CLI can download epubs from a list of story URLs on a page, it's not integrated with EpubMerge to do the merge for you.  The assumption is generally that if you're using CLI, you want to do your own scripting anyway.

FFF web service can't do anthologies and it's going to in future.  It would run into the timeout issue even faster.

**Comment by kephas** [comment]
Actually, I just updated the FFF calibre plugin to be sure I'm testing the latest version, and I'm already downloading to epub and there's no such option anywhere. (including after I installed EpubMerge).

**Comment by JimmXinu** [comment]
Make sure that you've restarted Calibre after installing EpubMerge.  Then it's one of the FFF menu options.  

![capture](https://user-images.githubusercontent.com/11446969/34192017-c6aef4e8-e510-11e7-8f70-a70f8818021b.png)

**Comment by mcepl** [comment]
@JimmXinu still, wouldn't it be possible to do the same just with plain fanficfare on the command line:
```sh
$ fanficfare https://archiveofourown.org/series/1035816
```
would download whole series?

**Comment by mcepl** [comment]
I was not thinking about EpubMerge, although that's cool as well, however, I haven't got the point that ``--download-list`` could have AO3 series URL as parameter. Thank you.

**Comment by Twilight666** [comment]
Is it possible to further intergrate the above in FanFicFare?

For example I download using the CLI by having a text file where I paste all the URLs to be downloaded.
And then the CLI reads that after setting the necessary path in personal.ini

Can FanFicFare read that one of the URLs is https://archiveofourown.org/series/... and get the URLs from it and add those in the list of Stories to download

**Comment by JimmXinu** [comment]
FFF doesn't recognize series URLs.  The 'list' features will retrieve any URL, then parse it looking for valid story URLs.  That feature is deliberately as general as possible so that it can be pointed at series pages, author list pages, somebody's hand-crafted favorites page, whatever.

I'm not interested in adding epub merging or spider downloading to FFF CLI at this time.  I will consider including code if some one else wants to write it.

Now let's stop adding discussion to an issue that was closed a year ago...
