### ISSUE TITLE
Update on Calibre

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#255]
The new update in out on the CLI but not no Calibre

**Comment by JimmXinu** [comment]
The cron job that picks up Calibre plugin updates sometimes takes a while to notice a new release.

If it still isn't showing up tomorrow, then we'll ping Kovid about it.

You can install manually from the [MR thread](https://www.mobileread.com/forums/showthread.php?t=259221) if you don't want to wait.

**Comment by JimmXinu** [comment]
FYI, I'm seeing the update in the in-Calibre plugin list now.
