### ISSUE TITLE
CLI: QQ One-Shots

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#257]
I am not sure if this only applies in Questionable Questing but I was downloading a few stories and a couple of them failed.
They were both one-shots without threadmarks so that might be the issue.

Specifically I tried to download

> https://forum.questionablequesting.com/threads/smoldering-rwby.4554/

And the full response was:

> Traceback (most recent call last):
>   File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "c:\python27\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "c:\Python27\Scripts\fanficfare.exe\__main__.py", line 9, in <module>
>   File "c:\python27\lib\site-packages\fanficfare\cli.py", line 267, in main
>     passed_personalini)
>   File "c:\python27\lib\site-packages\fanficfare\cli.py", line 364, in do_download
>     adapter.getStoryMetadataOnly()
>   File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 231, in getStoryMetadataOnly
>     self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
>   File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 315, in doExtractChapterUrlsAndMetadata
>     return self.extractChapterUrlsAndMetadata()
>   File "c:\python27\lib\site-packages\fanficfare\adapters\base_xenforoforum_adapter.py", line 310, in extractChapterUrlsAndMetadata
>     threadmarks = self.extract_threadmarks(souptag)
>   File "c:\python27\lib\site-packages\fanficfare\adapters\adapter_forumquestionablequestingcom.py", line 50, in extract_threadmarks
>     threadmarksas = navdiv.find_all('a',{'class':'OverlayTrigger','href':re.compile('threadmarks.*category_id=')})
> AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by JimmXinu** [comment]
Fixed in 56a6047
