### ISSUE TITLE
Crash from command line on startup when installing via pip

### ISSUE THREAD

**Issue by Risen-phoenix** [JimmXinu/FanFicFare#258]
Command given: `fanficfare`

Traceback: 
```Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare==2.20.0', 'console_scripts', 'fanficfare')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/fanficfare/cli.py", line 36
    print 'This program requires Python 2.5 or newer.'
                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int 'This program requires Python 2.5 or newer.')?
```

System information: 
OS: Artix rolling x86_64
Kernel: 4.14.6-1-ARCH
Python versions installed: python2 2.7.14-1 and python 3.6.3-1

**Comment by JimmXinu** [comment]
Python 3 made `print` a function instead of a keyword.  FanFicFare doesn't support Python 3.  

The PyPi/pip setup for FanFicFare specifies Python 2.6 or 2.7, and `pip` creates the actual `fanficfare`.  So theoretically it shouldn't be trying to run under Python 3.

Your trace shows that FFF has been installed in `python3.6/site-packages`, however.  I don't know how that would have happened.

**Comment by Risen-phoenix** [comment]
Solved by using `pip2` instead of `pip` as provided by OS packages. Thanks for pointing that out, the `print 'This program requires Python 2.5 or newer.'` line in the traceback threw me off that.
