### ISSUE TITLE
Wattpad adaptor site abrev broken

### ISSUE THREAD

**Issue by jcc10** [JimmXinu/FanFicFare#260]
The Wattpad adapter is broken it is currently returning:

`"siteabbrev":""`

it should be:

`"siteabbrev":"wattpad"`

I have no idea how to fix this, I don't even know what is going wrong. All I know is that when I export the json, there is no site-abbrev.

**Comment by JimmXinu** [comment]
Fixed in efb6365b90ad6ebfa56709f5e22f15f1306b9767.  Will be in the next version.
