### ISSUE TITLE
Web service version error

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#264]
I was downloading using the Web service version (https://fanficfare.appspot.com/) and I noticed that when I tried to download from FFnet it gave me a 500 Server Error.
I didn't check everything but AO3 stories worked properly

Specifically, one of the stories I used was:
>https://www.fanfiction.net/s/9736987/20/White-Knight

And the response was:
>Error: Server Error

>The server encountered an error and could not complete your request.
>Please try again in 30 seconds.

**Comment by JimmXinu** [comment]
I'm not seeing any problems when I try it.  I also see at least one other person successfully downloading from ffnet in the logs.

The web service has a limited quota([FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-has-the-web-service-version-of-fanficfare-stopped-working)), it's possible you bumped into that, or possibly a concurrent operations limit.

However, if AO3 worked in the web service immediately after you saw that error, it's more likely ffnet had a transient problem, or there was a network issue, or ffnet blocked connections from the web service for a while.

Regardless, I'm not seeing any problems with it.

**Comment by Twilight666** [comment]
Ok it was working and now it is weird... Some times it works and sometimes not

this works (and i tried downloading twice and it worked both times)
>https://www.fanfiction.net/s/11561060/1/
but this keeps throwing error 500 (and i tried downloading the above in between... and that one worked immediately)
https://www.fanfiction.net/s/12817778/1
