### ISSUE TITLE
StoriesOnline not downloading/updating again (2018)

### ISSUE THREAD

**Issue by BlackSnakeMoaning** [JimmXinu/FanFicFare#265]
Similar to this issue from 2015: https://github.com/JimmXinu/FanFicFare/issues/113

When trying to download a story, the log-in pop-up promp window appears.

After filling in the credentials the windows resets, and after the second try the download just fails.

Trying to download through the web app failed as well.

**Comment by JimmXinu** [comment]
I'm not seeing this problem.  

Check and make sure you're using the default skin, there's [an FAQ about that](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-cant-i-use-a-different-skin-on-my-favorite-site).  For storiesonline.net that's Theme=Class.  It's an issue we've seen before.
