### ISSUE TITLE
Web service version error (Redux of #264)

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#266]
I tried to add a new reply to #264 but it stayed closed so I am posting a new issue instead:

I was downloading using the Web service version (https://fanficfare.appspot.com/) and I noticed that when I tried to download from FFnet it gave me a 500 Server Error.
I didn't check everything but AO3 stories worked properly

Specifically, one of the stories I used was:

>https://www.fanfiction.net/s/9736987/20/White-Knight

And the response was:

>Error: Server Error
>
>The server encountered an error and could not complete your request.
>Please try again in 30 seconds.

I checked further and it is weird... Some times it works and sometimes not:

This works (and i tried downloading twice and it worked both times)
>https://www.fanfiction.net/s/11561060/1/

But this keeps throwing error 500 (and i tried downloading the above in between... and that one worked immediately)
>https://www.fanfiction.net/s/12817778/1

**Comment by JimmXinu** [comment]
I'm seeing an error of: 
`Exceeded soft private memory limit of 128 MB with 145 MB after servicing 366 requests total`

Which doesn't quite match the logs which say `DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded` while hitting https://www.fanfiction.net/u/6716408/Quatermass  ; a rather lengthy author page.  

It looks like the initial 'look up metadata' processing (which includes looking up the author page) is either taking too much memory or too much time for Google Apps' tastes.  Sometimes different pages on ffnet just take longer to load than others.  I recall one story that one particular chapter that would consistently take over a minute to load for no reason I ever found.

All I can do is again refer you to the [FAQ about web the service](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-has-the-web-service-version-of-fanficfare-stopped-working), specifically the part about:
> Generally, it is recommended to use the Calibre plugin or command line (CLI) versions if you want to do more than occasional downloads.
