### ISSUE TITLE
TtHFanfic.org Fetch URLs not retrieving all stories from page

### ISSUE THREAD

**Issue by calvertvl** [JimmXinu/FanFicFare#268]
TtH by default restricts story rating to FR18.

if is_adult is false, then the current behavior is IMO correct.

In this case, I have set is_adult to true, and also have provided login credentials. My TtH account's default rating is further set to FR21.

Download works fine for stories rated FR21 when credentials are provided, but when fetching URLs from a page, it appears that the user is not logged in and the default story rating restriction of FR18 applies, therefore not all stories are downloaded.

is_adult is set to true globally in this case; if it was false I would expect the current behavior.

Example:
For https://www.tthfanfic.org/AuthorStories-20566/Katrina.htm
Expected output (all ratings):
```
https://www.tthfanfic.org/Story-29997-9/Katrina+BTVS+Builders+Junkyard+Dog.htm
https://www.tthfanfic.org/Story-29830-4/Katrina+BTVS+Builders.htm
https://www.tthfanfic.org/Story-28886/Katrina+Art+and+Banners+and+Such.htm
https://www.tthfanfic.org/Story-27523/Katrina+BTVS+AB+It+s+not+a+case+of+But.htm
https://www.tthfanfic.org/Story-26962/Katrina+TDWP+BTVS+On+a+Wing+and+a+Prayer.htm
```
Actual output (only FR18 and below):
```
https://www.tthfanfic.org/Story-29997-9/Katrina+BTVS+Builders+Junkyard+Dog.htm
https://www.tthfanfic.org/Story-29830-4/Katrina+BTVS+Builders.htm
https://www.tthfanfic.org/Story-27523/Katrina+BTVS+AB+It+s+not+a+case+of+But.htm
```

Note that there is a special case in the code for AO3 to log in because AO3 does not show adult stories without it; that is not exactly the case for TtH, but I've described my findings below.

There does seem to be a session cookie, so if a session can be opened for fetching URLs, then fetching this URL should set the max rating to FR21:
https://www.tthfanfic.org/setmaxrating.php?sitemaxrating=5
After that point, the original page could be fetched.

There is not a specific cookie that saves the default rating.

The other option, of course, is simply to log in prior to fetching, as is done for AO3, in which case the account's specified default maximum rating would apply.

**Comment by JimmXinu** [comment]
I don't see the need to do login (since we'd still need is_adult separately anyway) and I want to do sitemaxrating as a POST since the page does.

See what you think of 11e8126

**Comment by calvertvl** [comment]
Yes, that resolves the issue, and I agree...no need to log in when it can be set in the session.
