### ISSUE TITLE
wuxiaworld.com has revamped their site

### ISSUE THREAD

**Issue by ksurl** [JimmXinu/FanFicFare#270]
new site design went live a few days ago. they're no longer using wordpress on the backend.

**Comment by ksurl** [comment]
will the adapter be updated to support the new site or is it going to be abandoned?

**Comment by cryzed** [comment]
Let's not be hasty, the adapter not being updated within a week doesn't mean it'll be abandoned.

**Comment by JimmXinu** [comment]
Huh.  I guess committing the PR also closed the issue.  I didn't know it would do that.  Anyway, new test version shortly.

**Comment by cryzed** [comment]
I think it's related to me writing "Fixes #274" in the pull request. If you hover over that part you'll see it was recognized by GitHub as my intention.

**Comment by JimmXinu** [comment]
I agree.  I noticed that it linked the two, but actually closing the issue when I committed the changes from CLI was a bit more automation than I expected.  Convenient though.

Doing it from CLI allowed me to test before merging, which was good; but I prefer 'Squash & Merge' for the more linear history path.  Not that it makes any real difference.

As always, thanks for your help. 👍

**Comment by cryzed** [comment]
Of course :+1:!

**Comment by gcomyn** [comment]
Since I was the one who originally adapted it, I'll take a look at the new site, and see if I can get it to work again.

I'm currently working 40 hrs a week, so It may not be until this Saturday that I have the time to complete it.

GComyn

**Comment by cryzed** [comment]
@gcomyn the issue has already been resolved (check the comments above yours).
