### ISSUE TITLE
Chapters of stories from sufficientvelocity and spacebattles are being saved in reverse order

### ISSUE THREAD

**Issue by ATotalGit** [JimmXinu/FanFicFare#278]
Rather than being saved as:

Chapter 1
Chapter 2
Chapter 3

Stories are being saved as:

Chapter 3
Chapter 2
Chapter 1

**Comment by JimmXinu** [comment]
Known issue.  I've put a [test version of the plugin out](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2), but they were talking about more threadmark changes.

**Comment by JimmXinu** [comment]
'Fixed' in ef0815e916c69bfa05d4b1fde972e45a314abd8a
May need more changes before release depending on if they change threadmarks more.
