### ISSUE TITLE
FanFicFare does not allow specifying target file name

### ISSUE THREAD

**Issue by ZyX-I** [JimmXinu/FanFicFare#280]
(Or, at least, does not have any signs of such feature in `fanficfare --help`.) I have my own naming convention for my library which means I have to use FanFicFare to download to some directory without epub files and then move and rename `*.epub` file found there to a proper location.

**Comment by JimmXinu** [comment]
Use `output_filename` in personal.ini or `fanficfare --option=output_filename=whatever.epub ...`

From `defaults.ini`:
```
## python string Template, string with ${title}, ${author} etc, same as titlepage_entries
## Can include directories.
#output_filename: books/${title}-${siteabbrev}_${storyId}${formatext}
#output_filename: books/${formatname}/${siteabbrev}/${authorId}/${title}-${siteabbrev}_${storyId}${formatext}
output_filename: ${title}-${siteabbrev}_${storyId}${formatext}
```
