### ISSUE TITLE
Spacebattles: utf8' codec can't decode byte 0xfb

### ISSUE THREAD

**Issue by jeancinq** [JimmXinu/FanFicFare#283]
With calibre fanficfare plugin (version: 2.24.0)
I tried downloading the story from the following url:
https://forums.spacebattles.com/threads/gaemon-redux-asoiaf-si.627031/
Inside a task with multiple other stories.

But it failed with the following error message:

> 'utf8' codec can't decode byte 0xfb in position 56: invalid start byte

I latter tried downloading this story alone, and it worked, so maybe it was an isolated error or maybe it was because of the multiples stories in the initial task.

**Comment by JimmXinu** [comment]
If you can't duplicate the problem, and I can't duplicate the problem (I tried), there isn't really anything I can investigate.  If you have the full list of story URLs, I could try that, but that's about it.

**Comment by jeancinq** [comment]
Full list of stories url:

> FFF: INFO: 2018-03-28 21:18:26,645: calibre_plugins.fanficfare_plugin.jobs(104): 
> Réussi :
> https://forums.sufficientvelocity.com/threads/adaptation-with-extreme-prejudice-planetary-annihilation-multicross-si.29125/
> https://forums.sufficientvelocity.com/threads/definitions-worm-dc.45151/
> https://forums.sufficientvelocity.com/threads/fate-denied-a-star-wars-si.36312/
> https://forums.sufficientvelocity.com/threads/coffin-angel-40k.18346/
> https://forums.sufficientvelocity.com/threads/kansas-city-shuffle-changeling-the-lost-quest-complete.15436/
> https://forums.sufficientvelocity.com/threads/the-lost-files-c-tl-dresden-files-ck2-ish.26170/
> https://forums.sufficientvelocity.com/threads/skitter-studies-dresden-files-worm.36003/
> https://forums.sufficientvelocity.com/threads/lamarckian-my-hero-academia-si.44288/
> https://forums.sufficientvelocity.com/threads/of-gods-and-monsters-a-raynare-quest.42842/
> https://forums.sufficientvelocity.com/threads/hunger-frozen-disney-dark-fantasy-au.40401/
> https://forums.sufficientvelocity.com/threads/forge-of-destiny-xianxia-quest.35583/
> https://forums.sufficientvelocity.com/threads/the-roaring-age-nwod.34770/
> https://forums.sufficientvelocity.com/threads/marked-for-death-a-rational-naruto-quest.24481/
> https://forums.sufficientvelocity.com/threads/searching-for-purpose-clarketech-killbot-multicross-world-3-stargate.21728/
> https://forums.sufficientvelocity.com/threads/dragons-game.44768/
> https://forums.sufficientvelocity.com/threads/puella-magi-memento-mori-pmmm-quest.22689/
> https://forums.sufficientvelocity.com/threads/splintered-worm-qa-quest.24509/
> https://forums.sufficientvelocity.com/threads/persona-4-the-garden-of-sinners-persona-4-kara-no-kyoukai.14818/
> https://forums.sufficientvelocity.com/threads/shadow-quest-persona.13318/
> https://forums.sufficientvelocity.com/threads/the-mockshow-show-worm-quest.39750/
> https://forums.sufficientvelocity.com/threads/a-re-incarnation-quest.35001/
> https://forums.sufficientvelocity.com/threads/the-kings-of-men-lord-of-the-rings-warhammer-fantasy-ck-ii-quest.25498/
> https://forums.sufficientvelocity.com/threads/making-headway-young-justice-multicross.18173/
> https://forums.sufficientvelocity.com/threads/anderson-quest-killing-vampires-and-werewolves-and-leprechauns-hellsing-bloodborne.17262/
> https://forums.sufficientvelocity.com/threads/passing-through-traveler-episode-1-growth.31621/
> https://forums.spacebattles.com/threads/realignment-hp.351838/
> https://forums.spacebattles.com/threads/a-song-of-ice-and-fires-that-werent-all-my-fault-asoiaf-dresden-files.336499/
> https://forums.spacebattles.com/threads/further-adventures-of-tanya-the-evil-saga-of-tanya-the-evil-dresden-files.504364/
> 
> FFF: INFO: 2018-03-28 21:18:26,648: calibre_plugins.fanficfare_plugin.jobs(105): 
> Échoué :
> https://forums.spacebattles.com/threads/gaemon-redux-asoiaf-si.627031/
> 
>

**Comment by cryzed** [comment]
That was likely a connection error delivering some corrupted data.

**Comment by JimmXinu** [comment]
I agree--it's almost certainly a transient.  But I'm running a batch download with those URLs just in case.  It's taking forever because I set sleep time=5s before I started it.

**Comment by JimmXinu** [comment]
It took better than 2 hours with the slow down I used, but I didn't see any problems downloading all of these together.

Until it can be duplicated, I'm going to assume it was a transient problem of some kind, not a problem with FFF itself.
