### ISSUE TITLE
Bug in royalroadl

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#286]
I was reading (after I downloaded it with the CLI) the story Everybody Loves Large Chests:

> https://royalroadl.com/fiction/8894/everybody-loves-large-chests/

This is a LitRPG so the MC has a status window that (along with other messages) is printed as on the site as a table

To give an example look at the end of this chapter:

> https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/119107/moonlighting-8

The resulting table that is downloaded has issues:
First of all some of the table cells (such as 'Spell List') has an attribute named collspan that defines the width of the cell. That attribute is missing from the downloaded file
Also some times some cells are set as 

> \<td style="text-align: center"\>\&nbsp;\</td\>

that means that the cell is empty. Those cells ar replaced with newlines in the downloaded file

Both of the above cause the table alignment to be out of order and/or broken.

I don't know if this applies to other sites and this was the story I was reading so I don't know a story with less chapters for easier testing but I hope this is easily fixed

**Comment by JimmXinu** [comment]
Hmmm.  FFF has HTML clean up code that removes any empty or whitespace only(including `&nbsp;`) tags except for `p` tags.  It also removes all except a few whitelisted tag attributes.

So here's what I've done in 7b34b7e5c2698c862f03dcc49475f5487ca8297e:

- I've added a new setting `keep_empty_tags` which defaults to `p,td,th`.
- I've added `colspan,rowspan` to the default value for `keep_html_attrs`.

That takes care of allowing empty table cells and row and column spans of same.

I have _**not**_ added attribute `style` to the default `keep_html_attrs`.  You can do that yourself by putting `add_to_keep_html_attrs:,style` in your personal.ini.  Put it under `[royalroadl.com]` for just that site or `[defaults]` for all sites.  Or use storyURL sections for specific stories.

I've uploaded 2.24.1 with these changes to pypitest.  Install with the usual:
> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`
