### ISSUE TITLE
Lush Stories Adapter doesn't work [Errno 11001]

### ISSUE THREAD

**Issue by Tharos123** [JimmXinu/FanFicFare#290]
Lush Stories returns the following error message: <urlopen error [Errno 11001] getaddrinfo failed>

And I'm curious. Does the entry "This adapter will download the stories from the www.fireflyfans.net forum  pages" in the Adapter for Lush Stories have a reason?

**Comment by JimmXinu** [comment]
Author URL seems to have changed on the site.  Fixed in 5d57fdb.

No, that comment was probably incorrectly copied from previous adapter.
