### ISSUE TITLE
Bug in RoyalRoal (probable connection with #287)

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#294]
Ok I tried to download stories from RoyalRoad with the new test version, after the changes from bug #287 
BunkerCore downloaded fine but the story I posted the bug about originaly is no longer working.
The url is 

> https://royalroadl.com/fiction/8894/everybody-loves-large-chests/

The error message is:

> Traceback (most recent call last):
>   File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "c:\python27\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "c:\Python27\Scripts\fanficfare.exe\__main__.py", line 9, in <module>
>   File "c:\python27\lib\site-packages\fanficfare\cli.py", line 267, in main
>     passed_personalini)
>   File "c:\python27\lib\site-packages\fanficfare\cli.py", line 439, in do_download
>     output_filename = write_story(configuration, adapter, options.format, options.metaonly)
>   File "c:\python27\lib\site-packages\fanficfare\cli.py", line 65, in write_story
>     writer.writeStory(outstream=outstream, metaonly=metaonly)
>   File "c:\python27\lib\site-packages\fanficfare\writers\base_writer.py", line 198, in writeStory
>     self.story = self.adapter.getStory() # get full story
>   File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 177, in getStory
>     data = self.getChapterTextNum(url,index)
>   File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 327, in getChapterTextNum
>     return self.getChapterText(url)
>   File "c:\python27\lib\site-packages\fanficfare\adapters\adapter_royalroadl.py", line 224, in getChapterText
>     soup = self.make_soup(self._fetchUrl(url))
>   File "c:\python27\lib\site-packages\fanficfare\adapters\adapter_royalroadl.py", line 108, in make_soup
>     self.handle_spoilers(soup)
>   File "c:\python27\lib\site-packages\fanficfare\adapters\adapter_royalroadl.py", line 123, in handle_spoilers
>     legend.string = stripHTML(smalltext)
>   File "c:\python27\lib\site-packages\fanficfare\htmlcleanup.py", line 63, in stripHTML
>     return soup.get_text(strip=True)
> AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by JimmXinu** [comment]
I cannot duplicate the issue.  

However, it's easy to add a check for the problem shown: 2db8e070b4978ef14266c71b907a0cbda6a11927

CLI 2.24.5 uploaded to test.pypi.org.
