### ISSUE TITLE
Fanfiction.net Login

### ISSUE THREAD

**Issue by fighttrooper** [JimmXinu/FanFicFare#298]
Hi, it's entirely possible I have just read over it. but I couldn't find a feature to download all the stories a user of fanfiction.net follows or is a part of the favourites. is this possible (even with the download limit set so fanfiction doesn't respond)?

**Comment by JimmXinu** [comment]
I've added a [FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#how-do-i-download-a-list-of-all-of-an-authors-stories-or-a-users-favorites-list-on-fanfictionnet) for this.

You can get a user's favorites or an author's stories list, but there isn't a way to get your own follows/alerts list.  I don't have any plans to add login for ffnet to get those, sorry.

**Comment by gcomyn** [comment]
you have user page that has the list of all of your favorites, even if you haven't uploaded any stories... you can get your list of favorites from that. To delete from your favorites list, you need to login, but going to your user page has the list of them for everyone to see.

**Comment by fighttrooper** [comment]
Thank you very much! I’ll definetly use it!
