### ISSUE TITLE
Chapter Range on the CLI

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#302]
In Issue #300 you mentioned using the chapter range feature to download fics from ffnet that are too big to be downloaded.
I used it and it works great!
But it doesn't seem to work in the CLI version. Is it not supported or should I do somethinh different?

**Comment by JimmXinu** [comment]
They are command line options in CLI.  
```
fanficfare -h
...
  -b START, --begin=START
                        Begin with Chapter START
  -e END, --end=END     End with Chapter END
...
```
As I recall, they appeared in the CLI first and then were later added to the plugin and web service as `[1-5]` chapter ranges on the URLs due to the different environment limitations.

**Comment by Twilight666** [comment]
...oh
But that only works if I am downloading one story and I am using command prompt.
When I am home (and I have access to my computer) I prefer to have a text file were I save all the URLs and when I run fanficfare.exe it loads all my prefered settings from personal.ini and downloads all the stories I picked.
This way I have to open cmd and only run one story at a time (otherwise the above chapter range will apply to all of the stories in the txt file)

Is there a posibility to add a similar ability to the CLI, or maybe add the option to download the latest 5 chapters or something? That way I could download the stories quickly and if I want to I can then download the complete versions of the ones I liked?

**Comment by JimmXinu** [comment]
Multiple download from file wasn't a CLI option at the time and nobody asked for individual chapter range before.  I'll look into it.

**Comment by JimmXinu** [comment]
FanFicFare-2.25.5 uploaded to pypitest.  Re-open this issue if you find any problems with it.
