### ISSUE TITLE
Request for a feature

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#307]
This is related to issue #302 
Is it possible to add the possibility to download say a story like this:

> https://www.fanfiction.net/s/12592223/[49-]

or this:

> https://www.fanfiction.net/s/12592223/[49-*]

This story is 50 chapters long so it would download the last 2 chapters.

**Comment by JimmXinu** [comment]
It already works that way for https://www.fanfiction.net/s/12592223/[49-]

If you're using it as a CLI argument, you have to quote or escape appropriately for your shell.
