### ISSUE TITLE
Please add support for Story Only threads if thread title includes 'Story(-| )?Only'

### ISSUE THREAD

**Issue by deepbhattacharya** [JimmXinu/FanFicFare#308]
I know the stated reason (possible server overuse etc) but could you not add a check that the thread title includes the string Story Only? Many of my favorite stories don't have an indexed thread. Since you support reading mode threads this should not be a big issue for you?

**Comment by JimmXinu** [comment]
Clearly, you're already aware of the answer given for this request previously.

And a extremely cursory look at the 'Archive' threads on SV alone shows that some variant of 'Story Only' in the thread title is _not_ consistently present.
