### ISSUE TITLE
Webnovel.com Error

### ISSUE THREAD

**Issue by TheOne320** [JimmXinu/FanFicFare#309]
When trying to download from webnovel.com I get the following error:

Status
Title
Author
Comment
URL
Bad
Unknown
Unknown
'NoneType' object has no attribute 'find_all'
https://www.webnovel.com/book/7931338406001705

**Comment by JimmXinu** [comment]
Already fixed in [test version](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2), will be in next released version
