### ISSUE TITLE
Anthology has no summary in the comments

### ISSUE THREAD

**Issue by Tharos123** [JimmXinu/FanFicFare#310]
If I summarize a Anthology of ebooks over a few pages, only the respective titles of the individual pages are in the comments. But not the summary of the pages.

When I read the FAQ, I see that EpubMerge is used in Anthology. So I guess that's the problem there.

**Comment by JimmXinu** [comment]
There's an option in FanFicFare config to included story descriptions in the anthology comments.

![capture](https://user-images.githubusercontent.com/11446969/41989932-9e5a29be-7a06-11e8-975c-8a252f49b8ff.PNG)
