### ISSUE TITLE
GravityTales error

### ISSUE THREAD

**Issue by minijackson** [JimmXinu/FanFicFare#312]
Hello, and thanks for the great addon!

I'm having trouble adding this novel:

http://gravitytales.com/novel/the-good-student/

I have this error:

`'NoneType' object has no attribute 'h3'`

Version: v2.26.0

Let me know if I can do more to help.

**Comment by JimmXinu** [comment]
Fixed 2be25aa2f24a8528e5867d9fe7bd0eb0b3b46bdd 
Will appear in the next released version.
