### ISSUE TITLE
RoyalRoad issue

### ISSUE THREAD

**Issue by minijackson** [JimmXinu/FanFicFare#313]
Hello and thanks *again* for the great addon

I'm having an issue adding this fanfiction:

https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests

The behavior is that there is a python process stuck, with 100% CPU consumption.

Log:

```
Download 1 FanFiction book(s)
FFF: INFO: 2018-07-03 11:26:01,493: calibre_plugins.fanficfare_plugin.jobs(50): FanFicFare v2.26.0
FFF: INFO: 2018-07-03 11:26:01,494: calibre_plugins.fanficfare_plugin.jobs(54): Adding jobs for URLs:
FFF: INFO: 2018-07-03 11:26:01,494: calibre_plugins.fanficfare_plugin.jobs(56): http://royalroadl.com/fiction/8894
```

Version: v2.26.0

**Comment by JimmXinu** [comment]
Downloaded correctly for me after ~5 minutes.

How long did you wait for it?  Because that story has 260+ chapters which is going to take a while.

That site is also one of the ones that is changed to use https in the current test version.  It's possible that has an effect.  Try with the [latest test version](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).  Or with the next release, which I plan to put out today.

**Comment by minijackson** [comment]
I've stopped it after ~20 minutes with the version you linked. I don't have the best internet connection, but it shouldn't take that long ^^

**Comment by JimmXinu** [comment]
Are you talking about 20 minutes just to get started, or for the background download?

If we're talking about the time to download the entire story, depending on:
- Your settings (`slow_down_sleep_time`), 
- Your internet connection, and,
- Whether the site is throttling your access (we've seen it with other sites when you download a lot of stuff), 

...it could well take longer than 20 minutes.  If each chapter took 10 seconds (inconvenient, but not outrageous), it would take more than 40 minutes for the 263 chapters.

**Comment by minijackson** [comment]
Okay, so I left it running for longer this time, and set `slow_down_sleep_time:0.1` in the `[defaults]` section of `personal.ini`, and after ~1h30, it finished! (I wasn't sure this would work, because I monitored network activity with nethogs and saw nothing from python/Calibre/etc)

This still seems to me like long time, even for 263 chapters so I don't know if it's normal behavior.

But it works, thanks for the pointers!

**Comment by Twilight666** [comment]
Hey I just saw this.
After it downloaded did you check the epub that was created?
What was the size of the file?
Everybody Loves Large Chests has ~ 55 fanart pictures as part of the story so it might be what was slowing it down even more if you have such a bad internet connection

**Comment by minijackson** [comment]
It's 7.1 MB and I checked, I can see pictures. But I don't have that bad of a connection, it should be between 750 kB/s and 1.5 MB/s

**Comment by JimmXinu** [comment]
The fact that it eventually finishes proves that FFF is working correctly.  

The delays you are seeing are outside our control, sorry.
