### ISSUE TITLE
Adding support for harrypotterfanfiction.com

### ISSUE THREAD

**Issue by maxcb97** [JimmXinu/FanFicFare#314]
The site was reopened at the start of this month, but they changed the formatting so the old adapter removed in [3e49134](https://github.com/JimmXinu/FanFicFare/commit/3e49134cf6750660f28418f0aa27a502fbfeeb45) no longer works.

**Comment by JimmXinu** [comment]
I'll look into this, but it's not going to make it into today's new release.

**Comment by JimmXinu** [comment]
This is basically a new site now.  But since it's also kind of an existing site, I've (re)added it. 9e16cdf4ef42bed4c72c284b26c6e9093e63c0e7

Plugin test version [here](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2) or use test.pypi.org for CLI.
