### ISSUE TITLE
Feature Request: Skip Chapters

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#318]
Some stories have several chapters that are not actual story chapters (Q&A, author notes, gallery chapters)
An example like that is this:

> https://royalroadl.com/fiction/8894

While it would be complicated to use would it be possible to use something like:

> https://royalroadl.com/fiction/8894/[1-28,30-121,123-]

to basically skip some chapters?

**Comment by JimmXinu** [comment]
Yes, it would be complicated.

I would not implement something like that as part of the 'range' feature as you indicate because you would have to enter that complicated 'range' URL every time you wanted to update it, too.  URL ranges are not saved(although there are `first_chapter`/`last_chapter` settings you can put in `personal.ini` that are equivalent).

A `personal.ini` setting for a list of chapter URLs to ignore is more workable, but would require refactoring how the chapter list is created and `numChapters` set across all adapters.  

I would lean towards chapter URLs vs numbers because some authors/sites insert chapters in the 'middle' relative to the entire list--especially xenforo threadmarks where all Sidestory chapters come after Threadmark chapters, etc.  

Recording chapter numbers to ignore isn't necessarily easy either--the example story you gave doesn't show chapter numbers on the source site.

If you would find something like this acceptable:
```
[https://www.royalroadl.com/fiction/8894]
ignore_chapter_list:
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/103862/not-a-chapter-q-a
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/126673/not-a-chapter-qa-with-the-author
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/134099/not-a-chapter-ellc-world-map
 ...
```
... I will looking into implementing.

FYI, you can put the chapter link into each chapter's output using something like this, perhaps in `[epub]` for all sites.  This is a setting I use personally:
```
[base_xenforoforum:epub]
chapter_start:<?xml version="1.0" encoding="UTF-8"?>
 <html xmlns="http://www.w3.org/1999/xhtml">
 <head>
 <title>${chapter}</title>
 <link href="stylesheet.css" type="text/css" charset="UTF-8" rel="stylesheet"/>
 <meta name="chapterurl" content="${url}"></meta>
 <meta name="chapterorigtitle" content="${origchapter}"></meta>
 <meta name="chaptertoctitle" content="${tocchapter}"></meta>
 <meta name="chaptertitle" content="${chapter}"></meta>
 </head>
 <body>
 <h3>${chapter}</h3>
 <p class="skip_on_ffdl_update"><a class="small" href="${url}">chapter link</a></p>
```

**Comment by Twilight666** [comment]
Yeah the solution with the ignore list is perfectly fine. I would have to edit personal.ini but it might be for the best since I could then redownload the story without having to figure out what the url has to be each time.

I don't get the last bit though. From what I can guess it seemsto to add a urk link under 'chapter link' that redirects to the original url to open on the browser, right? But what does that have to do with the current issue? Also what does the skip_on_ffdl_update class do?

**Comment by JimmXinu** [comment]
Alright, I'll look into implementing it.

Redownload == Update?  I highly encourage using EPUB and Update so as not to download 200+ chapters for every update...

The `chapter_start` setting, as you say, puts chapter URL link at the start of each chapter, so you don't have to go looking for it.  I include that in all my base_xenforoforum ebooks for ease of going back to the forum discussion at that post.  Also gives you an easy place to grab the chapter URL if you want to add it to an ignore list...

**Comment by JimmXinu** [comment]
Another thought about this feature req occurred to me while working on word count for #319:

Because word count is usually taken from the site's metadata (and most sites don't include chapter word counts) excluding chapters will cause word count to be inaccurate for most stories.

**Comment by JimmXinu** [comment]
v2.27.3 Plugin and CLI test versions with `ignore_chapter_url_list` feature are posted.

Extra per-chapter metadata as requested in #319 will require some more work, but depended on infrastructure changes made for this.

**Comment by JimmXinu** [comment]
I've put out CLI test version v2.27.4.  

This adds a few bits of metadata per-chapter for base_xenforo.

For more details, see:
https://github.com/JimmXinu/FanFicFare/blob/chapter_metadata/fanficfare/defaults.ini#L705

**Comment by Twilight666** [comment]
OK, A little help
I am downloading this:

> https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests


I have updated FanFicFate to the latest test version and I have added this:

> [https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests]
> ignore_chapter_url_list:
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/103862/not-a-chapter-q-a
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/126673/not-a-chapter-qa-with-the-author
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/134099/not-a-chapter-ellc-world-map
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/137623/not-a-chapter-art-gallery
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/152116/not-a-chapter-qa-session
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/164640/not-a-chapter-art-gallery-2-electric-boogaloo
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/165702/not-a-chapter-best-girl-poll
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/169823/not-a-chapter-kindle-re--release
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/197943/not-a-chapter-amazon-book-stuff
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/203679/not-a-chapter-announcement-qa-with-the-author
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/229104/not-a-chapter-fanart-dump

 to personal.ini
But it downloads everything.
What am I doing wrong?

Also this:
> https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/[260-]
should also download the latest chapters apart from 
>  https://www.royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/229104/not-a-chapter-fanart-dump
right? Because that doesn;t work either

**Comment by JimmXinu** [comment]
You need to use the 'canonical' URLs that FFF uses.  Note the `www.' is removed and the shortened story URL form.  That's why I specifically mentioned about adding chapter URL to `chapter_start` earlier.

I assume, although I can't see them, that you have a leading space for each ignore line.

This works for me:
```
[https://royalroadl.com/fiction/8894]
ignore_chapter_url_list:
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/103862/not-a-chapter-q-a
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/126673/not-a-chapter-qa-with-the-author
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/134099/not-a-chapter-ellc-world-map
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/137623/not-a-chapter-art-gallery
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/152116/not-a-chapter-qa-session
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/164640/not-a-chapter-art-gallery-2-electric-boogaloo
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/165702/not-a-chapter-best-girl-poll
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/169823/not-a-chapter-kindle-re--release
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/197943/not-a-chapter-amazon-book-stuff
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/203679/not-a-chapter-announcement-qa-with-the-author
 https://royalroadl.com/fiction/8894/everybody-loves-large-chests/chapter/229104/not-a-chapter-fanart-dump
```

Re: [260-], you need to be aware that by completely ignoring chapters, you are changing the chapter numbers.  You'll want [250-] with a 10 line ignore list.  You can see the adjusted chapter list in CLI with `-m`.

I was testing using base_xenforo (since I was also thinking about the requested chapter metadata for it) and it has more code for normalizing both story and chapter URLs.  I will probably need to change the comments on `ignore_chapter_url_list`.

**Comment by Twilight666** [comment]
OK I fixed it, removed www from all urls in the ignore list, and fixed the legend to [https://royalroadl.com/fiction/8894] and it worked!
Thanks!!

**Comment by JimmXinu** [comment]
Remember to try out the metadata per-chapter for base_xenforo.

For more details, see:
https://github.com/JimmXinu/FanFicFare/blob/chapter_metadata/fanficfare/defaults.ini#L705

**Comment by Twilight666** [comment]
Jusy tried that out too, it works as well!

**Comment by JimmXinu** [comment]
What section do you have `tocpage_entry` set in?  And what story URL are you using?  Because I'm not seeing this error.

**Comment by Twilight666** [comment]
I am downloading this:
`https://forums.spacebattles.com/threads/sailor-moon-overlord-the-queen-of-the-moon.577922/`
Currently I have this:
```
[base_xenforoforum]
#use_reader_mode:true
#replace_failed_smilies_with_alt_text:true
#use_threadmark_wordcounts:true
tocpage_entry:
 <a href="#section${index}">${chapter}</a> (added on: ${date}) <br />
#skip_threadmarks_categories:Apocrypha,Media,Staff Post
```
I put everything else in comment.

I then changed it to:
```
[base_xenforoforum]
#use_reader_mode:true
#replace_failed_smilies_with_alt_text:true
#use_threadmark_wordcounts:true
tocpage_entry:
 <a href="#section${index}">${chapter}</a> TMP1--TMP2 <br />
#skip_threadmarks_categories:Apocrypha,Media,Staff Post
```
And it worked (without adding date or wordcount)
Also I copy pasted the first one in my CLI's personal.ini and it worked fine. For some reason calibre does not seem to understand what $(kwords) and $(date) means

**Comment by Twilight666** [comment]
.... oh yeah I use everything
Calibre is basically my Library so I have a limited amount of stories there and they are not always up to date.
The stories I download with CLI are usually stories that I will delete afterwards (unless I really like them and then add them to calibre) or stuff like https://royalroadl.com/fiction/8894 which is huge and I download the last couple of chapters and at some point I update it in the library.
Hell I even use the webservice if I am away from home.
But yeah now that you mention it Calibre says that the plugin version in 2.27.3.

But yeah the CLI version works perfectly

**Comment by JimmXinu** [comment]
I've updated the master branch and the posted plugin test version.  If you run into any more problems, go ahead and open a new issue for them.
