### ISSUE TITLE
Emailing to Kindle for .mobi formats?

### ISSUE THREAD

**Issue by Fijjetmonster** [JimmXinu/FanFicFare#322]
Downloading things from my phone and then sending them to my Kindle is a real hassle. Especially because if I include one .epub, then the entire email won't take any of the .mobi files.

**Comment by JimmXinu** [comment]
I'll look into it, but it looks like there would be some pretty tight limitations--only 100 emails per day--for _all_ users, not _each_ user.

**Comment by ksurl** [comment]
use calibri to convert to mobi

**Comment by JimmXinu** [comment]
Revisiting this again, Amazon is now accepting the same mobi files it was rejecting a couple weeks ago.  

On one hand, that's good.  OTOH, it also means it could stop working again at any time.

Now that I can play with it, I see that sending a newer version of the same fic creates a new book on Kindle with the same name.  That's annoying, but presumably how it works for you manually now.

I'm still not 100% sure how (or if) this option should be offered, but you can try it out at:
http://2-37-13-dot-fanficfare.appspot.com

**Comment by JimmXinu** [comment]
Closed for lack of response to test version provided.
