### ISSUE TITLE
request for mark_new_chapters

### ISSUE THREAD

**Issue by Nothorse** [JimmXinu/FanFicFare#330]
If you update a story multiple times, and have mark_new_chapters: true, currently all new chapters after that initial download are marked as new. It would be neat if there were an option to either generally remove the mark on update from existing chapters, or have a flag on update to do the same, if that's even possible.

**Comment by JimmXinu** [comment]
In the next version you will be able to set `mark_new_chapters:latestonly` to get that.

**Comment by Nothorse** [comment]
Cool. Thanks.
