### ISSUE TITLE
Spacebattles/SufficientVelocity format change

### ISSUE THREAD

**Issue by Xon** [JimmXinu/FanFicFare#332]
To reduce the server load of rendering very large threadmark lists, these sites now only render a chunk at a time and have a filler "load more" links.

https://forums.sufficientvelocity.com/threads/to-boldly-go-a-starfleet-quest.32005/threadmarks

The filler row has this sort of HTML;
```html
<li class="primaryContent threadmarkListItem ThreadmarkFetcher _depth1 filler" data-range-min="43" data-range-max="399" data-thread-id="32005" data-category-id="1" title="356 hidden"> ...
</li>
```
Clicking on the above HTML will call;
```https://forums.sufficientvelocity.com/threads/to-boldly-go-a-starfleet-quest.32005/threadmarks/load-range?min=43&max=399&category_id=1```
Notes;
- return results can be json wrapped or HTML, depending on accepts header
- This requests returns threadmarks > 43 and < 399

This returns some arbitrary length list of threadmarks. There may be additional filler rows in the returned data.

This approach is also used in the XenForo 2 version of this add-on, but the HTML may change to something to be more responsive design friendly before it SB/SV migrate to XF2.

**Comment by JimmXinu** [comment]
Thanks, I appreciate the heads up.

> - This requests returns threadmarks > 43 and < 399

It seems a little odd that `load-range` cannot return the first threadmark, even with `min=0` but I can work with it.

**Comment by Xon** [comment]
I've tweaked how it selects items to fetch, the threadmark list should always have the first threadmark in the list.

**Comment by JimmXinu** [comment]
There's a possible 'off-by-one' issue with the end of the list.  I can work around it trivially, but I thought you should know.

When a filler line occurs at the end of a threadmark list, the `data-range-max` value on the `<li>` is one too small to use directly.  I need to use `data-range-max`+1 when calling `load-range` to get all the threadmarks.  

Further, when there's a ton of threadmarks and I need to fetch `load-range` more than once, the value for `data-range-max` in the response appears to be _decremented_ each time if I don't add 1 to max.  So for the [example above](https://forums.sufficientvelocity.com/threads/to-boldly-go-a-starfleet-quest.32005/threadmarks), the cat=1 list (1280 threadmarks) ends with a filler line:
```
<li ... data-category-id="1" data-range-max="1279" data-range-min="49" data-thread-id="32005" title="1230 hidden"> ...
```
Fetch 
`....32005/threadmarks/load-range?min=49&max=1279&category=1`
final filler line is:
```
<li ... data-category-id="1" data-range-max="1278" data-range-min="249" data-thread-id="32005" title="1028 hidden"> ...
```
Fetch 
`....32005/threadmarks/load-range?min=249&max=1278&category=1`
final filler line is:
```
<li ... data-category-id="1" data-range-max="1277" data-range-min="449" data-thread-id="32005" title="827 hidden"> ...
```
And so on.

But I can add 1 to max whenever I fetch `load-range` easily enough.

And I don't see an issue like this in browser--it looks like filler lines never appear at the end of a threadmark list, in Chrome at least.

**Comment by Xon** [comment]
Yeah, I fixed that bug in the XF2 version but forgot to fix it in the XF1 version. Just deploying a fix to SB/SV now for it.
