### ISSUE TITLE
Support for www.Royalroad.com

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#334]
Now that www.royalroad.com is also accepted as a host to download the new urls work.
However in personal.ini I have to have options for both if I want a story to work both ways.

Both in the options and in the ignore chapter list.
FunficFare supports both but is it possible to understand it's the same site and apply the same options in both cases?
Because if I want to add new chapter in the ignore lit I must remember to do it twice. Same if I want to add a new option

**Comment by Twilight666** [comment]
Also I checked and legend_spoilers does not work on www.Royalroad.com

**Comment by JimmXinu** [comment]
Why do you want to keep both versions?  You should be able to use just royalroad.com URLs now.

Please provide a story URL demonstrating the `legend_spoilers` problem.  I don't read that site, so I don't have examples in hand.  Obviously you do, if you're seeing an issue.

**Comment by Twilight666** [comment]
OK I will just remove the old ones if it is certain it has the new one permanently
As for the remove_legends , I am not 100% certain it won't work but on calibre when I tried to add:
```
[www.royalroad.com]
legend_spoilers:true
```
for the new URL it says that  legend_spoilers not valid in section [www.royalroad.com] -- only valid in {list of sites}

**Comment by JimmXinu** [comment]
<shrug> I have no control over what the sites choose to do with their domain names.

`legend_spoilers`/`remove_spoilers` should work in `[royalroad.com]`.  The warnings are a separate piece of code.  Fix in the next release. be37084d
