### ISSUE TITLE
Error in Webservice (FFnet)

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#335]
I was using the webservice to download various stories.
One of the stories I used was:

> https://www.fanfiction.net/s/13022804/6/Choose-your-own-Award

and it gave an error.

I tried again and it worked.

However because of how it works I can't see the error to post it here since when I tried again, the list of previously downloaded stories replaced the error message with the downloaded story.

From what  I remmeber it mentioned some kins of URL error and had the url: https://www.fanfiction.net/s/13022804/2 mentioned in the message.

The same thing happened sometime earlier today and the same thing happened then.
The latest error happened at ~13:10 GMT

**Comment by JimmXinu** [comment]
If there's a problem with the FanFicFare software itself, it is almost always consistent in failing.
If a story sometimes fails and sometimes works, especially with the web service, it's almost always something else outside my control: site issues(including blocking), network, or web service engine.

There are a couple FAQs that apply:
- [Why am I having errors downloading from fanfiction.net?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-am-i-having-errors-downloading-from-fanfictionnet)
- [Why has the web service version of FanFicFare stopped working?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-has-the-web-service-version-of-fanficfare-stopped-working)
