### ISSUE TITLE
CLI test version

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#337]
Hey, can I use the latest test version on CLI?
I checked here:

> https://test.pypi.org/project/FanFicFare/#history

and it doesn't seem to have been added.

Did it not work or is it no longer possible now that python3 is being supported as well

**Comment by JimmXinu** [comment]
I just hadn't done it.  I don't always do CLI (or web service) test versions unless specifically asked.

**Comment by Twilight666** [comment]
Ok thanks, I updated the test CLI version to 3.0.2 and #336 is working
