### ISSUE TITLE
Minor Feature request for Archive of Our Own

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#340]
On AO3 sometimes the author will include his prediction to how many chapters his fic will be by having a

> Chapters:8/11

like in here:

> https://archiveofourown.org/works/4675508/chapters/10671143

Is it possible to add this in the inline Title page metadata?

Edit: What I basically saying is that if it's Chapters:8/11 to add the /11 in the **Chapters:** 8 part, but if it was Chapters:8/? then have it **Chapters:** 8 like it is now

**Comment by JimmXinu** [comment]
The `numChapters` metadata is a numeric value.  It's set by the number of chapters collected.  I can't change it just for AO3.

What I can do is add a new metadata entry, such as `ao3chapters` (label: "AO3 Chapters"), that contains the '8/11' or '3/?' from the site.  You could remove '/?' with `replace_metadata` if desired:

```
[archiveofourown.org]
add_to_replace_metadata:
 ao3chapters=>/\?$=>
```

**Comment by Twilight666** [comment]
In that case wouldn't the chapter metadata be basically included twice in AO3?
Is it even possible to skip the original chapters metadate just for ao3?

In fact, it's fine. This was just a minor request for a specific site.
You can just skip this. It looks like it's more trouble to implement for the user than it's worth for such a minor change in the epub. And since the author can just change the projected number of chapters for his fic at will, it is not such an important field

**Comment by JimmXinu** [comment]
If you added `ao3chapters` to `titlepage_entries` without removing `numChapters`, yes, you'd get both.

Changing `titlepage_entries` for AO3 only in personal.ini is not difficult, as is changing `ao3chapters_label` if you don't like 'AO3 Chapters' as the label.

Adding `ao3chapters` to the adapter is quite easy--I've coded it already.  But if you wouldn't use it, I won't bother putting it in.

**Comment by Twilight666** [comment]
To clarify if I use titlepage_entries under [archiveofourown.org] and add all the entries that are currently used by default but skip numChapters then it would work.
But then I would have to keep it up-to-date to any changes.
That's complicated, is very easy to make mistakes, for something that is very subjective and depends on the authors whims.

Never mind then. There is not need to add this. Sorry for the inconvenience
