### ISSUE TITLE
Feature Request: Royal Road TOC extras

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#341]
This is similar to #336 and #319 
In RoyalRoad in each chapter there is a value that has the date published here:

> \<i class="fa fa-calendar" title="Published"></i> <time ...

In the central TOC the above time is parsed in how many days/months ago it was so it can't be used directly.
Is it possible to gather the individual dates in each chapter and use then in the inline TOC?

**Comment by JimmXinu** [comment]
Not without more re-architecting than it's worth.  Chapter list and therefore chapter metadata are gathered during `extractChapterUrlsAndMetadata()` which explicitly does _not_ fetch chapters.
