### ISSUE TITLE
XenForoForum/Calibre Plugin Threadmark overload!

### ISSUE THREAD

**Issue by conantheimp** [JimmXinu/FanFicFare#342]
I tried to download a story with a metric onager-load of threadmarks on Sufficient Velocity. 162 threadmarks at last check. The story downloaded just fine(and I was pleasently surprised to find that it properly ported most of the embedded pictures), but I learn after reading for a few days that it skipped a good third of the chapters!

After chapter 10.8(plus another ancillary mark), it skips directly to 16.2, leaving out a good portion of, well, everything. On further investigation the problem seems to be with how XFF parses the threadmarks. On SF, when I look at the threadmarks, there being so many, the site so helpfully "hides" some after a certain number have been created, preventing the list from being overwhelmingly long. Said hiding is demonstrated by an ellipses("..."), hiding a good 40 posts behind a single mouse-click.

However, clicking is reasonably beyond the current set up of (my current version of/my settings of?) FanFicFare, and as such won't actually read those links as existing.

Any idea if there is a fix within reach my own reach, or if this is an issue you can tackle in a reasonable amount of time?

For the record, here's the fic in question: https://forums.sufficientvelocity.com/threads/hatchling-quest-worm-metroid.22540/

**Comment by JimmXinu** [comment]
Update to the current version.

This was reported a month ago (#332) and is already fixed.  Just to be sure, I downloaded that story and got all chapters.
