### ISSUE TITLE
Erorr, time data does not match format

### ISSUE THREAD

**Issue by sadekodinny** [JimmXinu/FanFicFare#345]
I've try to update novels from http://www.wuxiaworld.co/ 
in calibre and web service, it returns same error:
time data '2018/10/10 23:08:49' does not match format '%Y/%m/%d %I:%M:%S'

- The list of novels with erorrs:
http://www.wuxiaworld.co/Martial-God-Asura/
http://www.wuxiaworld.co/Martial-World/
http://www.wuxiaworld.co/Super-Gene/
http://www.wuxiaworld.co/True-Martial-World/
http://www.wuxiaworld.co/War-Sovereign-Soaring-The-Heavens/
http://www.wuxiaworld.co/Lord-Xue-Ying/
http://www.wuxiaworld.co/Dragon-Marked-War-God/
http://www.wuxiaworld.co/Swallowed-Star/
http://www.wuxiaworld.co/King-of-Gods/
http://www.wuxiaworld.co/Against-the-Gods/

- The list of updated novels:
http://www.wuxiaworld.co/Sovereign-of-the-Three-Realms/
http://www.wuxiaworld.co/Ancient-Godly-Monarch/
http://www.wuxiaworld.co/God-of-Slaughter/
http://www.wuxiaworld.co/Martial-Peak/
http://www.wuxiaworld.co/A-Record-of-a-Mortal-is-Journey-to-Immortality/
http://www.wuxiaworld.co/I-am-Really-a-Superstar/

**Comment by JimmXinu** [comment]
Test versions posted.
https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2
https://3-0-9-dot-fanficfare.appspot.com/
