### ISSUE TITLE
Make -u more scripting friendly

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#350]
After the fiasco of #347, I would like two more suggestions for making ``-u`` option more scripting friendly:

1. If I have ``defaults.progressbar: true`` in ``~/.fanficfare/personal.ini``, would it be possible to somehow switch it off (either ``--no-progressbar`` or ``--quiet`` to the command line)?

2. Could the script return exit status according to whether there the book was actually updated or whether it was already up-to-date?

**Comment by mcepl** [comment]
Just for those who may trip on this issue looking for the backup script for their library (yes, I’ve read FAQ and I try to be as gentle towards the publishing sites as possible):
```sh
#!/bin/sh

export DAYS=91

find ~/Knihy/fanfiction/ -name \*.epub -mtime -${DAYS} -print0 | \
    xargs -t -L 50 -0 fanficfare -o slow_down_sleep_time=6 -u \
        >/tmp/knih_update.log 2>&1
find ~/Knihy/fanfiction/ -daystart -mtime -1 -name \*.epub -print -exec ~/.bin/epubsetdate '{}' \;
```
(the last line is completely optional, and it uses my other script [epubsetdate](https://gitlab.com/snippets/1932697) to set mtime of the file according to the last-updated time in the document).

**Comment by JimmXinu** [comment]
@mcepl - Why don't you add that to the [User Contrib wiki page](https://github.com/JimmXinu/FanFicFare/wiki/UserContributedContent)?

That will have more long term visibility than a closed issue.

**Comment by mcepl** [comment]
> @mcepl - Why don't you add that to the [User Contrib wiki page](https://github.com/JimmXinu/FanFicFare/wiki/UserContributedContent)?
> 
> That will have more long term visibility than a closed issue.

Done. Thank you for the suggestion.
