### ISSUE TITLE
Storiesonline gives a 307 during login 

### ISSUE THREAD

**Issue by FZelle** [JimmXinu/FanFicFare#351]
FFF: DEBUG: 2018-10-22 11:10:34,296: configurable.py(1178): Giving up on https://storiesonline.net/sol-secure/login.php
FFF: DEBUG: 2018-10-22 11:10:34,298: configurable.py(1179): HTTP Error 307: Temporary Redirect

This started last week.

**Comment by JimmXinu** [comment]
Fixed in 65623b2f52d3741effbb2fad36ff1520f66ea87b
