### ISSUE TITLE
Issue with the web service

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#358]
I have been trying to use the webservice and for some reason it doesn't seem to be working today for ffnet
It keeps giving the error:

> Deadline exceeded while waiting for HTTP response from URL: \<Story url>

That includes this:

> https://www.fanfiction.net/s/13075474/[68]

that I had downloaded yesterday and tried again today as a test

**Comment by JimmXinu** [comment]
See FAQs:

- [Why has the web service version of FanFicFare stopped working?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-has-the-web-service-version-of-fanficfare-stopped-working)
- [Why am I having errors downloading from fanfiction.net?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-am-i-having-errors-downloading-from-fanfictionnet)

In fact, we've had this conversation before #335.

**Comment by Twilight666** [comment]
FYI over the past 2 weeks, every time I have tried the web service was not working for FFnet

**Comment by Twilight666** [comment]
It seems to be working now
