### ISSUE TITLE
Royal Road image issue on CLI

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#360]
I was downloading

> https://www.royalroad.com/fiction/8894

and for some reason the images are not working properly
specifically the latest chapter

> https://www.royalroad.com/fiction/8894/[298]

has an image that was not downloaded and the previous one

> https://www.royalroad.com/fiction/8894/[297] 

had 2 images  and only one was downloaded
Edit: Also I just checked the calibre version downloaded them fine (on the other hand the webservice does not download images anyway)

**Comment by JimmXinu** [comment]
What errors do you get?

I just downloaded those two chapters using CLI and got all three images just fine.  See debug and epub attached.

```
python fanficfare\cli.py -d "https://www.royalroad.com/fiction/8894/[297-298]"
FFF: DEBUG: 2018-11-15 18:57:53,026: cli.py(184):     OS Version:Windows-10-10.0.17763
FFF: DEBUG: 2018-11-15 18:57:53,026: cli.py(185): Python Version:2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
FFF: DEBUG: 2018-11-15 18:57:53,026: cli.py(186):    FFF Version:3.1.9
FFF: DEBUG: 2018-11-15 18:57:53,058: adapter_royalroadcom.py(151): URL: https://www.royalroad.com/fiction/8894
FFF: DEBUG: 2018-11-15 18:57:53,059: configurable.py(1099): #####################################
pagecache(GET) MISS: https://www.royalroad.com/fiction/8894
FFF: DEBUG: 2018-11-15 18:57:54,881: configurable.py(1099): #####################################
pagecache(GET) MISS: https://i.imgur.com/YKWcrl3.jpg
FFF: DEBUG: 2018-11-15 18:57:55,125: adapter_royalroadcom.py(221): stars:(4.650216)
FFF: DEBUG: 2018-11-15 18:57:55,132: configurable.py(1099): #####################################
pagecache(GET) MISS: https://www.royalroadcdn.com/exterminatus/everybody-loves-large-chests-full-AACAAjOieQo=.jpg
FFF: INFO: 2018-11-15 18:57:55,352: base_writer.py(183): Save directly to file: Everybody Loves Large Chests-rylrdl_8894.epub
FFF: DEBUG: 2018-11-15 18:57:55,526: adapter_royalroadcom.py(238): Getting chapter text from: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/304806/legacy-5
FFF: DEBUG: 2018-11-15 18:57:55,526: configurable.py(1099): #####################################
pagecache(GET) MISS: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/304806/legacy-5
FFF: DEBUG: 2018-11-15 18:57:56,431: configurable.py(1099): #####################################
pagecache(GET) MISS: https://cdn.discordapp.com/attachments/317306506863181845/509826096305405952/house_mimics_small_ones_shot_copy.jpg
FFF: DEBUG: 2018-11-15 18:57:57,036: configurable.py(1099): #####################################
pagecache(GET) MISS: https://cdn.discordapp.com/attachments/400347411391971329/509751312351756289/house_mimics_medium_ones_shot_copy.png
FFF: DEBUG: 2018-11-15 18:57:58,118: adapter_royalroadcom.py(238): Getting chapter text from: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/306891/legacy-6
FFF: DEBUG: 2018-11-15 18:57:58,119: configurable.py(1099): #####################################
pagecache(GET) MISS: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/306891/legacy-6
FFF: DEBUG: 2018-11-15 18:57:58,821: configurable.py(1099): #####################################
pagecache(GET) MISS: https://cdn.discordapp.com/attachments/407834367721865216/510191108962123779/House_mimics_Homer.png
```

[Everybody Loves Large Chests-rylrdl_8894.zip](https://github.com/JimmXinu/FanFicFare/files/2587582/Everybody.Loves.Large.Chests-rylrdl_8894.zip)

**Comment by Twilight666** [comment]
Ok I went on the command propmt ad run it with debug, here is the output:
> FFF: DEBUG: 2018-11-16 08:26:36,944: cli.py(184):     OS Version:Windows-10-10.0.17134
> FFF: DEBUG: 2018-11-16 08:26:36,944: cli.py(185): Python Version:2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
> FFF: DEBUG: 2018-11-16 08:26:36,944: cli.py(186):    FFF Version:3.1.0
> FFF: DEBUG: 2018-11-16 08:26:37,006: adapter_royalroadcom.py(151): URL: https://www.royalroad.com/fiction/8894
> FFF: DEBUG: 2018-11-16 08:26:37,006: configurable.py(1099): #####################################
> pagecache(GET) MISS: https://www.royalroad.com/fiction/8894
> FFF: DEBUG: 2018-11-16 08:26:42,510: configurable.py(1099): #####################################
> pagecache(GET) MISS: https://i.imgur.com/YKWcrl3.jpg
> FFF: DEBUG: 2018-11-16 08:26:43,186: adapter_royalroadcom.py(216): stars:(4.650324)
> FFF: DEBUG: 2018-11-16 08:26:43,201: configurable.py(1099): #####################################
> pagecache(GET) MISS: https://www.royalroadcdn.com/exterminatus/everybody-loves-large-chests-full-AACAAjOieQo=.jpg
> FFF: INFO: 2018-11-16 08:26:43,621: base_writer.py(183): Save directly to file: C:\Users\user\Documents\COLLEC~1\_CONVE~1\FanFicFare\epubs_tmp\Exterminatus - Everybody Loves Large Chests (Ch 279-280)-rylrdl_8894.epub
> FFF: DEBUG: 2018-11-16 08:26:43,772: adapter_royalroadcom.py(233): Getting chapter text from: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/304806/legacy-5
> FFF: DEBUG: 2018-11-16 08:26:43,772: configurable.py(1099): #####################################
> pagecache(GET) MISS: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/304806/legacy-5
> FFF: DEBUG: 2018-11-16 08:26:46,322: configurable.py(1099): #####################################
> pagecache(GET) MISS: https://cdn.discordapp.com/attachments/317306506863181845/509826096305405952/house_mimics_small_ones_shot_copy.jpg
> FFF: DEBUG: 2018-11-16 08:26:48,319: configurable.py(1099): #####################################
> pagecache(GET) MISS: https://cdn.discordapp.com/attachments/400347411391971329/509751312351756289/house_mimics_medium_ones_shot_copy.png
> FFF: INFO: 2018-11-16 08:26:51,753: story.py(1207): Failed to load or convert image,
> parent:https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/304806/legacy-5
> skipping:https://cdn.discordapp.com/attachments/400347411391971329/509751312351756289/house_mimics_medium_ones_shot_copy.png
> Exception: unknown color specifier: u'#none'
> FFF: DEBUG: 2018-11-16 08:26:51,973: adapter_royalroadcom.py(233): Getting chapter text from: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/306891/legacy-6
> FFF: DEBUG: 2018-11-16 08:26:51,987: configurable.py(1099): #####################################
> pagecache(GET) MISS: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/306891/legacy-6
> FFF: DEBUG: 2018-11-16 08:26:53,963: configurable.py(1099): #####################################
> pagecache(GET) MISS: https://cdn.discordapp.com/attachments/407834367721865216/510191108962123779/House_mimics_Homer.png
> FFF: INFO: 2018-11-16 08:26:56,272: story.py(1207): Failed to load or convert image,
> parent:https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/306891/legacy-6
> skipping:https://cdn.discordapp.com/attachments/407834367721865216/510191108962123779/House_mimics_Homer.png
> Exception: unknown color specifier: u'#none'
> Downloaded Story: "Everybody Loves Large Chests (Ch 279-280)" by "Exterminatus", Chapters: 280, Updated on: "2018-11-15"
and here is the file
[Exterminatus - Everybody Loves Large Chests.zip](https://github.com/JimmXinu/FanFicFare/files/2588173/Exterminatus.-.Everybody.Loves.Large.Chests.zip)
The issues that I get are the 

> FFF: INFO: 2018-11-16 08:26:56,272: story.py(1207): Failed to load or convert image,

and to make it clear the only image options I have set are:

> include_images:true
> make_firstimage_cover:false

and also the exception:

> Exception: unknown color specifier: u'#none'

and the only thing having none in my personall.ini file as a value is 

> background_color: none

which applies to the whole epub not to some conversion to the image

**Comment by JimmXinu** [comment]
`background_color: none` is the problem.

FFF assumes that `background_color` is a hex code color value and passes it as such both into the CSS and into the image conversion process.

There's a notation about that on the `remove_transparency` setting in `defaults.ini`, but not `background_color`.  The color is still parsed by the convert routine, even if `remove_transparency` isn't turned on.

I've added verbiage to the ini files about that and code(139976c1) to enforce it for image conversion.

I've put up a test version of the CLI containing that change.
