### ISSUE TITLE
Error 'utf8' codec can't decode

### ISSUE THREAD

**Issue by szereka** [JimmXinu/FanFicFare#362]
Hiya All
i got this little problem could i get som small help to figure if it me or something else ??

Status : Title : Author : Comment : URL 

Error : Ginny's Plaything by scandalous : lostfanfiction :
'utf8' codec can't decode byte 0xe5 in position 30: invalid continuation byte :
https://hpfanficarchive.com/stories/viewstory.php?sid=43 

My Best Regards
Szereka

PS here is the Complete LOG DS

[error log.txt](https://github.com/JimmXinu/FanFicFare/files/2631298/error.log.txt)

**Comment by szereka** [comment]
Hello thx that worked if i want to do "inclute_images:false" for all of hpfanficarchive.com is the text =

[https://hpfanficarchive.com] or [hpfanficarchive.com]
include_images:false

becuse Most stories Should not have Images that i save

Regards
Szereka

**Comment by JimmXinu** [comment]
```
[hpfanficarchive.com]
include_images:false
```
