### ISSUE TITLE
Minor Issues in Hentai-Foundry

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#363]
To clarify these are issues with the site not FFFare.

example story:

> https://www.hentai-foundry.com/stories/user/Cambrian/31595/Emporium-of-Everything-Multiverse

First of all, for the last month the was an issue with the metadata where new chapters have a wordcount of zero and size of 0. As a result the metadata in the TOC is wrong and so is the overall wordcount. In the above story chapters 4 and 5 have that issue.
I don't think there is anything you can do about it, but I thought I should mention it in case it could cause issues (divide by zero or some other weird exception)

The second one is a issue that has existed for a while. Basically the updated date is wrong. For example in the above story it says it is updated on October 7, 2018 which is the original publiched date. And every time it was updated the updated date stayed the same.
The above can be dealt with by using the metadata data of the last chapter and if it is different you could replace the updated date with that one.
Or you could add another field, like 'Last Chapter Date'.
And maybe add an option for Hentai-Foundry to use it if users don't want to use whatever solution you choose.

To be honest though these are bugs on the site so you could leave things as is

**Comment by JimmXinu** [comment]
I've made a change to look for chapter dates newer than the story Updated Date and set `dateUpdated` to the newest.  ded6f59c798c7f43f7cae192dccb1d0b0e974a70

As for word count and size, I don't know that 0 words for chapter can't be legitimate (a chapter containing only an image maybe?).  

I also added a comment to defaults.ini about how to exclude numWords & size.  

You'd do something like this:
```
[www.hentai-foundry.com]
## Sometimes (perhaps often?) HF stories word counts and size are
## incorrect.  You can exclude them from being used like so:
add_to_exclude_metadata_pre:
 numWords=~.*
 size=~.*
```
You can, of course, apply that by story URL sections instead.
