### ISSUE TITLE
Problem with Updating ArchiveOfOurOwn Stories (calibre)

### ISSUE THREAD

**Issue by tag0** [JimmXinu/FanFicFare#365]
I have a number of stories downloaded from AO3, and I just today (Jan. 1, 2019) tried to update four of them. I checked the URLs and everything is fine. I updated both calibre and the FanficFare plugin (thanks for it, BTW), and I still encountered the problem that has shown up. The following is the resulting error log.

Status        Title                        Author                                        Comment                              URL
Bad            Erased Potential     theslytherinpaladin                    HTTP Error 404: Not Found  https://archiveofourown.org/works/11088315
Bad            Nii-chan! Nii-chan! The_Fluffy_Villain_Fluff_Master HTTP Error 404: Not Found https://archiveofourown.org/works/13967733
Bad            Royal Ward             Catstaff                                      HTTP Error 404: Not Found https://archiveofourown.org/works/1999356
Bad    The War is Far From Over Now   Dont_call_me_Carrie     HTTP Error 404: Not Found https://archiveofourown.org/works/10799406

**Comment by tag0** [comment]
Added: Okay, I just tried downloading it (the whole thing, rather than just updating since Dec. 15th) via the web version of FanficFare. The attached (please ignore the colouring) is the screenshot of what I got in response. Notice that the "Source" URL is indicating a previously used link, and when I click on it, I go directly to the story.
![fff failed](https://user-images.githubusercontent.com/5554126/50579749-8edc7400-0e22-11e9-8d3f-2dfe76928406.jpg)

**Comment by JimmXinu** [comment]
Several recent commits already address that (latest was 32935e507dac6ab0779cb25e1f17a6031a43a864).  As far as I know, it's fixed.  

Test versions of the plugin are [regularly posted](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).
