### ISSUE TITLE
Hentai Foundry issue with new release

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#367]
You didn't release a new test version for #366 so I didn't check, but this seems to be a completely different bug.
Here are some stories:
```
http://www.hentai-foundry.com/stories/user/Cambrian/31875/Hella-Potter-and-Reincarnated-OC-Harry-Potter-AU
http://www.hentai-foundry.com/stories/user/Cambrian/32318/Teaching-Young-Master-Black-Lagoon
http://www.hentai-foundry.com/stories/user/Cambrian/32372/Subverted-Loyalty-Hunter-x-Hunter
http://www.hentai-foundry.com/stories/user/Cambrian/31595/Emporium-of-Everything-Multiverse
```
and they all return the same error in CLI and Calibre
`Failed: Exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>). Run URL individually for more detail.`

Also if you try for an individual story (for example the first)

> Traceback (most recent call last):
>   File "c:\Python27\Scripts\fanficfare-script.py", line 11, in <module>
>     load_entry_point('FanFicFare==3.4.0', 'console_scripts', 'fanficfare')()
>   File "c:\python27\lib\site-packages\fanficfare\cli.py", line 290, in main
>     passed_personalini)
>   File "c:\python27\lib\site-packages\fanficfare\cli.py", line 402, in do_download
>     adapter.getStoryMetadataOnly()
>   File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 287, in getStoryMetadataOnly
>     self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
>   File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 371, in doExtractChapterUrlsAndMetadata
>     return self.extractChapterUrlsAndMetadata()
>   File "c:\python27\lib\site-packages\fanficfare\adapters\adapter_hentaifoundrycom.py", line 80, in extractChapterUrlsAndMetadata
>     data = self._fetchUrl(url)
>   File "c:\python27\lib\site-packages\fanficfare\configurable.py", line 1293, in _fetchUrl
>     referer=referer)[0]
>   File "c:\python27\lib\site-packages\fanficfare\configurable.py", line 1282, in _fetchUrlOpened
>     referer=referer)
>   File "c:\python27\lib\site-packages\fanficfare\configurable.py", line 1183, in _fetchUrlOpened
>     raise(excpt)
> urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

**Comment by JimmXinu** [comment]
The site's SSL cert expired Jan 6, 2019.  You can try reporting it to the site administrators.

This is one of the down sides of everybody going to https.  If they don't update it within a couple weeks, re-open this and I'll look into changing the adapter to http.

**Comment by Twilight666** [comment]
FYI The updated the certificate and it's now working
