### ISSUE TITLE
Problem Downloading specific storiesonline.net story

### ISSUE THREAD

**Issue by LordHarkon** [JimmXinu/FanFicFare#368]
So. I tried downloading a story from storiesonline.net, but i get this error "Story not found in Author's list--change Listings Theme back to Classic" and I don't know what to do. This error occurs with a few other stories too, but not with the majority of them.
The story in question is [this.](https://storiesonline.net/s/19414/cunt-farm-connie-the)

**Comment by JimmXinu** [comment]
Looks like there's a problem with that story in the site's DB.  It doesn't appear in the author's story list, and when you click '**Show Story Details**' you get '**Error! Story not found...**'

You can try reporting the issue to the author or the site admins, but there isn't much I can do about server side issues.
