### ISSUE TITLE
Support for other blog-like sites

### ISSUE THREAD

**Issue by DonaldTsang** [JimmXinu/FanFicFare#369]
- [ ] Deviantart Novels/Journals
- [ ] Blogger
- [ ] Tumblr Blogs

**Comment by JimmXinu** [comment]
I've looked at [blog-like sites](https://github.com/JimmXinu/FanFicFare/wiki/SupportedSites#sites-not-supported) before.  They were not a good fit for FanFicFare.

However, if you provide a few links to stories for each site requested I will at least look at them.

**Comment by DonaldTsang** [comment]
### Regarding DeviantArt
- [ ] `<div class="text">` has everything in the text
- [ ] `<img class="smshadow">` has the thumbnail
- [ ] `<div class="metadata">` and `<div class="text block">` needs some wrangling for tagging

**Comment by JimmXinu** [comment]
No story URLs provided.

**Comment by nadjahrobinson** [comment]
Hi. I know this was forever ago, but would you be willing to take a look at this still.
I have several tumblr examples:
A single fic
https://www.tumblr.com/themidnightcrimson/765896295455080449/super-dark-wanda-with-a-cameo-from-agnes-too?source=share

A fic linked from a masterlist
https://www.tumblr.com/jpmarvel90/725705386669309952/dont-let-me-down-mini-series

A masterlist linked with all the fic parts
https://www.tumblr.com/wandascrush/764755830782509056?source=share

A fic linked with a masterlist and to other parts in sequence
https://www.tumblr.com/just-aake/761185591043948544/a-feline-connection?source=share

I totally get this is not ideal for the plugin but if you had any idea on how to make something to programmatically stitch posts together into an epub, I could possibly work from there.
