### ISSUE TITLE
Increase coverage (https://github.com/kanasimi/work_crawler)

### ISSUE THREAD

**Issue by DonaldTsang** [JimmXinu/FanFicFare#371]
In the README of https://github.com/kanasimi/work_crawler there are many websites that can be included in future versions of FanficFare

**Comment by JimmXinu** [comment]
Clearly, there's already a tool to download those sites.

Unless you yourself are planning to do the implementation to add these to FFF, I don't think this issue is useful to keep open.

**Comment by DonaldTsang** [comment]
@JimmXinu the tool is in JS, not Python, so there is a difference.
