### ISSUE TITLE
Royalroad.com update emails not linking

### ISSUE THREAD

**Issue by Ryune** [JimmXinu/FanFicFare#373]
For a while, emails for RR were actually working and updating stories they were linked to in the emails despite being clicktracker links. As of a day or so ago this is no longer the case. I've checked and my passthrough email for FFF scraping is still getting emails from them.

**Comment by JimmXinu** [comment]
Please include a couple examples of what the emailed URLs from Royalroad.com now look like.

**Comment by Ryune** [comment]
Huh. So after several days of not updating my royal road stories, I set FFF to update stories again so I could confirm that it was getting the other stories though GMX's redirect code. Low and behold but it grabs the RR stories this time. Sorry for the bother.
