### ISSUE TITLE
wuxiaworld.co when downloading stories handshake opperation timed out.

### ISSUE THREAD

**Issue by mhussaincov** [JimmXinu/FanFicFare#378]
hi there,
running fanficfare from git.
on arch linux.
when i try to download a story such as
https://www.wuxiaworld.co/Swallowed-Star/
I get
handshake opperation timed out,
changed connect timeout to 10.0 incase that would help
it did not,
increased time out to larger numbers it did not work,
increased sleep time between chapter get requests,
to every 10 seconds,
no go,
increesed sleep time to longer increments no joy.

is there something i'm doing wrong?
wuxiaworld.com works with out issue,
thanks for your assistence.
Majid

**Comment by JimmXinu** [comment]
Connection issues of all types are usually something outside of FanFicFare.

'handshake opperation timed out' implies it's an error during SSL/TLS connection.  From my test download of the story (which worked, BTW, but took over an hour due to the size), https is only used during the initial metadata collection.  I did see at least one connection fail and retry during chapter downloads.

You might have luck with updating your OS's certificate store but I don't know how you'd do that on arch linux.

It could also be an issue with a firewall/proxy, your computer's firewall software (if any), problems on the site, or the site blocking you if you've been downloading 'too much'.

If you run in debug (`-d`) and post the debug output with the error it might tell me more.

**Comment by mhussaincov** [comment]
hey there jymm,
how do i do that via arch-linux?
thanks for your swift responce :)
Majid Hussain


On 21/02/2019, Jim Miller <notifications@github.com> wrote:
> Connection issues of all types are usually something outside of FanFicFare.
>
> 'handshake opperation timed out' implies it's an error during SSL/TLS
> connection.  From my test download of the story (which worked, BTW, but took
> over an hour due to the size), https is only used during the initial
> metadata collection.  I did see at least one connection fail and retry
> during chapter downloads.
>
> You might have luck with updating your OS's certificate store but I don't
> know how you'd do that on arch linux.
>
> It could also be an issue with a firewall/proxy, your computer's firewall
> software (if any), problems on the site, or the site blocking you if you've
> been downloading 'too much'.
>
> If you run in debug (`-d`) and post the debug output with the error it might
> tell me more.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/JimmXinu/FanFicFare/issues/378#issuecomment-466098111


-- 
kind regards,
Majid Hussain

**Comment by mhussaincov** [comment]
hi there,
will do,
reinstalled arch so lets see how this goes :)

On 21/02/2019, Jim Miller <notifications@github.com> wrote:
> Connection issues of all types are usually something outside of FanFicFare.
>
> 'handshake opperation timed out' implies it's an error during SSL/TLS
> connection.  From my test download of the story (which worked, BTW, but took
> over an hour due to the size), https is only used during the initial
> metadata collection.  I did see at least one connection fail and retry
> during chapter downloads.
>
> You might have luck with updating your OS's certificate store but I don't
> know how you'd do that on arch linux.
>
> It could also be an issue with a firewall/proxy, your computer's firewall
> software (if any), problems on the site, or the site blocking you if you've
> been downloading 'too much'.
>
> If you run in debug (`-d`) and post the debug output with the error it might
> tell me more.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/JimmXinu/FanFicFare/issues/378#issuecomment-466098111


-- 
kind regards,
Majid Hussain

**Comment by mhussaincov** [comment]
hi there jimm,
here is the error I get
FFF: DEBUG: 2019-02-21 19:54:28,043: configurable.py(1179): Caught an
exception reading URL:
http://www.wuxiaworld.co/Swallowed-Star/1016454.html sleeptime(0)
Exception <urlopen error _ssl.c:1039: The handshake operation timed
out>.
FFF: DEBUG: 2019-02-21 19:54:28,545: configurable.py(1102):
#####################################
pagecache(GET) MISS: http://www.wuxiaworld.co/Swallowed-Star/1016454.html
FFF: DEBUG: 2019-02-21 19:54:39,557: adapter_wuxiaworldco.py(124):
Getting chapter text from:
http://www.wuxiaworld.co/Swallowed-Star/1016455.html
FFF: DEBUG: 2019-02-21 19:54:39,557: configurable.py(1102):
#####################################
pagecache(GET) MISS: http://www.wuxiaworld.co/Swallowed-Star/1016455.html
^X      FFF: DEBUG: 2019-02-21 19:55:46,396: configurable.py(1179):
Caught an exception reading URL:
http://www.wuxiaworld.co/Swallowed-Star/1016455.html sleeptime(0)
Exception <urlopen error _ssl.c:1039: The handshake operation timed
out>.

I hope this is of some help?
Majid

On 21/02/2019, Majid Hussain <mhussaincov93@gmail.com> wrote:
> hey there jymm,
> how do i do that via arch-linux?
> thanks for your swift responce :)
> Majid Hussain
>
>
> On 21/02/2019, Jim Miller <notifications@github.com> wrote:
>> Connection issues of all types are usually something outside of
>> FanFicFare.
>>
>> 'handshake opperation timed out' implies it's an error during SSL/TLS
>> connection.  From my test download of the story (which worked, BTW, but
>> took
>> over an hour due to the size), https is only used during the initial
>> metadata collection.  I did see at least one connection fail and retry
>> during chapter downloads.
>>
>> You might have luck with updating your OS's certificate store but I don't
>> know how you'd do that on arch linux.
>>
>> It could also be an issue with a firewall/proxy, your computer's firewall
>> software (if any), problems on the site, or the site blocking you if
>> you've
>> been downloading 'too much'.
>>
>> If you run in debug (`-d`) and post the debug output with the error it
>> might
>> tell me more.
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/JimmXinu/FanFicFare/issues/378#issuecomment-466098111
>
>
> --
> kind regards,
> Majid Hussain
>


-- 
kind regards,
Majid Hussain

**Comment by JimmXinu** [comment]
It appears that wuxiaworld.co now redirects http URLs to https.  Changing to use https directly might help.  I've put up a test CLI version with that change.  You can install it with:

`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

Also, the output you included here shows request errors, but not terminating errors.  There should be a line `Giving up on [URL]` when it fails completely.

**Comment by mhussaincov** [comment]
hi there,
will the change made propagate to your git repo?
it is how i get fanficfare via an AUR helper :)
Majid

On 21/02/2019, Jim Miller <notifications@github.com> wrote:
> It appears that wuxiaworld.co now redirects http URLs to https.  Changing to
> use https directly might help.  I've put up a test CLI version with that
> change.  You can install it with:
>
> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade
> FanFicFare`
>
> Also, the output you included here shows request errors, but not terminating
> errors.  There should be a line `Giving up on [URL]` when it fails
> completely.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/JimmXinu/FanFicFare/issues/378#issuecomment-466147768


-- 
kind regards,
Majid Hussain

**Comment by JimmXinu** [comment]
Yes, I pushed the changes into the github repo (ea8a072fd20a1f306a6d94669d3fd1bac4216762).

**Comment by mhussaincov** [comment]
hi there jimm,
it works now,
least for me :)
i'll close this issue :)
thanks for your help!
Majid Hussain
