### ISSUE TITLE
Formatting issue on AO3

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#379]
I was downloading this story:
https://archiveofourown.org/works/17867453
and part of it are similar to messenger posts.

In order to simulate that it has parts of the text aligned to the center, and to the right, but for some reason those parts are not downloaded correctly and everything gets aligned to the left.

**Comment by JimmXinu** [comment]
That particular story (in the first chapter, at least) uses `align` attributes for that.  You can include `align` in the (HTML & EPUB) output with:

`add_to_keep_html_attrs:,align`

I assume you know how to choose which section (`[defaults]`, site or storyURL) is appropriate for you.

From `defaults.ini`:
```
## Some attributes cause problems for EBook readers.  By default,
## FanFicFare will remove all attributes except the ones specified
## from all tags.  (The only exception is that <img> tags will also
## keep src, alt and longdesc attributes.  data-orighref is used by
## internalize_text_links to preserve links when chapters are
## inserted.)
## Example: To add 'style', 'title' and 'align' to the list to keep,
## in your personal.ini [defaults] put:
## add_to_keep_html_attrs:,style,title,align
keep_html_attrs:href,name,class,id,colspan,rowspan,data-orighref
```

**Comment by Twilight666** [comment]
Aaaah now I got it.
I was wondering why it seemed that other stories worked right while this had a problem!
Other stories had <p style="text-align:center;"> while this had <p align="right">.
Ok thank you!!
