### ISSUE TITLE
gravity tales downloading story then restarting download of story after story completes does not tell me that the story is up-to-date, it starts redownloading

### ISSUE THREAD

**Issue by mhussaincov** [JimmXinu/FanFicFare#380]
hi there,
as the subject line states,
I downloaded
http://gravitytales.com/novel/the-new-world
completely,
then restarted the download, instead of fanficfare telling me that the novel was up-to-date, it restarted downloading the story.
I stopped it after it started getting the first chapter again.
I had my suspissions that that adaptor was re getting up-to-date stories instead of informing me that it was up-to-date.
could someone conferm that this is a bug?
running fanficfare from git on arch linux.
I don't normaly make a habit of redownloading, wanted to conferm a huntch.
thanks,
Majid Hussain

**Comment by JimmXinu** [comment]
gravitytales.com doesn't provide a time with `dateUpdated`, just a date.  If `dateUpdated` is the same _date_ as the file timestamp, FFF assumes that the site has been updated more recently.

Which is one of the reasons I recommend using EPUB format and `-u`/`--update-epub` which will use the number of chapters instead of `dateUpdated` to make that call.

So near as I can tell, it's functioning as designed.

**Comment by mhussaincov** [comment]
hey there,
thanks for the clarification :)
Majid

On 25/02/2019, Jim Miller <notifications@github.com> wrote:
> gravitytales.com doesn't provide a time with `dateUpdated`, just a date.  If
> `dateUpdated` is the same _date_ as the file timestamp, FFF assumes that the
> site has been updated more recently.
>
> Which is one of the reasons I recommend using EPUB format and
> `-u`/`--update-epub` which will use the number of chapters instead of
> `dateUpdated` to make that call.
>
> So near as I can tell, it's functioning as designed.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/JimmXinu/FanFicFare/issues/380#issuecomment-467125552


-- 
kind regards,
Majid Hussain
