### ISSUE TITLE
Questionable questing issue: Not taking threadmarks

### ISSUE THREAD

**Issue by Ryune** [JimmXinu/FanFicFare#387]
For some reason I can't get a specific thread to download properly. It's _only_ this specific thread too. The issue is that every download ignores the threadmark and instead downloads the links in the first post.

https://forum.questionablequesting.com/threads/one-bad-day-away-demigod-x-dimensional-travel-cyoa.9188

**Comment by JimmXinu** [comment]
Functioning as designed.

It is (was?) common for older stories on the BaseXenForo sites to still have a table of contents post with a single threadmark to it.  To address that, FFF has a `minimum_threadmarks` setting that defaults to 2.  So if there are less than 2 threadmarks, by default, FFF will not use them.

You can change that setting in your personal.ini for specific stories using storyUrl sections, or for all BaseXenForo  using:

```
[base_xenforoforum]
minimum_threadmarks:1
```

There are [several options specific to BaseXenForo sites](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/defaults.ini#L626) you might want to check out.
