### ISSUE TITLE
fanficauthors.net: complains about missing credentials and then it freezes

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#389]
```
historical$ fanficfare -d https://aaran-st-vines.nsns.fanficauthors.net/Makers_of_Fine_Wands_
since_382_BC/index/
FFF: DEBUG: 2019-03-23 13:17:07,501: cli.py(184):     OS Version:Linux-4.20.13-1-default-x86_
64-with-glibc2.2.5
FFF: DEBUG: 2019-03-23 13:17:07,501: cli.py(185): Python Version:3.7.2 (default, Dec 30 2018,
 16:18:15) [GCC]
FFF: DEBUG: 2019-03-23 13:17:07,501: cli.py(186):    FFF Version:3.5.0
FFF: DEBUG: 2019-03-23 13:17:07,551: adapter_fanficauthorsnet.py(155): URL: https://aaran-st-
vines.nsns.fanficauthors.net/Makers_of_Fine_Wands_since_382_BC/
Login Failed, Need Username/Password.
```
That's all what happens, after that there is nothing for half-an-hour.

**Comment by JimmXinu** [comment]
I don't see anything in the output given about 'missing 
credentials'--that phrase usually indicates an SSL problem.

Do you have a valid username/password set for fanficauthors.net?  The 
adapter requires user/pass for all stories on fanficauthors.net.

**Comment by mcepl** [comment]
> The adapter requires user/pass for all stories on fanficauthors.net.

That genuinely confuses me. When I go to that URL with Firefox, I am not asked for anything, so why FFF is?

Also, I found out, that the site actually provides ePUB files on its own, so FFF is useful only for following updates (``-u``). I guess, what I miss most is some kind of error message which would explain more than just ``Login Failed, Need Username/Password.``.

**Comment by JimmXinu** [comment]
I didn't write that adapter originally (I didn't think it was worthwhile since, as you say, it has epub download); so I'm not sure why it requires user/pass all the time.  On some sites, what chapters are available depend on if you are logged in and one site even changes the 'bad' words if you aren't.

But FFF does tell you 'Need Username/Password' and prompt for it, so I'm not sure what else you'd want.

**Comment by mcepl** [comment]
Well, perhaps, one big error message "Don't bother with FFF, download directly!"?
