### ISSUE TITLE
sufficient velocity asks for login then doesn't download

### ISSUE THREAD

**Issue by kyoam** [JimmXinu/FanFicFare#392]
tried to download link below

https://forums.sufficientvelocity.com/threads/a-game-of-chance-worm-cyoa-si-fic.38911/

fanfic fare asked to login and then would not download 

the log showed this
URL
Bad
Unknown
Unknown
HTTP Error 403: Forbidden
https://forums.sufficientvelocity.com/threads/a-game-of-chance-worm-cyoa-si-fic.38911/

**Comment by JimmXinu** [comment]
SV stories very rarely require login.  And the story link given doesn't require login when I look at it or try to download it.

I cannot duplicate the problem reported.  I assume you are using the Calibre plugin version of FFF.  Can you run Calibre in debug (under the Preferences drop down), try again and then post the debug log?

**Comment by kyoam** [comment]
here it is

calibre Debug log
calibre 3.40.1  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: FanFicFare (3, 6, 0)
calibre 3.40.1  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: FanFicFare (3, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 70.8837209302 x 70.7010309278
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
FFF: DEBUG: 2019-04-12 09:11:58,513: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:C:\Users\Owner\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[2.36] main UI initialized...
[2.36] Hiding splash screen
[72.89] splash screen hidden
[72.89] Started up in 72.89 seconds with 108 books

**Comment by kyoam** [comment]
and now after the debug mode was launched it worked fine. go figure.

**Comment by JimmXinu** [comment]
I'm glad it was just a temporary problem then.

For future reference, when I ask for a debug log, I mean a debug log while running FanFicFare, not just while starting calibre.

**Comment by kyoam** [comment]
I'm honestly not sure how to set that up sorry
