### ISSUE TITLE
Error when downloading Long QQ fic

### ISSUE THREAD

**Issue by Carnifex-Chan** [JimmXinu/FanFicFare#393]
I have tried multiple times to download this specific fic from Questionable Questing, https://forum.questionablequesting.com/threads/ninja-ninja-tactics.5980/ , and usually it is running for over 2 hours. Then, it will suddenly stop and just say error and nothing else. it is a pretty long fic, with 1.3 million words, but i have downloaded fics of similar length from Spacebattles and Sufficient Velocity, and have had no trouble downloading other fics from QQ. I have tried making it skip index and extras, but it doesn't seem to make a difference. Please help!

**Comment by Twilight666** [comment]
Hey

I had a similar problem with a QQ fic taking too long to download (https://forum.questionablequesting.com/threads/a-tale-of-masks-in-another-world-one-piece.7648/)
My problem was that the story-posts had a lot of embeded images.

From what I can see the same thing applies here.

**Comment by JimmXinu** [comment]
What is the error you receive?  

Have you tried running Calibre in debug mode (under Calibre Preferences dropdown) while downloading?

I suspect @Twilight666 is probably right--lots of images and lots of chapters.

**Comment by Carnifex-Chan** [comment]
should I disable images then?

**Comment by Carnifex-Chan** [comment]
and Jimmxinu it just says "error" and nothing else

**Comment by Carnifex-Chan** [comment]
It ran for just under 2 hours then stopped with error, the log says memoryerror

**Comment by JimmXinu** [comment]
Then it apparently ran out of memory.  Whether that's because of limits imposed by your hardware or software limits somewhere along the line, I don't know.  You can probably get around it by using chapter ranges to only download part at a time.

Are you running FanFicFare in Calibre as a plugin, or from CLI?  

I've started that story downloading my Calibre and see what happens, but it's only 1:10 into it.  We'll see if I have the same issue.

**Comment by JimmXinu** [comment]
It finished successfully for me after ~ 2 hours 35 minutes.  

I checked around the 2:15 mark and the process size had grown to 5G of memory.  But I had some extra debug output for another issue that likely inflated that some.

So given all I have to work from is 'the log says memoryerror', I have to assume that you just ran out of memory and that it's not a flaw in FFF.

For your convenience, [here's a copy of the epub from my download](https://drive.google.com/file/d/1e3W7tSAuvAubSQnbG6Gi26OHdBVHYaAa/view?usp=sharing).  I will not be leaving that up for long, so grab it quick if you want it.  Also, it's made with whatever my test library settings happened to be.
