### ISSUE TITLE
Fanfiction not downloading final chapter

### ISSUE THREAD

**Issue by Ryune** [JimmXinu/FanFicFare#401]
Recently ran into this issue. The last chapter of this fic will not download. the comment says "already contains 30 chapters" when the site says 31 chapters. I'm currently running the newest test build.

https://www.fanfiction.net/s/13125259/1/

**Comment by JimmXinu** [comment]
When ffnet puts up a new chapter, it doesn't always appear on all of their servers at once.  We've seen it before where you can get an update notice and see a new chapter in your browser before FFF can see it.

FFF has a feature to help with that you can turn on:
```
[www.fanfiction.net]
check_next_chapter:true
```

When on, FFF will try to download one chapter past the list it's gotten from the site.  But it will do that for all ffnet downloads, so it adds an extra network request.

Or you can just wait an hour or so.
