### ISSUE TITLE
Feature Request AO3

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#402]
I am not sure if there already is a way to do this but is it possible to do something to make the notes in AO3 more readable.
I saw the exclude_notes option in personal.ini, but that just removes them.

Can you add the option for a way to seperatate chapter text from notes visually in the result?
Maybe add a \<hr/\> tag between them, maybe add a style option like margin to make it more the way it looks in the site

Example of a story with notes

> https://archiveofourown.org/works/18640942/chapters/45659566

**Comment by JimmXinu** [comment]
All the different kinds of notes have bolded headings and are in `<blockquote>` tags that (by default) should be indented from the normal text.  Have you changed blockquote appearance in your CSS?  Or perhaps it is ignored by your ereader?

I might be willing to add some HTML class attributes to the notes so you can use CSS settings to change their appearance.

**Comment by Twilight666** [comment]
I checked with a different reader (calibre viewer) and you are right, it is indented.
It looks like my default reader (Cool Reader) is ignoring it.
Sorry for this.

As for adding the ability to change the style for it, that would help but it might be an issue for other users if it would add the changes on top of the normal indent. On the other hand it would be optional...

So I don't know, whatever you wish. I edited the blockquote to add style='margin:5%' and it worked so it would work in my reader at least

**Comment by JimmXinu** [comment]
The point behind adding class(es) would be to avoid adding an optional feature for it--the classes would be added all the time and it would be up to the user to do something with them in CSS.

If you can add a style margin to the blockquote and have it work, perhaps you should just add a marge to all blockquotes via FFF's `output_css` or in your Cool Reader settings?

**Comment by Twilight666** [comment]
I can't find an option in Cool Reader that affects blockquote (there is even a preformated and a cite/quotation stylesheet but it doen't seem to affect it). If you have any idea where I should go in the settings that would be awesome but...
I can't actually download load something right now, but I went in stylesheet.css on the epub and added the line blockquote {margin:5%} so that part seems to work!
Thanks!

**Comment by JimmXinu** [comment]
Okay, we'll leave it at that, then.
