### ISSUE TITLE
Feature Request (related to #402)

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#403]
Ok I did the whole thing described in #402  with adding  `blockquote { margin: 5%%; } ` in `output_css` (I had to add another % for it to work like it said)
The problem was that it lost all the other options!
I had to paste the whole thing from personal.ini and append the above to it.

Is there a way to make it easier to use and maintain?
Maybe add an option that appends to the default with the added option to overwrite an original style:

> output_css_edit:
>  blockquote { margin: 5%%; }
>  h2 { text-align: center; font-weight: bold;}

That would add the blockquote option and overwrite the h2 one by making it bold and centered while the default was just centered

**Comment by JimmXinu** [comment]
Such a [feature already exists](https://github.com/JimmXinu/FanFicFare/wiki/INI-File#add_to_keyword):
```
add_to_output_css:
 blockquote { margin: 5%%; }
 h2 { text-align: center; font-weight: bold;}
```
Note the leading spaces before each line.
