### ISSUE TITLE
Issue with mediaminer.org

### ISSUE THREAD

**Issue by ElPiratoR63** [JimmXinu/FanFicFare#407]
it seems there is an issue when downloading stories from www.mediaminer.org. I'm not sure if it's the site or the program

**Comment by JimmXinu** [comment]
The story I usually use downloaded fine.

Can you please provide a story URL, any error messages you receive and/or a description of the problem when reporting any issue.

**Comment by ElPiratoR63** [comment]
Status
Title
Author
Comment
URL
Error
Omni Piece
HVulpes
'NoneType' object has no attribute 'get_text'
https://www.mediaminer.org/fanfic/s/crossover-with-non-anime-series-fan-fiction-one-piece-fan-fiction/omni-piece/161897

**Comment by JimmXinu** [comment]
Okay, that problem was fixed a while back (5e1ce3c45a0f570bba126ca4a40d397f7b34c2fa), but there hasn't been a new release since.

[You can get the test version of the plugin now.](https://www.mobileread.com/forums/showthread.php?p=3084025#post3084025)
