### ISSUE TITLE
Weirds CLI issue

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#408]
When I download using CLI for some reason it also prints this:
FFF: DEBUG: 2019-06-26 22:31:30,940: base_adapter.py(41): BS4:4.7.1
first.
I haven't actually enabled debug mode, and it started after the latest update (3.9.0 on Python 3)

**Comment by JimmXinu** [comment]
Hmm.  I've moved that debug output so it doesn't show up when not using -d(6c3b243d12f76167154846ff1a9a2b7df77f7a86).  Test CLI version in the usual  place:

`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by Twilight666** [comment]
Updated to 3.9.1 and the debug message is gone!
