### ISSUE TITLE
Feature request: Add popular image pastebins

### ISSUE THREAD

**Issue by hseg** [JimmXinu/FanFicFare#411]
Some fics (e.g. https://forums.spacebattles.com/threads/455278) host their images off-site (in this case, on imgur, but deviantart and photobucket have also been seen).
Naturally, this breaks the epubs when offline.
Adding adapters for these might be nice, although I'm aware this risks scope creep (what's next, youtube?)

**Comment by JimmXinu** [comment]
[Already have a feature to include image.](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/defaults.ini#L861)  Just not on by default in CLI.

**Comment by hseg** [comment]
OK. Rechecking the fic I encountered this problem with, it turns out that while *embedded* pictures work fine, image *links* (cf the last group of links) are not pulled in.
Will check later today if some postprocessing magic cannot fix this. But this is getting clearly out of the scope of this project. Thanks.

On 4 July 2019 1:03:04 GMT+03:00, Jim Miller <notifications@github.com> wrote:
>Closed #411.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JimmXinu/FanFicFare/issues/411#event-2458940120

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
