### ISSUE TITLE
Sufficient Velocity XF2 (Error:  'NoneType' object has no attribute 'h1')

### ISSUE THREAD

**Issue by Tarkin9188** [JimmXinu/FanFicFare#412]
Receiving this error when i download from Sufficient Velocity after they updated their forums.

[https://forums.sufficientvelocity.com/threads/taylor-varga-worm-luna-varga.32119/threadmarks](url)
[https://forums.sufficientvelocity.com/threads/mauling-snarks-worm.41471/threadmarks](url)

**Comment by JimmXinu** [comment]
Already fixed in test versions.  New release version in a few days.

> I've posted a test version of the plugin here:
> http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025
> 
> Test version of web service here:
> https://3-9-7-dot-fanficfare.appspot.com
> 
> Test version of CLI for pip install:  You'll have to get it from the testpypi repository.  This works for me on Debian:
> 
> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare` 

I'm going to leave this open so the next person who comes to report it can see it more easily.

**Comment by JimmXinu** [comment]
[Fix released](https://github.com/JimmXinu/FanFicFare/releases/tag/v3.10.0)
