### ISSUE TITLE
Feature requset, support for http://fanfics.me/

### ISSUE THREAD

**Issue by BabelAlexandria** [JimmXinu/FanFicFare#413]
Sample URLs:
* http://fanfics.me/fic130083
* http://fanfics.me/fic1028
It’s a Russian fanfiction community, some stories are originals, some are translations.

**Comment by JimmXinu** [comment]
a941dae6209fd4889494a5a90f64f876f6c50302

I've posted test versions of CLI and plugin

I've posted a test version of the plugin here:
http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025

Test version of CLI for pip install:  You'll have to get it from the
testpypi repository.  This works for me on Debian:

`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by BabelAlexandria** [comment]
Thank you!

I just tried downloading one of the listed stories, and it worked after requiring user/password data.

Although for the sake of feedback, there seemed to be one miner problem: I tried manually creating a subsection for [fanfics.me] in personal.ini with username: and password: lines, but it didn't stick — FFF still asks for manual u/p input for each new story download.

**Comment by JimmXinu** [comment]
Please provide a story URL on that site that requires login.
