### ISSUE TITLE
Having trouble with soupsieve, which crashes fanficfare.

### ISSUE THREAD

**Issue by Nothorse** [JimmXinu/FanFicFare#414]
Hi.

Since two days ago, my installation of fanficfare is broken with the following error
`/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selec
tors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'
FFF: DEBUG: 2019-07-19 17:30:01,868: base_adapter.py(41): BS4:4.7.1
Failed to read epub for update: (Cannot execute CSS selectors because the soupsieve package is not installed.) Continuin
g with update=false
Traceback (most recent call last):
  File "/usr/local/bin/fanficfare", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/fanficfare/cli.py", line 290, in main
    passed_personalini)
  File "/usr/local/lib/python2.7/dist-packages/fanficfare/cli.py", line 402, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/local/lib/python2.7/dist-packages/fanficfare/adapters/base_adapter.py", line 289, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/local/lib/python2.7/dist-packages/fanficfare/adapters/adapter_storiesonlinenet.py", line 243, in doExtractC
hapterUrlsAndMetadata
    elements = soup.select(element_name)
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1373, in select
    "Cannot execute CSS selectors because the soupsieve package is not installed."
NotImplementedError: Cannot execute CSS selectors because the soupsieve package is not installed.
`

Googling the error brings up de- and re-installing which I've tried but no joy. Any idea what it could be. 

I understand this is probably not a direct fanficfare problem, but unfortunately my python-skills are just about non-existant.

**Comment by Nothorse** [comment]
You always find the solution after reporting a problem

In this case, it's a python2.7 problem. It goes away by installing fanficfare with pip3.

**Comment by JimmXinu** [comment]
On my Python 2.7, beautifulsoup4 4.7.1 includes a requirement for soupsieve.  Earlier versions of BS didn't require soupsieve, so it's only appropriate that BS requires it and not FFF directly.

I can't speak to why your install had that problem.  But since you're past it, I'm going to forget about it.
