### ISSUE TITLE
Xenforo adapter: fic-specific setting of skip_threadmarks_categories ignored

### ISSUE THREAD

**Issue by hseg** [JimmXinu/FanFicFare#416]
A config of
```ini
skip_threadmarks_categories:Staff Post
[https://forums.sufficientvelocity.com/threads/28074]
skip_threadmarks_categories:Staff Post,Informational
```
still pulls in the ```Informational``` posts when downloading that thread.
Judging by results with modified settings, ```skip_threadmarks_categories``` is not accepted on a per-story basis.

**Comment by JimmXinu** [comment]
Use:
```
[https://forums.sufficientvelocity.com/threads/28074/]
skip_threadmarks_categories:Staff Post,Informational
```
Note the trailing `/`.

Or even better, use:
```
[https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/]
skip_threadmarks_categories:Staff Post,Informational
```
Then you also have the title visible.  Story URL will still work if title changes later.

**Comment by hseg** [comment]
Latest update triggered this again. Relevant config lines:
```
[https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/]
skip_threadmarks_categories:Staff Post,Informational
```
despite this, Staff and Informational posts are dragged in. Unsure what happened to trigger change.

**Comment by JimmXinu** [comment]
I am not seeing that behavior.  I copy-pasted from your post into my `personal.ini` and it worked as expected.

Do you have other `skip_threadmarks_categories` settings in `[overrides]` or another section for the same story URL, including `[https://forums.sufficientvelocity.com/threads/28074/]`?

I'd need to see your `personal.ini` to offer any further advice.

**Comment by hseg** [comment]
Sorry for long delay.
Reproduced with the following `defaults.ini` contents
(Note: these are the _entirety_ of my `defaults.ini`):
```ini
[base_xenforoforum]
skip_threadmarks_categories:Staff Post,Informational
```
also tried with
```ini
[https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/]
skip_threadmarks_categories:Staff Post,Informational
```
In each case, got the same results as for an empty `defaults.ini`.
Also tried with `defaults.ini` renamed to `personal.ini`. Same results

Note: for future reference, to get deterministic outputs, you want to set `PYTHONHASHSEED=0` (to make `list(set(...))` deterministic), fake the time `fanficfare` was invoked (since that is logged) and rebuild the epub deterministically (strip extra attributes, order files, set timestamps to a fixed time).
These will remove spurious differences between epubs compared using `diff`.
The following script will rebuild a zip file as described above.
```bash
# Ingredients of deterministic zip:
# Use deterministic ordering
# Fix timestamps
# Avoid using old ordering
# Don't use extended timestamp

copyCompressionLevel() {
zipinfo "$1" | awk -v zip="$1" -f <(cat - <<'EOF'
/fat|unx/ {
  if ($6 == "stor")
    lvl=0
  else lvl=9
  printf "zip -%sXq '%s' '%s'\n", lvl, zip, $9
}
EOF
) | sort
}

[ $# -ne 2 ] && echo 'USAGE: touchzip TIMESTAMP ZIP' && exit 1
time="$(date -d "$1")" || exit 1
zip="$PWD/$2" || exit 1
temp="$(mktemp -d)"

unzip "$zip" -d "$temp"
find "$temp" -exec touch -d "$time" {} +
cd "$temp" || exit 1
(echo rm "'$zip'"; copyCompressionLevel "$zip") | sh
```

**Comment by JimmXinu** [comment]
### Retrying
`skip_threadmarks_categories` directly affects the chapter list--it even stops FFF downloading the threadmarks pages for those categories to save server requests.

Which means you can do `fanficfare -m https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/` and just look at the chapter list.

I put those settings in `defaults.ini` in pwd, moved `personal.ini` to a new name and added env setting `PYTHONHASHSEED=0`.  

I still see the results expected. 

### Comparing Output
If you do want to compare complete downloads, I recommend using `fanficfare -f txt` and INI setting `include_titlepage: false` to get text only and leave out the title page with dates.  That seems like a lot less work than trying to normalize zip files.  Also, Calibre's Edit Book has a 'compare other ebook` feature now that works pretty well.

### Linux vs Windows?
I switched to a linux VM without any prior FFF settings and I did run into an issue with needing to use `-f` or include setting `always_overwrite: true` to overwrite an existing output file, but I assume you got past that if you needed to normalize zip files for comparison.  And again, I saw the chapter lists I expected.

### Other Possibilities
I still haven't seen anything that suggests there's something wrong with FFF.  If it were me, I'd suspect that setting is in an INI file that's not being read at all.  If you add a different setting does it work?  Like:

```
[https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/]
skip_threadmarks_categories:Staff Post,Threadmarks
add_to_replace_metadata:
 title=>^.*$=>Changed Title
```
Or try using `-c file.ini` CLI option to explicitly add the file?  Or `-o skip_threadmarks_categories=Staff Post,Threadmarks` CLI option to explicitly add that setting?

After that I would start suspecting cross OS newline issues maybe?

**Comment by hseg** [comment]
Sorry for the noise, it appears I should have questioned my assumption that I
had correctly placed the `defaults.ini` file.
Apparently, I've been running fanficfare all this time without my config ever
being touched. Don't know why I assumed fanficfare supported the XDG base dir
spec without checking.

i.e. there was no bug, I just put my config in the wrong place and was confused
that the settings weren't picked up. _facepalms_

On a related note, I've opened #459 which will justify that assumption.
