### ISSUE TITLE
Feature Request: Allow for partial downloads

### ISSUE THREAD

**Issue by anshu-krishna** [JimmXinu/FanFicFare#418]
I have been reading "The Wandering Inn" (https://www.royalroad.com/fiction/10073/the-wandering-inn). It has 14K+ pages. Although the story is divided into 6 books, all of them are added in the same RoyalRoad book. When downloading this book it results in a mammoth 14K+ paged ebook.
Please add a feature to download books partially so that I can download the ebook in 6 different chunks and separate all the (inner) six books in a separate epub. I am using FanFicFare as an plugin of Calibre.

**Comment by Twilight666** [comment]
You can already do that:

> https://www.royalroad.com/fiction/10073/[1-25]

downloads the first 25 chapters. You can choose whatever chapter range you want
also you you can use 

> https://www.royalroad.com/fiction/10073/[100-]

to get everything after chapter 99 to the end.

You can also use ignore_chapter_url_list in personal.ini to set specific chapters to be skipped.
As a note the skipped chapters are not counted in the chapter range, so if you skip chapter 4 in the above case you will download 1-3 and 5-26 so 25 chapters

**Comment by anshu-krishna** [comment]
I did't know that . Thank you for the help.

**Comment by anshu-krishna** [comment]
The partial download works as explained above but, updating a book with a trailing chapter number does not work properly.

For example:
If I use https://www.royalroad.com/fiction/10073/[100-] to download the book then all chapter except the first 99 are downloaded. But later when new chapters are available then updating the book downloads not only the new chapters at the end but also the first 99 chapters as well.

If I download the book when 340 chapters are available using [100-] then the book contains [chapter 100 to chapter 340]. Later when 342 chapters are available then updating should result in epub with [chapter 100 through to chapter 342], but instead it results in an epub with [chapter 1 thorough to chapter 342].

**Comment by JimmXinu** [comment]
Functioning as intended.

If you never want those first 99 chapters, you can set FFF to always start with chapter 100 for that story in personal.ini:
```
[https://www.royalroad.com/fiction/10073/]
first_chapter:100
```
Otherwise you have to give the chapter range every time you update--FFF doesn't automatically remember that.

**Comment by anshu-krishna** [comment]
OK. Thanks
