### ISSUE TITLE
New version issue in CLI

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#421]
When I download in CLI I get the following

> Traceback (most recent call last):
>   File "c:\Python3.7\Scripts\fanficfare-script.py", line 11, in <module>
>     load_entry_point('FanFicFare==3.10.5', 'console_scripts', 'fanficfare')()
>   File "c:\python3.7\lib\site-packages\fanficfare\cli.py", line 290, in main
>     passed_personalini)
>   File "c:\python3.7\lib\site-packages\fanficfare\cli.py", line 338, in do_download
>     output_filename)
>   File "c:\python3.7\lib\site-packages\fanficfare\cli.py", line 554, in get_configuration
>     configuration.read(conflist)
>   File "c:\python3.7\lib\site-packages\fanficfare\configurable.py", line 739, in read
>     self._read(fp, filename)
>   File "c:\python3.7\lib\site-packages\fanficfare\configurable.py", line 834, in _read
>     raise e
> configparser.ParsingError: Source contains parsing errors: 'c:\\python3.7\\lib\\site-packages\\fanficfare\\defaults.ini'
>         [line 800]: th use_threadmarks_description

calibre works thought

**Comment by JimmXinu** [comment]
I think it's fixed now. Had to bump version again.

**Comment by Twilight666** [comment]
CLI is now version 3.10.6 and it works.
