### ISSUE TITLE
fanficfare, when running in d-bug mode tell us if the story downloaded SUCCESSFULLY

### ISSUE THREAD

**Issue by mhussaincov** [JimmXinu/FanFicFare#422]
hi there,
would it be possible for this to be added?
when downloading a large story at the end of the download tell us if it downloads with out error?
I would find this functionality very useful if not that then maybe a error.log created in the directory of where stories are placed noteing the storie names that failed?
thanks for considdering my request,
Majid Hussain

**Comment by JimmXinu** [comment]
That work for you?

**Comment by mhussaincov** [comment]
hi there,
sorry?
I was requesting if it could be made so,
I am sorry if it sounded like I had Implemented this feature, i'm no programmer.
sorry again if it sounded by the subject line like I added this, I was
requesting if this was possable,
been fileing alot of buggs over on launchpad sorry for my error!
the log i deer sounds like something useful write?
could it be considdered?
sorry for being a pain,
Majid

On 02/08/2019, Jim Miller <notifications@github.com> wrote:
> That work for you?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/JimmXinu/FanFicFare/issues/422#issuecomment-517864025


-- 
kind regards,
Majid Hussain

**Comment by JimmXinu** [comment]
I meant for you to look at [the change tagged](https://github.com/JimmXinu/FanFicFare/commit/ef88db8c1a271dff13f454c6ace88bfcbecf5e85) by github to add such output.

You see a lot more when you click the github link and respond to issues on the website instead of run replying.

**Comment by mhussaincov** [comment]
hi there,
that indeed works!
many thanks for doing this! :)
and yes maybe I aught to read issues via the web-interface, my bad!
Majid

On 03/08/2019, Majid Hussain <mhussaincov93@gmail.com> wrote:
> hi there,
> sorry?
> I was requesting if it could be made so,
> I am sorry if it sounded like I had Implemented this feature, i'm no
> programmer.
> sorry again if it sounded by the subject line like I added this, I was
> requesting if this was possable,
> been fileing alot of buggs over on launchpad sorry for my error!
> the log i deer sounds like something useful write?
> could it be considdered?
> sorry for being a pain,
> Majid
>
> On 02/08/2019, Jim Miller <notifications@github.com> wrote:
>> That work for you?
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/JimmXinu/FanFicFare/issues/422#issuecomment-517864025
>
>
> --
> kind regards,
> Majid Hussain
>


-- 
kind regards,
Majid Hussain

**Comment by JimmXinu** [comment]
Okay.  I've uploaded a new test version of CLI with that change (v3.10.9)

**Comment by mhussaincov** [comment]
many thanks for that,
I get my version of fanficfare from it's source via the pkg build on
arch linux thanks for fanficfare by the way! :)

On 03/08/2019, Jim Miller <notifications@github.com> wrote:
> Closed #422.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/JimmXinu/FanFicFare/issues/422#event-2531375025


-- 
kind regards,
Majid Hussain
