### ISSUE TITLE
spacebattles not downloading

### ISSUE THREAD

**Issue by kyoam** [JimmXinu/FanFicFare#424]
space battles stories are not downloading url used
https://forums.spacebattles.com/threads/grand-foreigner-overlord-fgo-crossover.728632/

result
Error
Unknown
Unknown
No status line received - the server has closed the connection

**Comment by JimmXinu** [comment]
I have no issues downloading that story.  

> `the server has closed the connection`

The error given indicates one of: a network issue between you and the SB servers; transient errors or over-loading on the SB servers; or that SB is blocking your connection.

In all cases, it's outside of FFF's control.
