### ISSUE TITLE
Minor Bug on Spacebattles (and probably other Xenforo sites)

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#426]
So I was downloading this [Spacebattles Story](https://forums.spacebattles.com/threads/a-ghost-of-a-chance-worm-v1-cyoa-alt-taylor.766498/) and I noticed that some of the links created in the Informational posts didn't work.

I will use this [post](https://forums.spacebattles.com/posts/59202469/) as an example.

The post is basically a quote and the author's response. The quote includes a link to the original post.
The link though is

> goto/post?id=59202259#post-59202259

which doesn't work.
The actual link should be

> https://forums.spacebattles.com/goto/post?id=59202259#post-59202259

The issue is caused because SB assumes the https://forums.spacebattles.com/ in the beginning of the link and only saves the rest as part of the post since it's a link to the same website.

This probably applies to the other XenForo sites

**Comment by JimmXinu** [comment]
Hmmm.  I wasn't seeing that because the optional `normalize_text_links` feature fixes it.  

I'm thinking I might just turn these two options on by default for base_xenforoforum adapters.
```
## Apply adapter's normalize_chapterurl() to all links in chapter
## texts, if they match chapter URLs.  Currently only implemented by
## base_xenforoforum adapters.
#normalize_text_links:false

## Search all links in chapter texts and, if they match any included
## chapter URLs, replace them with links to the chapter in the
## download.  Only works with epub and html output formats.
## base_xenforoforum adapters should also use normalize_text_links
## with this.
#internalize_text_links:false
```

**Comment by Twilight666** [comment]
Okay, but if I am reading this right that would change links in the epub (or pdf or...) to other parts of the epub if the links match a url of a downloaded chapter,

In this case the 

> goto/post?id=59202259#post-59202259

would redirect to the url

> https://forums.spacebattles.com/goto/post?id=59202259#post-59202259

which is not part of the epub.

Instead it would be a broken link

**Comment by JimmXinu** [comment]
`normalize_text_links` changes href `goto/post?id=59202259#post-59202259` to `https://forums.spacebattles.com/posts/59202469/`.

Then, if post-59202469 is included in the epub as a chapter, `internalize_text_links` will change the href to `fileXXXX.xhtml` for that chapter.

If you have a demonstrated case using `normalize_text_links` and/or `internalize_text_links` that results in broken links, I'd like to see it.

**Comment by Twilight666** [comment]
Sorry I think I misunderstood this part
Apply adapter's normalize_chapterurl() to all links in chapter texts, **if they match chapter URLs.**

I now understand that when it says match chapter URLs it means if the _formatting_ matches chapter URLs
I tried downloading using normalize_text_links and it works.
