### ISSUE TITLE
The problem with non-English characters in the file name

### ISSUE THREAD

**Issue by gunmetal313** [JimmXinu/FanFicFare#428]
The problem with non-English characters in the file name
1) download fanficfare https://ficbook.net/readfic/6299091
`
FFF: DEBUG: 2019-09-15 23:01:11,924: configurable.py(1001): Encoding:utf8
FFF: DEBUG: 2019-09-15 23:01:12,463: adapter_ficbooknet.py(109): Title: (The Enchanted Library (Заколдованная библиотека))
FFF: DEBUG: 2019-09-15 23:01:12,478: adapter_ficbooknet.py(117): Author: (Silvxr)
FFF: DEBUG: 2019-09-15 23:01:12,512: adapter_ficbooknet.py(142): numChapters: (12)
FFF: INFO: 2019-09-15 23:01:12,679: base_writer.py(183): Save directly to file: The Enchanted Library (_ _)-fbn_6299091.epub
`

## Actual result:
File name with spaces, brackets, file name length is not controlled
In the presence of Russian or other non-English characters, only a dash, prefix and id fan fiction remain

## ideas to fix
-  add global option "only prefix and id" ?
-  use translit https://pypi.org/project/transliterate/ ?
-  use transliteration only for supported languages (check Metadata('language') and do not add story name to file name for unsupported language
- When the option to use the new file naming option is enabled, rename files
1. detect old_file_name "The Enchanted Library (_ _)-fbn_6299091.epub". 
2. Rename to new_file_name "The_Enchanted_Library_Zakoldovannaya_biblioteka_fbn_6299091.epub"

I can write code to solve the problem with file names (and maintaining backward compatibility with renaming to a new format file name)

**Comment by JimmXinu** [comment]
Have you already investigated changing the existing settings to achieve your goals?

From [`defaults.ini`](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/defaults.ini):

```
## python string Template, string with ${title}, ${author} etc, same as titlepage_entries
## Can include directories.
#output_filename: books/${title}-${siteabbrev}_${storyId}${formatext}
#output_filename: books/${formatname}/${siteabbrev}/${authorId}/${title}-${siteabbrev}_${storyId}${formatext}
output_filename: ${title}-${siteabbrev}_${storyId}${formatext}

## Normally, try to make the filenames 'safe' by removing invalid
## filename chars.  Applies to default_cover_image, output_filename &
## zip_filename.
allow_unsafe_filename: false

## The regex pattern of 'unsafe' filename chars for above.  First
## character . OR any one or more characters that are NOT a letter,
## number, or one of _. []()&'-
output_filename_safepattern:(^\.|/\.|[^a-zA-Z0-9_\. \[\]\(\)&'-]+)
```
