### ISSUE TITLE
Request for wuxiaworld.site

### ISSUE THREAD

**Issue by Rajvir8** [JimmXinu/FanFicFare#439]
The site has various Novels available

I'm hoping to download
https://wuxiaworld.site/novel/gamers-of-the-underworld/

As it is now under paywall inside Webnovel

**Comment by mhussaincov** [comment]
hi there,
does it use the same template as the "wuxiaworld.com and wuxiaworld.co sites?
could an adaptor be made via the template of the 2 other sites that I mentioned?
i'm not a coder sadly.
Majid

On 23/10/2019, Rajvir Daniel Singh <notifications@github.com> wrote:
> The site has various Novels available
>
> I'm hoping to download
> https://wuxiaworld.site/novel/gamers-of-the-underworld/
>
> As it is now under paywall inside Webnovel
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/JimmXinu/FanFicFare/issues/439


-- 
kind regards,
Majid Hussain

**Comment by Rajvir8** [comment]
Afraid I'm not sure myself either, would you know a good way to check if it uses the same template?  Or a guide that shows you how to do so.  I'd be happy to try checking myself but not sure how.

I can tell you that Fanfic Fare Closes the moment you try adding the link in, understandably as it is not a supported site.

**Comment by mhussaincov** [comment]
hi there,
no, as stated in my last email, i'm not a programmer lets hope someone
enters the breech and is able to assist,
Majid

On 23/10/2019, Rajvir Daniel Singh <notifications@github.com> wrote:
> Afraid I'm not sure myself either, would you know a good way to check if it
> uses the same template?  Or a guide that shows you how to do so.  I'd be
> happy to try checking myself but not sure how.
>
> I can tell you that Fanfic Fare Closes the moment you try adding the link
> in, understandably as it is not a supported site.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/JimmXinu/FanFicFare/issues/439#issuecomment-545408572


-- 
kind regards,
Majid Hussain

**Comment by Kolbo5** [comment]
Hello, this issue could be closed, I have added wuxiaworld.site adapter in #544

**Comment by JimmXinu** [comment]
Thanks!
