### ISSUE TITLE
--meta-only but without downloading even the title page

### ISSUE THREAD

**Issue by arisboch** [JimmXinu/FanFicFare#443]
It'd be nice if there was a switch so that really nothing but the meta-data gets downloaded, not even the title page.

**Comment by JimmXinu** [comment]
I'll add a `--no-output` option in the next test version.

**Comment by arisboch** [comment]
> I'll add a `--no-output` option in the next test version.

Nice, thanks in advance! The lack of this option is the only thing keeping me from writing the second installment of my (primitive) wrapper script for fanficfare.

**Comment by JimmXinu** [comment]
I've uploaded a test version of the CLI with these changes:
`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by arisboch** [comment]
Thx!
