### ISSUE TITLE
[Bug] Fanficfare new release fails to download multiple QQ stories

### ISSUE THREAD

**Issue by jeancinq** [JimmXinu/FanFicFare#446]
When downloading multiple stories from questionable questing (at least with NSFW ones), the 3.13.0 version of the Calibre plugin download successfully the first, but all the other fail, I think with the following error message: error 403: forbidden.
Downgrading Fanficfare back to 3.12.0 resolves the problem.

**Comment by JimmXinu** [comment]
I'm not able to duplicate the problem.  

Please run Calibre in debug mode (Calibre Preferences dropdown), try it again, and attach the debug log.

**Comment by jeancinq** [comment]
Here is the debug log of this problem.
[tmpds690g.txt](https://github.com/JimmXinu/FanFicFare/files/3855801/tmpds690g.txt)

**Comment by JimmXinu** [comment]
This is related to a background feature I added to save cookies between downloads.  Apparently it is causing problems with QQ.  I few ideas why which I may or may not pursue in detail.

I've posted a new test version of the plugin in [the usual place](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).

**Comment by JimmXinu** [comment]
31182e18fc62f4223c66eb0e0a130f745ba61292

**Comment by jpn8880** [comment]
hi guys im not a programmer but can you help me fix this problem , i cant download or send images onqq international  it happened over a year ago and was normal before that. works on my phone but not my notebook.

**Comment by JimmXinu** [comment]
1. I doubt very much that this (closed) issue has anything to do with any problems you may be having now.

1. "download or _send_ images"??  Are you sure you are in the right place?  This is only about the FanFicFare software package.

1. "works on my phone but not my notebook"?? FanFicFare doesn't run on any phone--at least not any version that I currently support.  The official web service was shutdown last year.  Any web service you may currently use is unsupported.

If you still think you have a problem with FanFicFare, please open a new issue, include a story URL that demonstrates the problem, clearly describe what you expect to happen and what you see happen including any error messages you get.

**Comment by jpn8880** [comment]
Ok sorry I just searched qq images not downloading and this thread came up
