### ISSUE TITLE
Suggestion for notes

### ISSUE THREAD

**Issue by nascalsn** [JimmXinu/FanFicFare#447]
Today when the chapter and notes are pulled, the notes are placed as follows: `<b>Note</b><blockquote>...</blockquote>`. My suggestion is that you put these notes inside a div with the `fff_notes` or similar class (`<div class="fff_notes"><b>Note</b><blockquote>...</blockquote></div>`).
Or put an extra section in CustomOutput such as `chapter_notes:<div class="notes">${note}</div>`.

**Comment by JimmXinu** [comment]
Which site(s) are you talking about?

**Comment by nascalsn** [comment]
> 
> 
> Which site(s) are you talking about?

I saw this for AO3, sorry I didn't specify it before.

**Comment by JimmXinu** [comment]
d389d2b12ec92e71b43cab95d0a7bd7ea01de6a3

CLI and plugin test versions in the usual places.
