### ISSUE TITLE
Issues with Images on RoyalRoad

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#450]
I was downloading 
https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/424559/expanded-normality-4
that has an image in a spoiler (I was downloading just that chapter).

Until recently similar images were downloaded, but now it does not.
I am using `include_images:true` but it seems to be skipping it.

Here is the debug output

> FFF: DEBUG: 2019-11-25 20:05:50,066: cli.py(193):     OS Version:Windows-10-10.0.18362-SP0
> FFF: DEBUG: 2019-11-25 20:05:50,066: cli.py(194): Python Version:3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
> FFF: DEBUG: 2019-11-25 20:05:50,067: cli.py(195):    FFF Version:3.13.0
> FFF: DEBUG: 2019-11-25 20:05:50,111: adapter_royalroadcom.py(151): URL: https://www.royalroad.com/fiction/8894
> FFF: DEBUG: 2019-11-25 20:05:50,111: configurable.py(1133): #####################################
> pagecache(GET) MISS: https://www.royalroad.com/fiction/8894
> FFF: DEBUG: 2019-11-25 20:05:54,485: configurable.py(999): Encoding:utf8
> FFF: DEBUG: 2019-11-25 20:05:56,344: adapter_royalroadcom.py(223): stars:(4.624195)
> FFF: INFO: 2019-11-25 20:05:56,462: base_writer.py(183): Save directly to file: `<PATH>`\Exterminatus - Everybody Loves Large Chests (Ch 310-310)-rylrdl_8894.epub
> FFF: DEBUG: 2019-11-25 20:05:56,550: adapter_royalroadcom.py(240): Getting chapter text from: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/424559/expanded-normality-4
> FFF: DEBUG: 2019-11-25 20:05:56,551: configurable.py(1133): #####################################
> pagecache(GET) MISS: https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/424559/expanded-normality-4
> FFF: DEBUG: 2019-11-25 20:05:58,237: configurable.py(999): Encoding:utf8
> FFF: DEBUG: 2019-11-25 20:05:59,517: cli.py(87): Successfully wrote '`<PATH>`\Exterminatus - Everybody Loves Large Chests (Ch 310-310)-rylrdl_8894.epub'
> Downloaded Story: "Everybody Loves Large Chests (Ch 310-310)" by "Exterminatus", Chapters: 310, Updated on: "2019-11-17"

**Comment by JimmXinu** [comment]
I'm not seeing this issue.  I'm able to download that chapter with images just fine.  (I did not download the entire 300+ chapter image filled story.)

The lack of any attempt to download images from either the story desc or the chapter in your debug output suggests that something in your config _is_ saying `include_images:false`.  I'd have to see your ini file to know for sure.

Also, the chapter URL given is chapter 331 when I look at it, not 310...

**Comment by Twilight666** [comment]
I searched the file and you are right I had  `include_images:false` at the `[https://www.royalroad.com/fiction/8894]` part where I had the `ignore_chapter_url_list`.... for _some_ reason that I don't even remember.
Also the reason I download 310 and not 331 is because I have 21 urls in the above ignore list.

Removed the extra line of code, and it worked fine
