### ISSUE TITLE
Over Quota?

### ISSUE THREAD

**Issue by joem5636** [JimmXinu/FanFicFare#451]
I've been getting 'over quota' messages for a week or two. Is it me or the system?

**Comment by JimmXinu** [comment]
This is not a code issue, but an issue of administration.

Due to changes in Google's policies, I'm shutting down the web service as it has been.

Further discussion should take place in the [FanFicFare Google Group](https://groups.google.com/forum/#!topic/fanfic-downloader/pYq8_BvWSxA).
