### ISSUE TITLE
Preparation for Calibre's switch to Python 3

### ISSUE THREAD

**Issue by cryzed** [JimmXinu/FanFicFare#453]
At least for my operating system (Arch Linux), I am now required to run the [Python 3 version of Calibre](https://github.com/kovidgoyal/calibre/blob/master/README.python3) due to otherwise conflicting packages. Unfortunately, my long-time favorite plugin, is not quite ready yet to be run using that version -- It seems to be mostly related to old Python 2 syntax in some parts of the core code (and probably adapters). I would like to create this issue to keep track of the Python 3 compatibility for FanFicFare and potentially help myself to make it compatible with both versions for now (although Python 2 will be dead soon).

For now I am getting this traceback when running calibre-python3 with FanFicFare:

```python-traceback
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 157, in __init__
    ac = self.init_iaction(action)
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 171, in init_iaction
    ac = action.load_actual_plugin(self)
  File "calibre_plugins.fanficfare_plugin.__init__", line 110, in load_actual_plugin
  File "/usr/lib/calibre/calibre/customize/__init__.py", line 612, in load_actual_plugin
    ac = getattr(importlib.import_module(mod), cls)(gui,
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 180, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1047
    except exceptions.FailedToLogin, f:
                                   ^
SyntaxError: invalid syntax
```

**Comment by cryzed** [comment]
I just discovered this [pull request](https://github.com/JimmXinu/FanFicFare/pull/395) which seems to have already some ongoing effort.

**Comment by JimmXinu** [comment]
[What I said on that PR](https://github.com/JimmXinu/FanFicFare/pull/395#issuecomment-491600622) still applies:

> I do plan to revisit this after Kovid starts making a Python3 Calibre version available for testing, but until then I'd rather it failed out right on Py3 rather than pass on first glance and have more subtle bugs left in.
> 
> If I've managed to miss Kovid making the Py3 Calibre available, please let me know. :-)

It looks like [that should be coming](https://github.com/kovidgoyal/calibre/pull/870#issuecomment-557963600) soonish.

Does Kovid's official Calibre binary not run on your linux variant?

**Comment by cryzed** [comment]
Calibre for Python 3 _does run_ on my system, just FanFicFare doesn't work with it currently.

> It looks like that should be coming soonish.

Good, in that case this issue still makes sense.

**Comment by eli-schwartz** [comment]
> I am now required to run the [Python 3 version of Calibre](https://github.com/kovidgoyal/calibre/blob/master/README.python3) due to otherwise conflicting packages

What are the conflicting packages? There should be no reason you cannot install https://www.archlinux.org/packages/community/x86_64/calibre/ just fine, although, optionally, you could use https://www.archlinux.org/packages/community/x86_64/calibre-python3/.

**Comment by JimmXinu** [comment]
PR #395 has been pulled into the trunk.  I have a bit more testing to do before posting a test version, but it should be soonish.

**Comment by JimmXinu** [comment]
[Test version](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2) posted.

**Comment by cryzed** [comment]
Thank you and sorry for not helping out - I've been pretty busy recently. @eli-schwartz it seems to haven been python2-qt5 and python3-qt5 conflicting. I'll have to see if this still happens later. I need both as dependencies.

**Comment by eli-schwartz** [comment]
python2-pyqt5 and python-pyqt5 should not be conflicting ever, for obvious reasons. ;)

Just do what pacman told you to do and remove pyqt5-common.

**Comment by cryzed** [comment]
Yes, I agree. I had already done this since then, but forgot what caused it - the issue is gone, thanks.
