### ISSUE TITLE
Feature Request: URL links

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#454]
I don't know how possible this is but I figured I should at least ask.
When I download part of a story (using for example `https://www.fanfiction.net/s/12990105/[10-15]`) the title page has a part that says `Tales From The Avenger (Ch 10-15) by DrAmishMDCategory` where 
`DrAmishMDCategory `is a link to the author page while `Tales From The Avenger (Ch 10-15)` is a link to the story.
Is it possible to edit the links so that for example `Tales From The Avenger` would stay as a link to the story and `10 `and `15 `would be links to the referred chapters?

**Comment by JimmXinu** [comment]
This would take a pretty fair degree of re-architecting to accomplish.  Unless there are more people wanting it, or a compelling use-case, I don't see this happening.

Personally, I use these settings to put a link in each chapter for a couple sites:
```
[base_xenforoforum:epub]
chapter_start:<?xml version="1.0" encoding="UTF-8"?>
 <html xmlns="http://www.w3.org/1999/xhtml">
 <head>
 <title>${chapter}</title>
 <link href="stylesheet.css" type="text/css" charset="UTF-8" rel="stylesheet"/>
 <meta name="chapterurl" content="${url}"></meta>
 <meta name="chapterorigtitle" content="${origchapter}"></meta>
 <meta name="chaptertoctitle" content="${tocchapter}"></meta>
 <meta name="chaptertitle" content="${chapter}"></meta>
 </head>
 <body>
 <h3>${chapter}</h3>
 <p class="skip_on_ffdl_update"><a class="small" href="${url}">chapter link</a></p>
```

(The `skip_on_ffdl_update` class helps keep updates clean.)
