### ISSUE TITLE
[bug?] on mc.stories.com Fanficfare fails to change metadata

### ISSUE THREAD

**Issue by jeancinq** [JimmXinu/FanFicFare#455]
With Fanficfare as the plugin of Calibre, on version 3.14.0:
When downloading at last some of the fictions on mcstories.com, "extratags" from my personal.ini are ignored. The fiction download correctly, but the only tag present is different from those I asked.

example URL with this problem:
`https://mcstories.com/DorianGraysMother/index.html`

Here is a debug log of the download:
[tmpfoltrk.txt](https://github.com/JimmXinu/FanFicFare/files/3990646/tmpfoltrk.txt)

Here is the is my personal_ini file (with redacted passwords and id):
[personal_ini.txt](https://github.com/JimmXinu/FanFicFare/files/3990655/personal_ini.txt)

It's possible I just made a syntax error in the file, but I can't see it.

**Comment by JimmXinu** [comment]
From `defaults.ini`:
```
[mcstories.com]
## Some sites do not require a login, but do require the user to
## confirm they are adult for adult content.  In commandline version,
## this should go in your personal.ini, not defaults.ini.
#is_adult:true

## Clear FanFiction from defaults, site is original fiction.
extratags:Erotica

extra_valid_entries:eroticatags
eroticatags_label:Erotica Tags
extra_titlepage_entries: eroticatags
```

So the `[mcstories.com]` section `extratags` is overriding yours from `[defaults]` because it's more specific.  Which isn't 100% intuitive, but it is functioning as designed.

I suggest using `add_to_extratags:FanFicFare` in personal.ini under `[defaults]` instead to get both.
