### ISSUE TITLE
skip_threadmark_categories not working

### ISSUE THREAD

**Issue by MrTyton** [JimmXinu/FanFicFare#456]
In personal.ini, I have the following lines

> [forums.sufficientvelocity.com]
> skip_threadmark_categories:Staff Post

but when I download [this](https://forums.sufficientvelocity.com/threads/mauling-snarks-worm.41471/reader/#threadmark-category-1) story, "Staff Posts" still show up in the epub in the end.

Did I mess something up or is there a bug?

**Comment by JimmXinu** [comment]
skip_threadmarks_categories:Staff Post

Note that it's threadmarks with an s.

**Comment by MrTyton** [comment]
You are correct. I am bad at reading.
