### ISSUE TITLE
Update AH?

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#457]
Ever since AH updated XF2 none on my stories have updated

**Comment by DragoLord19D** [comment]
This is what pops up.


Kentucky Fried Politics: A Colonel Sanders Timeline
gap80
'NoneType' object has no attribute 'h1'
https://www.alternatehistory.com/forum/threads/kentucky-fried-politics-a-colonel-sanders-timeline.451582/

**Comment by JimmXinu** [comment]
[Test version of plugin](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2) posted on the usual forum and test version of CLI uploaded to test.pypi.org.

**Comment by bluerubberone** [comment]
Literotica gets kicked back with this error everytime an attempt is made

"'NoneType' object has no attribute 'a'"

**Comment by JimmXinu** [comment]
@bluerubberone, you shouldn't report problems with Literotica in an issue about AH.

Also, I'm not seeing your issue.  Please open a new issue and include at least one story URL that exhibits the problem.
