### ISSUE TITLE
Delete/Update converted versions on updating fanfics

### ISSUE THREAD

**Issue by fjacobi** [JimmXinu/FanFicFare#458]
Hej,
when updating a book (in my case royalroad) the already converted versions are left untouched, so updating and sending it to my Kindle transfers the old mobi version.

Any chance that the update can delete/update the converted versions for ease of use?

**Comment by JimmXinu** [comment]
Assuming you are using the Calibre plugin, that's already a feature.  

Look in FFF's settings on the Basic tab under 'Updating Calibre Options' for 'Delete other existing formats' and under 'Post Processing Options' for 'Automatically Convert new/update books'.  

Auto convert uses the Calibre default output format from Calibre's Preferences->Behavior->Preferred Output Format setting.

If you're using FFF CLI, you can use the `post_process_cmd` INI setting.
