### ISSUE TITLE
FFF produces invalid EPub from SugarQuill

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#460]
```
tmp@stitny$ fanficfare --debug 'http://www.sugarquill.net/read.php?storyid=2292&chapno=1'
FFF: DEBUG: 2020-01-09 11:11:46,380: cli.py(193):     OS Version:Linux-5.3.12-2-default-x86_64-with-glibc2.2.5
FFF: DEBUG: 2020-01-09 11:11:46,380: cli.py(194): Python Version:3.7.3 (default, Apr 09 2019, 05:18:21) [GCC]
FFF: DEBUG: 2020-01-09 11:11:46,380: cli.py(195):    FFF Version:3.13.0
FFF: DEBUG: 2020-01-09 11:11:46,399: adapter_sugarquillnet.py(91): URL: http://www.sugarquill.net/read.php?storyid=2292&chapno=1
FFF: DEBUG: 2020-01-09 11:11:46,399: configurable.py(1133): #####################################
pagecache(GET) MISS: http://www.sugarquill.net/read.php?storyid=2292&chapno=1
.FFF: DEBUG: 2020-01-09 11:11:47,078: configurable.py(999): Encoding:utf8
FFF: DEBUG: 2020-01-09 11:11:47,078: configurable.py(1020): code failed:utf8
FFF: DEBUG: 2020-01-09 11:11:47,078: configurable.py(1021): 'utf-8' codec can't decode byte 0xe9 in position 14460: invalid continuation byte
FFF: DEBUG: 2020-01-09 11:11:47,079: configurable.py(999): Encoding:Windows-1252
FFF: DEBUG: 2020-01-09 11:11:47,138: adapter_sugarquillnet.py(130): Getting the author page: http://www.sugarquill.net/index.php?action=profile&id=854
FFF: DEBUG: 2020-01-09 11:11:47,138: configurable.py(1133): #####################################
pagecache(GET) MISS: http://www.sugarquill.net/index.php?action=profile&id=854
.FFF: DEBUG: 2020-01-09 11:11:48,329: configurable.py(999): Encoding:utf8
FFF: DEBUG: 2020-01-09 11:11:48,329: configurable.py(1020): code failed:utf8
FFF: DEBUG: 2020-01-09 11:11:48,329: configurable.py(1021): 'utf-8' codec can't decode byte 0x92 in position 10245: invalid start byte
FFF: DEBUG: 2020-01-09 11:11:48,330: configurable.py(999): Encoding:Windows-1252
FFF: INFO: 2020-01-09 11:11:48,446: base_writer.py(183): Save directly to file: Yarn Shop-sq_2292.epub
FFF: DEBUG: 2020-01-09 11:11:48,446: adapter_sugarquillnet.py(160): Getting chapter text from: http://www.sugarquill.net/read.php?storyid=2292&chapno=1
FFF: DEBUG: 2020-01-09 11:11:48,446: configurable.py(1133): #####################################
pagecache(GET) MISS: http://www.sugarquill.net/read.php?storyid=2292&chapno=1
.FFF: DEBUG: 2020-01-09 11:11:49,132: configurable.py(999): Encoding:utf8
FFF: DEBUG: 2020-01-09 11:11:49,133: configurable.py(1020): code failed:utf8
FFF: DEBUG: 2020-01-09 11:11:49,133: configurable.py(1021): 'utf-8' codec can't decode byte 0xe9 in position 14460: invalid continuation byte
FFF: DEBUG: 2020-01-09 11:11:49,133: configurable.py(999): Encoding:Windows-1252
FFF: DEBUG: 2020-01-09 11:11:49,292: cli.py(87): Successfully wrote 'Yarn Shop-sq_2292.epub'
tmp@stitny$
```
produces [Yarn Shop-sq_2292.epub](https://github.com/JimmXinu/FanFicFare/files/4039814/Yarn.Shop-sq_2292.epub.zip) which is invalid (both by the opinion of my EPub reader and http://validator.idpf.org/application/validate). The validator says:

FATAL 	OEBPS/title_page.xhtml 	8 	68 	Fatal Error while parsing file: The reference to entity "chapno" must end with the ';' delimiter.

ERROR 	OEBPS/title_page.xhtml 	- 	- 	Error while parsing file: The reference to entity "chapno" must end with the ';' delimiter.

ERROR 	OEBPS/file0001.xhtml 	13 	26 	Error while parsing file: element "td" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")

ERROR 	OEBPS/file0001.xhtml 	39 	9 	Error while parsing file: element "option" not allowed anywhere; expected the element end-tag, text or element "a", "abbr", "acronym", "address", "applet", "b", "bdo", "big", "blockquote", "br", "cite", "code", "del", "dfn", "div", "dl", "em", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "ol", "p", "pre", "q", "samp", "script", "small", "span", "strong", "sub", "sup", "table", "tt", "ul" or "var" (with xmlns:ns="http://www.w3.org/2000/svg")

ERROR 	OEBPS/file0001.xhtml 	64 	9 	Error while parsing file: element "option" not allowed anywhere; expected the element end-tag, text or element "a", "abbr", "acronym", "address", "applet", "b", "bdo", "big", "blockquote", "br", "cite", "code", "del", "dfn", "div", "dl", "em", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "ol", "p", "pre", "q", "samp", "script", "small", "span", "strong", "sub", "sup", "table", "tt", "ul" or "var" (with xmlns:ns="http://www.w3.org/2000/svg")

ERROR 	OEBPS/file0001.xhtml 	106 	9 	Error while parsing file: element "option" not allowed anywhere; expected the element end-tag, text or element "a", "abbr", "acronym", "address", "applet", "b", "bdo", "big", "blockquote", "br", "cite", "code", "del", "dfn", "div", "dl", "em", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "ol", "p", "pre", "q", "samp", "script", "small", "span", "strong", "sub", "sup", "table", "tt", "ul" or "var" (with xmlns:ns="http://www.w3.org/2000/svg")

**Comment by JimmXinu** [comment]
The unescaped `&` in href on the titlepage I'll cop to.  That should be `&amp;`  Not sure why it isn't, but it's only story URL on title page and only 3 sites use `&` in story URLs, so it's a bit obscure.

The `<td>` should be changed to a `<div>`. 

The incorrect `<option>` tags are as the author included them.  Not going to do anything about those.

**Comment by JimmXinu** [comment]
Test CLI version uploaded to test.pypi.org

**Comment by mcepl** [comment]
Yes, thank you very much. With the code from test.pypi.org I can download http://www.sugarquill.net/read.php?storyid=2292&chapno=1 as a correct EPub. Thank you.
