### ISSUE TITLE
phoenixsong adapter cuts a lot of text out

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#463]
With FanFicFare 3.4.17 when downloading https://www.phoenixsong.net/fanfiction/story/5284/ I get [Seventeen-phs_5284.epub](https://github.com/JimmXinu/FanFicFare/files/4086648/Seventeen-phs_5284.zip). Notice how much text is actually cut (even the first letter of Harry to Ginny is one-liner in EPub).

**Comment by JimmXinu** [comment]
I assume you mean v3.14.7.  Which I also assume means you're using the CLI from testpy.  v3.15.0 has been released to the non-test pypi channel--not that it makes a difference in this case.

phoenixsong.net is an old site and it's HTML is... poor.  The chapter HTML handling is less than ideal.  

I've changed it to also include `<blockquote>` tags, which were being left out.  cdb589966f9956b4bd4a167c5098e025ba3e70a7

I've pushed v3.15.3 to test.pypi.  Let me know if you need the plugin test version instead.

(I recognized that story, buy my copy came from [SIYE](http://www.siye.co.uk/siye/viewstory.php?sid=126923) instead which didn't have that problem.)

**Comment by mcepl** [comment]
Thank you, with 3.15.3 the story has been downloaded perfectly. Thank you. And yes, it is not bad, although I just couldn’t overcome my deep disdain to the magical trunks.
