### ISSUE TITLE
storiesonline.net: login broken

### ISSUE THREAD

**Issue by mvlcek** [JimmXinu/FanFicFare#464]
The login for storiesonline.net does not work any more due to a change on the web site:
when loading https://storiesonline.net/sol-secure/login.php a hidden parameter (v) is now included in the form.
Fix:
- load https://storiesonline.net/sol-secure/login.php
- parse page for hidden fields (e.g. regex "type=\"hidden\"\s+name=\"([^\"]+)\"\s+value=\"([^\"]+)\""
- include the fields in the login parameters to send
- proceed with submitting the login request including the hidden parameters

**Comment by JimmXinu** [comment]
6a6007441f7ede8581125cc651872eee68da1549
