### ISSUE TITLE
Fanficfare says there is a problem with my user configuration.

### ISSUE THREAD

**Issue by dr361** [JimmXinu/FanFicFare#467]
Fanficfare says there is a problem with my user configuration. I just try to download a fic  from Wattpad and fanficfare said there was a problem with my user configuration I don’t know anything about code and cannot fix it, and the alternate link  https://fanficfare.appspot.com/ is over quota again.

**Comment by JimmXinu** [comment]
Without a copy of your user config or at least an error message I cannot help you.  (You should also always include the story URL when reporting problems.)

The [web service version was officially closed](https://github.com/JimmXinu/FanFicFare/wiki#web-service-version) late last year.

**Comment by dr361** [comment]
My user configuration is this.

[defaults]
## Some sites also require the user to confirm they are adult for
## adult content.  Uncomment by removing '#' in front of is_adult.  In
## commandline version, this should go in your personal.ini, not
## defaults.ini.
#is_adult:true

## Don't like the numbers at the start of chapter titles on some
## sites?  You can use strip_chapter_numbers to strip them off.  Just
## want to make them all look the same?  Strip them off, then add them
## back on with add_chapter_numbers.  Don't like the way it strips
## numbers or adds them back?  See chapter_title_strip_pattern and
## chapter_title_add_pattern.
#strip_chapter_numbers:true
#add_chapter_numbers:true

[epub]
## include images from img tags in the body and summary of stories.
## Images will be converted to jpg for size if possible.  Images work
## in epub format only.  To get mobi or other format with images,
## download as epub and use Calibre to convert.
#include_images:true

## If not set, the summary will have all html stripped for safety.
## Both this and include_images must be true to get images in the
## summary.
#keep_summary_html:true

## If set, the first image found will be made the cover image.  If
## keep_summary_html is true, any images in summary will be before any
## in chapters.
#make_firstimage_cover:true

## Resize images down to width, height, preserving aspect ratio.
## Nook size, with margin.
#image_max_size: 580, 725

## Change image to grayscale, if graphics library allows, to save
## space.
#grayscale_images: false


## Most common, I expect will be using this to save username/passwords
## for different sites.  Here are a few examples.  See defaults.ini
## for the full list.

[www.twilighted.net]
#username:YourPenname
#password:YourPassword
## default is false
#collect_series: true

[ficwad.com]
#username:YourUsername
#password:YourPassword

[www.twiwrite.net]
#username:YourName
#password:yourpassword
## default is false
#collect_series: true

[www.adastrafanfic.com]
## Some sites do not require a login, but do require the user to
## confirm they are adult for adult content.
#is_adult:true

[www.twcslibrary.net]
#username:YourName
#password:yourpassword
#is_adult:true
## default is false
#collect_series: true

[www.fictionalley.org]
#is_adult:true

[www.harrypotterfanfiction.com]
#is_adult:true

[www.fimfiction.net]
#is_adult:true
#fail_on_password: false

[www.tthfanfic.org]
#is_adult:true
## tth is a little unusual--it doesn't require user/pass, but the site
## keeps track of which chapters you've read and won't send another
## update until it thinks you're up to date.  This way, on download,
## it thinks you're up to date.
#username:YourName
#password:yourpassword


## This section will override anything in the system defaults or other
## sections here.
[overrides]
## default varies by site.  Set true here to force all sites to
## collect series.
#collect_series: true
It’s the default one 
Here is the message 
I get when I downloaded 

Error happened: There's an error in your User Configuration: Unknown Site(https://www.wattpad.com/280639201-unnatural-romance-chapter-1-blood-moon). Supported sites: (archive.skyehawke.com, archiveofourown.org, ashwinder.sycophanthex.com, asr3.slashzone.org, bdsm-geschichten.net, bloodshedverse.com, bloodties-fans.com, buffynfaith.net, chaos.sycophanthex.com, csi-forensics.com, dark-solace.org, devianthearts.com, dramione.org, efiction.esteliel.de, erosnsappho.sycophanthex.com, fanfic.castletv.net, fanfic.hu, fanfic.potterheadsanonymous.com, fanfiction-junkies.de, fanfiction.csodaidok.hu, fanfiction.mugglenet.com, fanfiction.portkey.org, fanfiction.tenhawkpresents.com, fannation.shades-of-moonlight.com, fhsarchive.com, fictionmania.tv, fictionpad.com, ficwad.com, finestories.com, grangerenchanted.com, hlfiction.net, hpfanficarchive.com, imagine.e-fic.com, indeath.net, ksarchive.com, literotica.com, lotrfanfiction.com, lumos.sycophanthex.com, merlinfic.dtwins.co.uk, national-library.net, ncisfic.com, netraptor.org, nfacommunity.com, nha.magical-worlds.us, nocturnal-light.net, occlumency.sycophanthex.com, onedirectionfanfiction.com, pommedesang.com, ponyfictionarchive.net, pretendercentre.com, samandjack.net, samdean.archive.nu, scarhead.net, sg1-heliopolis.com, sheppardweir.com, spikeluver.com, stargate-atlantis.org, storiesonline.net, test1.com, thehexfiles.net, thehookupzone.net, themaplebookshelf.com, themasque.net, thequidditchpitch.org, tokra.fandomnet.com, tolkienfanfiction.com, trekiverse.org, voracity2.e-fic.com, www.adastrafanfic.com, www.checkmated.com, www.destinysgateway.com, www.dokuga.com, www.dotmoon.net, www.dracoandginny.com, www.efpfanfic.net, www.fanfiction.net, www.fanfiktion.de, www.ficbook.net, www.fictionalley.org, www.fictionpress.com, www.fimfiction.net, www.harrypotterfanfiction.com, www.henneth-annun.net, www.hpfandom.net, www.ik-eternal.net, www.libraryofmoria.com, www.mediaminer.org, www.midnightwhispers.ca, www.ncisfiction.net, www.nickandgreg.net, www.phoenixsong.net, www.potionsandsnitches.org, www.potterfics.com, www.psychfic.com, www.qaf-fic.com, www.restrictedsection.org, www.scarvesandcoffee.net, www.simplyundeniable.com, www.sinful-desire.org, www.siye.co.uk, www.squidge.org, www.storiesofarda.com, www.thealphagate.com, www.thepetulantpoetess.com, www.tthfanfic.org, www.twcslibrary.net, www.twilightarchives.com, www.twilighted.net, www.twiwrite.net, www.walkingtheplank.org, www.whofic.com, www.wizardtales.net, www.wolverineandrogue.com, www.wraithbait.com)

Sent from my iPhone

> On Feb 7, 2020, at 1:14 PM, Jim Miller <notifications@github.com> wrote:
> 

﻿
Without a copy of your user config or at least an error message I cannot help you. (You should also always include the story URL when reporting problems.)

The web service version was officially closed late last year.

**Comment by dr361** [comment]
I only use because I cannot use Calibre also yours was the only service that used to download Wattpad. No other fanfic downloader would.

Sent from my iPhone

> On Feb 7, 2020, at 1:14 PM, Jim Miller <notifications@github.com> wrote:
> 

﻿
Without a copy of your user config or at least an error message I cannot help you. (You should also always include the story URL when reporting problems.)

The web service version was officially closed late last year.

**Comment by dr361** [comment]
The story url is

https://www.wattpad.com/280639201-unnatural-romance-chapter-1-blood-moon

Sent from my iPhone

> On Feb 7, 2020, at 1:14 PM, Jim Miller <notifications@github.com> wrote:
> 

﻿
Without a copy of your user config or at least an error message I cannot help you. (You should also always include the story URL when reporting problems.)

The web service version was officially closed late last year.

**Comment by JimmXinu** [comment]
It looks like your version of FanFicFare is old enough it doesn't wattpad.com.  

What FanFicFare version do you have, and where are you running it?  CLI or Calibre plugin?  I don't recognize the error message "There's an error in your User Configuration".

**Comment by dr361** [comment]
Also the fanficfare.appspot.com is saying this all the time.

Sent from my iPhone

> On Feb 7, 2020, at 1:14 PM, Jim Miller <notifications@github.com> wrote:
> 

﻿
Without a copy of your user config or at least an error message I cannot help you. (You should also always include the story URL when reporting problems.)

The web service version was officially closed late last year.

**Comment by dr361** [comment]
2013

Sent from my iPhone

> On Feb 7, 2020, at 1:45 PM, Jim Miller <notifications@github.com> wrote:
> 

﻿
It looks like your version of FanFicFare is old enough it doesn't wattpad.com.

What FanFicFare version do you have, and where are you running it? CLI or Calibre plugin? I don't recognize the error message "There's an error in your User Configuration".

**Comment by dr361** [comment]
I just run it from the webpage 

Sent from my iPhone

> On Feb 7, 2020, at 1:45 PM, Jim Miller <notifications@github.com> wrote:
> 

﻿
It looks like your version of FanFicFare is old enough it doesn't wattpad.com.

What FanFicFare version do you have, and where are you running it? CLI or Calibre plugin? I don't recognize the error message "There's an error in your User Configuration".

**Comment by dr361** [comment]
This will answer your question 


Sent from my iPhone

> On Feb 7, 2020, at 1:45 PM, Jim Miller <notifications@github.com> wrote:
> 

﻿
It looks like your version of FanFicFare is old enough it doesn't wattpad.com.

What FanFicFare version do you have, and where are you running it? CLI or Calibre plugin? I don't recognize the error message "There's an error in your User Configuration".

**Comment by JimmXinu** [comment]
The web service I used to run was fanficfare.appspot.com--the one that's always 'Over Quota' and isn't supported anymore.

I don't know what page you're using now, but it's not one I support, sorry.

**Comment by dr361** [comment]
Well now what I cannot afford Calibre 

Sent from my iPhone

> On Feb 7, 2020, at 1:52 PM, Jim Miller <notifications@github.com> wrote:
> 

﻿
The web service I used to run was fanficfare.appspot.com--the one that's always 'Over Quota' and isn't supported anymore.

I don't know what page you're using now, but it's not one I support, sorry.

**Comment by cryzed** [comment]
Calibre is free. Please do the minimal amount of research instead of expecting to be spoonfed everything - unless you want to pay Jimm for his support. You are extremely rude.

**Comment by dr361** [comment]
I am sorry I am just trying get help. I am actually a very nice person. Sorry if that doesn’t come across in text I apologize. I just am not very good with code or using code to convert ebooks. I usually just use a program like this one. I just wanted to read fanfiction offline because I am in a place with intermittent internet. I can guess how hard you guys work. Someone told me Calibre was not free and would cost $1500.00. They must have been taking the Mickey. I am just not good with computers beyond the basics. I had no idea that the website had been shutdown for a while. I just got back on today please believe I meant no offense.
I won’t bother you again sorry to be a burden.

Sent from my iPhone

> On Feb 7, 2020, at 8:44 PM, Chris Braun <notifications@github.com> wrote:
> 

﻿
Calibre is free. Please do the minimal amount of research instead of expecting to be spoonfed everything - unless you want to pay Jimm for his support. You are extremely rude.

**Comment by cryzed** [comment]
> Someone told me Calibre was not free and would cost $1500.00. They must have been taking the Mickey.

Yeah, sorry if I have trouble believing that.

> I won’t bother you again

Your problem is solved at this point anyways. You know Calibre is free. FanFicFare is available as a plugin for Calibre and you won't be limited by the site you used previously; enjoy.

**Comment by JimmXinu** [comment]
Calibre is a free, open source program for managing your ebooks:
https://calibre-ebook.com/download

I assumed @dr361 meant they couldn't afford a computer to run Calibre, which isn't impossible.

I believe this has been discussed as much as it needs to be, so I'm locking the issue.
