### ISSUE TITLE
A quick question 

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#468]
I don’t know if it’s me and I downloaded something wrong but ever since the latest update for Calibre I haven’t been able to download anything from fanficfare... It just keeps running and running, my latest attempt has been running for about 12 hours...
![image](https://user-images.githubusercontent.com/36297332/74297393-5b9a3300-4d0c-11ea-9ca1-e0a59ea262dd.jpg)

**Comment by JimmXinu** [comment]
12 hours is a bit excessive for most downloads.  And the status/progress shown seems to indicate that the FFF background job was still waiting to start.

If Calibre isn't launching the BG job, that's a Calibre issue, not anything I can help with.

I would suggest restarting Calibre in debug mode and trying a single download of a story you are able to view in browser on the same computer.

**Comment by DragoLord19D** [comment]
Well, I tried the debug and it said it was fine but once I updated fanficfare it worked fine so, *Shrug*
