### ISSUE TITLE
Add option to add apocrypha chronologically rather than at the end

### ISSUE THREAD

**Issue by HaniiPuppy** [JimmXinu/FanFicFare#469]
I downloaded Purple Days from SpaceBattles and noticed that Fanficfare adds the apocrypha right at the end of the story. While I can understand the logic behind putting the apocrypha at the end of the story rather than in-place, (especially for shorter stories) I'd really rather just generally have chapters and apocrypha appear in the order they were posted, chronologically.

Alternatively, a note to say when (in terms of between which chapters) a piece of apocrypha was contributed would be helpful, so I can at least know where in the story it fits, roughly.

**Comment by JimmXinu** [comment]
I'm willing to add a new feature to sort all threadmark chapters by `date` (instead of category then author's chosen order), but it would be for all included threadmarks, not just apocrypha inserted into regular threadmarks.  (Unless, of course, those are the only threadmark categories you include.)

FYI, you can get threadmark dates included in the chapter titles now with just INI changes.  That's the closest available to some kind of note about where apocrypha would go.

```
[base_xenforoforum:epub]
# BaseXenForo chapters have 'date', 'words', and 'kwords' available
# for each chapter.  These can be used with custom output (see
# https://github.com/JimmXinu/FanFicFare/wiki/CustomOutput ) or with
# chapter_title_*_pattern settings.

## The basic pattern used when not using add_chapter_numbers or
## mark_new_chapters
chapter_title_def_pattern:${title} ${date}

## Pattern used with add_chapter_numbers, but not mark_new_chapters
chapter_title_add_pattern:${number}. ${title} ${date}

## Pattern used with mark_new_chapters, but not add_chapter_numbers
## (new) is just text and can be changed.
chapter_title_new_pattern:(new) ${title} ${date}

## Pattern used with add_chapter_numbers and mark_new_chapters
## (new) is just text and can be changed.
chapter_title_addnew_pattern:${number}. (new) ${title} ${date}

## The 'date' value for chapters mentioned above can be formated with
## datethreadmark_format.  Otherwise it will default to
## dateCreated_format
datethreadmark_format:%%Y-%%m-%%d %%H:%%M
```

**Comment by JimmXinu** [comment]
Another FYI, I've found [at least one story](https://forums.spacebattles.com/threads/quicksave-worm-alt-power-taylor.355765/) where post order is different from date order--the Index post in that thread was actually a few minutes *after* the 1.1 post and thus order by date, it would go: 1.1, Index, 1.2.

The feature I'm proposing would *not* be able to fix that.

**Comment by JimmXinu** [comment]
Add `order_threadmarks_by_date` setting. 9901796331995e64ce8af46db80376ecf23be437

```
## By default, FFF orders threadmarks first by category, then in the
## order they appear as determined by the author.  When
## order_threadmarks_by_date:true, all included threadmarks
## (skip_threadmarks_categories still works) will instead be ordered
## by their initial post datetime.  Different threadmark categories
## will be mixed together, and I've seen at least one case of post
## order on the site disagreeing with post datetime.
#order_threadmarks_by_date:false
```

**Comment by HaniiPuppy** [comment]
Oh wow, that was fast - thank you!
