### ISSUE TITLE
Hentai Foundry Tag issue

### ISSUE THREAD

**Issue by Cupbox** [JimmXinu/FanFicFare#471]
As illustrated in the gif, the icons in the bottom right corner of a HF story are tags. Could they be added?
![2020-02-28_04-07-58](https://user-images.githubusercontent.com/13769570/75495274-0d488d80-59b6-11ea-9c31-5cc6baac215a.gif)

**Comment by JimmXinu** [comment]
Those are already being collected in the site specific metadata entry 
'warnings'.

If you want them included in Calibre's tags, you can add warnings to the 
include_subject_tags setting in your personal.ini.  For example:

[www.hentai-foundry.com]
add_to_include_subject_tags:,warnings

**Comment by Cupbox** [comment]
Thank you so much. 
Works perfectly for me.
