### ISSUE TITLE
archiveofourown download limits

### ISSUE THREAD

**Issue by UncoveredBulb** [JimmXinu/FanFicFare#472]
Hi, I used to use fanficfare a few years ago to download fics in bulk, and recently decided to update my collection, only I'm getting 429 errors after 35 or so fics. What's changed? Is there a workaround?

fanficfare is CLI version 3.16.0
site: archiveofourown.org
error: `Failed to read epub for update: (HTTP Error 429: Too Many Requests) Continuing with update=false`

**Comment by JimmXinu** [comment]
Please see FAQ: 
[Why shouldn't I just select my entire library and use FanFicFare plugin to check for updates?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-shouldnt-i-just-select-my-entire-library-and-use-fanficfare-plugin-to-check-for-updates)

All I can suggest is increasing the `slow_down_sleep_time` setting higher than the default(2 for AO3) and downloading smaller batches with more time in between.
