### ISSUE TITLE
XenForo story with manually specified post ids?

### ISSUE THREAD

**Issue by inklesspen** [JimmXinu/FanFicFare#475]
I know this is getting pretty esoteric, but there's one Worm "fic" that's been posted exclusively as omakes on another fic. It's "The Fourth", posted on SufficientVelocity.

The "parent" fic so far hasn't added these to threadmarks, so the only way to find the posts is in an index post in the first page of the thread. However, there are many other unrelated posts also in the index post.

Would it be possible to extract a story by manually specifying the post ids that make it up? So far, there's only 8 of them.

**Comment by JimmXinu** [comment]
There is a feature for *excluding* chapters you could use to exclude all the other chapters when downloading from the [post URL](https://forums.sufficientvelocity.com/posts/1920312/):
```
## You can exclude chapters from a story by listing their chapter URLs
## in ignore_chapter_url_list.  Chapter URLs will be normalized before
## being used, so you can use either longer or normalized chapter
## URLs.
## NOTE: This will cause numWords(word count) to be off for most sites.
## This setting should be used in a specific story's section.
## Example:
[https://forums.sufficientvelocity.com/posts/1920312/]
ignore_chapter_url_list:
 https://forums.spacebattles.com/posts/10157294/
 https://forums.spacebattles.com/posts/10157297/
 https://forums.spacebattles.com/posts/10157299/
 https://forums.spacebattles.com/threads/lengthy-thread-name.100849/#post-10157400
```
(no, I didn't look up the actual chapter urls)

But it's probably easier to download using the [post URL](https://forums.sufficientvelocity.com/posts/1920312/) and then pare down to only those chapters using the EpubSplit Calibre plugin or some other editing tool.

In future, please include story URLs.  It's actually kind of uncommon that also I read whatever any given user cares about.

**Comment by inklesspen** [comment]
Sure, I'd be happy to. (I honestly didn't think it was relevant. But here we go.)
https://forums.sufficientvelocity.com/threads/with-friends-like-these-altpower-taylor-worm-x-post.9324/
https://forums.sufficientvelocity.com/posts/3028431/
https://forums.sufficientvelocity.com/posts/3050073/
https://forums.sufficientvelocity.com/posts/3277179/
https://forums.sufficientvelocity.com/posts/6207886/
https://forums.sufficientvelocity.com/posts/7549112/
https://forums.sufficientvelocity.com/posts/8522720/
https://forums.sufficientvelocity.com/posts/9635084/
https://forums.sufficientvelocity.com/posts/13662161/

**Comment by JimmXinu** [comment]
I meant next time you come here asking about something, please include the story URL from the start.

9 times out of 10, I need a story URL before I can even look at whatever issue I'm being asked about. This particular time I knew the story already.

**Comment by rredford** [comment]
> There is a feature for _excluding_ chapters you could use to exclude all the other chapters when downloading from the [post URL](https://forums.sufficientvelocity.com/posts/1920312/):

Where do I put in chapters exclude info in?
