### ISSUE TITLE
Cover Images aren't grabbed from Fanfiction.net

### ISSUE THREAD

**Issue by rdragonrydr** [JimmXinu/FanFicFare#476]
I'm somewhat confused by this, but as far as I can tell, for stories that have cover images on FFN, this does not capture them when archiving.

In the logs, it states that it gets the URL of the image, but none appears in the book or as the Calibre cover image/metadata.

I'm fairly sure that it SOMETIMES does do this for Spacebattles/SufficientVelocity, since I seem to have cover images for a few of those which I haven't added (but most don't). It also does work for RRL stories.

Sorry; I don't currently have a log since my clipboard somehow dropped it, and I now have nothing I need to update...

**Comment by JimmXinu** [comment]
Calibre Plugin FanFicFare does download images by default, but only in epub and html output formats.  There are several settings in FFF's config under the Cover tab as well as Basic (Update Calibre Metadata options) that can effect whether the cover is updated.

I've just checked to be sure, and FFF does download cover with a randomly selected ffnet story with cover image.  

Note that by default, FFF does _not_ download and use the image ffnet shows with the story if it is the same as the author's image.  If you want those anyway, add `skip_author_cover:false` under `[www.fanfiction.net]` in your `personal.ini`.

Without at least story URLs to investigate, I'm inclined to close this and you can come back when you have specifics.  I'll leave it open for the moment, but not for hugely long.

**Comment by rdragonrydr** [comment]
Below is log data from a fanfiction.net story whose cover does not appear, but does have one on FFN:

FFF: INFO: 2020-04-03 16:19:58,854: calibre_plugins.fanficfare_plugin.jobs(95): Logfile for book ID 274 (Worm - Waterworks)
FFF: INFO: 2020-04-03 16:19:58,854: calibre_plugins.fanficfare_plugin.jobs(96): url:(https://www.fanfiction.net/s/11847642/1/) id:(274)
FFF: DEBUG: 2020-04-03 16:18:33,190: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(100): URL: https://www.fanfiction.net/s/11847642/1/
FFF: DEBUG: 2020-04-03 16:18:33,191: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1112): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/11847642/1/
FFF: DEBUG: 2020-04-03 16:18:33,191: calibre_plugins.fanficfare_plugin.fanficfare.configurable(985): Encoding:utf8
FFF: DEBUG: 2020-04-03 16:18:33,355: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(298): cover_url://ff74.b-cdn.net/image/3812136/180/
FFF: DEBUG: 2020-04-03 16:18:33,357: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1122): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/u/4583733/SeerKing
FFF: DEBUG: 2020-04-03 16:18:39,063: calibre_plugins.fanficfare_plugin.fanficfare.configurable(985): Encoding:utf8
FFF: DEBUG: 2020-04-03 16:18:41,969: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(311): authimg_url://ff74.b-cdn.net/image/3851678/150/
FFF: DEBUG: 2020-04-03 16:18:41,972: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1122): #####################################
pagecache(GET) MISS: https://ff74.b-cdn.net/image/3812136/180/
FFF: INFO: 2020-04-03 16:19:47,118: calibre_plugins.fanficfare_plugin.fanficfare.story(1239): Failed to load or convert image, 
parent:https://www.fanfiction.net/s/11847642/1/
skipping:https://ff74.b-cdn.net/image/3812136/180/
Exception: <urlopen error ('_ssl.c:711: The handshake operation timed out',)>
FFF: INFO: 2020-04-03 16:19:47,966: calibre_plugins.fanficfare_plugin.jobs(294): Do update - epub(15) vs url(16)
FFF: INFO: 2020-04-03 16:19:47,966: calibre_plugins.fanficfare_plugin.jobs(295): write to /tmp/calibre_3.21.0_tmp_KKQb3z/fanficfare_YvCYYj/Worm - Waterworks-SeerKing-6eMFal.epub
FFF: INFO: 2020-04-03 16:19:47,967: calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer(183): Save directly to file: /tmp/calibre_3.21.0_tmp_KKQb3z/fanficfare_YvCYYj/Worm - Waterworks-SeerKing-6eMFal.epub
FFF: DEBUG: 2020-04-03 16:19:49,465: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(354): Getting chapter text from: https://www.fanfiction.net/s/11847642/16/
FFF: DEBUG: 2020-04-03 16:19:49,465: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1122): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/11847642/16/
FFF: DEBUG: 2020-04-03 16:19:57,948: calibre_plugins.fanficfare_plugin.fanficfare.configurable(985): Encoding:utf8
FFF: DEBUG: 2020-04-03 16:19:58,242: calibre_plugins.fanficfare_plugin.fanficfare.writers.writer_epub(460): writer_epub: no new cover, has old cover, write image.

I don't believe that a single FFN story in my library has a cover, so if it's working, perhaps I have something set incorrectly? I haven't tinkered with the configs at all, so perhaps it's off by default?

**Comment by JimmXinu** [comment]
On 4/3/2020 3:24 PM, rdragonrydr wrote:
> pagecache(GET) MISS: https://ff74.b-cdn.net/image/3812136/180/
> FFF: INFO: 2020-04-03 16:19:47,118: 
> calibre_plugins.fanficfare_plugin.fanficfare.story(1239): Failed to load 
> or convert image,
> parent:https://www.fanfiction.net/s/11847642/1/
> skipping:https://ff74.b-cdn.net/image/3812136/180/
> Exception: <urlopen error ('_ssl.c:711: The handshake operation timed 
> out',)>

The log file indicates that you had an SSL error while downloading the image.

I don't know why that would be exactly, but I have a few ideas:

- The image does come from a CDN server (ff74.b-cdn.net), so it could be a misconfigured CDN server that is topographically near you.
- It out dated DNS either on your end or your ISP. 
- It could be an overzealous firewall security system somewhere.

Given that it was an operation timeout, I don't think it's like to be a cert mis-match problem, but I could be wrong about that.

And if you don't have *any* covers from ffnet, that raises the odds of a long-term network issue like a firewall deliberately blocking it or poisoned DNS.

Regardless, I don't know of anything FFF can do about it.  It's a network or server issue.

**Comment by rdragonrydr** [comment]
I think that one may have been the site, sorry. I tried again with a different story, and there don't seem to be errors. However, it seems to say there's already an image when there isn't (but it seems to have used the default blank calibre cover).

Download 1 FanFiction Book(s)
FFF: INFO: 2020-04-06 22:02:05,832: calibre_plugins.fanficfare_plugin.jobs(53): FanFicFare v3.15.0
FFF: INFO: 2020-04-06 22:02:05,833: calibre_plugins.fanficfare_plugin.jobs(57): Adding jobs for URLs:
FFF: INFO: 2020-04-06 22:02:05,833: calibre_plugins.fanficfare_plugin.jobs(59): https://www.fanfiction.net/s/12881633/1/
FFF: INFO: 2020-04-06 22:13:20,143: calibre_plugins.fanficfare_plugin.jobs(95): Logfile for book ID None (Swords and Sorcery: All Ore Nothing)
FFF: INFO: 2020-04-06 22:13:20,143: calibre_plugins.fanficfare_plugin.jobs(96): url:(https://www.fanfiction.net/s/12881633/1/) id:(None)
FFF: DEBUG: 2020-04-06 22:02:06,905: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(100): URL: https://www.fanfiction.net/s/12881633/1/
FFF: DEBUG: 2020-04-06 22:02:06,905: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1112): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/12881633/1/
FFF: DEBUG: 2020-04-06 22:02:06,906: calibre_plugins.fanficfare_plugin.fanficfare.configurable(985): Encoding:utf8
FFF: DEBUG: 2020-04-06 22:02:07,071: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1112): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/Harry-Potter_and_Fate-stay-night_Crossovers/224/2746/
FFF: DEBUG: 2020-04-06 22:02:07,071: calibre_plugins.fanficfare_plugin.fanficfare.configurable(985): Encoding:utf8
FFF: DEBUG: 2020-04-06 22:02:07,376: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(298): cover_url://ff74.b-cdn.net/image/5232790/180/
FFF: DEBUG: 2020-04-06 22:02:07,378: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1122): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/u/5292097/Susanoh13
FFF: DEBUG: 2020-04-06 22:02:12,948: calibre_plugins.fanficfare_plugin.fanficfare.configurable(985): Encoding:utf8
FFF: DEBUG: 2020-04-06 22:02:14,068: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(311): authimg_url://ff74.b-cdn.net/image/5140856/150/
FFF: DEBUG: 2020-04-06 22:02:14,071: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1122): #####################################
pagecache(GET) MISS: https://ff74.b-cdn.net/image/5232790/180/
FFF: DEBUG: 2020-04-06 22:02:18,614: calibre_plugins.fanficfare_plugin.fanficfare.story(97): image used unchanged
FFF: INFO: 2020-04-06 22:02:18,788: calibre_plugins.fanficfare_plugin.jobs(246): write to /tmp/calibre_3.21.0_tmp_6flWEI/fanficfare_CRZVdU/Swords and Sorcery_ All Ore Nothing-Susanoh13-28I29A.epub
FFF: INFO: 2020-04-06 22:02:18,789: calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer(183): Save directly to file: /tmp/calibre_3.21.0_tmp_6flWEI/fanficfare_CRZVdU/Swords and Sorcery_ All Ore Nothing-Susanoh13-28I29A.epub
FFF: DEBUG: 2020-04-06 22:02:18,790: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(354): Getting chapter text from: https://www.fanfiction.net/s/12881633/1/
FFF: DEBUG: 2020-04-06 22:02:18,790: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1112): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/12881633/1/
FFF: DEBUG: 2020-04-06 22:02:18,790: calibre_plugins.fanficfare_plugin.fanficfare.configurable(985): Encoding:utf8
FFF: DEBUG: 2020-04-06 22:02:19,001: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(354): Getting chapter text from: https://www.fanfiction.net/s/12881633/2/
FFF: DEBUG: 2020-04-06 22:02:19,001: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1122): #####################################

**Comment by JimmXinu** [comment]
Or you can go into FFF's settings on the _Calibre Cover_ tab and configure FFF to set the Calibre cover image on download/update.

(Not all of the importing code is run when FFF does add_format_with_hooks().  And because some users don't want their Calibre covers updated all the time.)

It looks like that setting defaults to 'No' for historical reasons.  I might change.

**Comment by rdragonrydr** [comment]
Much of those options are greyed out for some reason, including the setting for downloading the cover. It's selected, but greyed out, so selecting "create Calibre cover" makes it impossible to change back.

Other than that, I have set it to update Calibre's cover on finding a cover in the Epub, but I'm not entirely sure that it's working. I'll post back if I find out that it isn't.
