### ISSUE TITLE
problem with long fanfics

### ISSUE THREAD

**Issue by kyoam** [JimmXinu/FanFicFare#477]
tried to download this fic 6 times and keep getting errors. I hope to not have to download each threadmark individually

https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/

**Comment by JimmXinu** [comment]
Thanks for including the story URL, but it would also help to know the errors you get.  Especially if you run in debug (`-d` for CLI or under Calibre's Preferences dropdown for Calibre Plugin) and report what you get there.

Generally, that story is just huge.  [We've see before that it takes forever and a ton of memory](https://www.mobileread.com/forums/showthread.php?p=3907136#post3907136):

>  That story has 4000+ chapters, some 4 million words and at least hundreds of images.
> 
> I've started it downloading in case I see anything interesting, but I'm not going to be surprised if it's just bigger than is going to work. I'll report back later.
> 
> If you're using 32bit Calibre, you should try 64bit. It's much more likely to work.
> 
> Update: This eventually finished for me after ~2 hours using Calibre 64bit on windows10. The process grew to >3G. And it was 749 images to go with the 4343 chapters and 3.99 million words.
> 
> I don't think there's anything in FFF specifically that failed for you, it's just really big. 

If nothing else, you can use chapter ranges to download the story in parts.

**Comment by kyoam** [comment]
how do you access chapter ranges?

**Comment by JimmXinu** [comment]
In Calibre plugin, append the range like [1-100] to the story URL, for example:
`https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/[1-1000]`

Then when it's finished, do `https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/[1001-2000]` etc.

That also works in CLI, but you need to quote or escape appropriately for your OS.  Or use `-b` and `-e` options.

From CLI help:
```
  -b START, --begin=START
                        Begin story with Chapter START.  --begin and --end
                        will be overridden by a chapter range on the STORYURL
                        like STORYURL[1-2], STORYURL[-3], STORYURL[3-] or
                        STORYURL[3]
  -e END, --end=END     End story with Chapter END.  --begin and --end will be
                        overridden by a chapter range on the STORYURL like
                        STORYURL[1-2], STORYURL[-3], STORYURL[3-] or
                        STORYURL[3]
```

**Comment by kyoam** [comment]
I use the plugin so thank you for that info also i've been using the x64 ver. i'm now trying the dl in debug mode and will see the log has to say

**Comment by kyoam** [comment]
full story failed again log from debug mode atteched will try chapter range.

[tmpu31e5r.txt](https://github.com/JimmXinu/FanFicFare/files/4400594/tmpu31e5r.txt)

**Comment by kyoam** [comment]
chapter range works well. thanks for the help.

**Comment by JimmXinu** [comment]
If you look at the bottom of that debug log, it says: `MemoryError`  And if you look at the top it says: `32bit process running on 64bit windows`.  

I'm pretty sure that if you installed and ran 64bit Calibre instead, you could do it all at once.

But if ranges worked for you, great.
