### ISSUE TITLE
Possible issue on AO3 for Calibre and CLI 

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#480]
The story `https://archiveofourown.org/works/23414953` is marked as adult in AO3 and in order to download it you have to verify that you are an adult

In my personal.ini settings on both Calibre and CLI I have set `is_adult:true` but FFF keeps asking me to verify that I am an adult, but it doesn't work. Both pressing y and enter in CLI, and pressing the yes button on Calibre.

I have tried removing the  `is_adult:true` but nothing changes
Also the error I get is this:

> Traceback (most recent call last):
>   File "c:\Python3.7\Scripts\fanficfare-script.py", line 11, in <module>
>     load_entry_point('FanFicFare==3.17.0', 'console_scripts', 'fanficfare')()
>   File "c:\python3.7\lib\site-packages\fanficfare\cli.py", line 308, in main
>     passed_personalini)
>   File "c:\python3.7\lib\site-packages\fanficfare\cli.py", line 491, in do_download
>     metaonly=options.metaonly, nooutput=options.nooutput)
>   File "c:\python3.7\lib\site-packages\fanficfare\cli.py", line 80, in write_story
>     writer = writers.getWriter(writeformat, config, adapter)
>   File "c:\python3.7\lib\site-packages\fanficfare\writers\__init__.py", line 34, in getWriter
>     return EpubWriter(config,story)
>   File "c:\python3.7\lib\site-packages\fanficfare\writers\writer_epub.py", line 55, in __init__
>     BaseStoryWriter.__init__(self, config, story)
>   File "c:\python3.7\lib\site-packages\fanficfare\writers\base_writer.py", line 53, in __init__
>     self.story = adapter.getStoryMetadataOnly() # only cache the metadata initially.
>   File "c:\python3.7\lib\site-packages\fanficfare\adapters\base_adapter.py", line 297, in getStoryMetadataOnly
>     self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
>   File "c:\python3.7\lib\site-packages\fanficfare\adapters\base_adapter.py", line 381, in doExtractChapterUrlsAndMetadata
>     return self.extractChapterUrlsAndMetadata()
>   File "c:\python3.7\lib\site-packages\fanficfare\adapters\adapter_archiveofourownorg.py", line 171, in extractChapterUrlsAndMetadata
>     raise exceptions.AdultCheckRequired(self.url)
> fanficfare.exceptions.AdultCheckRequired: Story requires confirmation of adult status: (https://archiveofourown.org/works/23414953)

**Comment by JimmXinu** [comment]
AO3 has changed something on their site.  Investigating what.

**Comment by JimmXinu** [comment]
Probably fixed in a1a7ea4d4036b953ee90de2adc51cf9f2c78e66d
