### ISSUE TITLE
HELP?

### ISSUE THREAD

**Issue by dummypimp** [JimmXinu/FanFicFare#487]
ahh this embarrassing but,, how do i use it? make it a browser plug in? or somthing? kinda lost could anyone please help. or give me a guide on what to do?

thank you

**Comment by jschpp** [comment]
Hi @dummypimp 
FanFicFare is used primarily in combination with calibre - see [wiki](https://github.com/JimmXinu/FanFicFare/wiki/CalibrePlugin)

If you still have a question feel free to ask again

**Comment by JimmXinu** [comment]
Github issues are for reporting problems with the software, not asking for basic user support.  

There are links on the [project home page](https://github.com/JimmXinu/FanFicFare) for the FanFicFare [discussion list](https://groups.google.com/group/fanfic-downloader) and [plugin version discussion thread](https://www.mobileread.com/forums/showthread.php?t=259221).
