### ISSUE TITLE
Keep Getting 'Download Aborted, Taking Too Long' -- Any way to change timeout?

### ISSUE THREAD

**Issue by Katylar** [JimmXinu/FanFicFare#489]
For some reason I keep getting a Download Aborted error whenever I try to download a longer fic or multiple ones. I have a pretty beefy internet connection, so it's not a speed/bandwidth issue. Probably something to do with the HTTPS requests. Given that, is there any way for me to change the timeout limit so I don't get aborted?

**Comment by JimmXinu** [comment]
Please provide at least one story URL for each site you're seeing this with, the exact error message and, ideally, a debug log of it happening.  You can run debug mode in CLI with `-d` or in Calibre under Calibre's Preferences drop down.

**Comment by JimmXinu** [comment]
Another possibility I just remembered: Calibre has a 'Abort jobs that take longer than:' setting under Calibre's Preferences > Misc.  I'd set that to 'Never' if it isn't already.

**Comment by JimmXinu** [comment]
No follow up from OP.
