### ISSUE TITLE
sufficientvelocity and spacebattles no longer working

### ISSUE THREAD

**Issue by DarrigoTR** [JimmXinu/FanFicFare#493]
Both these sites update to Xenforo 2 and are no longer working with FanFicFare. They now have a short "verifying your browser" page on first login per session, I assume to check that your a human user.

**Comment by DarrigoTR** [comment]
Sorry, it looks like this was a complication with my VPN. Though some sites worked with FanFicFare through the VPN and these 2 did not.

**Comment by JimmXinu** [comment]
Sounds like similar/the same as #488.
