### ISSUE TITLE
Issues downloading story from HPFF

### ISSUE THREAD

**Issue by freitagdavid** [JimmXinu/FanFicFare#494]
So I was attempting to download [this ](https://harrypotterfanfiction.com/viewstory.php?psid=23584&showRestricted) story from harrypotterfanfiction.com and it seems like there are some page elements missing maybe the formatting is different on such an old story. This is the only story I've found with this issue.

```
Traceback (most recent call last):
  File "C:\Python38\Scripts\fanficfare-script.py", line 11, in <module>
    load_entry_point('FanFicFare==3.19.8', 'console_scripts', 'fanficfare')()
  File "c:\python38\lib\site-packages\fanficfare\cli.py", line 307, in main
    do_download(url,
  File "c:\python38\lib\site-packages\fanficfare\cli.py", line 423, in do_download
    adapter.getStoryMetadataOnly()
  File "c:\python38\lib\site-packages\fanficfare\adapters\base_adapter.py", line 297, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "c:\python38\lib\site-packages\fanficfare\adapters\base_adapter.py", line 381, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "c:\python38\lib\site-packages\fanficfare\adapters\adapter_harrypotterfanfictioncom.py", line 91, in extractChapterUrlsAndMetadata
    h2.find('i').extract() # remove author
AttributeError: 'NoneType' object has no attribute 'extract'
```

**Comment by JimmXinu** [comment]
That story actually demonstrated two unrelated problems:
- New(?) code on the site for requiring `is_adult` processing: 7a5730c7207fb565ab05c7723212efd34dabdd13
- Author page parsing failed if the author had their own story in their favorites list: a2f1817f306d7684af8d5ea5909ff7981eec8172

It looks like you're a CLI user, so I pushed a new test version with these changes to pip:
```
pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare 
```

**Comment by freitagdavid** [comment]
I use both the CLI and the the calibre plugin I can work with the CLI for now I was mostly testing if it was an issue across the different releases thanks for the quick response. Seems to be working. When can I expect this fix in the calibre plugin?

**Comment by JimmXinu** [comment]
[Test version posted now](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).  Next release version probably next week.

**Comment by freitagdavid** [comment]
Awesome thank you so much for the quick response probably the fastest response I've ever gotten on a repo keep up the good work!
