### ISSUE TITLE
Support for pulling tags from Webnovel [Enhancement]

### ISSUE THREAD

**Issue by Shanakthra** [JimmXinu/FanFicFare#495]
Hi. Really impressed with using the plug-in with Calibre.

Would like to know if it is possible to add the tags for a story from Webnovel to the metadata of the created epub on Calibre?

Not a big deal though. Was annoying manually checking and typing each tag out since Webnovel doesn't allow copy and paste. Not a make or break - just for organisational purposes. Still enjoying reading them on the device of my choice.

**Comment by JimmXinu** [comment]
The adapter for webnovel.com already collects `sitetags` and includes them in the titlepage by default.

If you mean you'd like them auto-populated into Calibre's Tags column, you do that with a setting in `personal.ini` (under the FFF config tab of the same name):

```
[www.webnovel.com]
add_to_include_subject_tags: ,sitetags
```

If that isn't what you mean, please provide a story URL that has these tags and describe where/what they are--I don't read that site.

**Comment by Shanakthra** [comment]
I've tried using the solution you gave above, but it hasn't outputted the tags I was looking for. My humble apologies for being vague in the post earlier. 

For my example I will use the story found at: 
https://www.webnovel.com/book/16988982106183705/Battle-Ready-(Pokemon-Fanfic)

On the site, the tags for the story are "Action", "Pokemon" and "Adventure"
However, when the plugin is used in Calibre, the tags it manages to get and populate the metadata for the epub are "Anime & Comics", "Fanfiction", and "In-progress"

Hope this helps clarify what I was referring to

**Comment by JimmXinu** [comment]
Okay, the site apparently changed at some point.  Thanks for pointing out the problem.

Fixed in ebd77e5c5240e3ba971cfeb5608b5eeb4743513e  Test version up in the [usual place](https://www.mobileread.com/forums/showthread.php?p=3084025#post3084025).
