### ISSUE TITLE
Fanfic fare issue

### ISSUE THREAD

**Issue by dr361** [JimmXinu/FanFicFare#496]
Hi I downloaded fanficfare forCalibre  for the first time and it didn’t show the plugin in the menu at the top like it supposed to what did I do wrong? I just clicked it on get plug-ins and it downloaded it but I can’t launch it. Please Help I am not the best at computer coding so I need help. Thank you

**Comment by JimmXinu** [comment]
Make sure you restarted Calibre after installing the plugin.

Go into Calibre's Preferences -> Toolbar & Menus settings to add FanFicFare where you'd like it.  "Main Toolbar" is the row of icon buttons at the top.  If you have too many of those to fit on the screen there should be a button of some kind at the right edge to show the hidden ones.

Be aware that 'Main Toolbar while Device is connected' is *only* while a device is connected.

Here's a [link](https://www.mobileread.com/forums/showthread.php?t=118680) for some more info about using plugins.

**Comment by dr361** [comment]
That was the problem thank you

Sent from my iPhone

On Jun 6, 2020, at 2:39 PM, Jim Miller <notifications@github.com> wrote:

﻿
Closed #496.
