### ISSUE TITLE
FanficAuthors.net Error parsing metadata

### ISSUE THREAD

**Issue by cyrix22** [JimmXinu/FanFicFare#497]
I was trying to get some stories from  [FanficAuthors.net](https://fanficauthors.net) and found that some of the stories failed to download.

After comparing with some stories that did download properly, i figured that if the genre is blank or is left empty by the author, FanFicFare has an error that results in a failed download.

However, i could be wrong as that is the only noticeable difference with the stories that successfully downloaded.

This is the error message :
Status : Error
Title : Unknown
Author : Unknown
Comment : Error parsing metadata: 'https://jeconais.fanficauthors.net/Chances/'
URL : https://jeconais.fanficauthors.net/Chances/

These are the list of stories that i couldn't get :
[https://jbern.fanficauthors.net/The_Inner_Eye_of_Harry_Potter/](https://jbern.fanficauthors.net/The_Inner_Eye_of_Harry_Potter/)
[https://jbern.fanficauthors.net/The_Lie_Ive_Lived/](https://jbern.fanficauthors.net/The_Lie_Ive_Lived/)
[https://jbern.fanficauthors.net/To_Fight_the_Coming_Darkness/](https://jbern.fanficauthors.net/To_Fight_the_Coming_Darkness/)
[https://jbern.fanficauthors.net/Turn_Me_Loose_A_Harry_Potter_Adventure/](https://jbern.fanficauthors.net/Turn_Me_Loose_A_Harry_Potter_Adventure/)
[https://jbern.fanficauthors.net/Unlikely_Allies/](https://jbern.fanficauthors.net/Unlikely_Allies/)
[https://jeconais.fanficauthors.net/Chances/](https://jeconais.fanficauthors.net/Chances/)
[https://kinsfire.fanficauthors.net/Masquerade/](https://kinsfire.fanficauthors.net/Masquerade/)
[https://kinsfire.fanficauthors.net/The_Last_Straw/](https://kinsfire.fanficauthors.net/The_Last_Straw/)

**Comment by JimmXinu** [comment]
Thanks for catching that and tracing it down so precisely.  Fixed in fa784d58f9dbb981e44adc4905590fce16600e9c

Test version up.
