### ISSUE TITLE
Two new Possible issues that I'm experiencing

### ISSUE THREAD

**Issue by LunaNoctus** [JimmXinu/FanFicFare#499]
'NoneType' object has no attribute 'a'

I get this when I try to download things from the old site and I get this (included in the image) on the new front-end, if this can be fixed then that'd be great but I might be an isolated incident 

![4B4CBC82-8ADA-4F35-9AEF-215003CDC356](https://user-images.githubusercontent.com/66657181/84101170-037def80-a9d3-11ea-979c-d0918da960df.jpeg)

**Comment by JimmXinu** [comment]
As of late November 2019, the web service version is shutdown.  See the [Wiki Home](https://github.com/JimmXinu/FanFicFare/wiki#web-service-version) page for details.
