### ISSUE TITLE
Request for Apply All option when encountered Stories already in Anthology message

### ISSUE THREAD

**Issue by ghus3rz** [JimmXinu/FanFicFare#501]
![Calibre_fff_skip_anthology](https://user-images.githubusercontent.com/60832011/86529611-8d42af00-bee4-11ea-9f71-1deb8580c18b.PNG)

Hi
Is it possible if when come across this messages, there is option for "Apply All" when retrieving the metadata? For me, the context would be is, I would like to Skip All whenever the pop up messages occurs during the retrieve metadata as I can check skipped stories after job is done if I want to do something different with a particular stories 

Thanks

**Comment by JimmXinu** [comment]
That's a standard yes/no question dialog that doesn't have an option for additional buttons.  So adding a third option would require a fair bit of code.

In FFF config, under _Check for existing Series Anthology books_ there's also _Reject Without Confirmation_.  That sounds like it meets your stated use case?

**Comment by ghus3rz** [comment]
oh cool . I missed that option. Then should be ok .
Thanks for the info
