### ISSUE TITLE
Support for syosetu.com and novel18.syosetu.com

### ISSUE THREAD

**Issue by Miraihi** [JimmXinu/FanFicFare#506]
I'm not sure if I'm the only one who reads web novels in Japanese, but a support for that site is a must for any web novel parser in my humble opinion.

Examples:
http://ncode.syosetu.com/n6006cw/
http://novel18.syosetu.com/n4100bm/

**Comment by JimmXinu** [comment]
From FAQs: [Please add site XYZ to FanFicFare?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#please-add-site-xyz-to-fanficfare)

**Comment by praschke** [comment]
This can be closed.
