### ISSUE TITLE
Fanficfare is down

### ISSUE THREAD

**Issue by Lokpi** [JimmXinu/FanFicFare#514]
I cannot access fanficfare.

**Comment by JimmXinu** [comment]
I am able to get FanFicFare from both `pip` (CLI) and as Calibre plugin.

The FFF web service was [discontinued last year](https://github.com/JimmXinu/FanFicFare/wiki#important-notice-about-web-service-version).

**Comment by Lokpi** [comment]
Thank you. That clears it up for me.
