### ISSUE TITLE
It should be possible to delay fetching chapter titles

### ISSUE THREAD

**Issue by JasonGross** [JimmXinu/FanFicFare#518]
In #517, I've added support for a site that allows fetching the text of all chapters at once.  However, it takes a while for BeautifulSoup to parse so much html (especially when there are tens of thousands of elements on the page), so it would be nice to delay the parsing of the html to the point at which we're downloading the book, rather than just when we're fetching metadata.  It's pretty easy to get a chapter count (just count the number of divs with a particular class, which can be done with a regex or even simpler methods), and it's only slightly trickier to get a chapter count from the metadata page.

Creating a title for each chapter is somewhat tricker, though, so I'd rather just wait to do it until I'm asked to actually get the text for that chapter (or even for the first chapter).  There doesn't seem to be any reason to forbid this, and it seems like it might be as simple as making `getStory` in `base_adapter` indirect through `get_chapters` (which I can then override to perform the title computation the first time it's called).  It's also possible there's a better way to do this.

**Comment by JimmXinu** [comment]
Request is specific to PR #517 for glowfic.com, which is a poor fit for FFF.
