### ISSUE TITLE
Issue with webnovel - invalid URL

### ISSUE THREAD

**Issue by Shanakthra** [JimmXinu/FanFicFare#520]
Currently experiencing an issue when trying to add novels from webnovel.com to the Calibre library. When trying to download a book, after entering the book URL into the pop-up box (eg. https://www.webnovel.com/book/game-of-thrones%3A-the-prideful-one._17509790806343405), the plugin does not download the book and returns "No valid story URLs entered"

Not sure if this is with regards to the change in how webnovel adds the story name to the URL now, compared to earlier when the URL just had the story numerical ID to identify the book. 

Please check when you have time

**Comment by JimmXinu** [comment]
Test versions in the usual places.  This fix works for me, but I don't read that site.

**Comment by JimmXinu** [comment]
Assumed fixed.
