### ISSUE TITLE
Make an semi-official google colab that can run this.

### ISSUE THREAD

**Issue by S10MC2015** [JimmXinu/FanFicFare#522]
This will make it so that people can run the command line version of this on the go.

ex https://colab.research.google.com/gist/S10MC2015/4237d37eeb23c6df198fee607b5761c3/fanficfare.ipynb

(I am not sure if this is violating colab ToS tho)

**Comment by JimmXinu** [comment]
I'm not particularly interested in supporting it as a run environment myself.

But it looks like it shouldn't be any more complicated than:

1. Go to https://colab.research.google.com/
1. New Notebook -- requires Google account
1. `!pip install FanFicFare`
1. `!fanficfare '<storyUrl>'`
1. Wait.  Possibly a long time.
1. Download the output from Files.

If you'd like to make a Wiki page here for others to follow, that's fine.    

Additional possible considerations: 
- installing `PIL`/`Pillow`(?) for image processing and 
- `personal.ini` file
- setting 'local' datetime?
- actually downloading the ebook on ipad--I can't figure it out; it just works in Android and Windows.
