### ISSUE TITLE
How do I make a config file?

### ISSUE THREAD

**Issue by KirbyFan102** [JimmXinu/FanFicFare#525]
I want to configure the default download location, but I don't know how to make a config file. Or where to put it, for that matter.
Actually, I think it might be useful to have a file with an example of what a generic config file for FanFicFare looks like, the same way Gallery-dl has one

**Comment by JimmXinu** [comment]
See [the FanFicFare INI File wiki page](https://github.com/JimmXinu/FanFicFare/wiki/INI-File).
