### ISSUE TITLE
There doesn't appear to be any way to alter the default download directory

### ISSUE THREAD

**Issue by KirbyFan102** [JimmXinu/FanFicFare#527]
At least in the command line version. I've checked the wiki as best as I could, and used the -h option. There was nothing that seemed to allow you to point to your desired download location. I don't think most people want their user folder getting clogged with hundreds of fanfics and having to go through the hassle of moving them every time.

**Comment by Edocsil** [comment]
That's what your personal.ini file is for..

```## python string Template, string with ${title}, ${author} etc, same as titlepage_entries
## Can include directories.
#output_filename: books/${title}-${siteabbrev}_${storyId}${formatext}
#output_filename: books/${formatname}/${siteabbrev}/${authorId}/${title}-${siteabbrev}_${storyId}${formatext}
output_filename: ${title}-${siteabbrev}_${storyId}${formatext}

## Make directories as needed.
make_directories: true

**Comment by KirbyFan102** [comment]
Is that mentioned anywhere on the wiki?

**Comment by Edocsil** [comment]
> Is that mentioned anywhere on the wiki? And how can I use this to alter the default directory?

Indirectly. In the FAQ it tells you how to configure the plugin, and links you to the defaults file which explains every option available. I guess it should be answered directly.

All you need is to have a personal.ini file in any of the folders FFF will look for with the options you want.

This is an example of my output configuration. The file is on ~/.fanficfare/personal.ini.

```
[archiveofourown.org]
output_filename: storage/downloads/ePubs/Fanficfare/AO3/${title} - ${author}${formatext}
use_view_full_work:true

[fanfiction.net]
output_filename: storage/downloads/ePubs/Fanficfare/ffnet/${title} - ${author}${formatext}

**Comment by KirbyFan102** [comment]
So you change the default directory by changing the output filename for the file? That's... not intuitive at all. Okay.
