### ISSUE TITLE
[bug?] Fanficfare open an identification prompt even if id/password are present in the personal.ini file

### ISSUE THREAD

**Issue by jeancinq** [JimmXinu/FanFicFare#528]
With the Calibre (version 4.22 for Windows 64bit) plugin version of FanFicFare version 3.21.6:
When downloading some stories, FFF asks for me to identify myself via a prompt, even though my password and id are already present in my personal.ini file. It does download fine after entering those in the prompt.
It only happens with a few stories.
I know it happened multiple times with [this story](https://forums.spacebattles.com/threads/si-archives-draft-7-or-si-army-war-chronicles.854976/ ) and also happened to me with a story on SV, albeit I can't recall the URL for that one.
It's not a critical issue, though it can be somewhat annoying.
Thanks for any help.

**Comment by JimmXinu** [comment]
I don't see that happening and I download from SB & SV regularly.

If you run Calibre in debug mode (under Calibre Preferences dropdown), capture a debug log of the problem happening and post it here, that would help.

**Comment by jeancinq** [comment]
Here is a debug log when it happened: 
[debug_log_09082020.txt](https://github.com/JimmXinu/FanFicFare/files/5047923/debug_log_09082020.txt)
Here is also my personal.ini file (version without my passwords):
[09082020personal.ini.txt](https://github.com/JimmXinu/FanFicFare/files/5047934/09082020personal.ini.txt)

**Comment by JimmXinu** [comment]
You have:
```
[www.forums.spacebattles.com]
username:XXXXXXXX
password:XXXXXXXX

[www.forums.sufficientvelocity.com]
username:XXXXXXXX
password:XXXXXXXX
```

Remove the `www.` from those two section names.  Those sites don't use www in their domain name.
