### ISSUE TITLE
getting errors when downloading from literotica using the Calibre plugin

### ISSUE THREAD

**Issue by nzall** [JimmXinu/FanFicFare#529]
I'm getting the below error when attempting to download a series from Literotica. Dave from Grrl Power recommended this plugin in a recent comment annotation (found at https://grrlpowercomic.com/archives/comic/grrl-power-866-rooftop-rally/#comments, at the bottom of the annotation), but either I'm doing something incredibly simply wrong or there's a bug in the Calibre plugin. Note that I haven't changed anything about the default settings of both Calibre and FFF.

Status
Title
Author
Comment
URL
Error
Unknown
Unknown
u'rejecturls'
https://www.literotica.com/s/upon-a-savage-shore-ch-01

Note: when I try to edit the reject URLs list, I'm getting the error

calibre, version 4.22.0
ERROR: Unhandled exception: <b>KeyError</b>:u'rejecturls'

calibre 4.22  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: FanFicFare (3, 22, 0)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.config", line 685, in show_rejectlist
  File "calibre_plugins.fanficfare_plugin.config", line 210, in get_list
  File "calibre_plugins.fanficfare_plugin.config", line 142, in _get_listcache
  File "calibre_plugins.fanficfare_plugin.prefs", line 258, in __getitem__
KeyError: u'rejecturls'

**Comment by ggould256** [comment]
FYI:  In the calibre database, updating the preferences -> namespaced:FanFicFarePlugin:settings item to have a `rejecturls: [],` in it solves this problem.

So the problem is probably a failure to create a key in the preferences if it is not already present.

**Comment by nzall** [comment]
@ggould256 Thanks for the advice. Where exactly do I update this?

**Comment by JimmXinu** [comment]
This is a bug.  

I've released a new version with a fix, your Calibre will be able to see it after a while.  Not sure how long that takes lately.  You can manually install it from [here](https://www.mobileread.com/forums/showthread.php?t=259221) if you want it immediately.

**Comment by nzall** [comment]
thanks for the quick fix. I'm a programmer myself, so I took the liberty of manually editing the plugin zip file and adding the fix myself. I assume that once the plugin is updated on the Calibre front, it'll either automatically overwrite it or I can force it to overwrite?

**Comment by JimmXinu** [comment]
Calibre doesn't do automatic updates, but it will eventually alert you that there's a newer plugin version and prompt you to install it.

**Comment by nzall** [comment]
Thanks. one last question that doesn't exactly have to do with this plugin, but I didn't want to create an entire issue for it: if I have jobs running when Calibre exits, do they automatically get picked back up and continued where they left off when I next start Calibre again? I accidentally started 2 long running fanfic downloads right before I wanted to go to bed...
