### ISSUE TITLE
wuxiaworld.co incomplete chapter collection?

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#531]
There is a report of incomplete chapter lists collected for wuxiaworld.co:

https://www.mobileread.com/forums/showthread.php?p=4023579&postcount=4413

@teffalump, can you look into that, since you touched that code last?

**Comment by teffalump** [comment]
Yeah, can confirm that it is happening. That specific story actually has a missing chapter (73) on the site, so it was breaking my duplication check. I'll put a fix in.

**Comment by teffalump** [comment]
Should be fixed in #532

**Comment by JimmXinu** [comment]
I merged #532 in, but I'm still only seeing up to "Chapter 626 – How Do You Know That?" in the collected chapter list, while the site shows up to "Chapter 1418, Dragon Bone Sword"?

**Comment by teffalump** [comment]
Fixed in #533; Sorry about all the fixes... I seem to have rushed the coding.

**Comment by JimmXinu** [comment]
Thanks for your help!
