### ISSUE TITLE
Wuxiaworld.co is giving errors

### ISSUE THREAD

**Issue by aditseng** [JimmXinu/FanFicFare#534]
'NoneType' object has no attribute 'h1' when trying to download https://www.wuxiaworld.co/Wu-Dong-Qian-Kun/ or any other

**Comment by JimmXinu** [comment]
Already fixed, will be in the next release.

If you don't want to wait for the next release, I've posted a test version of the plugin here:
http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025

Test version of CLI for pip install:  You'll have to get it from the
testpypi repository.  This works for me on Debian:

`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`
