### ISSUE TITLE
Error with fiction.live

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#538]
@HazelSh, there's a [report on the mobile read forum thread](https://www.mobileread.com/forums/showthread.php?p=4030714&postcount=4477) about an error with fiction.live.

Can you look into that?

For my reference, fiction.live support was added in PR #535.

**Comment by dakswiggin** [comment]
Issue lies in how 'nextLive' time formatted from feed's timestamp. In case above once story goes live it can be downloaded.
For other story FictionLive api feed is https://fiction.live/api/node/36CseBiWSq6ZwCiM4/
Timestamp for nextLive is 1599518460000.
Adapted transforms it to '\xc2\xe5\xf0 08, 2020 at 01:41' which i believe causes error with conversion to utf - ''utf8' codec can't decode byte 0xc2 in position 0: invalid continuation byte'.

**Comment by cryzed** [comment]
> Adapted transforms it to '\xc2\xe5\xf0 08, 2020 at 01:41' which i believe causes error with conversion to utf - ''utf8' codec can't decode byte 0xc2 in position 0: invalid continuation byte'.

Not sure what you mean by "Adapted" here. I tested downloading this story with the fanficfare CLI (master) and it worked without issues.

**Comment by dakswiggin** [comment]
Sorry, typo. Meant adapter.
Yes, once 'nextLive' time changed (e.g. as pointed above story goes live) GUI version downloads story  https://fiction.live/stories/Descendant-of-a-Demon-Lord/SBBA49fQavNQMWxFT ok.

Btw, latest official release for CLI is 3.22.0, GUI 3.22.1, support for Fiction.live was added in beta releases later.

**Comment by cryzed** [comment]
> Btw, latest official release for CLI is 3.22.0, GUI 3.22.1, support for Fiction.live was added in beta releases later.

Latest official release for GUI must be 3.22.6 -- I did not install a test release by hand. And yeah I mentioned that I was using the git master version for the CLI.

I'm not sure how the adapter would turn the timestamp into such a strange date, it's straightforward to turn it into a `datetime` object:

```
user@desktop ~ $ import requests
user@desktop ~ $ data = requests.get('https://fiction.live/api/node/SBBA49fQavNQMWxFT').json()
user@desktop ~ $ data['nextLive']
1599501600000
user@desktop ~ $ from datetime import datetime
user@desktop ~ $ datetime.fromtimestamp(data['nextLive'] / 1000)
datetime.datetime(2020, 9, 7, 20, 0)
```

**Comment by dakswiggin** [comment]
@cryzed 
sorry, seems you're now mixing two stories.
Let me clear a bit - yes, initial report was for https://fiction.live/api/node/SBBA49fQavNQMWxFT but after it was live today issue resolved.
Unreadable unicode symbols above are from https://fiction.live/api/node/36CseBiWSq6ZwCiM4/
Yes, manual execution of code have same results for me - like
>>> import requests
>>> data = requests.get('https://fiction.live/api/node/36CseBiWSq6ZwCiM4/').json()
>>> data['nextLive']
1599518460000L
>>> from datetime import datetime
>>> datetime.fromtimestamp(data['nextLive'] / 1000)
datetime.datetime(2020, 9, 8, 1, 41)
>>> _.strftime("%b %d, %Y at %H:%M %p")
'Sep 08, 2020 at 01:41 AM'
Output with strange timestamp was what i get when added extra debug log (in join_list) to story.py to get list of metadata values and run updated plugin in debug mode via GUI

**Comment by cryzed** [comment]
Alright it's just a mystery to me where you got the `'\xc2\xe5\xf0 08, 2020 at 01:41'` string initially from. The JSON API only seems to deliver an integer here, a timestamp and the Python script shouldn't have turned the timestamp into this string AFAIK. Did this string appear verbatim in the JSON response at some point as the value for `nextLive`?

**Comment by dakswiggin** [comment]
Initial traceback - 
`Traceback (most recent call last):
File "calibre_plugins.fanficfare_plugin.dialogs", line 701, in do_loop
File "calibre_plugins.fanficfare_plugin.fff_plugin" , line 1234, in prep_download_loop
File "calibre_plugins.fanficfare_plugin.fanficfare.story", line 872, in getAllMetadata
File "calibre_plugins.fanficfare_plugin.fanficfare.story", line 785, in getMetadata
File "calibre_plugins.fanficfare_plugin.fanficfare.story", line 654, in doReplacements
File "calibre_plugins.fanficfare_plugin.fanficfare.story", line 503, in join_list`

So I've added simply logger.debug(vallist) (which i expect should return list of metadata values) to fanficfare.story.Story.join_list, packed it as plugin and added to Calibre. Launched Calibre in debug mode, attempted to download story and checked Calibre's debug log where found story metadata values and this particular timestamp.

**Comment by cryzed** [comment]
> Yes, manual execution of code have same results for me - like

So you actually ran the above code snippet (I posted) on your system and you got the same/similar date string back? If so, it's really a mystery how it happened initially. So this issue is invalid, correct? Only the other issue with the `None` error is still relevant?

**Comment by dakswiggin** [comment]
Issue related to Win10 regional settings.
In case regional format is English all ok, in case it's Ukrainian (my native) error with timestamp conversion happens.

**Comment by cryzed** [comment]
Interesting. So this is most likely an issue with [this line](https://github.com/JimmXinu/FanFicFare/blob/36e26b059276aafd4bc13bf4bb211a68be3d6673/fanficfare/story.py#L503) in combination with the Ukrainian locale. So while you found a workaround, the issue is still there.

**Comment by dakswiggin** [comment]
Issue lies within .strftime function and particularly system's datetime locale settings. Please try following snippet (works for me under Win10):

import requests
data = requests.get('https://fiction.live/api/node/36CseBiWSq6ZwCiM4/').json()
data['nextLive']
1599518460000L
from datetime import datetime
datetime.fromtimestamp(data['nextLive'] / 1000)
datetime.datetime(2020, 9, 8, 1, 41)
_.strftime("%b %d, %Y at %H:%M %p")
import locale
locale.setlocale(locale.LC_ALL, "Ukrainian_Ukraine.1252")
'??? 08, 2020 at 01:41 '

I suppose that cyrillic 'Вер 08, 2020 at 01:41' can't be properly parsed.
Explicitly setting locale to en before datetime conversion should resolve issue.

**Comment by cryzed** [comment]
I unfortunately don't have a Windows 10 system to test this on, but I'll trust what you are saying. This seems like an unfortunate combination of Python 2's Unicode handling, Windows 10 being... Windows 10 and the Unicode handling in FanFicFare.

**Comment by JimmXinu** [comment]
> Latest official release for GUI must be 3.22.6 -- I did not install a test release by hand. And yeah I mentioned that I was using the git master version for the CLI.

cryzed was correct--current released FFF plugin version is v3.22.1.  Current test version is v3.22.9.  If you have v3.22.6 installed, somebody installed it from zip file.  FYI, fiction.live is _not_ officially supported yet by FFF--it's still in testing.

Timezones in py2 are a pain due to not actually including any timezones.  I don't remember if py3 is any better.  

My question is why is `join_list()` being called on a date.  And why has this never cropped up before?  Many FFF users are in non-English locales and other adapters convert unixtime successfully.

I don't have time to look into this tonight, but I'll come back to it, since it looks like it may be a general FFF problem and not fiction.live specific.

**Comment by cryzed** [comment]
> cryzed was correct--current released FFF plugin version is v3.22.1. Current test version is v3.22.9. If you have v3.22.6 installed, somebody installed it from zip file. FYI, fiction.live is not officially supported yet by FFF--it's still in testing.

Then I was incorrect. I have 3.22.6 installed in Calibre, but I don't remember installing that by hand -- I was notified about that update by Calibre itself and also installed it that way... strange.

> Timezones in py2 are a pain due to not actually including any timezones. I don't remember if py3 is any better.

AFAIK It's not. Third-party libraries are popular, pendulum, pytz and such. But there was patch to timezone-related stuff to the stdlib sometime, maybe it got better. I luckily only rarely have to deal with that.

> My question is why is join_list() being called on a date. And why has this never cropped up before? Many FFF users are in non-English locales and other adapters convert unixtime successfully.

Yes that seems strange, sounds like the adapter code is doing something strange, but I didn't look too closely. Alternatively maybe Ukrainian users are just rare. I don't think many adapters are calling `datetime.strftime()` themselves, especially with the `%b` format character that turns the current month into a locale-aware name (i.e. "Sep" and such).

> I don't have time to look into this tonight, but I'll come back to it, since it looks like it may be a general FFF problem and not fiction.live specific.

Great to hear.

**Comment by HazelSh** [comment]
> sounds like the adapter code is doing something weird

The adapter is absolutely doing it's own thing with times. Most adapters IIRC call base_adapter.makeDate to parse a string representing the date, but the fiction.live API gives an int timestamp which the adapter has to parse and format. 

Having googled the issue a bit, it seems that python2/windows/unicode is a disaster. I'm not sure what I can do in the adapter to help -- call the function in the context of a different locale is one option. I'll look for more.

**Comment by HazelSh** [comment]
join_list is getting called on a date because there's a date as a string in the metadata (when the story has an upcoming live time). Maybe metadata dates outside of the standard updated/created/published just haven't come up before in other adapters.

**Comment by JimmXinu** [comment]
I was missing that it's a date being put into a site specific metadata entry, not one of the standard dates.  

In fact, `setMetadata('live',...)` is explicitly given a string value, not date object.  The date -> string change is happening in the adapter.  FFF has code for handling date objects in metadata and allowing user config formatting but it's not being used in this case.

I can force the locale by putting:
```
import locale
locale.setlocale(locale.LC_ALL, "Ukrainian_Ukraine.1252")
```
...directly in the plugin code.

Then I do get _Next Live Session: ??? 07, 2020 at 17:41_ on the title page, but not an error.  And nothing I've done, including playing with the example code above, will give me anything for a `%b` month in Uk but `???`.

I do have Win10, and I did install the Ukrainian language.  I wasn't able to try it while actually set to Ukrainian because my keyboard suddenly didn't have the letters I knew. :-)

**At this point, the only solution I have is to simply not use `%b` and [change this line](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/adapters/adapter_fictionlive.py#L151) from `%b %d, %Y at %H:%M %p` to something like `%Y-%m-%d at %H:%M %p` instead.**

I would be curious what happens when @dakswiggin puts `%b` in their `personal.ini` for one of the standard dates.  The defaults are:
```
dateCreated_format:%%Y-%%m-%%d %%H:%%M:%%S
datePublished_format:%%Y-%%m-%%d
dateUpdated_format:%%Y-%%m-%%d
```
(Double `%%` needed for escaping in INI format.)

When I try it while forcing the locale to Uk, I again get `???`.   

If @dakswiggin sees the correct month abbrev, it would be wroth pursuing making `live` a true date with a `live_format` setting to allow user customization.

**Comment by dakswiggin** [comment]
@JimmXinu  Tried to change dateCreated format to 
`%%b, %%d, %%Y %%H:%%M:%%S`
Got ''utf8' codec can't decode byte 0xc2 in position 0: invalid continuation byte' with xenforo adapter and using my native locale.
Probably `live` should better use standard approach like all other date values rather that custom implementation here.

**Comment by JimmXinu** [comment]
That's a bummer that `%b` doesn't work, but I don't know how I'd go about trying to fix it when I can't see it happen.

So, yeah, I think the answer is going to be 'don't use `%b`'.

@HazelSh, making `live` date format configurable is pretty easy, just set the date object in the code instead of calling `.strftime(...)` and add `live_format:%%Y-%%m-%%d at %%H:%%M %%p` after `live_label` in the defaults files.

**Comment by HazelSh** [comment]
OK, will do.

**Comment by JimmXinu** [comment]
New test version posted in [the usual place](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).
