### ISSUE TITLE
fiction.live - certain story URLs are not recognized

### ISSUE THREAD

**Issue by muchtea** [JimmXinu/FanFicFare#541]
Hello and thank you @HazelSh for adding support for the site.
I just came across this issue #https://github.com/kemayo/leech/issues/31 for a different fiction.live-downloader.
There are some stories with 'Sci-fi' instead of 'stories' in the URL and some quest ids start with a '-' and are 20 characters long, which isn't covered by the current regex.

Example stories:
https://fiction.live/Sci-fi/Endless-Journey/-JTOp94O1JnJQ10y557N
https://fiction.live/stories/The-Traveler/-JEdsoZFs11asUSB-SEQ

I think this should work, but better double check that:
`https?://fiction\.live/(Sci-fi|stories|anonkun)/[^/]*/([a-zA-Z0-9]{17}|[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}|[a-zA-Z0-9\-]{20})/?(home)?`

**Comment by HazelSh** [comment]
I swear, every time I start thinking this site is somewhat reasonable, something else turns up. I'll sort this. Thanks for the suggested regex, I may use it.

**Comment by HazelSh** [comment]
As I expected as soon as I saw `Sci-fi`, it's worse than that. 
https://fiction.live/Writing/Side-Quest-Suggestion-Quest/gXKah64TFtZs2fwEd

stories that are old, but not old enough to be in the UUID-id style, have the first tag? genre? in the url. I have no idea where to get an exhaustive list of possible options for these.

I'm gonna write a script to scrape story urls. A brief look at fiction.live/stories doesn't show where the urls are coming from, so this may take a bit.

**Comment by JimmXinu** [comment]
Unless you're trying to collect metadata from it, does it matter what's in the URL other than the story ID?
`https?://fiction\.live/[^/]*/[^/]*/([a-zA-Z0-9]+)`

**Comment by HazelSh** [comment]
Yeah, I suppose it doesn't matter. Still, that's too permissive -- I need to rule out URLs that aren't a story frontpage. I think I've got it now.

I might do that script to scrape URLs anyway, just to see if there's any more surprises waiting.

**Comment by JimmXinu** [comment]
New Test version posted in [the usual place](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).
