### ISSUE TITLE
fiction.live - adding support for multi route stories

### ISSUE THREAD

**Issue by muchtea** [JimmXinu/FanFicFare#543]
@HazelSh  I just tried the calibre plugin and it is working really well, although stories with multiple routes are apparently not supported,

Looking randomly through many quests on that site, it seems that most stories having the multiple routes feature activated don't actually use it at all. The few that do, use it like other stories use the appendix (omake, character info, inventory, etc.).

I think, supporting stories with multiple routes can be done by adding the chapters for each route to the end with 'Route: {title}' after the appendices. That would work well enough for most (maybe all) stories.

The api to get the content for a route chapter is 'https://fiction.live/api/anonkun/route/{route_id}/chapters'. It only needs the route id and no timestamps or story id, unlike the regular chapters. It returns json that can be processed the same way as the other chapters. 

The story metadata from "https://fiction.live/api/node/{s_id}/" contains a dict "routes" with the route ids and titles. I don't think that dict exists if the story has no routes, even if "multiRoute" is true.

Example stories using multiple routes:
https://fiction.live/stories/Is-It-Okay-To-Use-Stealth-Skills-In-A-Dungeon-/GFACwD5vcyTqHcFpz #has a few routes but only one with content, a single short omake
https://fiction.live/stories/RWBY-Parallel-Quest/G6u7NofdZmpKvHaKc #uses it like other quests use the appendix
https://fiction.live/stories/My-Hero-Academia-Quest/SaTyHwb82mshqsJ8n/home  #doesn't have a single actual route, just has it activated for some reason - here the download would work exactly the same as with all stories without multipleRoute set to true

**Comment by muchtea** [comment]
Just found this story with a lot of actually used routes: https://fiction.live/stories/The-Gynarchy/czyGfAtJpRgtzGFmW/home

As it turns out, the routes returned by https://fiction.live/api/node/czyGfAtJpRgtzGFmW/ are not in the same order as they are on actual page: https://fiction.live/stories/The-Gynarchy/czyGfAtJpRgtzGFmW/routesList
And they are also apparently, sometimes, incomplete. According to the metadata returned, there are 116 routes, when it should be 135. No clue why that is a thing.

However using this api url: https://fiction.live/api/anonkun/routes/czyGfAtJpRgtzGFmW/ gets all routes in the correct order (plus timestamps, route titles "t" and subtitles "d" as shown on the webpage - which are apparently not necessarily the same as the ones shown in the story metadata) and it returns all 135 routes.

**Comment by JimmXinu** [comment]
@HazelSh, 

If you do attempt this, you'll probably want to know about these two FFF options (which are on by default):
```
## Apply adapter's normalize_chapterurl() to all links in chapter
## texts, if they match the known pattern(s) for chapter URLs.  As of
## writing, base_xenforoforum, adapter_archiveofourownorg &
## adapter_tthfanficorg implement normalize_chapterurl().
normalize_text_links:true

## Search all links in chapter texts and, if they match any included
## chapter URLs, replace them with links to the chapter in the
## download.  Only works with epub and html output formats.
## normalize_text_links will improve URL matching considerably.
internalize_text_links:true
```

So if you include navigation links in the chapter text that match chapter URLs it has chapters for, FFF will convert them to internal relative links for you.  This sees a lot of use in SV/SB/etc stories.  Look for `internalize_text_links` in `fanficfare/writers/writer_epub.py` and `fanficfare/writers/writer_html.py` if you want to see how it's implemented.

Note, however, that this can conflict with Epub Update, because FFF doesn't update chapters it already has.  So a new link in an old chapter won't appear unless you do Overwrite.

**Comment by HazelSh** [comment]
Unlikely to happen soon, but I'll keep it in mind as a future feature if I find time. It might be more doable in an ebook than I thought, especially with internal links. Thanks @muchtea for the API investigation work.
