### ISSUE TITLE
Add option to skip SSL validation

### ISSUE THREAD

**Issue by t-e-r-m** [JimmXinu/FanFicFare#546]
Adding a `--insecure` flag would be very useful. It would help archiving websites that are about to shut down / die.

**Comment by JimmXinu** [comment]
While I haven't tried it lately, there is the `use_ssl_unverified_context` setting you can set `true` in `personal.ini` in the Calibre Plugin.

Without an example of site that this would be useful for, I'm not inclined to add this feature for no other reason than not being able to test it.

**Comment by t-e-r-m** [comment]
Thanks for the help, I'll try using calibre.

The website that's giving me SSL troubles is http://www.phoenixsong.net

**Comment by JimmXinu** [comment]
Looking at it, I don't think it's implemented completely in the plugin anymore.  However, I've add a "undocumented" `--unverified_ssl` option you can use.  

Test version at:

`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare `

**Comment by JimmXinu** [comment]
FYI, I remembered how `use_ssl_unverified_context` works in the plugin: It only works on updates with Background Metadata checked.

Due to the 'monkey patch' way the unverified context is applied, FFF only does it in the background job and not the main Calibre process.

**Comment by t-e-r-m** [comment]
Thanks a lot for implementing the feature! It works well!

**Comment by NightMachinary** [comment]
@JimmXinu Can you document this feature? It's a nice one, and having in the help of the tool is much better than searching for it in the issues here.
