### ISSUE TITLE
fiction.live: unhashable type: 'dict'

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [JimmXinu/FanFicFare#551]
While experimenting with the new fiction.live support, I found this story that can't be downloaded: https://fiction.live/stories/Star-Wars-Twilight-of-the-Republic/zZMpSXnx8f7RxJnoa

Trying to download the story fails during metadata with status error and comment "unhashable type: 'dict'".

Story dates from early 2017 so I wouldn't be surprised if some remnant of an earlier version of the site's weird API is breaking it.

**Comment by muchtea** [comment]
Same issue mentioned in #547 . Happens due to a typo. Gonna fix that right now.
