### ISSUE TITLE
wuxiaworld.site - strip embedded <style> elements

### ISSUE THREAD

**Issue by ElminsterAU** [JimmXinu/FanFicFare#553]
@Kolbo5 could you please have a look at the wuxiaworld.site adapter and add some code to strip out any <style> elements inside the <body> element? Some epub readers have trouble with that and display the contents of the <style> element as normal text.

**Comment by JimmXinu** [comment]
If that's truly the problem, we should probably make that available for all sites, not just wuxiaworld.site.

Can you provide some example story URLs?  And what epub reader(s) have that issue?

**Comment by ElminsterAU** [comment]
I'm seeing the problem with https://play.google.com/store/apps/details?id=com.flyersoft.moonreader which with over 10 million downloads is one of the more commonly used epub readers on android. 

![image](https://user-images.githubusercontent.com/27037648/93357624-dd92a180-f883-11ea-97bd-4b75435d2f56.png)

As far as I'm aware, it's going to affect all stories on wuxiaworld.site.

Here is one that it definitely happens with: https://wuxiaworld.site/novel/um-sorry-ive-been-reincarnated/
![image](https://user-images.githubusercontent.com/27037648/93357801-116dc700-f884-11ea-8136-6e62de47a756.png)

**Comment by JimmXinu** [comment]
I am also seeing this happen using FBReader and Aldicko Classic Premium on Android.  But not in Calibre's Reader on Win10.

And I can confirm that just dropping `<style> whatever </style>` into chapter text in a different site's epub will show `whatever` as text.  Not ideal.

**Comment by ElminsterAU** [comment]
I can confirm that this seems to be fixed in the latest test version.
