### ISSUE TITLE
Requesting an optional feature for downloading author notes on royalroad.com

### ISSUE THREAD

**Issue by BabelAlexandria** [JimmXinu/FanFicFare#556]
Hello!

If I understand it correctly, it is currently impossible to configure FFF to download author-notes of Royalroad story chapters in addition to the chapters themselves. [[previous discussion link I've managed to find through google]](https://www.mobileread.com/forums/showpost.php?p=3816609&postcount=3274)

>If you post a couple story URLs that show author notes as a site feature (not an author convention), I'll look into it.

Here are some story links and corresponding chapters that showcase this website feature:

* [story 29358](https://www.royalroad.com/fiction/29358/dungeon-crawler-carl) - [A/N for 29358-91](https://www.royalroad.com/fiction/29358/dungeon-crawler-carl/chapter/554343/chapter-91) (Ctrl+F to "Hey all!")
* [story 21178](https://www.royalroad.com/fiction/21178/the-outer-sphere) - [A/N for 21178-222](https://www.royalroad.com/fiction/21178/the-outer-sphere/chapter/446194/chapter-222-bid-high) (Ctrl+F to "Enjoy!")
* [story 31514](https://www.royalroad.com/fiction/31514/the-menocht-loop) - [A/N for 31514-78](https://www.royalroad.com/fiction/31514/the-menocht-loop/chapter/553624/78-gala-ii) (Ctrl+F to "Most recently we've")

Also, using the post — thank y'all for such a versatile and great piece of software.

**Comment by JimmXinu** [comment]
This is certainly doable now that I have some examples.

However, your first example shows author notes both at the beginning _and_ end of the chapter.  I assume you'd like both?

**Comment by BabelAlexandria** [comment]
Oh, I didn't even notice the A/N up there at the top. You are right, of course, it would be reasonable to download all of them, since one could never know which field would a given author use for important information.

_(hope this comment doesn't re-categorise the request as an open issue)_
