### ISSUE TITLE
SIYE works over https as well

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#558]
```
tmp@stitny$ fanficfare https://www.siye.co.uk/siye/viewstory.php?sid=1133
Bad Story URL: (https://www.siye.co.uk/siye/viewstory.php?sid=1133) for site: (www.siye.co.uk) Example: (http://www.siye.co.uk/siye/viewstory.php?sid=1234)
tmp@stitny$
```

The HTTPS URL above works perfectly well, and I guess promoting use of secure connections is The Right Thing™ to do, isn’t it?

**Comment by JimmXinu** [comment]
Except when the https breaks later.  See 2590ec564f950af226990c3a901ae58c8579c10e and https://www.phoenixsong.net/ right now...

**Comment by mcepl** [comment]
Yes, quality of support for some fanfiction sites is horrible (I have Firefox in strict HTTPS-only mode and number of websites I have to add to my exceptions list is quite exceptional). Somehow, if we could support both (and **non-default** behaviour would be to try http if https fail)?

**Comment by mcepl** [comment]
And yes, fix in 34535be works perfectly. Thank you.

**Comment by JimmXinu** [comment]
I added an 'undocumented' CLI option `--unverified_ssl` in response to #546.  You may use that, but I offer no support if it burns down your house. :-)

**Comment by mcepl** [comment]
> I added an 'undocumented' CLI option `--unverified_ssl` in response to #546. You may use that, but I offer no support if it burns down your house. :-)

That’s all what I expect. Thank you.
