### ISSUE TITLE
Can't add a particular Royal Road URL/Book...

### ISSUE THREAD

**Issue by chrisric** [JimmXinu/FanFicFare#561]
Hi,

I have never had an issue adding Royal Road books in the past and infact can add all but the below one even today. Not sure why.

https://www.royalroad.com/fiction/7696/two~worlds

Apologies if I missed something obvious.

Thanks.

-Chris

Debig Log:

`EpubMerge: DEBUG: 2020-09-30 08:55:35,263: calibre_plugins.epubmerge.epubmerge_plugin(158): macmenuhack file_path:/Users/chrisric/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
FFF: DEBUG: 2020-09-30 08:55:35,279: calibre_plugins.fanficfare_plugin.fff_plugin(210): Plugin FanFicFare macmenuhack file_path:/Users/chrisric/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 3.48  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: EpubSplit (2, 9, 0) && EpubMerge (2, 11, 0) && FanFicFare (3, 23, 8) && Generate Cover (1, 5, 25) && EpubCheck (0, 2, 3) && Count Pages (1, 10, 0) && Modify ePub (1, 4, 1)
calibre 3.48  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: EpubSplit (2, 9, 0) && EpubMerge (2, 11, 0) && FanFicFare (3, 23, 8) && Generate Cover (1, 5, 25) && EpubCheck (0, 2, 3) && Count Pages (1, 10, 0) && Modify ePub (1, 4, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.80] main UI initialized...
[1.80] Hiding splash screen
[1.81] splash screen hidden
[1.81] Started up in 1.81 seconds with 159 books
FFF: DEBUG: 2020-09-30 08:57:26,430: calibre_plugins.fanficfare_plugin.fff_plugin(989): FanFicFare v3.23.8
FFF: DEBUG: 2020-09-30 08:57:26,565: calibre_plugins.fanficfare_plugin.fff_plugin(1103): url:https://www.royalroad.com/fiction/7696
FFF: DEBUG: 2020-09-30 08:57:26,592: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_royalroadcom(151): URL: https://www.royalroad.com/fiction/7696
FFF: DEBUG: 2020-09-30 08:57:26,593: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1152): #####################################
pagecache(GET) MISS: https://www.royalroad.com/fiction/7696
FFF: DEBUG: 2020-09-30 08:57:30,595: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1010): Encoding:utf8
FFF: DEBUG: 2020-09-30 08:57:32,811: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1152): #####################################
pagecache(GET) MISS: https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png
FFF: DEBUG: 2020-09-30 08:57:33,159: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_royalroadcom(223): stars:(4.527905)
FFF: DEBUG: 2020-09-30 08:57:33,174: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1152): #####################################
pagecache(GET) MISS: https://www.royalroadcdn.com/covers-full/7696-two-worlds.jpg
FFF: ERROR: 2020-09-30 08:57:33,301: calibre_plugins.fanficfare_plugin.dialogs(738): Exception: {u'publisher': None, u'series': u'', u'comments': u'', u'collision': u'Update EPUB if New Chapters', u'site': 'www.royalroad.com', u'author': [u'Unknown'], u'showerror': True, u'uniqueurl': u'https://www.royalroad.com/fiction/7696[None-None]', u'end': None, u'added': False, u'status': u'Error', u'pubdate': None, u'comment': u'list.remove(x): x not in list', u'author_sort': [u'Unknown'], u'calibre_id': None, u'good': False, u'url': u'https://www.royalroad.com/fiction/7696', u'listorder': 0, u'begin': None, u'title': u'Unknown'}:list.remove(x): x not in list
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 725, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1188, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1070, in get_story_metadata_only
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 297, in getStoryMetadataOnly
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 381, in doExtractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_royalroadcom", line 234, in extractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 474, in setCoverImage
  File "calibre_plugins.fanficfare_plugin.fanficfare.story", line 1287, in addImgUrl
ValueError: list.remove(x): x not in list
`

**Comment by JimmXinu** [comment]
That's an interesting corner case.  The code recently added for the `dedup_img_files` option (#550) interacts badly when a `make_firstimage_cover` image is replaced by an explicit cover image.  

Usually, explicit cover images are added before any possible first image, but that story has an image in the description and `adapter_royalroadcom.py` happens to set the description before the cover image.
