### ISSUE TITLE
Problems with downloading some stories on Fiction.Live

### ISSUE THREAD

**Issue by IceCold1039** [JimmXinu/FanFicFare#564]
When I try to download these urls, 
https://fiction.live/stories/Golden-Empire-Chapter-1-Authority/c3ea820a-a8e6-4917-8067-f04d7eeca1ab/home 
https://fiction.live/stories/Golden-Empire-Chapter-2-Purpose/a9b355a5-802d-4ac4-9afc-a89666375ac6/home
https://fiction.live/stories/Golden-Empire-Chapter-3-Ruin/5426e7f3-64d7-4eb5-8736-2299c7feddf8/home

produces an error with the comment contentRating.

This story, https://fiction.live/stories/Iron-A-Tief-s-Quest/fSu8BbLHw3nHQfnXn/home
 gives out the comment, unhashable type: 'dict

@HazelSh

**Comment by HazelSh** [comment]
The contentRating error should be fixed in the latest test version -- please update to that version. 

I'll look into the other error.

**Comment by muchtea** [comment]
That second error should already be fixed as well in the latest test version.

**Comment by JimmXinu** [comment]
Agreed, I don't see either of these errors in the latest test version.
