### ISSUE TITLE
Allow logged-in download at Spacebattles?

### ISSUE THREAD

**Issue by rdragonrydr** [JimmXinu/FanFicFare#569]
I just noticed that stories in the unlisted fiction section at SB cannot be archived because they don't appear unless a user is logged in. Can this be added to the plugin?

Here is an example:
https://forums.spacebattles.com/threads/small-medium-litrpg.699457/

**Comment by JimmXinu** [comment]
Set `username`, `password` and `always_login:true` in `personal.ini`:
```
[forums.spacebattles.com]
username:yourusername
password:yourpassword
always_login:true
```

Unlike other sites, SB/SV, etc doesn't give us any indicator when a story exists, but requires login.

However, I do see that that info is missing from `defaults.ini`.
