### ISSUE TITLE
[FR] Support series pages on archive of Our Own

### ISSUE THREAD

**Issue by NightMachinary** [JimmXinu/FanFicFare#570]
E.g., https://archiveofourown.org/series/1087368 .

**Comment by JimmXinu** [comment]
I just answered [this in the discussion group](https://groups.google.com/forum/#!topic/fanfic-downloader/xJm0nmO7duM) this week.  Coincidence?

> The FanFicFare Calibre plugin already has a feature to create an anthology from AO3 series.  You invoke it with the 'Get Story URLs from Web Page' feature, enter the series URL and click the 'For Anthology Epub' button.  You must have Calibre and both the FanFicFare and EpubMerge plugins.
> 
> FFF CLI doesn't have the anthology feature to make a single epub, but you can still download the series:
> 
> For FFF CLI, you can run fanficfare with `-l` and the series URL to get the list of story URLs or `--download-list` to both get the story URLs and download them.
