### ISSUE TITLE
Email filtering issue?

### ISSUE THREAD

**Issue by rdragonrydr** [JimmXinu/FanFicFare#574]
Is there a way to turn off the "email protection" feature that removes email addresses from archived stories?
In several of my archives, it has falsely triggered or has removed "made up" emails that were story-relevant.

I can't seem to find anything relating to this in personal.ini, the default plugins config, or the settings.
Is it possible to turn off this feature?

**Comment by JimmXinu** [comment]
FFF doesn't do that.  It's the site.

I've only seen it happen with SB/SV where it's a security feature to stop programs--technically, just like FFF--from harvesting addresses.  Since I'm not implementing support for a javascript engine to work around it, there isn't anything to be done.
