### ISSUE TITLE
Not working on ficbook.net

### ISSUE THREAD

**Issue by rebel42** [JimmXinu/FanFicFare#575]
Hi! After last update fanficfare stopped to update already existing story from site "ficbook.net" and don't download a new story from this sire either. 
When a try to download there is an error in fanficfare journal :
"
Status - error
Name - Unknown
Author  Unknown
Coomecnt  'NoneType' object has no attribute '__getitem__'
URL  https://www.ficbook.net/readfic/3432002" 

How can i avoid this error? maybe to add something in personal.ini

**Comment by JimmXinu** [comment]
The site changed.  Already fixed in 78fa57a63c6ea3e33a298bd92d9e4d8110feb58a

[Test version plugin here](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).
