### ISSUE TITLE
FFF not seeing Threadmarks

### ISSUE THREAD

**Issue by DarrigoTR** [JimmXinu/FanFicFare#576]
I'm just getting the first chapter of a story unless there are links in the first post, in which case it loads the links target after the first post. This seems to be a Xenforo problem.

**Comment by JimmXinu** [comment]
Already fixed in 1ca7036594a30bbd650f7b0bacb4259ef48d756b

> I've posted a test version of the plugin here:
> http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025
>
> Test version of CLI for pip install:  You'll have to get it from the testpypi repository.  This works for me on Debian:
>> pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare

**Comment by dakswiggin** [comment]
Sorry but test CLI version for some reason works only for SB. For SV fic update (https://forums.sufficientvelocity.com/threads/calibration-bahhscq-sanctioned.61266/threadmarks) i'm getting epub with only 4 chapters where only first is really have a threadmark (and is first post in thread) and other 3 seems not even threadmarked (epub https://drive.google.com/file/d/1vdeb0YcyAxRWFC1o7azv24Kgn3EY_JzC/view?usp=sharing).

**Comment by JimmXinu** [comment]
I just installed it from https://testpypi.python.org/pypi and test and that story downloaded fine for me. FFF Version:3.24.9

It's possible that only a subset of SV's servers have been updated and for some reason you hit an older one.  Or perhaps they're rolling out another change and I'm the one seeing an older version.

If it's still happening tomorrow, let me know.

**Comment by dakswiggin** [comment]
Sorry - you've got all 33+ chapters?

**Comment by JimmXinu** [comment]
All 40, yes.

**Comment by JimmXinu** [comment]
Still working for me this morning.

**Comment by dakswiggin** [comment]
Yes, resolved by itself today too. Thanks
