### ISSUE TITLE
[FR] Add support for patreon.com

### ISSUE THREAD

**Issue by NightMachinary** [JimmXinu/FanFicFare#577]
An example story on patreon:

https://www.patreon.com/theblankcanvas/posts?filters[tag]=A%20Cadmean%20Victory

**Comment by JimmXinu** [comment]
I am not interested in adding support for paid content.  

I made some comments last year in #440 about my views on legalities and why I want to avoid them as much as possible.

**Comment by NightMachinary** [comment]
[**@JimmXinu**](https://github.com/JimmXinu) commented on [Oct 28, 2020, 7:25 PM GMT+3:30](https://github.com/JimmXinu/FanFicFare/issues/577#issuecomment-718029923 "2020-10-28T15:55:15Z - Replied by Github Reply Comments"):
> I am not interested in adding support for paid content.
> 
> I made some comments last year in [#440](https://github.com/JimmXinu/FanFicFare/issues/440) about my views on legalities and why I want to avoid them as much as possible.

Actually, this is free. I think it won't fit into fanficfare though; It has that ridiculous Cloudflare anti-DDOS that blocks tools like curl. Feel free to close this issue.
