### ISSUE TITLE
Spacebattles download refuses to download from threadmarks

### ISSUE THREAD

**Issue by Randomuser131** [JimmXinu/FanFicFare#578]
While trying to download [Manager](https://forums.spacebattles.com/threads/manager-worm.280060/),  FFF downloads only the first 2 chapters, even though it has a threadmarks covering all chapters.

**Comment by Edocsil** [comment]
Works fine for me using FFF Version:3.24.9. Are you using the latest test version? Xenforo had some changes recently that broke the adapter.

**Comment by JimmXinu** [comment]
Dup of #576
