### ISSUE TITLE
Only first post appears for download at SpaceBattles?

### ISSUE THREAD

**Issue by rdragonrydr** [JimmXinu/FanFicFare#579]
I was attempting to archive https://forums.spacebattles.com/threads/here-comes-the-new-boss-nothing-like-the-old-boss-worm-au.853195/, but for some strange reason it will only fetch the first post, and nothing else. I don't think anything's timing out, and the thread has threadmarks, but it's still not working.

Here's the log:

Download 1 FanFiction Book(s)
FFF: INFO: 2020-10-28 22:24:35,840: calibre_plugins.fanficfare_plugin.jobs(53): FanFicFare v3.23.0
FFF: INFO: 2020-10-28 22:24:35,840: calibre_plugins.fanficfare_plugin.jobs(57): Adding jobs for URLs:
FFF: INFO: 2020-10-28 22:24:35,840: calibre_plugins.fanficfare_plugin.jobs(59): https://forums.spacebattles.com/threads/here-comes-the-new-boss-nothing-like-the-old-boss-worm-au.853195/
FFF: INFO: 2020-10-28 22:24:57,332: calibre_plugins.fanficfare_plugin.jobs(95): Logfile for book ID None (Here Comes The New Boss)
FFF: INFO: 2020-10-28 22:24:57,333: calibre_plugins.fanficfare_plugin.jobs(96): url:(https://forums.spacebattles.com/threads/here-comes-the-new-boss-nothing-like-the-old-boss-worm-au.853195/) id:(None)
FFF: INFO: 2020-10-28 22:24:36,942: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(426): url: https://forums.spacebattles.com/threads/here-comes-the-new-boss-nothing-like-the-old-boss-worm-au.853195/
FFF: DEBUG: 2020-10-28 22:24:36,942: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1139): #####################################
pagecache(GET) HIT: https://forums.spacebattles.com/threads/here-comes-the-new-boss-nothing-like-the-old-boss-worm-au.853195/
FFF: DEBUG: 2020-10-28 22:24:36,945: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1007): Encoding:utf8
FFF: INFO: 2020-10-28 22:24:36,946: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(431): use useurl: https://forums.spacebattles.com/threads/here-comes-the-new-boss-nothing-like-the-old-boss-worm-au.853195/
FFF: INFO: 2020-10-28 22:24:37,986: calibre_plugins.fanficfare_plugin.jobs(246): write to /tmp/calibre_3.21.0_tmp_tTOCMA/fanficfare_JfRgRb/Here Comes The New Boss-HowlingGuardian-ZfMNem.epub
FFF: INFO: 2020-10-28 22:24:37,987: calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer(182): Save directly to file: /tmp/calibre_3.21.0_tmp_tTOCMA/fanficfare_JfRgRb/Here Comes The New Boss-HowlingGuardian-ZfMNem.epub
FFF: DEBUG: 2020-10-28 22:24:37,988: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(670): Getting chapter text for: https://forums.spacebattles.com/threads/853195/ index: 0
FFF: DEBUG: 2020-10-28 22:24:37,988: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(706): Not using reader mode
FFF: DEBUG: 2020-10-28 22:24:37,988: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1149): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/853195/
FFF: DEBUG: 2020-10-28 22:24:55,485: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1007): Encoding:utf8
FFF: INFO: 2020-10-28 22:24:56,412: calibre_plugins.fanficfare_plugin.fanficfare.writers.writer_epub(362): Saving EPUB Version 2.0
FFF: DEBUG: 2020-10-28 22:24:56,948: calibre_plugins.fanficfare_plugin.wordcount(60): 	Word count - count_words method:3057
FFF: INFO: 2020-10-28 22:24:56,948: calibre_plugins.fanficfare_plugin.jobs(313): get_word_count:3057
FFF: INFO: 2020-10-28 22:24:56,950: calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer(182): Save directly to file: /tmp/calibre_3.21.0_tmp_tTOCMA/fanficfare_JfRgRb/Here Comes The New Boss-HowlingGuardian-ZfMNem.epub
FFF: INFO: 2020-10-28 22:24:56,952: calibre_plugins.fanficfare_plugin.fanficfare.writers.writer_epub(362): Saving EPUB Version 2.0

FFF: INFO: 2020-10-28 22:24:57,334: calibre_plugins.fanficfare_plugin.jobs(100): 
Download Results:
Add https://forums.spacebattles.com/threads/here-comes-the-new-boss-nothing-like-the-old-boss-worm-au.853195/ Download epub completed, 1 chapters.

FFF: INFO: 2020-10-28 22:24:57,334: calibre_plugins.fanficfare_plugin.jobs(124): 
Add
https://forums.spacebattles.com/threads/here-comes-the-new-boss-nothing-like-the-old-boss-worm-au.853195/

**Comment by JimmXinu** [comment]
Site changed.  Already fixed in test versions and previously reported in #576.  And #578.
