### ISSUE TITLE
Unable to download wattpad reading lists anymore

### ISSUE THREAD

**Issue by outlaws2330** [JimmXinu/FanFicFare#582]
There's an issue now that doesn't allow multiple books from one reading list to be downloaded simultaneously anymore. Before I was able to download a max of 30 books at once from my reading list but not anymore.

**Comment by JimmXinu** [comment]
If individual book downloads still work, then it isn't anything in the FFF code.  

It is entirely possible that the site is deliberately preventing you from doing multiple simultaneous downloads--other sites do.

If you can point to individual downloads that are failing, please include story URL(s).

**Comment by outlaws2330** [comment]
I checked and I can still download individual books, I guess wattpad updated the site and its preventing it. Now I just get a HTTP ERROR 403: Forbidden when doing the reading lists

**Comment by JimmXinu** [comment]
Since you haven't found reported stories that fail--and haven't given me any of the list URLs you say were failing--I'm going to close this.
