### ISSUE TITLE
fanfiction.net site broken (FFnet "Chapter not found")

### ISSUE THREAD

**Issue by Edocsil** [JimmXinu/FanFicFare#583]
So, for the last couple of days most fics from fanfiction.net refuse to update. Sometimes after a few hours some work, others still don't after a few days. Forcing FFF to download the fics again will not download the last chapters from this stories.

I honestly have no idea what's going on.

> FFF: DEBUG: 2020-11-02 21:11:56,484: cli.py(209):     OS Version:Linux-4.14.98-perf-g978603e-aarch64-with-libc  FFF: DEBUG: 2020-11-02 21:11:56,484: cli.py(210): Python Version:3.9.0 (default, Oct  8 2020, 15:54:02)         [Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489                                 FFF: DEBUG: 2020-11-02 21:11:56,485: cli.py(211):    FFF Version:3.24.9
FFF: DEBUG: 2020-11-02 21:12:06,062: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13705908/4/Ghosts-From-Beyond-Defenders-of-Realms                 FFF: DEBUG: 2020-11-02 21:12:06,063: configurable.py(1152): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/13705908/4/Ghosts-From-Beyond-Defenders-of-Realms             FFF: DEBUG: 2020-11-02 21:12:12,087: configurable.py(1010): Encoding:utf8                                       Failed to read epub for update: (Error downloading Chapter: https://www.fanfiction.net/s/13705908/4/Ghosts-From-Beyond-Defenders-of-Realms!  'Chapter not found. Please check to see you are not using an outdated url.') Continuing with update=false                                  FFF: DEBUG: 2020-11-02 21:12:12,109: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13705908/4/Ghosts-From-Beyond-Defenders-of-Realms                 FFF: DEBUG: 2020-11-02 21:12:12,111: configurable.py(1142): #####################################               pagecache(GET) HIT: https://www.fanfiction.net/s/13705908/4/Ghosts-From-Beyond-Defenders-of-Realms
FFF: DEBUG: 2020-11-02 21:12:12,112: configurable.py(1010): Encoding:utf8
URL(https://www.fanfiction.net/s/13705908/4/Ghosts-From-Beyond-Defenders-of-Realms) Failed: Exception (Error downloading Chapter: https://www.fanfiction.net/s/13705908/4/Ghosts-From-Beyond-Defenders-of-Realms!  'Chapter not found. Please check to see you are not using an outdated url.'). Run URL individually for more detail.
FFF: DEBUG: 2020-11-02 21:12:12,247: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/12670110/202/Abaddon-Born-e
FFF: DEBUG: 2020-11-02 21:12:12,247: configurable.py(1152): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/12670110/202/Abaddon-Born-e
FFF: DEBUG: 2020-11-02 21:12:17,922: configurable.py(1010): Encoding:utf8
Failed to read epub for update: (Error downloading Chapter: https://www.fanfiction.net/s/12670110/202/Abaddon-Born-e!  'Chapter not found. Please check to see you are not using an outdated url.') Continuing with update=false
FFF: DEBUG: 2020-11-02 21:12:17,952: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/12670110/202/Abaddon-Born-e
FFF: DEBUG: 2020-11-02 21:12:17,954: configurable.py(1142): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/12670110/202/Abaddon-Born-e
FFF: DEBUG: 2020-11-02 21:12:17,955: configurable.py(1010): Encoding:utf8
URL(https://www.fanfiction.net/s/12670110/202/Abaddon-Born-e) Failed: Exception (Error downloading Chapter: https://www.fanfiction.net/s/12670110/202/Abaddon-Born-e!  'Chapter not found. Please check to see you are not using an outdated url.'). Run URL individually for more detail.
FFF: DEBUG: 2020-11-02 21:12:18,095: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13324619/33/New-Game
FFF: DEBUG: 2020-11-02 21:12:18,096: configurable.py(1152): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/13324619/33/New-Game
FFF: DEBUG: 2020-11-02 21:12:23,999: configurable.py(1010): Encoding:utf8
Failed to read epub for update: (Error downloading Chapter: https://www.fanfiction.net/s/13324619/33/New-Game!  'Chapter not found. Please check to see you are not using an outdated url.') Continuing with update=false
FFF: DEBUG: 2020-11-02 21:12:24,028: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13324619/33/New-Game
FFF: DEBUG: 2020-11-02 21:12:24,031: configurable.py(1142): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/13324619/33/New-Game
FFF: DEBUG: 2020-11-02 21:12:24,034: configurable.py(1010): Encoding:utf8
URL(https://www.fanfiction.net/s/13324619/33/New-Game) Failed: Exception (Error downloading Chapter: https://www.fanfiction.net/s/13324619/33/New-Game!  'Chapter not found. Please check to see you are not using an outdated url.'). Run URL individually for more detail.
FFF: DEBUG: 2020-11-02 21:12:24,172: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/11542676/15/Demon-Of-The-Hidden-Leaf
FFF: DEBUG: 2020-11-02 21:12:24,173: configurable.py(1152): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/11542676/15/Demon-Of-The-Hidden-Leaf
FFF: DEBUG: 2020-11-02 21:12:29,837: configurable.py(1010): Encoding:utf8
Failed to read epub for update: (Error downloading Chapter: https://www.fanfiction.net/s/11542676/15/Demon-Of-The-Hidden-Leaf!  'Chapter not found. Please check to see you are not using an outdated url.') Continuing with update=false
FFF: DEBUG: 2020-11-02 21:12:29,860: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/11542676/15/Demon-Of-The-Hidden-Leaf
FFF: DEBUG: 2020-11-02 21:12:29,861: configurable.py(1142): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/11542676/15/Demon-Of-The-Hidden-Leaf
FFF: DEBUG: 2020-11-02 21:12:29,862: configurable.py(1010): Encoding:utf8
URL(https://www.fanfiction.net/s/11542676/15/Demon-Of-The-Hidden-Leaf) Failed: Exception (Error downloading Chapter: https://www.fanfiction.net/s/11542676/15/Demon-Of-The-Hidden-Leaf!  'Chapter not found. Please check to see you are not using an outdated url.'). Run URL individually for more detail.
FFF: DEBUG: 2020-11-02 21:12:30,000: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13718446/4/Heroic-Folly
FFF: DEBUG: 2020-11-02 21:12:30,001: configurable.py(1152): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/13718446/4/Heroic-Folly
FFF: DEBUG: 2020-11-02 21:12:35,669: configurable.py(1010): Encoding:utf8
Failed to read epub for update: (Error downloading Chapter: https://www.fanfiction.net/s/13718446/4/Heroic-Folly!  'Chapter not found. Please check to see you are not using an outdated url.') Continuing with update=false
FFF: DEBUG: 2020-11-02 21:12:35,699: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13718446/4/Heroic-Folly
FFF: DEBUG: 2020-11-02 21:12:35,702: configurable.py(1142): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/13718446/4/Heroic-Folly
FFF: DEBUG: 2020-11-02 21:12:35,705: configurable.py(1010): Encoding:utf8
URL(https://www.fanfiction.net/s/13718446/4/Heroic-Folly) Failed: Exception (Error downloading Chapter: https://www.fanfiction.net/s/13718446/4/Heroic-Folly!  'Chapter not found. Please check to see you are not using an outdated url.'). Run URL individually for more detail.
FFF: DEBUG: 2020-11-02 21:12:35,845: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/12937408/14/The-Fourth-Beast
FFF: DEBUG: 2020-11-02 21:12:35,846: configurable.py(1152): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/12937408/14/The-Fourth-Beast
FFF: DEBUG: 2020-11-02 21:12:41,458: configurable.py(1010): Encoding:utf8
Failed to read epub for update: (Error downloading Chapter: https://www.fanfiction.net/s/12937408/14/The-Fourth-Beast!  'Chapter not found. Please check to see you are not using an outdated url.') Continuing with update=false
FFF: DEBUG: 2020-11-02 21:12:41,486: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/12937408/14/The-Fourth-Beast
FFF: DEBUG: 2020-11-02 21:12:41,489: configurable.py(1142): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/12937408/14/The-Fourth-Beast
FFF: DEBUG: 2020-11-02 21:12:41,492: configurable.py(1010): Encoding:utf8
URL(https://www.fanfiction.net/s/12937408/14/The-Fourth-Beast) Failed: Exception (Error downloading Chapter: https://www.fanfiction.net/s/12937408/14/The-Fourth-Beast!  'Chapter not found. Please check to see you are not using an outdated url.'). Run URL individually for more detail.
FFF: DEBUG: 2020-11-02 21:12:41,627: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13479009/19/Deliverance
FFF: DEBUG: 2020-11-02 21:12:41,628: configurable.py(1152): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/13479009/19/Deliverance
FFF: DEBUG: 2020-11-02 21:12:48,539: configurable.py(1010): Encoding:utf8
Failed to read epub for update: (Error downloading Chapter: https://www.fanfiction.net/s/13479009/19/Deliverance!  'Chapter not found. Please check to see you are not using an outdated url.') Continuing with update=false
FFF: DEBUG: 2020-11-02 21:12:48,560: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13479009/19/Deliverance
FFF: DEBUG: 2020-11-02 21:12:48,561: configurable.py(1142): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/13479009/19/Deliverance
FFF: DEBUG: 2020-11-02 21:12:48,562: configurable.py(1010): Encoding:utf8
URL(https://www.fanfiction.net/s/13479009/19/Deliverance) Failed: Exception (Error downloading Chapter: https://www.fanfiction.net/s/13479009/19/Deliverance!  'Chapter not found. Please check to see you are not using an outdated url.'). Run URL individually for more detail.
FFF: DEBUG: 2020-11-02 21:12:48,702: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13485808/17/Darkness-Reborn
FFF: DEBUG: 2020-11-02 21:12:48,704: configurable.py(1152): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/13485808/17/Darkness-Reborn
FFF: DEBUG: 2020-11-02 21:12:54,836: configurable.py(1010): Encoding:utf8
Failed to read epub for update: (Error downloading Chapter: https://www.fanfiction.net/s/13485808/17/Darkness-Reborn!  'Chapter not found. Please check to see you are not using an outdated url.') Continuing with update=false
FFF: DEBUG: 2020-11-02 21:12:54,859: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/13485808/17/Darkness-Reborn
FFF: DEBUG: 2020-11-02 21:12:54,860: configurable.py(1142): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/13485808/17/Darkness-Reborn
FFF: DEBUG: 2020-11-02 21:12:54,862: configurable.py(1010): Encoding:utf8
URL(https://www.fanfiction.net/s/13485808/17/Darkness-Reborn) Failed: Exception (Error downloading Chapter: https://www.fanfiction.net/s/13485808/17/Darkness-Reborn!  'Chapter not found. Please check to see you are not using an outdated url.'). Run URL individually for more detail.
FFF: DEBUG: 2020-11-02 21:12:55,016: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/12455717/19/Harry-Potter-Master-of-Death
FFF: DEBUG: 2020-11-02 21:12:55,017: configurable.py(1152): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/12455717/19/Harry-Potter-Master-of-Death
FFF: DEBUG: 2020-11-02 21:13:00,831: configurable.py(1010): Encoding:utf8
Failed to read epub for update: (Error downloading Chapter: https://www.fanfiction.net/s/12455717/19/Harry-Potter-Master-of-Death!  'Chapter not found. Please check to see you are not using an outdated url.') Continuing with update=false
FFF: DEBUG: 2020-11-02 21:13:00,863: adapter_fanfictionnet.py(100): URL: https://www.fanfiction.net/s/12455717/19/Harry-Potter-Master-of-Death
FFF: DEBUG: 2020-11-02 21:13:00,865: configurable.py(1142): #####################################
pagecache(GET) HIT: https://www.fanfiction.net/s/12455717/19/Harry-Potter-Master-of-Death
FFF: DEBUG: 2020-11-02 21:13:00,868: configurable.py(1010): Encoding:utf8
URL(https://www.fanfiction.net/s/12455717/19/Harry-Potter-Master-of-Death) Failed: Exception (Error downloading Chapter: https://www.fanfiction.net/s/12455717/19/Harry-Potter-Master-of-Death!  'Chapter not found. Please check to see you are not using an outdated url.'). Run URL individually for more detail.
[21:13] Edoc@Termux:~ $

**Comment by JimmXinu** [comment]
Site is broken.  Nothing FFF can do about it.
See also [MR thread discussion](https://www.mobileread.com/forums/showthread.php?p=4053506&postcount=4792).

**Comment by Edocsil** [comment]
That certainly explains it. I did check if the URLs worked, but only with the app not on a browser.

Chapters work fine on the (android) app by the way, in case anyone wants to read stuff.

**Comment by kido5217** [comment]
There's discussion on CaerAzkaban mailing list too: [FF.net Problems
](https://caerazkaban.groups.io/g/main/topic/ff_net_problems/77961414?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,77961414)

**Comment by kyoam** [comment]
as of right now i've found a somewhat tedious work around

programs needed
1 bluestacks (android ui on pc/laptop)
2 ff.net app installed on bluestacks (mobile app seems to display new chapters no problem)
3 universal copy app installed on bluestacks
4 text editor software (note pad or equivalent at minimum)

step 1 open bluestacks
step 2 open ff. net app
step 3 bring up story or chapter desired
step 4 give universal copy access to screen data
step 5 click at top of screen to bring notifications up
step 6 click notification to activate universal copy mode
step 7 click all paragraphs and/or singular lines of text on current screen
step 8 click on double page button at top to copy selected text to clipboard (add skipping will be needed on free version)
step 9 paste clipboard text to text editor file
step 10 repeat steps 6 thru 9 until text editor file has entire chapter text
step 11 delete all in boxed "obj" instances
step 12 save text editor file.

this is a long process so i would only recommend this for chapters you NEED a personal copy of

**Comment by kyoam** [comment]
as of 2:26 am 11/6/20 ff.net fics are downladable at least on fff's test version
