### ISSUE TITLE
Issuse with AH.com

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#590]
Even with the test being used I still cannot download anything from AH other then the very first chapter.
This one is a fresh download:

Behold a Red Horse
Geon
Download epub completed, 1 chapters.
https://www.alternatehistory.com/forum/threads/behold-a-red-horse-a-sequel-to-let-them-pass.499390/

(There are 3 chapters btw)

And this is what happens when I try updating something I had already downloaded:

Skipped
A Hippie in the House of Mouse
Geekhis Khan
Existing epub contains 111 chapters, web site only has 1. Use Overwrite to force update.
https://www.alternatehistory.com/forum/threads/a-hippie-in-the-house-of-mouse-jim-henson-at-disney-1980.489210/

**Comment by JimmXinu** [comment]
Test versions up.
