### ISSUE TITLE
Scribblehub Tables

### ISSUE THREAD

**Issue by Anangaya** [JimmXinu/FanFicFare#591]
The tables are missing in the epub. It shows like I copy pasted the content (the table lines are missing the content is there). 

story = https://www.scribblehub.com/series/59028/a-hero-turned-succubus-tale/

**Comment by JimmXinu** [comment]
Please provide a specific chapter and a copy of some text just before what you're talking about.

**Comment by Anangaya** [comment]
Chapter 1

**Comment by Anangaya** [comment]
I open the epub with calibre editor and saw that they indeed was a table containing all the details. But it gets displayed without the table lines like shown above.

**Comment by JimmXinu** [comment]
FFF deliberately defaults to removing styling information to normalize the appearance of the generated ebooks.

You can instruct FFF to keep in-line style and/or add to FFF's output css in `personal.ini`.  How exactly you choose to do so is up to you.
```
[www.scribblehub.com]
## keep in-line styles
add_to_keep_html_attrs:,style

## add to FFF's CSS:
## (copied from scribblehub.com)
add_to_output_css:
 table {
    max-width: 100% !important;
    margin-bottom: 1.5em;
    margin-left: auto;
    margin-right: auto;
    height: 100% !important;
    background-color: #374558;
    color: #bfc4c9;
    border-collapse: collapse;
    border-color: black;
 }
 td {
    padding-left: 5px;
 }
```

**Comment by Anangaya** [comment]
Ok thanks
