### ISSUE TITLE
skip generating characters in other languages in CLI

### ISSUE THREAD

**Issue by cybergipsy2020** [JimmXinu/FanFicFare#593]
It seems that cli doesn't support saving ao3 fiction titles that have Chinese characters in. 
I was downloading from https://archiveofourown.org/works/15480408/ that has title `危险游戏` and it skips the Chinese character and saved the file as `_-ao3_15480408.epub`. 
It's not a big deal since it still shows `危险游戏` when I import the fic into calibre. Just letting you know!

**Comment by JimmXinu** [comment]
By default, FFF restricts the characters that can be used to name files to be sure they won't cause problems for anybody.

You can turn that off, or adjust the regexp in `personal.ini`:
```
## Normally, try to make the filenames 'safe' by removing invalid
## filename chars.  Applies to default_cover_image, output_filename &
## zip_filename.
allow_unsafe_filename: false

## The regex pattern of 'unsafe' filename chars for above.  First
## character . OR any one or more characters that are NOT a letter,
## number, or one of _. []()&'-
output_filename_safepattern:(^\.|/\.|[^a-zA-Z0-9_\. \[\]\(\)&'-]+)
```
Looking back, `output_filename_safepattern` isn't particularly well named or user-friendly, but it rarely comes up.
