### ISSUE TITLE
FFF CLI not grabing AO3 series name

### ISSUE THREAD

**Issue by cybergipsy2020** [JimmXinu/FanFicFare#594]
I downloaded an ao3 fic using CLI and import it into calibre, but the series name is missing in the meta. 
When I download the fic directly from the website it has its series name. Is there anything I can change to make it work?

**Comment by JimmXinu** [comment]
There isn't a standard metadata in epub (that I'm aware of) for series.

You could probably put the series into the file name with FFF CLI and then configure Calibre to recognize that and import it into series.

However, the simplest solution is to use the [FanFicFare Calibre plugin](https://www.mobileread.com/forums/showthread.php?t=259221) (see 'Get plugins' under the Calibre Preferences drop down) to download directly inside Calibre.  Series will automatically be populated then.
