### ISSUE TITLE
Feature Request Add support for waybackmachine versions of existing sites.

### ISSUE THREAD

**Issue by Dilnu** [JimmXinu/FanFicFare#595]
I'm not sure how difficult this would be. 
I guess it's probably difficult for a lot of sites for example Ao3 doesn't seem to be consistently archived.
Still it would be nice to have.

**Comment by JimmXinu** [comment]
This would be a significant head ache for not enough value, IMO.

I just spot checked and _all_ of the handful of stories I checked from AO3 and ffnet were either incomplete or not archived at all in web.archive.org
