### ISSUE TITLE
Progress Indicator would be nice

### ISSUE THREAD

**Issue by Anangaya** [JimmXinu/FanFicFare#597]
It would be neat if there was a progress indicator in the command line version so that we can get idea how long it takes to download some large novels.

**Comment by JimmXinu** [comment]
Already has one.
```
  -p, --progressbar     Display a simple progress bar while downloading--one
                        dot(.) per network fetch.
```

**Comment by Anangaya** [comment]
Not exactly very pretty when there are 500+ chapters, but I guess it is better than nothing. It would have been much better if it showed "the number of the chapters fetched/total number of chapters to be fetched" .
And I think it would be more convenient if progressbar was active by default.

**Comment by JimmXinu** [comment]
Progress bar was contributed code from a user -- I didn't think it was needed at all.  My assumption is that most CLI users are writing scripts and users who want direct interaction will use the Calibre plugin.  Plus turning it on by default would break existing user scripts.

You can also use `-d`/`--debug` and get a plethora of info on what's going on.

**Comment by Anangaya** [comment]
Ok then I will move to the calibre plugin too.
