### ISSUE TITLE
Problems with downloading a story on Fiction.Live

### ISSUE THREAD

**Issue by tr13dm03** [JimmXinu/FanFicFare#598]
Out of a few dozen stories I downloaded, one seemingly fails to extract any metadata and errors out with no title or author, as of 2020-11-16 v3.25.6 .

https://fiction.live/stories/Diary-of-a-Hopeless-Girl-in-Space-/nu7WT4qcbyoMeqmmt

@HazelSh

**Comment by HazelSh** [comment]
Investigating now. It's crashing in the chapter extraction, other metadata seems fine. 

Looks like it doesn't have any chapters, which I'm pretty sure the adapter can handle, except that it does have an appendix. 

I'll dig into this and fix it, probably next week. Thanks for the report

**Comment by HazelSh** [comment]
Pull request made that should fix this issue. @tr13dm03, check for a new fanficfare test version in a few days.
