### ISSUE TITLE
Updating EPUB deletes images from chapters that weren't updated

### ISSUE THREAD

**Issue by Epicpkmn11** [JimmXinu/FanFicFare#608]
I found this while testing my changes in #607, however on further testing it also affects at least Scribble Hub and AO3 (those are the only other sites I use).

When running "Update EPUB if New Chapters" and there are new chapters or always for "Update EPUB Always" any chapters that weren't updated by the latest download will have all their images lost. Cover images are not affected.

This affects both the latest test version and #607 so it's not my changes, however it doesn't affect the latest release so it seems to be a recent problem.

Tested with both the calibre plugin and the CLI version with these as they have a lot of images:
- https://www.scribblehub.com/series/119592/superluminal/
- https://archiveofourown.org/works/18727693
- https://mangadex.org/title/26530 (well, anything on MangaDex ;p)

From the CLI debug it seem to be trying to use the image sources inside the EPUB to pull from the internet:
```
FFF: DEBUG: 2020-12-13 10:22:28,632: configurable.py(1157): #####################################
pagecache(GET) MISS: images/ffdl-351.jpg
FFF: INFO: 2020-12-13 10:22:28,633: story.py(1290): Failed to load or convert image, 
parent:None
skipping:images/ffdl-351.jpg
Exception: unknown url type: 'images/ffdl-351.jpg'
```
and the image tags get turned into just `failedtoload`:
```html
<img longdesc="failedtoload" src="failedtoload"/>
```

**Comment by JimmXinu** [comment]
Image processing did change in the current code to handle inline images better.  I'm glad you noticed this before I released it.

**Comment by JimmXinu** [comment]
This bug has nothing to do with the inline images changes.  Instead, it was introduced in 'Allow <img> tags without src attr in epub to update' (285459758d55895516538a18e5baf1730b249293)

This is honestly something I should have know better about.  The `in` operator when applied to BeautifulSoup tag objects returns whether something is a sub-tag or contents _not_ whether something is an available attribute.  Need to use `.has_attr()` for that.

Thanks again for catching this, I was planning to release any day now.
