### ISSUE TITLE
Problems with email 

### ISSUE THREAD

**Issue by roon0** [JimmXinu/FanFicFare#609]
I was using the email function to update fanficfare without problems until Sunday luchtime (13/12/20).  Since then I have been getting the following.  I can still update if I enter manually but cannot through email.

calibre, version 5.4.2
ERROR: Unhandled exception: <b>UnicodeDecodeError</b>:'utf-8' codec can't decode byte 0x92 in position 6884: invalid start byte

calibre 5.4.2  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Clean Metadata (0, 0, 6) && DOC Input (1, 0, 1) && EpubMerge (2, 11, 0) && FanFicFare (3, 25, 0) && Find Duplicates (1, 8, 3) && SmartEject (2, 3, 0)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 585, in get_urls_from_imap_menu
  File "calibre_plugins.fanficfare_plugin.fanficfare.geturls", line 241, in get_urls_from_imap
  File "calibre_plugins.fanficfare_plugin.fanficfare.six", line 917, in ensure_str
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 6884: invalid start byte

**Comment by JimmXinu** [comment]
That error suggests that FFF is getting the emails, but there's something mis-encoded in one of them.

You can probably figure out which one by manually marking each 'read' so FFF doesn't try to retrieve it and try FFF get from email in between.

**Comment by roon0** [comment]
Thank you I will try that.

**Comment by roon0** [comment]
I manually put in all the links and then deleted the ones on my gmail.  That cleared the problem up.
