### ISSUE TITLE
storiesonline.net error

### ISSUE THREAD

**Issue by giaez** [JimmXinu/FanFicFare#610]
According to the log it says "Story not found in Author's list". Multiple links, including links I successfully downloaded two months before, all failing.
Already checked the authors' page from browser and the stories exist within their pages.
Using Calibre 64bit, Windows 7.

![Screenshot_302](https://user-images.githubusercontent.com/43065084/102139295-9e7ee700-3e98-11eb-822a-6948099d9941.png)

**Comment by JimmXinu** [comment]
Have you made sure you have Listings Theme set to Classic like it says?  

Please include story URL(s) in text, not just an image.

**Comment by JimmXinu** [comment]
I tried the first and last of these using the most recent test version and they both downloaded fine.

**Comment by Adam3011** [comment]
I am having the same issue. My Listings Theme is set to classic and access set to full, but no luck.

Here's one of the stories I've tried: https://storiesonline.net/s/14679/three-square-meals

I've tried it with several other stories picked at random and receive the error on all of them.

**Comment by JimmXinu** [comment]
Try changing your Listings Theme to something else and then back to Classic.  That worked for me, [see here](https://www.mobileread.com/forums/showthread.php?p=4072370&highlight=storiesonline#post4072370).

**Comment by Adam3011** [comment]
Just tried, also tried changing the access to filtered and back to full as well, but doesn't seemed to have worked, still showing the error.

**Comment by JimmXinu** [comment]
I don't know what to tell you, then.  I had the same issue the last time it was reported and changing settings (and viewing a list) back and forth fixed it.

I tried the story URL you gave just now and it worked fine for me, both in CLI and plugin.

**Comment by Edocsil** [comment]
I've personally tried changing every option multiple times and clearing the cache from the terminal, but it has yet to work. Currently I've the theme as classic, the layout as desktop, and 50 stories per page.

How should the author list look like? And more importantly, why is it trying to find the story in the list when it has the URL?

**Comment by JimmXinu** [comment]
This is the listing style that I see and that FFF is coded to work with:

![Capture](https://user-images.githubusercontent.com/11446969/103155787-644ef880-4768-11eb-86b9-2b0fbabe112f.PNG)

When the FFF adapter for storiesonline was written, that was the default new users got.  The same code is also shared with finestories.com and scifistories.com.

It's fairly common for FFF to have to get some story metadata details from the list of author's stories.  In the case of storiesonline, that includes genre, description, status, dateUpdated, datePublished, etc, etc.

I just went and tested changing my Listing Theme to Modern, what I see in the browser changed immediately, but *not* what FFF gets using the same user name.  

Nor did signing out and back in (in browser).  But it does appear to have reset my Listing to Classic in browser.

When you view source in browser and search for `css`, what is the first import that comes up for each of you?

**Comment by Adam3011** [comment]
I get these:

@import url('/res/css/t-classic2.css');
@import url(/res/css/aDefault.css);

**Comment by JimmXinu** [comment]
Hmmm.  That's what I see and it works fine.

If you want, I can provide a test version (of the plugin? or CLI?) that dumps the author list page to debug and you can try it and attach the results for me to see.

**Comment by Adam3011** [comment]
Sure, I can try the plugin.

**Comment by Edocsil** [comment]
I tried to download everything from that author you showed and this was the result.

```
FFF: DEBUG: 2020-12-26 18:34:32,589: cli.py(209):     OS Version:Linux-4.14.117-perf-gaf11d57-aarch64-with-libc
FFF: DEBUG: 2020-12-26 18:34:32,590: cli.py(210): Python Version:3.9.1 (default, Dec  9 2020, 13:22:01)
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489
FFF: DEBUG: 2020-12-26 18:34:32,590: cli.py(211):    FFF Version:3.27.0
FFF: DEBUG: 2020-12-26 18:34:32,746: configurable.py(1201): #####################################
pagecache(GET) MISS: https://storiesonline.net/a/chris89
FFF: DEBUG: 2020-12-26 18:34:43,188: configurable.py(1027): Encoding:utf8
FFF: DEBUG: 2020-12-26 18:34:43,533: adapter_storiesonlinenet.py(191): URL: https://storiesonline.net/s/23813
FFF: DEBUG: 2020-12-26 18:34:43,535: configurable.py(1201): #####################################
pagecache(GET) MISS: https://storiesonline.net/s/23813:i
FFF: DEBUG: 2020-12-26 18:34:54,336: configurable.py(1027): Encoding:utf8
FFF: DEBUG: 2020-12-26 18:34:54,341: adapter_storiesonlinenet.py(104): Will now login to URL (https://storiesonline.net/sol-secure/login.php) as (MAIL)
FFF: DEBUG: 2020-12-26 18:34:54,342: configurable.py(1201): #####################################
pagecache(GET) MISS: https://storiesonline.net/sol-secure/login.php
FFF: DEBUG: 2020-12-26 18:35:05,377: configurable.py(1027): Encoding:utf8
FFF: DEBUG: 2020-12-26 18:35:05,438: configurable.py(1115): #####################################
pagecache(POST) MISS: https://login.wlpc.com/index.php?cmd=SubmitEmail&email=MAIL&v=
FFF: DEBUG: 2020-12-26 18:35:15,840: configurable.py(1027): Encoding:utf8
FFF: DEBUG: 2020-12-26 18:35:15,894: configurable.py(1115): #####################################
pagecache(POST) MISS: https://login.wlpc.com/index.php?cmd=cred_set&email=MAIL&password=XXXXXXXX&v=
FFF: DEBUG: 2020-12-26 18:35:26,408: adapter_storiesonlinenet.py(163): e Location:https://storiesonline.net/sol-secure/login.php?rr=
FFF: DEBUG: 2020-12-26 18:35:26,411: configurable.py(1115): #####################################
pagecache(POST) MISS: https://storiesonline.net/sol-secure/login.php?rr=
FFF: DEBUG: 2020-12-26 18:35:36,895: configurable.py(1201): #####################################
pagecache(GET) MISS: https://storiesonline.net/s/23813:i
FFF: DEBUG: 2020-12-26 18:35:47,337: configurable.py(1027): Encoding:utf8
FFF: DEBUG: 2020-12-26 18:35:47,610: configurable.py(1201): #####################################
pagecache(GET) MISS: https://storiesonline.net/a/chris89/1
FFF: DEBUG: 2020-12-26 18:35:59,388: configurable.py(1027): Encoding:utf8
FFF: DEBUG: 2020-12-26 18:35:59,514: configurable.py(1201): #####################################
pagecache(GET) MISS: https://storiesonline.net/a/chris89/2
FFF: DEBUG: 2020-12-26 18:36:10,274: configurable.py(1303): Caught an exception reading URL: https://storiesonline.net/a/chris89/2  Exception HTTP Error 404: Not Found.
FFF: DEBUG: 2020-12-26 18:36:10,276: configurable.py(1316): Giving up on https://storiesonline.net/a/chris89/2
FFF: DEBUG: 2020-12-26 18:36:10,281: configurable.py(1317): HTTP Error 404: Not Found
NoneType: None
FFF: DEBUG: 2020-12-26 18:36:10,559: adapter_storiesonlinenet.py(191): URL: https://storiesonline.net/s/23300
FFF: DEBUG: 2020-12-26 18:36:10,561: configurable.py(1201): #####################################
pagecache(GET) MISS: https://storiesonline.net/s/23300:i
FFF: DEBUG: 2020-12-26 18:36:20,979: configurable.py(1027): Encoding:utf8
FFF: DEBUG: 2020-12-26 18:36:21,075: adapter_storiesonlinenet.py(251): Number of chapters: 1
FFF: DEBUG: 2020-12-26 18:36:21,085: configurable.py(1197): #####################################
pagecache(GET) HIT: https://storiesonline.net/a/chris89/1
FFF: DEBUG: 2020-12-26 18:36:21,086: configurable.py(1027): Encoding:utf8
FFF: DEBUG: 2020-12-26 18:36:21,175: configurable.py(1201): #####################################
pagecache(GET) MISS: https://storiesonline.net/a/chris89/2
FFF: DEBUG: 2020-12-26 18:36:31,679: configurable.py(1303): Caught an exception reading URL: https://storiesonline.net/a/chris89/2  Exception HTTP Error 404: Not Found.
FFF: DEBUG: 2020-12-26 18:36:31,682: configurable.py(1316): Giving up on https://storiesonline.net/a/chris89/2
FFF: DEBUG: 2020-12-26 18:36:31,682: configurable.py(1317): HTTP Error 404: Not Found
NoneType: None

```
This is the normal output, which is missing one story apparently.

```
URL(https://storiesonline.net/s/23813/bathroom-break-by-chris89) Failed: Exception (Story not found in Author's list--Set Access Level to Full Access and change Listings Theme back to Classic). Run URL individually for more detail.
URL(https://storiesonline.net/s/23300/dry-gulch) Failed: Exception (Story not found in Author's list--Set Access Level to Full Access and change Listings Theme back to Classic). Run URL individually for more detail.
```

As for the source code, chrome showed this:
 ```
<title>chris89: Stories</title>
<style>
@import url('/res/css/t-classic2.css');
@import url(/res/css/aBlue.css);
```

I use by necessity the CLI version on an android phone using Termux, so I'll try to help but figuring how to do some stuff takes time.

**Comment by JimmXinu** [comment]
@Adam3011, Here ([FanFicFare.zip](https://github.com/JimmXinu/FanFicFare/files/5743502/FanFicFare.zip)) is a test plugin version that will output the author page in the debug log.  You need to run Calibre in debug mode (under Calibre Preferences dropdown).

@Edocsil, I don't think I've ever tried using termux on android, and I don't know anything about it.  Did you trim off a lot of parameters in the log?  Because that doesn't look like a full login.

**Comment by Adam3011** [comment]
Here's the debug file:

[FFF Calibre Debug.txt](https://github.com/JimmXinu/FanFicFare/files/5743507/FFF.Calibre.Debug.txt)

**Comment by Edocsil** [comment]
Yes, but I can assure you the login is working, as the stories from that author were added to my daily limit even though I never opened them myself.

Anyway, I just saw Adam's log and I can guess mine would have the same issue, but if it matters and you upload a test branch that I can install with pip I don't mind confirming it.

**Comment by JimmXinu** [comment]
I think the fundamental problem here is that storiesonline isn't saving the Theme setting.  You can change it during a session, but next login, it's back to what it was before.  For me, that's Classic and for you two, it's Modern.

(You might report that to the site and see if they can get it fixed, since it does seem to be a legitimate problem with the site.  I would not mention FFF while doing so.)

I did look at implementing metadata parsing for both Classic and Modern themes.  However, the page structure between Classic and Modern is so different it would be completely re-implementing metadata parsing for the adapter.  Twice.

So instead, I've tried to add code to FFF to force the Theme to Classic for FFF's session.  @Adam3011, please try this version:
[FanFicFare.zip](https://github.com/JimmXinu/FanFicFare/files/5743589/FanFicFare.zip)

It has lots of extra output right now, but in theory should change Theme correctly.  I will pare down the output and make this code optional if it works for you.  If it does, I will also put up a CLI test version for @Edocsil.

**Comment by Adam3011** [comment]
Hmm, no luck, still getting the same error.

**Comment by Edocsil** [comment]
I've successful replaced 'adapter_storiesonlinenet.py' manually (which took me a while to figure where it was..), but it's not working for me either.

Could it be possible to add a -no-metadata option so we can at least get the chapters until the web gets fixed? Or that wouldn't work either?

**Comment by JimmXinu** [comment]
@Adam3011 -- That 'lots of extra output' I mentioned?  It would be help for me to see it.  From the debug log, same as before.

**Comment by Adam3011** [comment]
Sure, here it is:

[FFF Calibre Debug v2.txt](https://github.com/JimmXinu/FanFicFare/files/5743633/FFF.Calibre.Debug.v2.txt)

**Comment by JimmXinu** [comment]
Okay, last try.  This version outputs even more and tries to set the Theme to Modern, _then_ Classic.
[FanFicFare.zip](https://github.com/JimmXinu/FanFicFare/files/5743647/FanFicFare.zip)

Same again: try it (with something with only a few chapters please), post debug log.

**Comment by Adam3011** [comment]
Tried with another story, unfortunately still showing the same issue.

[FFF Calibre Debug v3.txt](https://github.com/JimmXinu/FanFicFare/files/5743655/FFF.Calibre.Debug.v3.txt)

**Comment by JimmXinu** [comment]
I give up.  The site isn't honoring its own settings; I classify that as broken.

I'll leave this issue open as a reminder to check it again someday, and I've [pushed a branch](https://github.com/JimmXinu/FanFicFare/tree/storiesonlinenet-force_classic_theme) with the changes we've experimented with.

**Comment by Adam3011** [comment]
I've reported the issue to the site, so I'll report back if I hear anymore on it.

**Comment by Adam3011** [comment]
Had a response from the site admin, apparently the themes settings were saved in a cookie and if it got deleted future theme settings wouldn't save properly. I had to change the settings and save them once more and now the problem seems to be fixed for me. Would be interested to know if its now fixed for others @Edocsil @giaez ?

**Comment by Edocsil** [comment]
I managed to get it to work, but I had to go back to the release version of the adapter. They must have changed something today because it was breaking my theme settings.

Thanks guys 😃

**Comment by JimmXinu** [comment]
Can one of you describe your exact steps to getting it working again?  Or was it something the site fixed on their end?

**Comment by Edocsil** [comment]
When I tried this morning my theme have been changed to Modern with Auto dark mode, and Classic was now in a different slot. 
I tried to download one story and failed, checking the settings the theme showed "name" instead of classic and the rest showed other stuff, after trying any of them the list fixed itself and I was back to modern auto night, I tried a second time and the same thing happened so I decided to restore the adapter to the one in the current released version, and it just worked.

**Comment by Adam3011** [comment]
It was fixed on their end. As with Edocsil, it set my theme to Modern with Auto dark mode (I assume this is what it was setting the theme to automatically, but not showing and causing the issues in the first place), so I just had to be set back to classic and saved again. Now it seems to work properly. (Tried it with 3.27.0 release and Calibre 5.8.1)

**Comment by JimmXinu** [comment]
Okay, thanks.

I can now see the theme presented to FFF change when I change it in browser.  And they've changed the settings drop down and Classic is now 5 instead of 0--which explains why the branch version fails, it assumes Classic==0.

So rather than some magic combination of deleting cookies and changing settings, I think they fixed something that was broken.

Regardless, it's fixed as long as FFF users follow the instructions to use Classic theme.
