### ISSUE TITLE
add support for scraping metadata from www.wlnupdates.com

### ISSUE THREAD

**Issue by Emasoft** [JimmXinu/FanFicFare#612]
Hi! Can you add support for scraping metadata from [www.wlnupdates.com](https://www.wlnupdates.com) ? It has a lot better metadata than novelupdates.com.
Thx!

**Comment by JimmXinu** [comment]
Fetching metadata from a separate site than the story host is rather outside FFF's paradigm.  It's not a change I'm interested in supporting.
