### ISSUE TITLE
Feature request: Multi-source stories

### ISSUE THREAD

**Issue by hseg** [JimmXinu/FanFicFare#615]
Xenforo sites have a page limit on threads, so some stories are posted across multiple threads. Some examples:
* [_A Skittering Heart_](https://forums.spacebattles.com/threads/a-skittering-heart-worm-kingdom-hearts.371816/), [thread 2](https://forums.spacebattles.com/threads/ash-worm-kingdom-hearts-thread-2-is-tuesday-over-yet.420875/)
* [_Alchemical Solutions_](https://forums.spacebattles.com/threads/alchemical-solutions-worm-exalted-story-only-thread.283060), [thread 24](https://forums.sufficientvelocity.com/threads/alchemical-solutions-worm-exalted-thread-24-xenial-xenos-xerox-xanthous-xiphos.54726/)

Similarly, AO3 supports series, e.g. [_Methods of Humanity_](https://archiveofourown.org/series/1855237), which in some cases are more conveniently read as one long book.

It would be nice if such usecases were supported. Currently, these break my usual method of packaging all fics I'm tracking into epubs and running `fanficfare -u *.epub`. Especially in the case of a series of oneshots, this would require a separate step of checking whether there are any new stories in the series.

**Comment by sstabeler** [comment]
I'm pretty sure this is what getting urls from a webpage for an anthology epub is for. For Xenforo, barring possibly Xenforo 2, where  threads can be linked so they have unified threadmarks- which would presumably be handled already without needing a change ot the adapter- what exactly could FanficFare do?

**Comment by hseg** [comment]
I use the fanficfare CLI, it appears that anthology support is limited to the calibre plugin. Any docs on using the cli for this?

**Comment by JimmXinu** [comment]
Have you seen this [past issue](https://github.com/JimmXinu/FanFicFare/issues/253#issuecomment-438112194)?

**Comment by hseg** [comment]
Haven't seen it, seems like this will be a dissatisying WONTFIX. Any reason why further integration is undesirable? 

On December 24, 2020 3:09:57 AM GMT+02:00, Jim Miller <notifications@github.com> wrote:
>Have you seen this [past issue](https://github.com/JimmXinu/FanFicFare/issues/253#issuecomment-438112194)?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JimmXinu/FanFicFare/issues/615#issuecomment-750686065
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JimmXinu** [comment]
- I already provide an integrated solution to do this in the Calibre plugin version.
- I already provide all the tools needed for you to script it together yourself in CLI.
- And, I assume that anyone using CLI is both a) script savvy enough to handle it and b) picky enough that I would have to add tons of configuration options if I did integrate it.
