### ISSUE TITLE
Error 403: Forbidden on Fanfiction.net (2020)

### ISSUE THREAD

**Issue by themaster567** [JimmXinu/FanFicFare#616]
Per the inclusion of the date, this is a fresh instance of this bug that's unrelated to the ticket from 2013. 

Anytime I go to download a fanfiction from Fanfiction.net, I get the exact same errors for every single story.
![calibre_dgNS20pEAG](https://user-images.githubusercontent.com/8242023/102843268-daed9e00-43d6-11eb-89b9-4acdebfebbfc.png)
I'm not sure how to go about fixing this. I've waited days and it's still happening. For now, I'm just using Web2Epub for that site, but it's just not the same.

**Comment by JimmXinu** [comment]
Dup of #614
