### ISSUE TITLE
Lushstories.com, stories cut off

### ISSUE THREAD

**Issue by aemilstark** [JimmXinu/FanFicFare#617]
When I get a story from Lushstories.com, sometimes my story ends with "To continue reading this story you must be a member. Join for FREE here." I have an account but I can't find anywhere to enter the credentials. 

I'm using the latest Calibre Plugin

**Comment by JimmXinu** [comment]
I didn't write the code for that site, but I've sent a message to the developer who originally added it.

**Comment by gcomyn** [comment]
Ok... I looked at the code, and thinking back on when I wrote it, I remember that the site does not have a standardized chapter listing.... each "chapter" is considered a story on it's own... The way that I get around that is to use the 'anthology' function to download all of the chapters into one epub. That is the only way that I saw doing it. 

I looked at many different authors, and some of their stories are not linked in any way, so you have to enter the urls that you want to be 1 epub into the anthology function, then let it download them all for you. 

It also doesn't have a login function, so you don't need an account on the site to get the stories.

GComyn

**Comment by JimmXinu** [comment]
@gcomyn thinks it isn't needed and @aemilstark didn't include any examples, so I'm going to assume @gcomyn is correct.  

You can re-open this if you have specific examples.
