### ISSUE TITLE
Not really an issue, but an idea that could be explored: Possible Wayback Machine Functionality

### ISSUE THREAD

**Issue by Khrystarlite** [JimmXinu/FanFicFare#618]
Hello JimmXinu,

I was wondering if it was possible to implement a way to extract fics from the Wayback Machine. A fic I like can only be accessed this way and I figure it would be nice to be able to use the plugin to get essentially "lost fics" like it.

Thanks,
Khrystarlite

**Comment by Edocsil** [comment]
#595 

This has already been requested before, seeing the dates I'm guessing his answer hasn't changed.

**Comment by Khrystarlite** [comment]
Ok then. "Issue closed" I guess.

**Comment by Khrystarlite** [comment]
Ok. "Issue" close I guess.
Maybe I'll ask to fork/pull and see if I could give it a try.

**Comment by JimmXinu** [comment]
You are certainly welcome to try.  If you come up with a reasonable implementation, I'll be happy to include it.  I just don't want to spend my time on it.
