### ISSUE TITLE
CLI issue for AO3 stories

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#620]
I was trying to download

> https://archiveofourown.org/works/28002693

and I get the following

> Traceback (most recent call last):
>   File "c:\python3.7\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\python3.7\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "c:\Python3.7\Scripts\fanficfare.exe\__main__.py", line 7, in <module>
>   File "c:\python3.7\lib\site-packages\fanficfare\cli.py", line 327, in main
>     passed_personalini)
>   File "c:\python3.7\lib\site-packages\fanficfare\cli.py", line 421, in do_download
>     adapter.getStoryMetadataOnly()
>   File "c:\python3.7\lib\site-packages\fanficfare\adapters\base_adapter.py", line 297, in getStoryMetadataOnly
>     self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
>   File "c:\python3.7\lib\site-packages\fanficfare\adapters\base_adapter.py", line 381, in doExtractChapterUrlsAndMetadata
>     return self.extractChapterUrlsAndMetadata()
>   File "c:\python3.7\lib\site-packages\fanficfare\adapters\adapter_archiveofourownorg.py", line 253, in extractChapterUrlsAndMetadata
>     m = re.match(r'(?P<author>.*) \[archived by ?(?P<archivist>.*)\]',stripHTML(byline))
>   File "c:\python3.7\lib\site-packages\fanficfare\htmlcleanup.py", line 71, in stripHTML
>     retval = soup.get_text(strip=True)
> AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by jschpp** [comment]
AOE3 has problems right now
https://twitter.com/AO3_Status/status/1346311018063007744

**Comment by JimmXinu** [comment]
I'm able to download that story fine with CLI.  I'm inclined to agree with @jschpp.
