### ISSUE TITLE
.ini code only working for multi-chapter ao3 fics?

### ISSUE THREAD

**Issue by HappyFaceSpider** [JimmXinu/FanFicFare#624]
Basically, could someone help me with the .ini file in Calibre? Seriously, not sure where I should ask, I know exactly 0 about any programming and computer codes, so I am really out of my depth here. 

So, I'm trying to give the files prefix based on the category. Basically my idea is that if category of the fic is XYZ then the title of the fic should be changed to ABC.title. So I have this code:

```
replace_metadata: 
 category=>^(.*)$=>XYZ
 title=>^(.*)$=>ABC.\1&&category=>XYZ
```
This is literally ALL the code I used for tests, so nothing should be interfering. 

My issue is that the category is changed in ALL fics, but the title only in SOME. The only way to make it work on all fics is to remove the &&category part of the second line altogether, but I can't do it, because obviously I plan on having more than one category in the end.

All the stories affected are on Ao3, but I don't really use other websites, so the sample size outside Ao3 was very small. All of the affected fics seem to be only 1 chapter long (weather or not the fic is completed doesn't seem to have an effect). The titles of multi-chapter fics are changed as planned. This is extremely bizarre.

Also, ideally I would like to change the titles of anthologies too. But the code above doesn't work with them and nothing else I could come up with does either. I might be just too stupid for this.

**Comment by JimmXinu** [comment]
The most active FFF forum for that sort of question is [the plugin thread on Mobile Read](https://www.mobileread.com/forums/showthread.php?t=259221).

My time and energy for FFF is all being used up by the ffnet issue right now.

**Comment by HappyFaceSpider** [comment]
Ok, thx a lot, and sorry to bother you during yet another ffnet crisis. :)

**Comment by JimmXinu** [comment]
Configuration issue (probably), closed without prejudice.
