### ISSUE TITLE
list index out of range quotev.com

### ISSUE THREAD

**Issue by Taemaly** [JimmXinu/FanFicFare#625]
When try to download any book from www.quotev.comI get list index out of range  error ,examples https://www.quotev.com/story/13175583/Spring-Spiral  https://www.quotev.com/story/12550044/The-Attorney   .I am using latest version if calibre and fanficfare .Please help

**Comment by JimmXinu** [comment]
Test version posted: https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2

Note that those two stories appear to have some broken UTF8 in them.  I changed the default coding for the whole site to utf8:ignore.
