### ISSUE TITLE
Deleted a book and can't redownload it?

### ISSUE THREAD

**Issue by amoonandstars** [JimmXinu/FanFicFare#627]
I downloaded a book off of QuoteV a while back and today it updated. I tried updating the book, but the plugin acted like it didn't need to be updated (even though a new chapter was out). I tried uninstalling Calibre and this plugin and reinstalling each, but it still did the same thing. Then, I tried deleting the book to re-add it, but now it's acting like I have the book and I can't get it back. It keeps giving a notification saying "None of the 1 URLS/stories given can be/need to be downloaded. See log for details." I also tried downloading it and choosing the option "Add New Book" where it says "If Story Already Exists?"

**Comment by JimmXinu** [comment]
Dup of #625

If you still have the problem after installing the latest test version you may reopen this issue--as long as you include the story URL and the error message.

**Comment by amoonandstars** [comment]
I updated the plugin within Calibre and have restarted the program, and I have also deleted and re-added the updated version of FanFicFare, but still get the same issue. Here is the error message:
<img width="329" alt="Help" src="https://user-images.githubusercontent.com/77309051/104259015-d0567f80-543d-11eb-9487-16bd000d68d8.PNG">

and the URL to the story: https://www.quotev.com/story/12549782

**Comment by amoonandstars** [comment]
I found the story in my recycle bin, so I have it back, but I still can't update it. I get the error message still that I screenshot above.

**Comment by JimmXinu** [comment]
I'm able to download it fine using the latest test version.

Did you install the test version posted at: https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2 ?
And have you clicked the button that says View log to see the actual error message?

**Comment by amoonandstars** [comment]
Thank you! I didn't realize there was another place to download FanFicFare, I've just been using this site and Calibre. The link you provided helped, so thank you! :)
