### ISSUE TITLE
fanfics.me error

### ISSUE THREAD

**Issue by Voblaa** [JimmXinu/FanFicFare#633]
When updating fanfic from https://fanfics.me/, an authorization error occurs. But when downloading with a manual login, there is no error.

**Comment by JimmXinu** [comment]
Please provide a story URL and a more detailed description of what you mean.

**Comment by Voblaa** [comment]
I have filled in the login and password for the site in the personal.ini file.
For example, for https://fanfics.me/fic116374
If I click "Update existing books" I get an authorization error. But if I use "Download from URL" and enter my login and password, then everything is downloaded fine.

**Comment by JimmXinu** [comment]
Test versions with fix posted to the usual places.
