### ISSUE TITLE
Suggestion: Rewrite Cloudflare Challenge error

### ISSUE THREAD

**Issue by chocolatechipcats** [JimmXinu/FanFicFare#634]
If I posted this in the general ffnet thread, it might get lost. And of course, this is only valid _if_ Cloudscraper is reimplemented.

I noticed that when ffnet went into under-attack mode, several users were confused about the  _Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version_ thinking the free version bit referred to either FFF itself or even ffnet. Which is actually a bit fair, because there's no indication that an embedded module is returning the error instead of FFF itself.

It's not unlikely that ffnet (or even other sites) to turn on the under-attack mode in the future in response to a DDoS or server migration or something. Rewriting the message would help. At least removing the last sentence, and indicating that the user should wait a few days before trying again.

Thanks for all your work!

**Comment by JimmXinu** [comment]
I thought of that too, it probably good you suggested it here; because I forgot it again.
