### ISSUE TITLE
"A Sword Without a Hilt" causes Mobi encoding to crash after the download phase is done

### ISSUE THREAD

**Issue by RMGiroux** [JimmXinu/FanFicFare#636]
First, let me admit that [ASWaH](https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/) is absurdly over-large, so it's not exactly a critical bug that FFF choked on it, but it IS a bug :)

FFF was able to download all 547 pages of Reader Mode posts and 4.7M words of _A Sword Without a Hilt_ from SufficientVelocity.

However, it looks like the Mobi encoding failed with a recursion error, after 9h of download/processing time.

Any idea what might have caused this issue, apart from this particular quest being unreasonably large?

(FWIW, retrying with "Epub" as the target succeeded in just over 3h, resulting in a "small" 82Mb EPUB file :) )
``
Download 1 FanFiction Book(s)
FFF: INFO: 2021-01-17 21:59:30,166: calibre_plugins.fanficfare_plugin.jobs(53): FanFicFare v3.28.0
FFF: INFO: 2021-01-17 21:59:30,166: calibre_plugins.fanficfare_plugin.jobs(57): Adding jobs for URLs:
FFF: INFO: 2021-01-17 21:59:30,167: calibre_plugins.fanficfare_plugin.jobs(59): https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/
FFF: INFO: 2021-01-18 07:04:56,149: calibre_plugins.fanficfare_plugin.jobs(95): Logfile for book ID None (A Sword Without a Hilt: A Song of Ice and Fire/D&D 3.5 Crossover)
FFF: INFO: 2021-01-18 07:04:56,163: calibre_plugins.fanficfare_plugin.jobs(96): url:(https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/) id:(None)
FFF: INFO: 2021-01-17 21:59:31,333: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(439): url: https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/
FFF: DEBUG: 2021-01-17 21:59:31,334: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1199): #####################################
pagecache(GET) HIT: https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/
FFF: DEBUG: 2021-01-17 21:59:31,334: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1029): Encoding:utf8
FFF: INFO: 2021-01-17 21:59:31,337: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(444): use useurl: https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/
FFF: DEBUG: 2021-01-17 21:59:39,021: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1199): #####################################
pagecache(GET) HIT: https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/threadmarks
FFF: DEBUG: 2021-01-17 21:59:39,022: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1029): Encoding:utf8

# .... LOTS of lines omitted

FFF: DEBUG: 2021-01-18 05:19:35,433: calibre_plugins.fanficfare_plugin.fanficfare.writers.writer_mobi(167): Writing chapter text for: Informational - Imperial Airforce Equipment
FFF: DEBUG: 2021-01-18 05:19:35,433: calibre_plugins.fanficfare_plugin.fanficfare.writers.writer_mobi(167): Writing chapter text for: Staff Post - Warning: Warning
FFF: DEBUG: 2021-01-18 05:19:35,433: calibre_plugins.fanficfare_plugin.fanficfare.writers.writer_mobi(167): Writing chapter text for: Staff Post - No. Just no.
**FFF: INFO: 2021-01-18 07:04:50,769: calibre_plugins.fanficfare_plugin.jobs(350): Exception:** {'title': 'A Sword Without a Hilt: A Song of Ice and Fire/D&D 3.5 Crossover', 'author_sort': ['DragonParadox'], 'author': ['DragonParadox'], 'comments': '<div class="bbWrapper"><div style="text-align: center"><span style="font-size: 1.375rem">A Sword Without a Hilt: A Song of Ice and Fire/D&amp;D 3.5 Crossover</span>\u200b</div><br/>\nIn a world where magic has all but guttered to ashes, becoming the fare of charlatans, petty conjurers, and ragged illusionists, a mighty change is stirring. From small and fragile sparks a great blaze will be reborn and men will again look in wonder awe and terror at those who would dare to call on secret powers. Heroes and fiends, champions and monsters, soon all will walk under the light of common day once more.</div>', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': None, 'begin': None, 'end': None, 'comment': 'maximum recursion depth exceeded while calling a Python object', 'url': 'https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/', 'site': 'forums.sufficientvelocity.com', 'series': '', 'added': False, 'pubdate': datetime.datetime(2016, 3, 24, 19, 44, 52, tzinfo=SafeLocalTimeZone()), 'publisher': 'forums.sufficientvelocity.com', 'uniqueurl': 'https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/[None-None]', 'listorder': 0, 'collision': 'Overwrite if Newer', 'is_adult': False, 'username': 'NoneGiven', 'password': '', 'icon': 'dialog_error.png', 'all_metadata': {'category': '', 'genre': "100% High Octane Dragon Fuel, A Song Of Ice And Fire, Asoiaf, Ave Corvidae, Battle Action Dragon Diplomacy, Best Sister, Bureaucromancy, D&D 3.5, Delicious Soul-Stuff, Dragon Dreams Come True, Dragon Ta'veren, Game Of Thrones, Greatest Uncle, Hubris Is A Coward's Word, In Defiance Of Gods And Men, Mammon's Folly, Mutually Assured Mage's Disjunction, Qm Murderhobo, Top Tier Coatl", 'characters': '', 'ships': '', 'warnings': '', 'extratags': 'FanFiction', 'author': 'DragonParadox', 'authorId': 'dragonparadox.5829', 'authorUrl': 'https://forums.sufficientvelocity.com//members/dragonparadox.5829/', 'lastupdate': 'Last Update Year/Month: 2021/01, Last Update: 2021/01/17', 'series': '', 'seriesUrl': '', 'language': '', 'status': 'In-Progress', 'datePublished': '2016-03-24 19:44', 'dateUpdated': '2021-01-17 13:53', 'dateCreated': '2021-01-17 21:56:19', 'rating': '', 'numChapters': '5,581', 'numWords': '', 'words_added': '', 'site': 'forums.sufficientvelocity.com', 'publisher': 'forums.sufficientvelocity.com', 'storyId': '27579', 'title': 'A Sword Without a Hilt: A Song of Ice and Fire/D&D 3.5 Crossover', 'titleHTML': "<a class='titlelink' href='https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/'>A Sword Without a Hilt: A Song of Ice and Fire/D&D 3.5 Crossover</a>", 'storyUrl': 'https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/', 'sectionUrl': 'https://forums.sufficientvelocity.com/threads/27579/', 'description': '<div class="bbWrapper"><div style="text-align: center"><span style="font-size: 1.375rem">A Sword Without a Hilt: A Song of Ice and Fire/D&D 3.5 Crossover</span>\u200b</div><br/>\nIn a world where magic has all but guttered to ashes, becoming the fare of charlatans, petty conjurers, and ragged illusionists, a mighty change is stirring. From small and fragile sparks a great blaze will be reborn and men will again look in wonder awe and terror at those who would dare to call on secret powers. Heroes and fiends, champions and monsters, soon all will walk under the light of common day once more.</div>', 'formatname': '', 'formatext': '', 'siteabbrev': 'fsv', 'version': 'FanFicFare v3.28.0', 'authorHTML': "<a class='authorlink' href='https://forums.sufficientvelocity.com//members/dragonparadox.5829/'>DragonParadox</a>", 'seriesHTML': '', 'langcode': '', 'output_css': '', 'cover_image': '', 'tagsfromtitledetect': '', 'tagsfromtitle': '', 'forumtags': "100% High Octane Dragon Fuel, A Song Of Ice And Fire, Asoiaf, Ave Corvidae, Battle Action Dragon Diplomacy, Best Sister, Bureaucromancy, D&D 3.5, Delicious Soul-Stuff, Dragon Dreams Come True, Dragon Ta'veren, Game Of Thrones, Greatest Uncle, Hubris Is A Coward's Word, In Defiance Of Gods And Men, Mammon's Folly, Mutually Assured Mage's Disjunction, Qm Murderhobo, Top Tier Coatl", 'parentforums': '', 'threadmarks_title': 'A Sword Without a Hilt: A Song of Ice and Fire/D&D 3.5 Crossover', 'threadmarks_description': '<div class="bbWrapper"><div style="text-align: center"><span style="font-size: 1.375rem">A Sword Without a Hilt: A Song of Ice and Fire/D&D 3.5 Crossover</span>\u200b</div><br/>\nIn a world where magic has all but guttered to ashes, becoming the fare of charlatans, petty conjurers, and ragged illusionists, a mighty change is stirring. From small and fragile sparks a great blaze will be reborn and men will again look in wonder awe and terror at those who would dare to call on secret powers. Heroes and fiends, champions and monsters, soon all will walk under the light of common day once more.</div>', 'threadmarks_status': 'Incomplete'}, 'tags': ['Ave Corvidae', 'Game Of Thrones', "Mammon's Folly", 'FanFiction', 'Qm Murderhobo', 'D&D 3.5', "Mutually Assured Mage's Disjunction", 'In-Progress', 'Delicious Soul-Stuff', 'Bureaucromancy', 'Battle Action Dragon Diplomacy', 'Top Tier Coatl', 'Dragon Dreams Come True', "Dragon Ta'veren", 'Asoiaf', 'In Defiance Of Gods And Men', "Hubris Is A Coward's Word", 'Best Sister', 'A Song Of Ice And Fire', 'Greatest Uncle', '100% High Octane Dragon Fuel'], 'updatedate': datetime.datetime(2021, 1, 17, 13, 53, 49, tzinfo=SafeLocalTimeZone()), 'timestamp': datetime.datetime(2021, 1, 17, 21, 59, 31, 326083, tzinfo=SafeLocalTimeZone()), 'calibre_columns': {}, 'outfile': '/var/folders/pp/0smt01617zg8zbw_v5v5w9gm0000gn/C/calibre_5.6.0_tmp_hgntaotk/fanficfare_5v7013zo/A Sword Without a Hilt_ A Song of Ice and Fire_D&D 3.5 Crossover-DragonParadox-qhpk3vu3.mobi'}:maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.jobs", line 248, in do_download_for_worker
    writer.writeStory(outfilename=outfile, forceOverwrite=True)
  File "calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer", line 230, in writeStory
    self.writeStoryImpl(outstream)
  File "calibre_plugins.fanficfare_plugin.fanficfare.writers.writer_mobi", line 180, in writeStoryImpl
    mobidata = c.ConvertStrings(files)
  File "calibre_plugins.fanficfare_plugin.fanficfare.mobi", line 70, in ConvertStrings
    self._ConvertStringsToFile(html_strs, out)
  File "calibre_plugins.fanficfare_plugin.fanficfare.mobi", line 139, in _ConvertStringsToFile
    self._ConvertStringToFile(tmp, out_file)
  File "calibre_plugins.fanficfare_plugin.fanficfare.mobi", line 147, in _ConvertStringToFile
    data = ensure_binary(html.CleanHtml())
  File "calibre_plugins.fanficfare_plugin.fanficfare.mobihtml", line 149, in CleanHtml
    return self._ReplaceAnchorStubs()
  File "calibre_plugins.fanficfare_plugin.fanficfare.mobihtml", line 77, in _ReplaceAnchorStubs
    assembled_text = ensure_binary(unicode(self._soup))
  File "bs4/element.py", line 1491, in __unicode__
  File "bs4/__init__.py", line 744, in decode
  File "bs4/element.py", line 1598, in decode
... # LOTS of lines omitted
  File "bs4/element.py", line 1598, in decode
  File "bs4/element.py", line 1692, in decode_contents
  File "bs4/element.py", line 1598, in decode
  File "bs4/element.py", line 1692, in decode_contents
  File "bs4/element.py", line 1555, in decode
  File "bs4/formatter.py", line 113, in attributes
RecursionError: maximum recursion depth exceeded while calling a Python object

FFF: INFO: 2021-01-18 07:04:56,179: calibre_plugins.fanficfare_plugin.jobs(100): 
Download Results:
Error https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/ maximum recursion depth exceeded while calling a Python object

FFF: INFO: 2021-01-18 07:04:56,179: calibre_plugins.fanficfare_plugin.jobs(124): 
Error
https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/
``

**Comment by JimmXinu** [comment]
FFF's mobi output is... poor.  There's even an [FAQ about it](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-doesnt-the-mobi-output-show-chapters-markers-on-the-progress-bar-in-kindle-or-include-images).  And mobi is a poor format, but that's another story.

The FFF mobi code predates my involvement in the project some 10 years ago.  I've tried working on it several times over the years and rarely had good results.  It is kept in FFF for the benefit of CLI users who don't want to Calibre around to convert with.

Since you are already using the Calibre plugin, IMO, there is no good reason to use FFF's mobi output.  Use the epub output (which also allows updates) and Calibre's far superior conversion code to make a Kindle format--preferably something newer than mobi, like azw3.
