### ISSUE TITLE
Hiding MOBI output in the Calibre plugin

### ISSUE THREAD

**Issue by chocolatechipcats** [JimmXinu/FanFicFare#640]
The FAQ says that the MOBI output is not good, and in a recent post either here or on MobileRead I think it was said it was only kept in place for the CLI users who don't have Calibre handy. 

In that case, would it be feasible to hide the MOBI output in only the Calibre plugin, where a better convert option would be available anyways? There's probably a bunch of reasons to not do this or just not worth the effort.

Thanks for all your work!

**Comment by JimmXinu** [comment]
Not interested.
