### ISSUE TITLE
Bug in commit 6e68624f2a

### ISSUE THREAD

**Issue by sidney** [JimmXinu/FanFicFare#641]
Commit 6e68624f2a has a bug in calibre-plugin/jobs.py line 311. It is missing `'failed':adapter.story.chapter_error_count,` that is referred to in the previous line, causing an exception if there is a chapter failure in an update.

**Comment by JimmXinu** [comment]
Crap, I ran across that myself and then forgot to fix it!  Thanks for reminding me.
