### ISSUE TITLE
Suggestion: "No Update" status in FFF log

### ISSUE THREAD

**Issue by chocolatechipcats** [JimmXinu/FanFicFare#643]
This is very low-priority/opinion thing.

When viewing a FanFicFare log, the status column shows currently shows "Bad" when there's no update (either "not overwriting" or "already contains X chapters").

My suggestion, if it's feasible and not too much work, is to show "No Update" instead. This would be useful for those who skim the logs to check for errors.

Thank you!

**Comment by JimmXinu** [comment]
Not interested.
