### ISSUE TITLE
styles are not saved for span tags for forums.sufficientvelocity.com

### ISSUE THREAD

**Issue by lartaud** [JimmXinu/FanFicFare#646]
Hello!

The epub generated by FanFicFare does not contain the size and color styles in spans.

Version: 
```
$ fanficfare -v
Version: 3.29.6
```

How to reproduce:
1. save `https://forums.sufficientvelocity.com/threads/taylor-is-doomed.58654/page-107#post-15033611` with any web browser
2. generate an epub file with `$ fanficfare -p https://forums.sufficientvelocity.com/threads/taylor-is-doomed.58654/`
3. unzip the epub and open file `OEBPS/file0014.xhtml` and the file from the web browser with any text editor
4. look for the string `Fires of Hell are hers to control` in both files
5. the 3 spans just before look like `<span class="fixed-color"><b><span><span>` in `OEBPS/file0014.xhtml` instead of `<span class="fixed-color" style="color: #CE181E"><b><span style="font-size: 1.125rem"><span style="font-family: 'book antiqua'">` as saved by the browser.

Regards.

**Comment by JimmXinu** [comment]
Working as designed.  From `defaults.ini`:
```
## Some attributes cause problems for EBook readers.  By default,
## FanFicFare will remove all attributes except the ones specified
## from all tags.  (The only exception is that <img> tags will also
## keep src, alt and longdesc attributes.  data-orighref is used by
## internalize_text_links to preserve links when chapters are
## inserted.)
## Example: To add 'style', 'title' and 'align' to the list to keep,
## in your personal.ini [defaults] put:
## add_to_keep_html_attrs:,style,title,align
keep_html_attrs:href,name,class,id,colspan,rowspan,data-orighref
```
You can use INI sections to control whether you allow inline styles everywhere, for some sites, or specific stories.

See also [wiki on add_to_](https://github.com/JimmXinu/FanFicFare/wiki/INI-File#add_to_keyword).

[This post](https://www.mobileread.com/forums/showthread.php?p=3748992&highlight=keep_html_attrs#post3748992) in the plugin discussion thread explains about already download chapters.
