### ISSUE TITLE
Make parsing of URLs more robust

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#652]
```
tmp@stitny$ fanficfare 'http://www.sugarquill.net/read.php?chapno=1&storyid=619'
Bad Story URL: (http://www.sugarquill.net/read.php?chapno=1) for site: (www.sugarquill.net)
    Example: (http://www.sugarquill.net/read.php?storyid=1234)
tmp@stitny$
```

This seems to me that FanFicFare parses URL using some string manipulation, not correct URL parsing. If those are used, there shouldn’t be any confusion about the value of `'storyid'` parameter:
```python
In [3]: urllib.parse.urlparse('http://www.sugarquill.net/read.php?chapno=1&storyid=619')
Out[3]: ParseResult(scheme='http', netloc='www.sugarquill.net', path='/read.php', params='', query='chapno=1&storyid=619', fragment='')

In [4]: rs = urllib.parse.urlparse('http://www.sugarquill.net/read.php?chapno=1&storyid=619')

In [5]: rs.query
Out[5]: 'chapno=1&storyid=619'

In [6]: urllib.parse.parse_qs(rs.query)
Out[6]: {'chapno': ['1'], 'storyid': ['619']}

In [7]:
```

**Comment by JimmXinu** [comment]
I suppose you are technically correct. 

However, for historical reasons, each of the 100+ sites in FFF has its own regular expression for matching story URLs.  And in practice, each site is pretty consistent with how it orders its parameters.  For example, all the links I see on sugarquill.net are `storyid`, then `chapno`.

If you'd like to take the time to apply this to the adapter for sugarquill.net (a site who's last story update was in in 2008), you are welcome to do so.

If you'd like to take the time to fix it in FFF as a general solution and test it against all supported sites, you would have to justify to me why it is important and I would scrutinize your code much more closely.

I have no interest in doing either myself.

**Comment by mcepl** [comment]
Right, I forgot that FanFicFare doesn’t have a proper test suite (and THAT problem I will certainly not fix). Let me file a pull request just for SugarQuill and SIYE (where I have met this problem before) and leave it at that.

**Comment by JimmXinu** [comment]
See #653
