### ISSUE TITLE
Caching: "Update Existing Fic" looks for only first chapter in cache

### ISSUE THREAD

**Issue by chocolatechipcats** [JimmXinu/FanFicFare#655]
Here's a situation I ran into yesterday. I discovered this when I tried to update a fanfic while ffnet was doing its Cloudflare thing. 

1. Find a ffnet fanfic and download it. Clear the browser cache. Use ebook-edit to delete the last chapter, (Or just have a fic that needs to be updated.)
3. Set use_browser_cache_only:true to avoid it falling back.
4. Open _only_ the last chapter of the fanfic in the browser. 
5. Take the fanfic in Calibre and use "Update Existing Fic" on it.

Expected result: It detect the last chapter in the browser cache and try to grab it.
Actual result: It looks for /s/xxxxxxxx/1/ and since it's not present in cache, just fails completely.

It works as expected if using Download from URLs on the target chapter URL.

**Comment by JimmXinu** [comment]
Correct.  Update Existing Fic uses the 'canonical' story URL, which for ffnet is chapter one.  That's where it looks for metadata and the list of chapters.  The 'downloader' parts of FFF and the 'browser cache' parts are not as closely tied as you seem to think.

You can either use URL or also open the first chapter in the browser.  

Working as intended.

**Comment by chocolatechipcats** [comment]
apologies for misunderstanding!
