### ISSUE TITLE
Help with questionablequesting

### ISSUE THREAD

**Issue by TheOne320** [JimmXinu/FanFicFare#659]
I am trying to download the complete story of "With This Ring (Young Justice SI) (Story Only)"
Link: https://forum.questionablequesting.com/threads/with-this-ring-young-justice-si-story-only.8961/

The problem is that fanficfare only downloads the first part of each chapter. For example the first part of chapter 1 ends with:
"Now to find somewhere familiar and see if it exists." and the next part should continue with "Finding Eastbourne isn't that hard.", but fanficfare does not download the further parts of chapter one and goes straight to the first part of chapter 2 "Welcome to Happy Hour".

What do I have to do to make it download everything correctly?

**Comment by Edocsil** [comment]
The author hasn't threadmarked most chapters so there's nothing that can be done.

Download it from the normal thread instead.

**Comment by Twilight666** [comment]
It's less he hasn't threadmarked most chapters and more like the story is organized in episodes so he only threadmarked the 107 chapters that mark the start of each episode instead of the full **2745** individual chapters

**Comment by TheOne320** [comment]
Everything is on questionablequesting. Each time he moved forums he revised the story.

**Comment by Twilight666** [comment]
No it isn't. The only QQ main thread starts halfway through Z-E-R-O (the episode with the character that changed gender that made everyone on SV crazy)

Yes eveything **is** on QQ, but that applies to the **story only thread**. But he hasn't threadmarked everything on that. Just the posts that mark the starts of the episodes
So the only way to download the story only thread would be if FFF allowed to download an entire thread (not just story posts)
And that's not happening

**Comment by Edocsil** [comment]
From Fanficfare's point of view each post is a chapter, and needs to be threadmarked. If you open the read mode of the forum you will see how it only shows what's threadmarked.

It's an issue that the author has to fix, as fanficfare can't download all posts indiscriminately, only what's in the threadmarks.

After checking the main thread it's clear everything is a mess.. without a proper TOC you will need to do lots of manual work.

**Comment by TheOne320** [comment]
OK thanks, I will have to read on my pc / phone until I reach the current chapters.

**Comment by Edocsil** [comment]
The main thread has links to epubs for up to chapter 72, I don't know if that is what's missing from QQ, but if you don't care about more than just reading in a kindle or something just download those and then use FFF for what's on QQ. Alternatively check if the SV is threadmarked. You will still end up with two epubs though.

**Comment by TheOne320** [comment]
Yeah, I saw the epubs and downloaded them, but they are not up to date with the newest revision on QQ. I will just read directly on the site until I can read the rest on my Kindle. Thanks anyway.

**Comment by JimmXinu** [comment]
Looks like this has already been answered.  Thanks, @Edocsil and @Twilight666, for explaining.
