### ISSUE TITLE
Download series of stories from AO3

### ISSUE THREAD

**Issue by kyoam** [JimmXinu/FanFicFare#666]
we know that fff can download individual stories but I do have a question

Ao3 has series of linked stories for example

https://archiveofourown.org/series/836265

which has 19 parts/stories to it

so does fan fic fare have or can receive eventually the functionality to input a series link for archive of our own and have fan fic fare download all relevant parts?

because as far as I know the only way now is to copy and paste each of the 19 fic links in order to get a series downloaded. through yes, but very time consuming.

**Comment by JimmXinu** [comment]
Both FanFicFare Calibre plugin and CLI have features for fetching story URLs from a web page URL and automatically downloading the stories found on the page.  _Get Story URLs from Web Page_ in plugin and the `-l/--list` and `--download-list` options in CLI.

The FanFicFare Calibre plugin also has an Anthology feature to automatically combine those stories into a single epub using the EpubMerge plugin.  _Get Story URLs from Web Page_ offers you the option to do individual books for an Anthology, or there is the _Anthology Options_ > _Make Anthology Epub from Web Page_ option.  Past issues you've opened suggest you already use the plugin.

**Comment by kyoam** [comment]
thanks for the info. trying it out now.
