### ISSUE TITLE
Secondary fetcher does not respect user_agent config option

### ISSUE THREAD

**Issue by ctoth** [JimmXinu/FanFicFare#669]
If the application does not find an appropriate adapter for retrieving a URL in geturls.py it falls back to an Urllib2-based opener (line 48)

This opener does not use the configured user agent.
I'm not quite sure how to get at the user agent set in config, but a line like 
```
        opener.addheaders = [('User-Agent', user_agent)]
```

Should do the trick
My overall use case is to attempt to use the download_links option with topwebfiction.com. This doesn't work for a couple reasons yet, but this is the first and easiest blocker to resolve :)

**Comment by JimmXinu** [comment]
Fair point.  

Are you using the Calibre Plugin or CLI?  And can you provide a specific URL to test with?

**Comment by ctoth** [comment]
﻿
I’m using the CLI
What I’m trying to do is to point FFF at a page of links to good fiction to have it automatically download it all.
I have this working with Royal Road like so:
```
fanficfare -u --download-list https://www.royalroad.com/fictions/weekly-popular
```
I’d like to also go:
```
fanficfare -u --download-list https://www.topwebfiction.com
```
I’m not sure if this use case is supported, but noticed the user agent bug while working on it.
 
I don’t expect FFF to be able to parse the Topwebfiction page. Only to look through the HTML for links to supported stories and automatically download them. Is this possible?
 
 
My personal.ini looks like:
```
[defaults]
is_adult: true
slow_down_sleep_time: 1
connect_timeout: 10.0
progressbar: true
mark_new_chapters: latestonly
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
use_browser_cache: true
browser_cache_path: C:\Users\Q\AppData\Local\Google\Chrome\User Data\Default\Cache
output_filename: c:/users/q/fanfic/${site}/${author}/${title}-${storyId}${formatext}
```

**Comment by JimmXinu** [comment]
16f9081a80f601e7cec3dd4243762569e1deadee

I've uploaded a test CLI version:

> Test version of CLI for pip install:  You'll have to get it from the
> testpypi repository.  This works for me on Debian:
>
> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

I'm able to fetch pages from topwebfiction.com now.  

However, I don't think it's actually going to help you a lot--all of the list pages I see on that site only link to individual story pages on topwebfiction.com.  You have to go to the individual story pages to see links to the story sites.

And I don't see any fanfic stories listed at all, which is FFF's forte.
