### ISSUE TITLE
fiction.live last update not being included?

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#672]
@HazelSh,

There's a [report on MR](https://www.mobileread.com/forums/showthread.php?p=4103984&postcount=5691) that the last update isn't always being included in fiction.live downloads.

Do you have time to take a look at it?

**Comment by HazelSh** [comment]
Will do.

**Comment by HazelSh** [comment]
Had an off-by-one error in the interaction between the most-recent-chuck timestamp tracker and the add_chapter_url function. Feeling a bit silly. Gonna go update the fictionlive stories I'm following. 

Thanks to chrnno on mobileread for the minimal test case, which made isolating the issue very simple. 

I believe that the difference between the two offered test cases is that, for the other story where the issue wasn't happening, the most recent update was an appendix -- those hit a slightly different code path which didn't have the bug.

**Comment by JimmXinu** [comment]
@HazelSh, Thanks for taking care of this!

**Comment by JimmXinu** [comment]
Test versions up in the usual places.

**Comment by HazelSh** [comment]
No problem.
