### ISSUE TITLE
some fiction.live requests failing with HTTP 400: bad request

### ISSUE THREAD

**Issue by HazelSh** [JimmXinu/FanFicFare#674]
Give me a bit to look into this. I suspect it's related to the requests change in 4.0.

It's not specific to particular stories or urls -- retrying has worked pretty well.

**Comment by JimmXinu** [comment]
Having any luck with this?  

I wouldn't bother you about it, but it's about time for the monthly FFF release.  I haven't seen any reports about this from anyone else, so I'm okay with releasing without it.

**Comment by HazelSh** [comment]
No luck. Been distracted by other things. It's been working fine on my desktop with a recent test version that includes the recent fanficfare changes, so I'm thinking the issue is local to my dev setup on my laptop. 

Feel free to close as couldn't-reproduce or something like that.

**Comment by HazelSh** [comment]
Actually, I will.

**Comment by JimmXinu** [comment]
Okay, thanks.
