### ISSUE TITLE
[Feature Request] Add Support for Override Title

### ISSUE THREAD

**Issue by Chirishman** [JimmXinu/FanFicFare#676]
I'd like support for the ability to override the title of a book in a way that persists between updates.

This is particularly needed for XenForo forums like SpaceBattles and SufficientVelocity where the regex more than occasionally will mangle a title. I can correct them in the "Title" field of Calibre manually and I can correct them in the epub itself by manually editing the epub but as soon as I update the fic the old messed up title is back (in the epub itself) and that's what I see when I load the ebook onto my reader.

**Comment by JimmXinu** [comment]
This is already possible with existing features.  Here are a couple examples from my own `personal.ini` settings:
```
[https://forums.spacebattles.com/threads/323254/]
add_to_replace_metadata:
 title=>^.*$=>Queen of the Swarm - SB

[https://forums.spacebattles.com/threads/tiamat-worm-alt-power.799148/]
add_to_replace_metadata:
 title=>^.*$=>Tiamat
```
For the one story only, the entire title is replaced with what comes after the final `=>`.  It is applied when a story is downloaded or updated, including 'Update Epub Always'.

There are wiki pages about [ini files](https://github.com/JimmXinu/FanFicFare/wiki/INI-File) and [replace_metadata](https://github.com/JimmXinu/FanFicFare/wiki/ReplaceMetadata) for all the details.

If you don't want to use `personal.ini` settings for some reason, you could instead use the 'New Only' setting for Title on the Standard Columns tab of FFF plugin settings.  FFF would not update the title as it appears in Calibre anymore and when Calibre sends your email to a book reader, Calibre's title would be used.  However, it would _not_ do anything about the title inside the pub in the title page.  It would also affect _all_ FFF downloads, not just specific ones.
