### ISSUE TITLE
Literotica download error 

### ISSUE THREAD

**Issue by dakswiggin** [JimmXinu/FanFicFare#679]
Calibre 5.14
Fanficfare 4.1.2

Author page https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions
Story pages https://www.literotica.com/s/lady-pixie-ch-01-bella (first in series) and https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt (last in series)
When attempting to download via both story links getting error 'Couldn't find story <https://www.literotica.com/s/lxxx (story page link)> on author's page <https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions>'

<details>
  <summary>Debug log below</summary>

EpubMerge: DEBUG: 2021-03-31 12:05:42,294: calibre_plugins.epubmerge.epubmerge_plugin(158): macmenuhack file_path:D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\fanficfare_macmenuhack.txt
FFF: DEBUG: 2021-03-31 12:05:42,302: calibre_plugins.fanficfare_plugin.fff_plugin(222): Plugin FanFicFare macmenuhack file_path:D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 5.14 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Count Pages (1, 11, 0) && EpubMerge (2, 11, 0) && FanFicFare (4, 1, 2) && Generate Cover (2, 0, 2)
calibre 5.14 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Count Pages (1, 11, 0) && EpubMerge (2, 11, 0) && FanFicFare (4, 1, 2) && Generate Cover (2, 0, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.84180790960451 x 91.89949748743719
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.58] db initialized
[0.58] Constructing main UI...
[2.44] main UI initialized...
[2.44] Hiding splash screen
Starting QuickView
FFF: DEBUG: 2021-03-31 12:07:21,303: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica(37): LiteroticaComAdapter:__init__ - url='https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt'
FFF: DEBUG: 2021-03-31 12:07:22,168: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica(37): LiteroticaComAdapter:__init__ - url='https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt'
FFF: DEBUG: 2021-03-31 12:07:22,169: calibre_plugins.fanficfare_plugin.fff_plugin(1110): FanFicFare v4.1.2
FFF: DEBUG: 2021-03-31 12:07:22,185: calibre_plugins.fanficfare_plugin.fff_plugin(1231): prep_download_loop url:https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt
FFF: DEBUG: 2021-03-31 12:07:22,198: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica(37): LiteroticaComAdapter:__init__ - url='https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt'
FFF: DEBUG: 2021-03-31 12:07:22,201: calibre_plugins.fanficfare_plugin.fanficfare.configurable(979): use_cloudscraper:
FFF: DEBUG: 2021-03-31 12:07:22,201: calibre_plugins.fanficfare_plugin.fanficfare.configurable(998): use_browser_cache:
FFF: DEBUG: 2021-03-31 12:07:22,201: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1012): use_basic_cache:true
FFF: DEBUG: 2021-03-31 12:07:22,202: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(234): 
========== MISS (GET) BasicCache
https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt
FFF: DEBUG: 2021-03-31 12:07:22,203: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(441): 
---------- REQ (GET) RequestsFetcher
https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt
D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\FanFicFare.zip\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.literotica.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
FFF: DEBUG: 2021-03-31 12:07:25,959: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(447): response code:200
FFF: DEBUG: 2021-03-31 12:07:25,960: calibre_plugins.fanficfare_plugin.fanficfare.requestable(50): Encoding:utf8
FFF: DEBUG: 2021-03-31 12:07:25,961: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica(148): set opened url:https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt
FFF: DEBUG: 2021-03-31 12:07:26,094: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(234): 
========== MISS (GET) BasicCache
https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions
FFF: DEBUG: 2021-03-31 12:07:26,094: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(441): 
---------- REQ (GET) RequestsFetcher
https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions
D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\FanFicFare.zip\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.literotica.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
FFF: DEBUG: 2021-03-31 12:07:26,548: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(447): response code:200
FFF: DEBUG: 2021-03-31 12:07:26,549: calibre_plugins.fanficfare_plugin.fanficfare.requestable(50): Encoding:utf8
FFF: ERROR: 2021-03-31 12:07:26,843: calibre_plugins.fanficfare_plugin.dialogs(721): Exception: {'title': 'Unknown', 'author_sort': ['Unknown'], 'author': ['Unknown'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': None, 'begin': None, 'end': None, 'comment': "Couldn't find story <https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt> on author's page <https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions>", 'url': 'https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt', 'site': 'literotica.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': None, 'uniqueurl': 'https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt[None-None]', 'listorder': 0, 'collision': 'Update EPUB if New Chapters'}:Couldn't find story <https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt> on author's page <https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions>
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 708, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1324, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1196, in get_story_metadata_only
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 308, in getStoryMetadataOnly
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 412, in doExtractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica", line 197, in extractChapterUrlsAndMetadata
calibre_plugins.fanficfare_plugin.fanficfare.exceptions.FailedToDownload: Couldn't find story <https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt> on author's page <https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions>
FFF: DEBUG: 2021-03-31 12:08:28,307: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica(37): LiteroticaComAdapter:__init__ - url='https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt'
FFF: DEBUG: 2021-03-31 12:08:29,092: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica(37): LiteroticaComAdapter:__init__ - url='https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt'
FFF: DEBUG: 2021-03-31 12:08:29,093: calibre_plugins.fanficfare_plugin.fff_plugin(1110): FanFicFare v4.1.2
FFF: DEBUG: 2021-03-31 12:08:29,108: calibre_plugins.fanficfare_plugin.fff_plugin(1231): prep_download_loop url:https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt
FFF: DEBUG: 2021-03-31 12:08:29,118: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica(37): LiteroticaComAdapter:__init__ - url='https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt'
FFF: DEBUG: 2021-03-31 12:08:29,120: calibre_plugins.fanficfare_plugin.fanficfare.configurable(979): use_cloudscraper:
FFF: DEBUG: 2021-03-31 12:08:29,121: calibre_plugins.fanficfare_plugin.fanficfare.configurable(998): use_browser_cache:
FFF: DEBUG: 2021-03-31 12:08:29,121: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1012): use_basic_cache:true
FFF: DEBUG: 2021-03-31 12:08:29,122: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(234): 
========== MISS (GET) BasicCache
https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt
FFF: DEBUG: 2021-03-31 12:08:29,122: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(441): 
---------- REQ (GET) RequestsFetcher
https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt
FFF: DEBUG: 2021-03-31 12:08:30,782: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(447): response code:200
FFF: DEBUG: 2021-03-31 12:08:30,783: calibre_plugins.fanficfare_plugin.fanficfare.requestable(50): Encoding:utf8
FFF: DEBUG: 2021-03-31 12:08:30,784: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica(148): set opened url:https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt
FFF: DEBUG: 2021-03-31 12:08:30,914: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(234): 
========== MISS (GET) BasicCache
https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions
FFF: DEBUG: 2021-03-31 12:08:30,915: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(441): 
---------- REQ (GET) RequestsFetcher
https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions
FFF: DEBUG: 2021-03-31 12:08:31,334: calibre_plugins.fanficfare_plugin.fanficfare.fetcher(447): response code:200
FFF: DEBUG: 2021-03-31 12:08:31,335: calibre_plugins.fanficfare_plugin.fanficfare.requestable(50): Encoding:utf8
FFF: ERROR: 2021-03-31 12:08:31,625: calibre_plugins.fanficfare_plugin.dialogs(721): Exception: {'title': 'Unknown', 'author_sort': ['Unknown'], 'author': ['Unknown'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': None, 'begin': None, 'end': None, 'comment': "Couldn't find story <https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt> on author's page <https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions>", 'url': 'https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt', 'site': 'literotica.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': None, 'uniqueurl': 'https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt[None-None]', 'listorder': 0, 'collision': 'Update EPUB if New Chapters'}:Couldn't find story <https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt> on author's page <https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions>
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 708, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1324, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1196, in get_story_metadata_only
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 308, in getStoryMetadataOnly
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 412, in doExtractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_literotica", line 197, in extractChapterUrlsAndMetadata
calibre_plugins.fanficfare_plugin.fanficfare.exceptions.FailedToDownload: Couldn't find story <https://www.literotica.com/s/lady-pixie-ch-04-a-spirit-of-revolt> on author's page <https://www.literotica.com/stories/memberpage.php?uid=5133625&page=submissions>
[96.86] splash screen hidden
[96.86] Started up in 96.86 seconds with 3189 books
</details>

**Comment by JimmXinu** [comment]
This is a problem in the current code with stories that don't have the `-ch-01` at the end of the URL.

I didn't write this adapter, nor do I read the site.  Plus it's a bit of a mess from the point of view of collecting chapters.  So I don't necessarily know _why_ certain code decisions where made.

I'm looking at it, but my first couple of ideas broke things in different ways.  I'll get back to you.

**Comment by JimmXinu** [comment]
I've attempted another fix(0971c3c76b4cf4dadc7a0cc3e875d76fedddfbed) and posted test versions in the usual places.

I'll leave this issue open until you've had a chance to try out the changes.

**Comment by dakswiggin** [comment]
Checked with Calibre plugin version, can confirm that issue resolved now. Thank you.
