### ISSUE TITLE
Crash on fanfiction.net where a story's category is disabled

### ISSUE THREAD

**Issue by quihi** [JimmXinu/FanFicFare#680]
Certain stories on fanfiction.net are still listed, but when trying to read them, lead to an error message (FanFiction.Net Message Type 1).

When trying to download them (or rather, everything else on the writer's page), fanficfare crashes.

Example story: https://www.fanfiction.net/s/743689/1/Century-of-Dreams-A-Sonnet-Sequence
The author profile linking to it: https://www.fanfiction.net/u/188360/Philosopher-At-Large

**Comment by JimmXinu** [comment]
ffnet has apparently removed the category "Fanfiction Poetry" and invalidated all stories using it.

The site only returns:
> FanFiction.Net Message Type 1
> Category for this story has been disabled. This is likely result of a category being removed for various reasons. Please visit the homepage for related announcements.

There is nothing I can think of that FanFicFare can do about this -- ffnet simply won't give us that page.

It's possible that they will change those stories to a different category that does still exist.  It's also possible that it's a mistake that will corrected.

If I were you, I would report the problem to ffnet and _not_ mention FFF to them.

**Comment by Edocsil** [comment]
As I understand it, the issue @quihi has is that when doing a --download-list Fanficfare supposedly (haven't tested it) crashes when it reaches a story with an  invalid category, instead of just outputting the error before continuing with the next story in the list.

I guess anyone experiencing this issue could just use --list and then put them in a file while removing the broken stories and then use --infile.

Seems a bit convoluted though.

**Comment by JimmXinu** [comment]
To me, the first thing to do on any error is to look at the page and then it's obvious in this case.  And I think, unless ffnet has started removing old categories wholesale, that this is going to exceedingly rare.  

But reporting the error more precisely to the user is not a bad idea. 878aa0b1a606d27ded1c45e510cd2036de31a127

CLI test version posted.

**Comment by quihi** [comment]
Yes, that was what I meant, thank you!  I appreciate this project very much.
