### ISSUE TITLE
Problem with ficbook.net

### ISSUE THREAD

**Issue by Hapapai** [JimmXinu/FanFicFare#683]
I tried using FanFicFare to update stories from ficbook.net and it failed.
Returned the next message: 

HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.ficbook.net/readfic/3339307'(403)
https://www.ficbook.net/readfic/3339307

**Comment by JimmXinu** [comment]
Already addressed in 5ff77100c546a6e0381af3c580db505742332af2

Test versions posted in the usual places:

http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025

Test version of CLI for pip install:  You'll have to get it from the
testpypi repository.  This works for me on Debian:

> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by Hapapai** [comment]
Thank you so much for the prompt response
