### ISSUE TITLE
Plugin bundled bs4 is completely broken on calibre 5.x

### ISSUE THREAD

**Issue by eli-schwartz** [JimmXinu/FanFicFare#685]
```
$ calibre-debug -r FanFicFare -- --help
Traceback (most recent call last):
  File "/usr/bin/calibre-debug", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/debug.py", line 315, in main
    plugin.cli_main([plugin.name] + args[1:])
  File "calibre_plugins.fanficfare_plugin.__init__", line 118, in cli_main
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.fanficfare_plugin.fanficfare.cli", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.__init__", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_efiction_adapter", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1349, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1323, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1304, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 423, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 656, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 713, in _get_module_code
  File "<frozen zipimport>", line 647, in _compile_source
  File "/home/eschwartz/.config/calibre/plugins/FanFicFare.zip/bs4/__init__.py", line 52
    'You are trying to run the Python 2 version of Beautiful Soup under Python 3. This will not work.'<>'You need to convert the code, either by installing it (`python setup.py install`) or by running 2to3 (`2to3 -w bs4`).'
                                                                                                      ^
SyntaxError: invalid syntax
```

bs4 is not source compatible with both python2 and python3, so in order to support both, you need to include multiple copies and play with the path to inject the right one.

**Comment by JimmXinu** [comment]
Correct.  Because it's not there for Calibre5--it's there for Calibre2.  FFF in Calibre5 uses Calibre's copy.

**Comment by eli-schwartz** [comment]
Clearly not, since in calibre v5 it is trying and failing to use the bundled copy when you attempt to use the CLI interface.

**Comment by JimmXinu** [comment]
I'm not seeing that problem on Win10.  I will look into it tomorrow.

**Comment by eli-schwartz** [comment]
The import semantics are kind of confusing. While I was poking around trying to figure out #684 I noticed that calibre itself adds the plugin zip (self.plugin_path) to the PYTHONPATH, but only during plugin initialization? Later on, if you use printf debugging to check the sys.path during the plugin runtime, it's already been removed (`calibre.customize.Plugin().__exit__() has gotten called`).

So I suspect you could get confusing results depending on exactly when you import a module.

**Comment by JimmXinu** [comment]
I cannot duplicate the problem using the [official Calibre release.](https://calibre-ebook.com/download_linux)

**Comment by eli-schwartz** [comment]
@kovidgoyal looking at where bs4 gets loaded, it turns out in the official binaries this is:
```
bs4=<module 'bs4' (/opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/bs4/__init__.pyc)>
sys.path=['/home/eschwartz/.config/calibre/plugins/FanFicFare.zip']
```
And in source builds,

```
sys.path=['/home/eschwartz/.config/calibre/plugins/FanFicFare.zip', '/home/eschwartz/git/calibre/src', '/usr/local/bin', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/lib/python3.9/site-packages']
```

So, when the plugin gets added to the head of the path: https://github.com/kovidgoyal/calibre/blob/3dd95981398777f3c958e733209f3583e783b98c/src/calibre/customize/__init__.py#L302-L310

It is overridden by the bypy frozen imports, and the actual effect is like it is added to the end of the path (because the bypy implementation does not use a path?).

But, on source builds, adding it to the head of the path means that these modules can override the ones calibre natively ships with. Which seems a bit dangerous.

It also depends on which one got loaded first, though... once it is in sys.modules it is preferred from there... Not sure what the solution is. :/ Move the plugin to the end of the path?

**Comment by kovidgoyal** [comment]
Moving it to end of path would be the correct solution.

**Comment by phasormaster** [comment]
I was able to resolve this issue by converting the bs4 library using 2to3 as instructed in the error message listed in bs4/\_\_init__.py. I extracted the FanFicFare.zip plugin file to a temporary directory, ran 2to3 on the bs4 directory, then replaced those files in the zip plugin file with the updated copies.
```
$ cd $(mktemp -d)
$ unzip ~/.config/calibre/plugins/FanFicFare.zip
$ 2to3 --no-diffs --nobackups --write bs4
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: Refactored bs4/__init__.py
RefactoringTool: Refactored bs4/dammit.py
RefactoringTool: Refactored bs4/diagnose.py
RefactoringTool: Refactored bs4/element.py
RefactoringTool: Refactored bs4/builder/__init__.py
RefactoringTool: Refactored bs4/builder/_html5lib.py
RefactoringTool: Refactored bs4/builder/_htmlparser.py
RefactoringTool: Refactored bs4/builder/_lxml.py
RefactoringTool: Files that were modified:
RefactoringTool: bs4/__init__.py
RefactoringTool: bs4/dammit.py
RefactoringTool: bs4/diagnose.py
RefactoringTool: bs4/element.py
RefactoringTool: bs4/builder/__init__.py
RefactoringTool: bs4/builder/_html5lib.py
RefactoringTool: bs4/builder/_htmlparser.py
RefactoringTool: bs4/builder/_lxml.py
$ zip -f ~/.config/calibre/plugins/FanFicFare.zip
freshening: bs4/builder/_html5lib.py (deflated 75%)
freshening: bs4/builder/_htmlparser.py (deflated 67%)
freshening: bs4/builder/_lxml.py (deflated 70%)
freshening: bs4/builder/__init__.py (deflated 67%)
freshening: bs4/dammit.py (deflated 73%)
freshening: bs4/diagnose.py (deflated 68%)
freshening: bs4/element.py (deflated 77%)
freshening: bs4/__init__.py (deflated 71%)
```

**Comment by cdobrich** [comment]
Just ran into this issue today, when I upgraded the plugin from 4.0.2 to 4.5.0. Using Calibre from the official Ubuntu repositories: Version: 5.11.0+dfsg-1.

The solution from @phasormaster seemed to have fixed the issue.

**Comment by giesse** [comment]
Having the same problem on Ubuntu (Calibre 4.99.4), just installed the plugin from the Calibre UI.

**Comment by giesse** [comment]
What I did, and seems to be working, was to delete the bs4 directory from the plugin zip file.

**Comment by JimmXinu** [comment]
That's a problem with Ubuntu's bundled version of Calibre.  

And not the only problem, if they're giving you Calibre 4.99.4.  4.99.X was a *test* series never meant for general use.  And 4.99.**4** wasn't even the last of 4.99.X, that was 4.99.17.  _And_ it's almost a year out of date.  Current Calibre version is 5.26.  

I only support the official Calibre versions as distributed from https://calibre-ebook.com/download

But FYI, FFF needs to carry the old `bs4` package to support older versions of Calibre that didn't have `bs4`.  By [Calibre's usage stats](https://calibre-ebook.com/dynamic/calibre-usage) there are more Calibre v2-4 users than Linux users, so I prioritize backward compatibility to the older (official) versions.

**Comment by eli-schwartz** [comment]
Based on agreement between @JimmXinu, Kovid, and I -- this is NOT a FanFicFare bug. It is a calibre bug.

The calibre bug was fixed in 5.15, so being able to upgrade to 5.11 is not going to help you, and using Ubuntu's broken, known buggy, experimental beta builds is going to be more than "not helpful", it is going to break ***all over the place***.

Even the debian maintainer of calibre does not recommend you use those Ubuntu versions, because they were only ever released to debian unstable for experimental testing purposes but Ubuntu went and grabbed them anyway and popped them into an LTS release for incomprehensible reasons. Actual stable versions of Debian only saw the official python2 versions of calibre and then went straight to calibre 5.0

It is maintainerless in Ubuntu, so there is no one to complain to and no one who will fix it. Just don't use calibre from the Ubuntu repositories. Please.

For debian you will need to use Debian Bookworm, or submit a Debian bug asking to backport the fixed version to Bullseye.

**Comment by giesse** [comment]
Any hope for a Snap version of Calibre to sidestep the issue with Ubuntu packages? I don't think Canonical cares much about debian packages for apps anymore.

In any case, I don't use Calibre much right now, but I'll keep this in mind and upgrade next time I have a chance.

**Comment by eli-schwartz** [comment]
The calibre developer has zero interest in playing the [![](https://imgs.xkcd.com/comics/standards.png)](https://xkcd.com/927/) game with Linux packaging formats and has rejected that suggestion many times.

The current tarball install is functionally identical except not coming from Ubuntu's appstore.

...

Aside: Snap is a highly controversial format on its own, no one is very impressed with Ubuntu's closed source paid service here. Not even if they promise you can upload free software for free using free upload tools. 

Consider flatpak instead. As a matter of fact there is a community maintained flatpak for calibre. Maybe you'll have luck with that.
