### ISSUE TITLE
[Alert/Notification/Warning if Chapters are less]

### ISSUE THREAD

**Issue by Kirekus** [JimmXinu/FanFicFare#686]
Could a prompt or warning system be implemented? Here, a user would be alerted if said ebook/fanfic's chapters has decreased drastically? I.e. if user's copy has 15 chapters then the site only has 5. Could one be prompted regarding that and asked if they want to proceed with the operation?

**Comment by JimmXinu** [comment]
Are you talking about CLI or plugin?  Because there are already some checks like that implemented.

**Comment by Kirekus** [comment]
The plugin. Could you tell me how do I implement such? What happens for me is that the file is just automatically overwritten with less chapters. Would like to be able to review the particular file before such.

**Comment by JimmXinu** [comment]
You have to use EPUB output format and [Update EPUB if New Chapters](https://github.com/JimmXinu/FanFicFare/wiki/UpdateModes#update-epub-if-new-chapters) mode, which is the only mode that looks at the number of chapters.

The Overwrite [Update Modes](https://github.com/JimmXinu/FanFicFare/wiki/UpdateModes#overwrite-if-newer) modes or [Update EPUB Always](https://github.com/JimmXinu/FanFicFare/wiki/UpdateModes#update-epub-always) _will_ update/overwrite even if there are fewer chapters.  They do not look at the number of chapters at all.

And FFF is not *able* to look at the number of chapters for formats other than EPUB.
