### ISSUE TITLE
Storiesonline.net delay

### ISSUE THREAD

**Issue by fidofido300** [JimmXinu/FanFicFare#687]
Storiesonline.net intrced a 20 second delay between chapter downloads.
Can you implement the same delay 
Thank You!

**Comment by JimmXinu** [comment]
I'm not seeing that.  And 20 seconds would be nearly twice the length of delay we use for any other site.  I suspect you've tripped a throttling mechanism on your IP or account.

Regardless, you can set such a delay for your self in `personal.ini`:
```
[storiesonline.net]
## number of seconds to sleep between calls to the story site.  May be
## useful if pulling large numbers of stories or if the site is slow.
## The actual sleep time used on each request is a random number
## between 0.5 and 1.5 times slow_down_sleep_time.
slow_down_sleep_time:20
```

If I get more reports about from other users, I will introduce a default delay.

**Comment by fidofido300** [comment]
thank you
I will add that to my personal.ini

**Comment by JimmXinu** [comment]
No further reports from other users.
