### ISSUE TITLE
Feature request - refresh titlepage

### ISSUE THREAD

**Issue by estherflails** [JimmXinu/FanFicFare#691]
Hello! Thank you very much for creating this plugin, it's been incredibly useful. I've been playing around with the settings in personal.ini and ended up changing the `titlepage_entries` to something I prefer. However, I already have a lot of stories downloaded and I'd rather not have to overwrite them all just to get the titlepage to look nicer.

Could something be implemented so it's possible to refresh just the titlepage without touching the chapters? It would be great if it could be done offline, since all the metadata it requires is already present in custom columns.

Thank you!

**Comment by JimmXinu** [comment]
This is something that's [come up before](https://www.mobileread.com/forums/showthread.php?p=3844436#post3844436), and I've investigated at least three different ways to implement it without being [happy about any of them](https://www.mobileread.com/forums/showthread.php?p=3844578&postcount=3425).

In the end, I concluded that the official answer is ['Update EPUB Always' mode](https://github.com/JimmXinu/FanFicFare/wiki/UpdateModes#update-epub-always).  Yes, it still generates some traffic, but it doesn't break anything.

**Comment by estherflails** [comment]
Oh, I see. Thank you for the answer and sorry for the redundant request!
