### ISSUE TITLE
CLI: Make errors more visible at a glance.

### ISSUE THREAD

**Issue by Edocsil** [JimmXinu/FanFicFare#692]
Hey Jim, I mostly update the stories I follow through email notifications, often in one daily batch at night which can be from just a few stories to two dozen or more, and over time I've come to realize just how painful checking the terminal for errors is, specially on a phone's small screen.

Could you add anything to make spotting errors more noticeable among all other text? Perhaps bolding certain outputs like "**xx contains ?? chapters, more than source: ??**" 

Sometimes authors can do things like deleting chapters to rewrite them, and if I don't pay close attention to the forums or the errors, I miss it and find out only when something doesn't make sense in the story while reading.

I hope I'm not asking for anything too complex, I understand this isn't an issue for most people.

*Thanks anyway!*

**Comment by JimmXinu** [comment]
Apparently, this is not easy to do in a cross platform way.  There is a long history of dozens of different terminal types doing things their own ways.  

I found a cross platform library([colorama](https://pypi.org/project/colorama/)) for getting color in both ANSI terminals and Windows, but not bold.  (And as soon as a color is applied, _somebody_ will pop up who uses that for their background color.)  

[ansimarkup](https://github.com/gvalkov/python-ansimarkup) has a bold, but it uses ANSI bright/dim through colorama and it looks terrible in cursory testing on windows.

I need to investigate and test a bit more.

**Comment by Edocsil** [comment]
Honestly, I would be very happy with anything, simply making the errors all in caps would be a HUGE improvement.

I'm guessing other options, such as a setting to only showing errors and hiding everything else, or outputting the errors to a log file are also time consuming to implement?

**Comment by JimmXinu** [comment]
I've uploaded a test version with `--color` option to apply blue & red colors to warning and failure print outs.

As usual:
`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare `

Let me know what you think.

**Comment by Edocsil** [comment]
Thanks! The contrast between different errors helps a lot!

![Screenshot_2021-05-04-20-38-05-356_com termux](https://user-images.githubusercontent.com/2257988/117053088-d3d98380-ad18-11eb-8458-58490b51b383.jpg)
