### ISSUE TITLE
author_avatar_cover:true error

### ISSUE THREAD

**Issue by Nellius** [JimmXinu/FanFicFare#695]
Trying to download [a story on spacebattles.com](https://forums.spacebattles.com/threads/a-young-girls-quirky-retirement-youjo-senki-my-hero-academia.926703/) or [a story on alternatehistory.com](https://www.alternatehistory.com/forum/threads/asoiaf-legacy-of-the-lost.391053/) with `author_avatar_cover:true` causes an error.

- Calibre: 5.17
- FanFicFare: 4.2.0
- Operating system: Peppermint Ten (based on Ubuntu 18.04 LTS)

```ini
[base_xenforoforum]
## use author(original poster)'s avatar as cover image when true.
author_avatar_cover:true
```
![Windowshot_2021-05-06_21:48:44](https://user-images.githubusercontent.com/46846893/117301116-44b5a280-aeb5-11eb-8208-e95e74df6554.png)

`author_avatar_cover:false` or `# author_avatar_cover:true` works fine.

**Comment by JimmXinu** [comment]
Yep, that's a bug.  Fix in next test version.

**Comment by JimmXinu** [comment]
Test versions up in the usual places.
