### ISSUE TITLE
forums.spacebattles.com Error 503

### ISSUE THREAD

**Issue by sutam1** [JimmXinu/FanFicFare#698]
![image](https://user-images.githubusercontent.com/59839681/119216066-02848780-ba97-11eb-8689-2a5b92735a89.png)
I tried to update my files from SpaceBattles, but all get error 503. 
Thanks.

**Comment by Edocsil** [comment]
Just try again after a few seconds. Like the error says, it's a temporarily issue with the site.

**Comment by sutam1** [comment]
I have 36 hours with the same error. I tried yesterday, and now today at least 1 time every 6 hours. I will try tomorrow again. I have posted this because the long time down, and the number of times the same error pops.

**Comment by JimmXinu** [comment]
That error is properly a temporary server error.  And I'm not seeing it 
happen right now.

503 is one of a handful of errors that FFF does *not* retry on--it 
typically indicates server overload and we don't want to be adding 
traffic to already struggling servers.

Depending on many factors about how the SB site is hosted, it's possible 
you or your region are being directed to a host that's failing.

It's also possible you've tripped a throttling mechanism and that's how 
it expresses.

It's possible changing your outside facing IP or using a VPN could help.

You could also try using cloudscraper through FFF with personal.ini setting:

[forums.spacebattles.com]
use_cloudscraper:true

**Comment by sutam1** [comment]
Here i have tried again with the edit line::
use_cloudscraper:true

![image](https://user-images.githubusercontent.com/59839681/119248752-f4973b00-bb58-11eb-8edd-11ef739dc88b.png)

No dice.

Here i have tried again and is the same error 503 without the edit line:

![image](https://user-images.githubusercontent.com/59839681/119248905-f7466000-bb59-11eb-8930-dd69b1ec2dce.png)

**Comment by JimmXinu** [comment]
FYI, the error message you got with `use_cloudscraper:true` probably indicates that CloudFlare was blocking your IP or IP range for some reason.
