### ISSUE TITLE
scribblehub.com "maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by TheOne320** [JimmXinu/FanFicFare#699]
Trying to download
https://www.scribblehub.com/series/137441/the-vampires-templar/
results in the error "maximum recursion depth exceeded". Is there any way to get the story?

**Comment by JimmXinu** [comment]
Chapter 63 has an excessive number of nested 'spoiler' tags that causes the HTML parser to fail when it hits Python's recursion limit.  I'm not interested in trying to change Python's recursion limit setting for authors doing silly things.

If you have `continue_on_chapter_error:true`, you'll get the rest of the story and can either edit that chapter in manually or read it online.
