### ISSUE TITLE
Suggestion: save backlog of failed downloads, so I can easily retry them

### ISSUE THREAD

**Issue by glenm125** [JimmXinu/FanFicFare#702]
I won't repeat all the discussions of Captcha errors downloading from ffn.

I've had moderate success by changing my VPN to a new country, then retrying the failed downloads.  It might take me a few countries before I get the whole list, but eventually I get there.

The problem is, it isn't particularly convenient to read the log, then go back into my email folder to mark those messages New again, and then repeat the Get Stories from Email.

What would be cool is if FFF could remember what has failed from the list of stories I have previously asked for, and let me "Retry Failed Loads". In essence, have FFN maintain a backlog and try to work it off on subsequent downloads.

Cheers,

glen

**Comment by JimmXinu** [comment]
Have you looked at the Update/Overwrite Error Column setting on the Custom Columns tab of FFF config?

**Comment by glenm125** [comment]
Oh, cool, that's another way to solve the problem. In essence, save the errors in that column, then when I want to retry I can sort on that column, select the books with that failure, and Update Existing Fanfiction Books. That is a feature I hadn't been aware of. Thanks!
