### ISSUE TITLE
Problem with ficbook

### ISSUE THREAD

**Issue by rebel42** [JimmXinu/FanFicFare#704]
Hi!
Last two days i tried using FanFicFare to update stories from ficbook.net and it is not working.
Get this error message:
HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.ficbook.net/readfic/10204035'(403)
Thanks!

**Comment by JimmXinu** [comment]
I'm seeing that now too.  FFF is already using cloudscraper with ficbook.net, I'm not sure what else can reasonably be done about it.

I also don't know how many FFF users read ficbook.net.  It's difficult for me to work on, not knowing Russian myself.

**Comment by zclimber** [comment]
I am Russian and I know some things about programming. Do you have a way to run FanFicFare under debugger? I want to take a look))

**Comment by JimmXinu** [comment]
It should be possible, but I don't know how.  I don't use a debugger, I just using `logger.debug()` a lot.

I do a lot of my testing on Win10 with CLI.  From the cloned repo dir, I set env vars `PYTHONPATH=.` and `PYTHONWARNINGS=` and run it as `python fanficfare\cli.py -d` with a script(batch file).

**Comment by HiTeeN** [comment]
Is there a way to use browser cache to download from ficbook? If it can be used to fanfiction.net, why not other sites? Sorry, im not understanding much in this topic, i just everyday used FFF for ficbook and its really annoying update 10-20 fics\day manually.

**Comment by JimmXinu** [comment]
Not currently.  It may be possible.

**Comment by JimmXinu** [comment]
I've added `use_browser_cache` for ficbook.net (5dd2d3297cea52e191ed6a7654b1a0d9413f50f7).  

Read the [BrowserCacheFeature](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature) doc on how to use it.  (I'll update the document to also mention ficbook.net when it is released.)

Note that ficbook.net isn't supported by WebToEpub, so that part isn't applicable--you'll have to click through chapters manually.

**Comment by JimmXinu** [comment]
Test versions posted in the usual places:

http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025

Test version of CLI for pip install:  You'll have to get it from the
testpypi repository.  This works for me on Debian:

> pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare

**Comment by HiTeeN** [comment]
Thank you for update, it works. Still have 1 question. Why do FFF even need to download books chapter-by-chapter from ficbook, if site have download option?

**Comment by JimmXinu** [comment]
If ficbook has a download option, why do you use FFF to download stories from it? :-)

Google translate tells me that trying to download epub says "This action is available only for registered users."  FFF doesn't currently know how to login to ficbook.

Plus, FFF is built around downloading chapters and parsing the HTML to standardize it.  Downloading an epub to open and then get HTML from is an additional level of complexity.

If somebody else wants to figure out ficbook login--through CloudFlare blocking, which is already preventing direct access--and downloading/parsing the epub, they are welcome to contribute code.

In the meantime, this is as fixed as it's likely to get.
