### ISSUE TITLE
Suggestion: Modification for Cloudflare errors

### ISSUE THREAD

**Issue by chocolatechipcats** [JimmXinu/FanFicFare#708]
Suggestion: add a link to the cache page to the error output, e.g. `cloudscraper reports: "Detected a Cloudflare version 2 Captcha challenge, This feature is not available...." Please see https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature`

Hopefully this might cut down on the # of posts about it.

**Comment by JimmXinu** [comment]
Good idea.  Link: #703
