### ISSUE TITLE
could support for wuxialeague be added?

### ISSUE THREAD

**Issue by Dnkhatri** [JimmXinu/FanFicFare#714]
https://www.wuxialeague.com

This is a sample url
https://www.wuxialeague.com/novel/39567/

**Comment by JimmXinu** [comment]
I will leave this open as an enhancement issue, but I would also point out:
- The first FAQ: [Please add site XYZ to FanFicFare?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#please-add-site-xyz-to-fanficfare)
- This [comment and the following discussion in another requested site](https://github.com/JimmXinu/FanFicFare/issues/440#issuecomment-545589619) about my views on downloading copyrighted material.
