### ISSUE TITLE
[Feature request]: Extend browser cache feature to Fictionpress

### ISSUE THREAD

**Issue by dysphere** [JimmXinu/FanFicFare#716]
When I try to download a fic from Fictionpress, I get 

> cloudscraper reports: (Detected a Cloudflare version 2 Captcha challenge, This feature is not available....) 
> See https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature for a possible workaround.

However, currently that feature is only available for ff.net.

**Comment by JimmXinu** [comment]
Test versions up in the usual places.
