### ISSUE TITLE
Cutting off in the middle of a scribblehub.com chapter

### ISSUE THREAD

**Issue by TheOne320** [JimmXinu/FanFicFare#720]
So in "Chapter 2: The First Wave" of this story:
https://www.scribblehub.com/read/111237-ideascape-an-adventure-litrpg/chapter/116795/

FanFicFare just ends the chapter after the table after "I called the menu up to check the skill drain on my mana." even though the chapter still continues after that.

**Comment by JimmXinu** [comment]
Chapter text is missing a `<div>` tag at the beginning of a table, so the `</div>` tag that _is_ there indicates that is where the `<div id="chp_raw">` that defines the chapter text ends.

Bug in that chapter text, not something in FFF.  I would just manually edit the rest of the text into that chapter.
