### ISSUE TITLE
[feature request] Making the use of vendored certificates optional

### ISSUE THREAD

**Issue by tr13dm03** [JimmXinu/FanFicFare#721]
While I understand the thought process that led to the inclusion of such certificates to simplify the use of SSL across OSes in FFF, I would much rather use my distro's certificate file in the plugin than some cert file of unknown origins (or having to patch in mine before making the plugin).

Would it be possible to make that into an option? I'm also wondering if removing the vendored libraries managing network access would also work if I'm willing to go through the bother before making the plugin.

**Comment by JimmXinu** [comment]
I'm not interested in doing it, but you could.  I believe @eli-schwartz has already done something similar for [archlinux](https://github.com/archlinux).

Some of the libraries are only there for older versions of Calibre (going back to v2.85.1) and aren't used in newer Calibre versions.

I believe you would also need a modified version of Calibre for un-vendering the libraries Calibre doesn't include.  To the best of my knowledge, Kovid's versions don't use OS installed libraries, except maybe certs.  But I primarily use the Windows version.

The script I use to generate the plugin zip is [makeplugin.py](https://github.com/JimmXinu/FanFicFare/blob/main/makeplugin.py).

**Comment by eli-schwartz** [comment]
I am pretty sure FanFicFare does not actually use those certs.

FanFicFare uses the `requests` module, which in turn uses the `certifi` module to obtain certificates which it refuses to obtain from the OS.

Simply removing both modules from the plugin, will cause FanFicFare to either use your system provided requests module (which may or may not be patched to use the system certificates), or fail entirely if you don't use a source build of calibre from a Linux or BSD distro.

**Comment by eli-schwartz** [comment]
And yes, I have a Linux package for FanFicFare the plugin which does all this. If you use Arch Linux, simply

```sh
pacman -S calibre fanficfare
```

and FanFicFare will show up as installed.
