### ISSUE TITLE
[Feature Request] INI file - provide conditionals within a section

### ISSUE THREAD

**Issue by jktrigg** [JimmXinu/FanFicFare#723]
Simple example: for [archiveofourown.org]:
if "fandom:=Willow (1988)" then character=>Willow=>Willow Ufgood
if "fandom:=Buffy*" then character=>Willow=>Willow Rosenberg

(Simplistic syntax, if you want blocks that'd be fine too. And yes, I'm specifically using the syntax Calibre uses for searches for the if conditional.
if "fandom:=Buffy*" {
  character=>Willow=>Willow Rosenberg
  character=>Amy=>Amy Madison
}
if "fandom:=Willow (1988)" {
  character=>Willow=>Willow Ufgood
}
if "fandom:=Doctor Who*" {
  character=>Amy=>Amy Pond
}

For that matter, a case statement would work too.
case fandom {
  "Buffy*" {
    character=>Willow=>Willow Rosenberg
    character=>Amy=>Amy Madison
  }
  "Willow (1988)" {
    character=>Willow=>Willow Ufgood
  }
  "Doctor Who*" {
    character=>Amy=>Amy Pond
 }
}

Also, allowing this syntax generally would a) be easier and b) be even more useful.)

**Comment by jktrigg** [comment]
Also, allowing something more like bash syntax for the case conditions would be good. "Doctor Who*|Dr. Who*"...

**Comment by JimmXinu** [comment]
The existing conditional keys feature already does that using regexp matching such as:

` character=>Willow=>Willow Ufgood&&category=>Willow`

See the [wiki page](https://github.com/JimmXinu/FanFicFare/wiki/ReplaceMetadata) or `defaults.ini` comments.
