### ISSUE TITLE
www.phoenixsong.net seems not working

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#724]
When updating https://www.phoenixsong.net/fanfiction/story/6551/ I got some weird PHP document, and the same I've got when I went to the plain https://www.phoenixsong.net/ . Not sure, what's going on, whether it is permanent or just a temporary issue.

**Comment by JimmXinu** [comment]
The phoenixsong.net web server is apparently misconfigured and serving the PHP pages instead of executing them.  Contact the phoenixsong.net admin to maybe get it fixed.

I don't generally remove a fanfic site while the DNS still points to a server, even if it's currently broken.
