### ISSUE TITLE
Fictionmania no longer accepting SSL (port 443) requests

### ISSUE THREAD

**Issue by unfw** [JimmXinu/FanFicFare#728]
When trying to download from fictionmania.tv, I am getting the following error:

HTTPSConnectionPool(host='fictionmania.tv', port=443): Max retries exceeded with url: /stories/details.html?storyID=33265656861324524536 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))

for url:

https://fictionmania.tv/stories/readtextstory.html?storyID=33265656861324524536

Looking at the site, it seems that fictionmania is no longer using TLS and is rejecting requests on port 443. Can we update this to use http instead of https?

**Comment by JimmXinu** [comment]
Already fixed by moving the fictionmania.tv back to using http(#718).  

This is available now in the test versions([FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#how-do-i-get-the-latest-test-version-of-fanficfare)), or wait for the next release, probably next week.
