### ISSUE TITLE
I can't download from webnovel.com!

### ISSUE THREAD

**Issue by tom221-e** [JimmXinu/FanFicFare#731]
help! this is the error that appears: 
Descargar 1 libro(s) de «fanfiction»
FFF: INFO: 2021-09-02 23:18:45,858: calibre_plugins.fanficfare_plugin.jobs(49): CPUs:3
FFF: INFO: 2021-09-02 23:18:45,859: calibre_plugins.fanficfare_plugin.jobs(52): FanFicFare v4.5.0
FFF: INFO: 2021-09-02 23:18:45,859: calibre_plugins.fanficfare_plugin.jobs(68): Lanzar proceso en segundo plano para www.webnovel.com:
https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305
FFF: INFO: 2021-09-02 23:18:51,360: calibre_plugins.fanficfare_plugin.jobs(130): 

================================================================================ site:(www.webnovel.com)
FFF: INFO: 2021-09-02 23:18:47,173: calibre_plugins.fanficfare_plugin.jobs(211): 

-------------------------------------------------------------------------------- https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305
FFF: DEBUG: 2021-09-02 23:18:47,189: configurable.py(1012): use_browser_cache:
FFF: DEBUG: 2021-09-02 23:18:47,190: configurable.py(1026): use_basic_cache:true
FFF: DEBUG: 2021-09-02 23:18:47,192: adapter_webnovelcom.py(85): https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305
FFF: DEBUG: 2021-09-02 23:18:47,196: fetcher.py(234): 
========== MISS (GET) BasicCache
https://www.webnovel.com/book/the-vampire-of-wall-street-%28my-wife-is-a-beautiful-ceo%29_20174290205479305
FFF: DEBUG: 2021-09-02 23:18:47,197: fetcher.py(461): 
---------- REQ (GET) RequestsFetcher
https://www.webnovel.com/book/the-vampire-of-wall-street-%28my-wife-is-a-beautiful-ceo%29_20174290205479305
FFF: DEBUG: 2021-09-02 23:18:50,614: fetcher.py(467): response code:200
FFF: DEBUG: 2021-09-02 23:18:50,615: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-09-02 23:18:50,854: fetcher.py(234): 
========== MISS (GET) BasicCache
https://www.webnovel.com/apiajax/chapter/GetChapterList?_csrfToken=84587889-c926-4963-ba03-0dec26fb74ff&bookId=20174290205479305
FFF: DEBUG: 2021-09-02 23:18:50,854: fetcher.py(461): 
---------- REQ (GET) RequestsFetcher
https://www.webnovel.com/apiajax/chapter/GetChapterList?_csrfToken=84587889-c926-4963-ba03-0dec26fb74ff&bookId=20174290205479305
FFF: DEBUG: 2021-09-02 23:18:51,123: fetcher.py(467): response code:404
FFF: INFO: 2021-09-02 23:18:51,123: calibre_plugins.fanficfare_plugin.jobs(439): Exception: {'title': 'The Vampire of Wall Street (My Wife is a Beautiful CEO)', 'author_sort': 'Photosphere', 'author': ['Photosphere'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': 3263, 'begin': None, 'end': None, 'comment': 'Story does not exist: (https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305)', 'url': 'https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305', 'site': 'www.webnovel.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': 'www.webnovel.com', 'listorder': 0, 'collision': 'Actualizar EPUB si hay nuevos capítulos', 'uniqueurl': 'https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305[None-None]', 'is_adult': False, 'username': 'NoneGiven', 'password': '', 'icon': 'dialog_error.png', 'epub_for_update': 'C:\\Users\\User\\AppData\\Local\\Temp\\calibre_gidmscfr\\fanficfare_ultkgym4\\old-3263-op780mzn.epub', 'calibre_columns': {}, 'outfile': 'C:\\Users\\User\\AppData\\Local\\Temp\\calibre_gidmscfr\\fanficfare_ultkgym4\\bgmeta-vmpo66ov.epub'}:Story does not exist: (https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305)
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 468, in request
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.webnovel.com/apiajax/chapter/GetChapterList?_csrfToken=84587889-c926-4963-ba03-0dec26fb74ff&bookId=20174290205479305

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 308, in getStoryMetadataOnly
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\adapter_webnovelcom.py", line 152, in doExtractChapterUrlsAndMetadata
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\requestable.py", line 114, in get_request
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\requestable.py", line 106, in get_request_redirected
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 390, in get_request_redirected
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 240, in fetcher_do_request
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 136, in fetcher_do_request
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 363, in do_request
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 479, in request
fanficfare.exceptions.HTTPErrorFFF: HTTP Error in FFF '404 Client Error: Not Found for url: https://www.webnovel.com/apiajax/chapter/GetChapterList?_csrfToken=84587889-c926-4963-ba03-0dec26fb74ff&bookId=20174290205479305'(404)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.jobs", line 260, in do_download_for_worker
  File "C:\Users\User\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 311, in getStoryMetadataOnly
fanficfare.exceptions.StoryDoesNotExist: Story does not exist: (https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305)

FFF: INFO: 2021-09-02 23:18:51,364: calibre_plugins.fanficfare_plugin.jobs(142): 
Resultado de la descarga:
Error https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305 Story does not exist: (https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305)

FFF: INFO: 2021-09-02 23:18:51,364: calibre_plugins.fanficfare_plugin.jobs(166): 
Error
https://www.webnovel.com/book/the-vampire-of-wall-street-(my-wife-is-a-beautiful-ceo)_20174290205479305

**Comment by tom221-e** [comment]
A possible solution in;
https://github.com/dipu-bd/lightnovel-crawler/commit/d9a63d60cd8ec8d95813b79c533cd4a0a18b6226

**Comment by JimmXinu** [comment]
I've posted a [plugin test version](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2) to address this.

Thanks for the reference to lightnovel-crawler's change--that sped things up considerably.

Leaving this open for the moment in case I missed something.

**Comment by tom221-e** [comment]
Thank you!

**Comment by tom221-e** [comment]
Error "NoneType": 
Descargar 1 libro(s) de «fanfiction»
FFF: INFO: 2021-09-07 20:05:16,577: calibre_plugins.fanficfare_plugin.jobs(49): CPUs:3
FFF: INFO: 2021-09-07 20:05:16,577: calibre_plugins.fanficfare_plugin.jobs(52): FanFicFare v4.5.2
FFF: INFO: 2021-09-07 20:05:16,577: calibre_plugins.fanficfare_plugin.jobs(68): Lanzar proceso en segundo plano para www.webnovel.com:
https://www.webnovel.com/book/super-dimensional-guild_21092459005185805
FFF: INFO: 2021-09-07 20:05:19,438: calibre_plugins.fanficfare_plugin.jobs(130): 

================================================================================ site:(www.webnovel.com)
FFF: INFO: 2021-09-07 20:05:17,986: calibre_plugins.fanficfare_plugin.jobs(211): 

-------------------------------------------------------------------------------- https://www.webnovel.com/book/super-dimensional-guild_21092459005185805
FFF: DEBUG: 2021-09-07 20:05:18,005: configurable.py(1012): use_browser_cache:
FFF: DEBUG: 2021-09-07 20:05:18,005: configurable.py(1026): use_basic_cache:true
FFF: DEBUG: 2021-09-07 20:05:18,008: adapter_webnovelcom.py(85): https://www.webnovel.com/book/super-dimensional-guild_21092459005185805
FFF: DEBUG: 2021-09-07 20:05:18,008: fetcher.py(234): 
========== MISS (GET) BasicCache
https://www.webnovel.com/book/super-dimensional-guild_21092459005185805
FFF: DEBUG: 2021-09-07 20:05:18,009: fetcher.py(461): 
---------- REQ (GET) RequestsFetcher
https://www.webnovel.com/book/super-dimensional-guild_21092459005185805
FFF: DEBUG: 2021-09-07 20:05:18,527: fetcher.py(467): response code:200
FFF: DEBUG: 2021-09-07 20:05:18,528: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-09-07 20:05:18,879: fetcher.py(234): 
========== MISS (GET) BasicCache
https://www.webnovel.com/go/pcm/chapter/get-chapter-list?_csrfToken=200b8f9e-ee47-42a3-bd7b-b0d14a4c6e53&bookId=21092459005185805&pageIndex=0
FFF: DEBUG: 2021-09-07 20:05:18,879: fetcher.py(461): 
---------- REQ (GET) RequestsFetcher
https://www.webnovel.com/go/pcm/chapter/get-chapter-list?_csrfToken=200b8f9e-ee47-42a3-bd7b-b0d14a4c6e53&bookId=21092459005185805&pageIndex=0
FFF: DEBUG: 2021-09-07 20:05:19,105: fetcher.py(467): response code:200
FFF: DEBUG: 2021-09-07 20:05:19,105: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-09-07 20:05:19,131: dateutils.py(73): val:36 unit_string:min unit:None
FFF: INFO: 2021-09-07 20:05:19,132: calibre_plugins.fanficfare_plugin.jobs(439): Exception: {'title': 'Super Dimensional Guild', 'author_sort': 'Andi_Candra', 'author': ['Andi_Candra'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': 3274, 'begin': None, 'end': None, 'comment': "argument of type 'NoneType' is not iterable", 'url': 'https://www.webnovel.com/book/super-dimensional-guild_21092459005185805', 'site': 'www.webnovel.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': 'www.webnovel.com', 'listorder': 0, 'collision': 'Actualizar EPUB si hay nuevos capítulos', 'uniqueurl': 'https://www.webnovel.com/book/super-dimensional-guild_21092459005185805[None-None]', 'is_adult': False, 'username': 'NoneGiven', 'password': '', 'icon': 'dialog_error.png', 'epub_for_update': 'C:\\Users\\TomasE\\AppData\\Local\\Temp\\calibre_8g83d5vf\\fanficfare_my2i0l5c\\old-3274-hp98097e.epub', 'calibre_columns': {}, 'outfile': 'C:\\Users\\TomasE\\AppData\\Local\\Temp\\calibre_8g83d5vf\\fanficfare_my2i0l5c\\bgmeta-wj0rn_9x.epub'}:argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.jobs", line 260, in do_download_for_worker
  File "C:\Users\TomasE\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 308, in getStoryMetadataOnly
  File "C:\Users\TomasE\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\adapter_webnovelcom.py", line 192, in doExtractChapterUrlsAndMetadata
  File "C:\Users\TomasE\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\dateutils.py", line 76, in parse_relative_date_string
TypeError: argument of type 'NoneType' is not iterable

FFF: INFO: 2021-09-07 20:05:19,439: calibre_plugins.fanficfare_plugin.jobs(142): 
Resultado de la descarga:
Error https://www.webnovel.com/book/super-dimensional-guild_21092459005185805 argument of type 'NoneType' is not iterable

FFF: INFO: 2021-09-07 20:05:19,439: calibre_plugins.fanficfare_plugin.jobs(166): 
Error
https://www.webnovel.com/book/super-dimensional-guild_21092459005185805

**Comment by JimmXinu** [comment]
[Test version posted](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2)

**Comment by CodeyAce95** [comment]
is this fixed yet

**Comment by JimmXinu** [comment]
As far as I know, the latest test version of FFF fixes it.

**Comment by CodeyAce95** [comment]
i installed it but did not work maybe i got the wrong link could you post it on this page please god bless

**Comment by CodeyAce95** [comment]
never mind installed the wrong plugin my bad thank you for your time god bless
