### ISSUE TITLE
Can't download a book from wattpad.com

### ISSUE THREAD

**Issue by onthanh** [JimmXinu/FanFicFare#735]
I have a trouble with download a book from website wattpad.com. I added the lastest version of FanFicFare, at https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2. Here is the error message:

![loi fanfic1](https://user-images.githubusercontent.com/90960550/133884396-90c2e5e0-1ae4-4b5f-9fba-14d3577ad675.PNG)

![loi fanfic2](https://user-images.githubusercontent.com/90960550/133884398-433b343e-5d39-4d2d-9309-5739d2e0daac.PNG)

Thanks

**Comment by JimmXinu** [comment]
Please post the story URL.  The test story I usually use for wattpad.com works fine.

**Comment by onthanh** [comment]
https://www.wattpad.com/story/262752496-edit-hoàn-đam-mỹ-xung-hỉ-trọng-sinh

**Comment by JimmXinu** [comment]
I'm able to download this story fine.  Can you try again while running Calibre in debug mode (under Calibre Preferences dropdown) and post the debug log?

**Comment by onthanh** [comment]
Oh when I enter the debug mode, it fix the problem. Thanks a lot!!

**Comment by JimmXinu** [comment]
Then I'm going to chalk this up to being a temporary server or network issue.
