### ISSUE TITLE
Fetching urls from this specific Ao3 series not working

### ISSUE THREAD

**Issue by distressanddisarae** [JimmXinu/FanFicFare#736]
I was using FFF for Ao3 on Calibre but when I tried to download a series of fics (here: https://archiveofourown.org/series/1319408) as individual books this came up:

>ERROR: Unhandled exception: <b>AttributeError</b>:'NoneType' object has no attribute 'get_text'
>
> calibre 5.27  embedded-python: True is64bit: True
> macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
> Python 3.8.5
> OSX: ('10.16', ('', '', ''), 'x86_64')
> Interface language: None
> Successfully initialized third party plugins: EpubMerge (2, 11, 0) && FanFicFare (4, 5, 0) && Generate Cover (2, 0, 2)
> Traceback (most recent call last):
>   File "calibre_plugins.fanficfare_plugin.fff_plugin", line 654, in get_urls_from_page_menu
>     frompage = self.get_urls_from_page(url)
>   File "calibre_plugins.fanficfare_plugin.fff_plugin", line 677, in get_urls_from_page
>     return get_urls_from_page(url,configuration)
>   File "/Users/namehere/Library/Preferences/calibre/plugins/FanFicFare.zip/fanficfare/geturls.py", line 45, in get_urls_from_page
>     return adapter.get_urls_from_page(url,normalize)
>   File "/Users/namehere/Library/Preferences/calibre/plugins/FanFicFare.zip/fanficfare/adapters/base_adapter.py", line 444, in get_urls_from_page
>     series = self.get_series_from_page(url,data,normalize)
>   File "/Users/namehere/Library/Preferences/calibre/plugins/FanFicFare.zip/fanficfare/adapters/adapter_archiveofourownorg.py", line 598, in get_series_from_page
>     retval['name']=stripHTML(soup.select_one("h2.heading"))
>   File "/Users/namehere/Library/Preferences/calibre/plugins/FanFicFare.zip/fanficfare/htmlcleanup.py", line 71, in stripHTML
>     retval = soup.get_text(strip=True)
> AttributeError: 'NoneType' object has no attribute 'get_text'

I get the same thing when trying to download it as an anthology, and after restarting and redownloading both FFF and calibre. It worked perfectly fine when I tried a different series, and it could download the books just fine when I put in the urls individually when trying to fetch the urls with FFF still didn't work. The only thing I could think of that might be causing an issue is that the series is restricted to Ao3 users, as that's the only major difference between the two series' that I could tell.
This is the report I got when I tried it in debug mode:

> EpubMerge: DEBUG: 2021-09-22 22:34:01,849: calibre_plugins.epubmerge.epubmerge_plugin(158): macmenuhack file_path:/Users/namehere/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
> FFF: DEBUG: 2021-09-22 22:34:01,878: calibre_plugins.fanficfare_plugin.fff_plugin(221): Plugin FanFicFare macmenuhack file_path:/Users/namehere/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
> QLayout::addChildLayout: layout "" already has a parent
> calibre Debug log
> calibre 5.27  embedded-python: True is64bit: True
> macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
> Python 3.8.5
> OSX: ('10.16', ('', '', ''), 'x86_64')
> Interface language: None
> Successfully initialized third party plugins: EpubMerge (2, 11, 0) && FanFicFare (4, 5, 0) && Generate Cover (2, 0, 2)
> calibre 5.27  embedded-python: True is64bit: True
> macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
> Python 3.8.5
> OSX: ('10.16', ('', '', ''), 'x86_64')
> Interface language: None
> Successfully initialized third party plugins: EpubMerge (2, 11, 0) && FanFicFare (4, 5, 0) && Generate Cover (2, 0, 2)
> devicePixelRatio: 1.0
> logicalDpi: 72.0 x 72.0
> physicalDpi: 128.00000192236715 x 128.00000192236715
> Using calibre Qt style: True
> [0.00] Starting up...
> [0.04] Showing splash screen...
> [0.40] splash screen shown
> [0.40] Initializing db...
> [1.19] db initialized
> [1.19] Constructing main UI...
> [9.01] main UI initialized...
> [9.01] Hiding splash screen
> Starting QuickView
> FFF: DEBUG: 2021-09-22 22:35:07,672: calibre_plugins.fanficfare_plugin.fff_plugin(675): get_urls_from_page URL:https://archiveofourown.org/series/1319408
> FFF: DEBUG: 2021-09-22 22:35:07,708: configurable.py(1012): use_browser_cache:
> FFF: DEBUG: 2021-09-22 22:35:07,710: configurable.py(1026): use_basic_cache:true
> FFF: DEBUG: 2021-09-22 22:35:07,711: fetcher.py(234): 
> ========== MISS (GET) BasicCache
> https://archiveofourown.org/series/1319408
> FFF: DEBUG: 2021-09-22 22:35:07,712: fetcher.py(461): 
> ---------- REQ (GET) RequestsFetcher
> https://archiveofourown.org/series/1319408
> FFF: DEBUG: 2021-09-22 22:35:08,183: fetcher.py(467): response code:200
> FFF: DEBUG: 2021-09-22 22:35:08,184: fetcher.py(156): random sleep(1.00-3.00):1.92
> FFF: DEBUG: 2021-09-22 22:35:10,106: requestable.py(50): Encoding:utf8
> calibre 5.27  embedded-python: True is64bit: True
> macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
> Python 3.8.5
> OSX: ('10.16', ('', '', ''), 'x86_64')
> Interface language: None
> Successfully initialized third party plugins: EpubMerge (2, 11, 0) && FanFicFare (4, 5, 0) && Generate Cover (2, 0, 2)
> Traceback (most recent call last):
>   File "calibre_plugins.fanficfare_plugin.fff_plugin", line 654, in get_urls_from_page_menu
>     frompage = self.get_urls_from_page(url)
>   File "calibre_plugins.fanficfare_plugin.fff_plugin", line 677, in get_urls_from_page
>     return get_urls_from_page(url,configuration)
>   File "/Users/namehere/Library/Preferences/calibre/plugins/FanFicFare.zip/fanficfare/geturls.py", line 45, in get_urls_from_page
>     return adapter.get_urls_from_page(url,normalize)
>   File "/Users/namehere/Library/Preferences/calibre/plugins/FanFicFare.zip/fanficfare/adapters/base_adapter.py", line 444, in get_urls_from_page
>     series = self.get_series_from_page(url,data,normalize)
>   File "/Users/namehere/Library/Preferences/calibre/plugins/FanFicFare.zip/fanficfare/adapters/adapter_archiveofourownorg.py", line 598, in get_series_from_page
>     retval['name']=stripHTML(soup.select_one("h2.heading"))
>   File "/Users/namehere/Library/Preferences/calibre/plugins/FanFicFare.zip/fanficfare/htmlcleanup.py", line 71, in stripHTML
>     retval = soup.get_text(strip=True)
> AttributeError: 'NoneType' object has no attribute 'get_text'
> 
> [67.55] splash screen hidden
> [67.55] Started up in 67.55 seconds with 2421 books

**Comment by JimmXinu** [comment]
Better error message will be in next test version.
