### ISSUE TITLE
Python 2 EoL?

### ISSUE THREAD

**Issue by stranger-danger-zamu** [JimmXinu/FanFicFare#741]
I've always end up thinking of implementing more sites in FFF, or like recently preparing a [flaresolverr solution](https://gist.github.com/stranger-danger-zamu/0a326a14a1123df92f5215414b3a6dd9), but then I'm stopped by the massive configuration file and just stop thinking of incorporating it into FFF. (I did see the flaresolverr test build though which was rad).

A week ago I finally read through `configuration.py` and noticed that it's a lot of manual validation and filtering which options are valid for which sites.  Libraries like pydantic, dataclasses, or attrs easily handle this, but they are strictly Python 3. 

So, I looked into why we still had Python 2 compatibility. Past issues mentioning that it was needed for users running Calibre. 

But now, Calibre 5 supports Python3, FFF also supports Python 3, and  Python 2 has been EoL since 2020 and people have had over a year to upgrade Calibre and FFF. 

Surely we can phase out the python 2 compatibility code. 

Most projects just tell users to upgrade and if they don't then continue using the last working version and expect no support for it. I don't know about you but it seems very reasonable to me.

**Comment by JimmXinu** [comment]
More than 30% of Calibre users are using a pre-5 version. That seems like an excessive number of users to disregard.  There are fewer Mac and Linux users.  Combined.

See https://calibre-ebook.com/dynamic/calibre-usage

Another thing to consider is that I do not accept "because it's newer" or "it's more pythonic" as sufficient reasons for changes.   And I believe very firmly in backward compatibility.  Replacing the config file parsing with anything that would break users' existing files would almost certainly be rejected.

**Comment by stranger-danger-zamu** [comment]
Oh! I didn't realize that such a large number were still utilizing an older version of Calibre. I thought Calibre had an auto-upgrade option already, but I might have been confusing it with something else.

---

As for backward compatibility of files, existing files would **not** break at all. 

Essentially I planned to use plain `configparser.ConfigParser` to parse the .ini files into a ConfigParser object. Then, instead of all the custom manual validation code, I'd use pydantic to parse the internal dictionary representation of the ConfigParser into the new Configuration object.

Since the adapters actually rely on `Configurable` and not `Configuration` directly, then no adapter should require a change. `Configurable` would most switch over to `getattr` instead of `dict.get` and that'd be its biggest change.
 
As for how the new Configuration class would work, it'd be a pydantic BaseModel which is just a fancy dataclass. The top-level configuration object would house all the possible sections. Each section would then either inherit the generic "defaults" config object type or a subclass of the defaults specific to the site, set of sites, format, or set of formats. 

Alas, Python 2. 

Anyways, thanks for all the work you put into this. It's been super helpful.

**Comment by JimmXinu** [comment]
I am resigned to maintaining py2/py3 compatible code for the time being, so I'm going to close this.

Something else to keep in mind is that it is not trivial to pull in python packages while running in Calibre.  If it's not already in bundled in Calibre, you have to either bundle it in the plugin or convince Kovid to add it.  Which he is understandable reluctant to do.
