### ISSUE TITLE
RoyalRoad.com: "name 'ts' is not defined" Error

### ISSUE THREAD

**Issue by dastrdly6585** [JimmXinu/FanFicFare#753]
As of today I am no longer able to update/download stories from royalroad.com.  Every story produces the same error comment: "name 'ts' is not defined".

Looking at the adapter it looks like the issue is at Line 64 of "adapter_royalroadcom.py" where 'ts' is used to set the date.

Sample links which won't work for me: 
https://www.royalroad.com/fiction/41521
https://www.royalroad.com/fiction/39307
https://www.royalroad.com/fiction/35645

Calibre version: 5.31.1 (x64)
FanFicFare version: Latest test version as of 11/01/2021

**Comment by JimmXinu** [comment]
Fixed in da5ec5b35705b045cb116eacc832f191a74a4793

Test versions up now.
