### ISSUE TITLE
Calibre Plugin - Royal Road not working - "name 'ts' is not defined"

### ISSUE THREAD

**Issue by Dioxycillin** [JimmXinu/FanFicFare#755]
Error Message:
"Status
Title
Author
Comment
URL
Error
Unknown
Unknown
name 'ts' is not defined
https://www.royalroad.com/fiction/43036"

So I was trying to download this story using the calibre plugin: https://www.royalroad.com/fiction/43036/magical-girl-kari-apocalypse-system and that error message came up. Furthermore it seems that this applies for other royal road stories.

I have tried uninstalling and reinstalling the fanficfare plugin and restarting calibre, but those did not alleviate the issue.

Lastly, I have the most recent versions of both calibre and fanficfare installed.

**Comment by JimmXinu** [comment]
Dup of #753.  And #754.
