### ISSUE TITLE
Storiesonline.net issue "Click to Load text..."

### ISSUE THREAD

**Issue by defendurname** [JimmXinu/FanFicFare#756]
Storiesonline.net changed how their stories load: it only loads a portion of the story and you need to click once or twice on a button before it reveals the rest: is there a way to solve this problem?

Here is the post that details the change:

https://storiesonline.net/d/s1/t9203/new-site-behaviour-click

**Comment by JimmXinu** [comment]
[It was discussed over on the MR forum](https://www.mobileread.com/forums/showthread.php?p=4168650&postcount=6646) a bit earlier today.

Paid Storiesonline.net accounts don't see that, and, reportedly, FFF works normally with them.  

Given that the site is original fiction, not fanfiction, I'm not inclined to try and work around it.  I might add an error message reporting it.

**Comment by defendurname** [comment]
That's disappointing - I have no idea how much work is involved, and its entirely your decision, but your work has been so useful to me and I would appreciate it if you could see if it was possible. If its impossible, or requires a great deal of work, then its fine to just leave it be.

Many thanks,

**Comment by stranger-danger-zamu** [comment]
I worked out the fix for this, but I don't really have the cycles to integrate it with FFF. 

Below is (Python 3) code to get all the content for some the chapter. I haven't looked at how FFF extracts content from the story so this just retrieves the initial HTML (stored as `content` on line 38) and the HTML that is loaded later (stored as `additional_content` on line 54). 

```python
import httpx
import re
import random
from urllib.parse import quote, urljoin

def parse_cookie(cookie_str: str) -> dict[str,str]:
    item_str = cookie_str.split(';')
    return dict((i_str.split('=',1) for i_str in item_str))


def get_substring_via_regex(html: str, pattern: re.Pattern) -> str|None:
    matches = pattern.findall(html)
    try:
        return matches[0]
    except:
        return None

get_story_id = lambda html: int(get_substring_via_regex(html, pattern=re.compile('var story_id=(\d+)')))
get_pid = lambda html: get_substring_via_regex(html, pattern=re.compile('var pid=(\d+)'))
get_ci  = lambda html: get_substring_via_regex(html, pattern=rre.compile("var ci='([^']+)'"))
get_tto = lambda html: get_substring_via_regex(html, pattern=rre.compile("var tto='([^']+)'"))

BASE_URL = 'https://storiesonline.net/'

def SO_fetchData(php_file_name:str, cmd:str, url_params:list[str]) -> httpx.Request:
    url_path = f"/res/responders/{php_file_name}.php?r={random.randint(100001)}"
    url_params = f'&cmd={cmd}&data[]={"".join(map(quote, url_params))}'
    url = urljoin(BASE_URL, url_path) + url_params
    return httpx.Request('POST', url)
    

def main(chapter_url: str, cookie_str: str):
    with httpx.client(cookies=parse_cookie(cookie_str)) as client:
        resp = client.get(chapter_url)
        resp.raise_for_status()
        content = resp.text

        #bypass double clicking variables
        story_id = get_story_id(content)
        pid = get_pid(content)
        ci = get_ci(content)
        tto = get_tto(content)

        ld1_req = SO_fetchData('tl', 'gt', [story_id, pid, ci, (story_id + 5), tto])
        resp = client.send(ld1_req)
        resp.raise_for_status()
        ver = resp.text

        ld2_req = SO_fetchData('tl','gr', [ver])
        resp = client.send(ld2_req)
        resp.raise_for_status()
        additional_content = resp.text

        ...
```

The JS code in the browser just uses a CSS selector to grab `div#sr` and replaces it's `.innerHTML` with the `additional_content`. For our purposes though it might be better to replace the `div#sr` element with `additional_content` as that might be more faithful to the old layout.

**Comment by JimmXinu** [comment]
I'm leaving this open for better visibility, but I'm marking wontfix.  See [my comment above](https://github.com/JimmXinu/FanFicFare/issues/756#issuecomment-958123103) for why.

**Comment by mvlcek** [comment]
A patched calibre plugin is available here: https://github.com/mvlcek/FanFicFare/releases/tag/v4.12.0

**Comment by JimmXinu** [comment]
#829 has been merged in.  I also added `slow_down_sleep_time:1` to `[storiesonline.net]` in `defaults.ini`. 

Test versions in the usual places.
