### ISSUE TITLE
wuxiaworld.site error message

### ISSUE THREAD

**Issue by morgan-rhea** [JimmXinu/FanFicFare#758]
Just a heads up, attempting to update any of the novels from this site using FFF results in this error message showing, example:

> HTTP Error in FFF '403 Client Error: Forbidden for url: https://wuxiaworld.site/novel/untouchable-lady'(403)

Any ideas?

**Comment by JimmXinu** [comment]
[This has come up in the MR discussion group.](https://www.mobileread.com/forums/showthread.php?p=4168644&postcount=6643)  

I said:
> I have to put wuxiaworld.site through flaresolverr before I get to that error. (I'm noticing a trend here I don't much like.)
> 
> Back in Sept, wuxiaworld.site changed from having the chapter list in a separate POST req to putting in the story page directly. Now, they appear to have changed back, but with a different POST url without any request parameters.
> 
> However, it's not working when I try from FFF. Not sure if that's because of something subtle I'm missing or because flaresolverr won't accept a POST with no parameters.
> 
> If somebody else wants to look at it, great; but I don't have the energy or interest for this right now.

**Comment by JimmXinu** [comment]
FYI, unless someone steps forward with a PR, this site will be removed in the next version, sometime Mar 2022.
