### ISSUE TITLE
feature request/website request the possibility to add the folowing site? https://thesylthorian.com/

### ISSUE THREAD

**Issue by mhussaincov93** [JimmXinu/FanFicFare#759]
hey there,
would it be possible to add this?
here is a story example I would be greatful for any considderations made.
https://thesylthorian.com/latest-chapters/ma-1
Majid Hussain

**Comment by JimmXinu** [comment]
Single author site for original non-fanfiction.  No, I don't think this is an appropriate site for FFF.  Sorry.

**Comment by mhussaincov93** [comment]
Hey there jim,

thanks for at least looking in to this.

also,

thank you for fanficfare!

Majid
