### ISSUE TITLE
ficbook.net BrouserCashe question

### ISSUE THREAD

**Issue by DarkKraban** [JimmXinu/FanFicFare#760]
Hi, I've recently tried to use brouserCashe feature to update a story from www.ficbook.net and got an error:
'NoneType' object has no attribute 'find_all'
Story URL: https://www.ficbook.net/readfic/6076863

Is it something with my settings or BrouserCashe is no longer supported for this site? FF.net works just fine
[tmpq9akkw9x.txt](https://github.com/JimmXinu/FanFicFare/files/7504158/tmpq9akkw9x.txt)

**Comment by JimmXinu** [comment]
Minor site change.  Fixed in 467d79120e3232d1756b6e8a013a9d3eb4275541
