### ISSUE TITLE
[Question] json output

### ISSUE THREAD

**Issue by billsargent** [JimmXinu/FanFicFare#761]
Is it possible to write a json file for each story downloaded? I want to use sqlite-utils to insert the metadata into a sqlite database.

**Comment by JimmXinu** [comment]
Option already exists:

```
  -j, --json-meta       Output metadata as JSON with download, or with --meta-
                        only flag.  (Only JSON will be output with --meta-only
                        flag.)  Also now series name and desc if available
                        with --list
```

**Comment by billsargent** [comment]
I understand that, but this outputs to stdout and I am asking is there a way for  it to write a filename for each story as it goes in batch.  Meaning, if I choose 12 works to download from AO3, that 12 json files come out as well. 

I can't seem to get the json output to std out to pipe into sqlite3 after the first story downloads. Seems that stacking json entries on top of each other doesn't seem to be valid to most things that import json. I'm not precluding that I may be doing something wrong though, which is why I asked.

**Comment by JimmXinu** [comment]
FFF technically outputs one json object per download to stdout, not a singular valid json.  So if you try to read it all as json without any other scripting, I can see why it would fail.

I've uploaded a test version that adds a new option:
```
  --json-meta-file      Similar to --json-meta, but output metadata for each
                        download as JSON to an individual file named by
                        appending ".json" to the output_filename.
```

Not sure why, but github isn't showing me this response, so I'm replying to the email I did get.

**Comment by billsargent** [comment]
That sounds like exactly what I want.

Something I’ve noticed that may or may not be a bug though is that I cannot pipe the data unless it’s with -m … with -j and -z, when I pipe it to tee or try to redirect output, I get nothing from stdout. 

in other words

fanficfare -f txt  -i ../urls.list --force -m -j -z |tee output.json

works

fanficfare -f txt  -i ../urls.list --force -j -z |tee output.json

does not.

I can see the json data on the screen but it just won’t pipe.

**Comment by JimmXinu** [comment]
It's just `print()` in both cases.  I've just tried and it works the same for me both ways, `-jz` and `-mjz`.

**Comment by billsargent** [comment]
I will pull from github then and try. I’m using what pip installs(4.7.0). This’ll also allow me to try your new option. I’m also running python 3.10.  I’ll test more tomorrow when it’s not past midnight 😊

**Comment by JimmXinu** [comment]
https://github.com/JimmXinu/FanFicFare#test-versions
> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by billsargent** [comment]
This all work perfectly now. You can close this if its open. Thanks for the help.
