### ISSUE TITLE
Psychfic.com adapter for current FFF version

### ISSUE THREAD

**Issue by HappyFaceSpider** [JimmXinu/FanFicFare#764]
So, apparently I have too much free time or smth, since I decided to dig through old, old websites. But since psychfic got deleted from FFF in 2017, I decided to remake adapter to work with the current version. I'm kinda noob at programming, but fixing this adapter took me like 5 min and it seems to work just fine, so I thought I'd share in case someone else was interested, but didn't have spare 5 min
[adapter_psychficcom.zip](https://github.com/JimmXinu/FanFicFare/files/7533978/adapter_psychficcom.zip)

EDIT: Yes, this is totally a copy of one of other adapters just fixed to work with psychfic.com links. I'm not good enough to make smth like that from zero.

**Comment by JimmXinu** [comment]
Thanks.  Test versions posted.
