### ISSUE TITLE
Add support for readonlymind.com

### ISSUE THREAD

**Issue by Sixthhokage1** [JimmXinu/FanFicFare#767]

**Comment by Nothorse** [comment]
I have a working adapter for ROM. What's the correct procedure to get it to you?

**Comment by JimmXinu** [comment]
Ideally, fork FFF, upload your changes to your fork and then create a Pull Request.  

Googling `contribute to github project tutorial` finds plenty of detailed instructions.

**Comment by Nothorse** [comment]
OK, done

**Comment by JimmXinu** [comment]
Added by Nothorse in #801

Test versions up in the usual places.
