### ISSUE TITLE
deviantart.com date format fails with %z

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#768]
@jcotton42, could you look at this?

`%z` isn't supported in python2 (at least) and should be avoided in FFF.  (FFF still supports older Calibre versions which still run py2).

Reported in [FFF's google group](https://groups.google.com/g/fanfic-downloader/c/lZwFxwbZprg/m/0kViwChjAwAJ):

> just tried downloading from deviantart.com using the new plugin here is 
> the error I have
> 
> Status
> Title
> Author
> Comment
> URL
> Error
> Unknown
> Unknown
> 'z' is a bad directive in format '%Y-%m-%dT%H:%M:%S.%f%z'
> https://www.deviantart.com/vision-king/art/Daring-Do-Legends-Of-The-Hidden-Temple-Chap-01-889825757

**Comment by jcotton42** [comment]
I'll PR a fix after work today.
