### ISSUE TITLE
Please add support for wordpress websites and novelupdates.com

### ISSUE THREAD

**Issue by vanessabluellie** [JimmXinu/FanFicFare#772]
Hello!

I was just wondering if it was possible to add support to fanficfare for **any wordpress websites** and **https://www.novelupdates.com/**.

Fanficfare is one of the only programs that actually justifies the novel when converted to pdf which is the best! So if possible, I hope more websites could be added! Thank you very much!

**Comment by T-Man2000** [comment]
I do not think that nu is possible. The page would be helpful at most as a source for metadata. Otherwise it only refers to other pages with various blog formats or own scripts.

**Comment by vanessabluellie** [comment]
> I do not think that nu is possible. The page would be helpful at most as a source for metadata. Otherwise it only refers to other pages with various blog formats or own scripts.

OH, that's okay! Then is it also not possible to **add support for wordpress websites** like webtoepub does?

**Comment by JimmXinu** [comment]
**Wordpress** has been requested several times.  Wordpress is a blogging software package/service that some people choose to write fiction on.  It's a very poor fit for FFF's site-author-story-chapter paradigm.  "Wordpress" covers any number of sites, which can be customized any number of ways, without consistent story/chapter structures or metadata to parse.

**novelupdates.com** is not a fanfiction site, or even a story site as such; it's an aggregator that points to other sites for the chapter texts.  Given that, I don't think it's feasible.

Normally, I leave these '[please add XYZ site](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#please-add-site-xyz-to-fanficfare)' issues open in case someone else wants to do it.  But in this case, I don't think I'd accept it even if someone did.
