### ISSUE TITLE
Try to redownload previously-errored chapters with -u

### ISSUE THREAD

**Issue by hseg** [JimmXinu/FanFicFare#775]
# Scenario
- Set up browser cache
- Take a story from fanfiction.net, forget to open one chapter (or be unlucky enough that page doesn't get stored/is cleared from cache)
- Download that story
- Notice the "N chapters errored downloading" message
- Reload the relevant chapters in browser
- Try running `fanficfare -u` on the epub

# Expectation
Regardless of whether there are new chapters, FFF will try to redownload all previously-errored chapters. Since the problematic chapter is now in cache, this will result in a fixed epub.

# Actuality
```
FFF: WARNING: 2021-12-03 00:00:00,000: base_writer.py(199): File(....epub) Updated(2021-12-03) more recently than Story(2021-12-02) - Skipping
```

As far as I can tell, the only option currently available is to add `--force`, which will redownload _all_ chapters, despite the epub being mostly up to date. This is particularly annoying for very long stories.

**Comment by JimmXinu** [comment]
Set `always_overwrite: true`.

As I recall, this is an ancient setting from before I first came to the project.  Or at least, that has to do with matching the behavior of the CLI from back then.

```
[defaults]
## Always overwrite output files.  Otherwise, the downloader checks
## the timestamp on the existing file and only overwrites if the story
## has been updated more recently.  Command line version only
always_overwrite: true
```

**Comment by hseg** [comment]
OK, a little testing shows that it is an adequate solution. The documentation you quote seems to mean it implies `--force`, but the `--debug` output seems to indicate it only polls errored and new chapters. Which is correct?

**Comment by hseg** [comment]
Going through the code:
- [`fanficfare/cli.py`](https://github.com/JimmXinu/FanFicFare/blob/a2523f1a1e2b63a66dade4de4555fc2694ea880b/fanficfare/cli.py#L593) shows `--force` implies `-o always_overwrite=true`. Other than this, the only difference between the two seems to be [this near-duplication](https://github.com/JimmXinu/FanFicFare/blob/a2523f1a1e2b63a66dade4de4555fc2694ea880b/fanficfare/cli.py#L462-L483) of the call to `write_story` 
- [`fanficfare/writers/base_writer.py`](https://github.com/JimmXinu/FanFicFare/blob/c8a695c73574a979f7c2281edd56e75b322f65dd/fanficfare/writers/base_writer.py#L193) shows `always_overwrite` controls whether to check modification time against update time
- Interestingly, `fanficfare/cli.py` never calls `writeStory` with `forceOverwrite=True`, even with `--force`. Instead, this code path is restricted to `calibre-plugin/jobs.py`
