### ISSUE TITLE
Novelfull.com is giving a 403 error

### ISSUE THREAD

**Issue by aditseng** [JimmXinu/FanFicFare#776]
```
HTTP Error in FFF '403 Client Error: Forbidden for url: https://novelfull.com/lord-of-all-realms.html'(403)
https://novelfull.com/lord-of-all-realms.html
```

**Comment by JimmXinu** [comment]
novelfull.com is one of the sites that is using CloudFlare to block automated access.

FFF can still be used if you also use the [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr/) proxy.

See: https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures#flaresolverr
