### ISSUE TITLE
Support for huge fics

### ISSUE THREAD

**Issue by hseg** [JimmXinu/FanFicFare#777]
Reporting for a discord compatriot:
For very large fics (many large chapters), FFF dies halfway through processing.
The example given was https://forums.sufficientvelocity.com/threads/a-sword-without-a-hilt-a-song-of-ice-and-fire-d-d-3-5-crossover.27579/reader/ (6k chapters, 5m words), for which the FFF Calibre plugin gave up 4h in. [Error log](https://github.com/JimmXinu/FanFicFare/files/7669862/Error.txt)
Judging by the traceback, I suspect there is just a bug in this particular fic.

However, the fact that such large fics exist in the wild suggests it might be useful to both have a dry-run feature (listing the urls FFF would need to download) and a basic cache implementation (storing `scheme://domain/path` at `$cache/domain/path` or the like) so that a) retrying partial downloads doesn't hit the server again and b) users can use external downloaders to download the pages in parallel

In any case, I suspect this kind of fic is rare enough that this bug isn't high priority, but I thought it'd be useful as a stress-test case.

**Comment by JimmXinu** [comment]
Error text says: `calibre, version 5.8.1 (win32, embedded-python: True)`  

We've seen other users have problems with extremely large stories using windows 32bit version.  As I recall most, if not all, had better luck using 64bit Calibre.  Plus the usual suggestions about upgrading to the latest official versions.

For development purposes, FFF CLI has an undocumented `--save-cache` feature that saves cache and cookie state to a couple files on disk.  I use it all the time when developing adapters to avoid hitting the same pages over and over testing the parsing.

I spent some considerable time pondering how and whether to make that an official user feature and eventually concluded that all the details of managing such a cache properly were not worth it.  This is built on the  `use_basic_cache` feature that passes cache/cookies from foreground to background job in Calibre, if you're curious.

In theory, FFF could save cache/cookies while downloading for failure recovery.  In practice, I don't think it's common and would be even more complicated to make work correctly.

Multiple parallel downloads is something FFF deliberately does _not_ do in an effort to be more respectful of the hosting sites.

**Comment by JimmXinu** [comment]
No follow up from OP; uncommon corner case usually solvable with 64bit version or splitting using chapter ranges.
