### ISSUE TITLE
cli.py: Split off argument parsing into a function

### ISSUE THREAD

**Issue by hseg** [JimmXinu/FanFicFare#779]
Both `do_download` and `get_configuration` in `cli.py` need a valid `options` parameter. For scripts reusing FFF's logic (or just test harnesses), it'd be useful to have a way to construct such an object. In particular, it'd be better to reuse FFF's logic here to keep in sync.

The obvious-looking answer is to wrap [`fanficfare/cli.py:74-180`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L74-L180) in a `parseArgs` function. More work, but potentially also benefiting readability would be to entirely break up `main` into phases, eg
*   `parseArgs` (lines [`74-180`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L74-L180),[`217-221`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L217-L221),[`234-236`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L234-L236))
*   `validateArgs` ([`182-184`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L182-L184),[`223-225`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L223-L225),[`238-242`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L238-L242))
*   `setup` ([`186-191`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L186-L191),[`197-215`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L197-L215))
*   `dispatch` ([`193-195`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L193-L195),[`227-232`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L227-L232),[`246-322`](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/cli.py#L246-L322))

(in fact, looking at some of this, there might be room for leaning on some of `argparse`'s features to remove some of the validation/dispatch logic)

But even `parseArgs` alone would immediately be useful to me -- I have written a little wrapper around FFF's `-l` functionality to notify me if any author/collection I follow has added a story. As long as I didn't need to use cache configuration, all was fine, but now that I'm monitoring some FFN pages, I'd like to reuse my browser cache configuration from my `personal.ini`.

In case it is relevant, below is the FFF-specific part of the script, assuming this issue is resolved.
```python
def indexFile(adapter, url, name=None):
    import urllib

    return '{}_{}'.format(
        adapter.story.getMetadata('siteabbrev'),
        urllib.parse.urlparse(url).path.replace('/', '%')[1:])
    + f'-{name}' if name else ''


def getIndex(url):
    from fanficfare import adapters
    from fanficfare import geturls
    from fanficfare.cli import parseArgs, get_configuration

    options, _ = parseArgs(['-l', url])
    configuration = get_configuration(url, None, None, options)
    adapter = adapters.getAdapter(configuration, url, anyurl=True)
    page = geturls.get_urls_from_page(url)
    return {
        'urllist': page['urllist'],
        'file': indexFile(adapter, url, page.get('name'))
    }
```

**Comment by JimmXinu** [comment]
You may submit a PR with such changes if you'd like.

**Comment by hseg** [comment]
> (in fact, looking at some of this, there might be room for leaning on some of `argparse`'s features to remove some of the validation/dispatch logic)

Had misread original code -- we use `optparse`, which is less clever than `argparse`. In particular, folding in the logic for `version` and having the mutual exclusivity of list/download enforced by the parser is off the table.

Is there any reason we use `optparse`, though? It is deprecated since 3.2, released 2011-02-20

**Comment by JimmXinu** [comment]
FFF maintains backward compatibility to Python 2.7 for older Calibre versions.  And the Calibre plugin can be called as CLI.

There are still some 25% of Calibre users on Python 2.7.  It's now very close, but there are still more Calibre users on Calibre v2 than use Calibre on Linux, for example.  https://calibre-ebook.com/dynamic/calibre-usage

**Comment by hseg** [comment]
Fair enough. Though `argparse` was backported to python 2.7 as well.

**Comment by hseg** [comment]
OK, it's getting late here, will leave the expanded refactor for later.

**Comment by hseg** [comment]
OK, my use case is satisfied. Will still work on the refactor, but that will be a separate PR.
