### ISSUE TITLE
More detail on which chapters failed

### ISSUE THREAD

**Issue by foreal26** [JimmXinu/FanFicFare#785]
This is related to #647 

I've fully moved over to using browser caching with FanFicFare. Every once in a while I'll update a fic in my calibre library and the log says something like

```
Update epub completed, added 2 chapters, 1 failed chapters, for 34 total.
```

Is there any way to see which chapter failed and/or add it?

**Comment by JimmXinu** [comment]
Open the epub and failed chapters will be marked in the TOC.  TOC entry will end with "(CHAPTER ERROR)".  That text can be changed with setting `chapter_title_error_mark` if you like.

Next time you update that epub, FFF will not count ERROR chapters towards determining if the story has new chapters, and FFF will try to download ERROR chapters again.  So you can load the failed chapters in browser and run update on the story immediately.
