### ISSUE TITLE
Support pulling stories from Fanfiction.net Communities

### ISSUE THREAD

**Issue by pokeball99** [JimmXinu/FanFicFare#790]
Example: https://www.fanfiction.net/community/Longest-Stories/64113

**Comment by JimmXinu** [comment]
From what I see, all of the stories under fanfiction.net/community are normal ffnet stories that work as well as any do from ffnet these days.  See #703 about the ongoing issues with ffnet.

Please provide specific story url example(s) if there are different ones.

**Comment by JimmXinu** [comment]
You can re-open this if you come up with an example.

**Comment by pokeball99** [comment]
@JimmXinu what was meant was, in the example of the OP link, instead of having to manually collect the 500+ story links in that community to post, one could simply put in the single link, and it'd download the fics.

**Comment by JimmXinu** [comment]
FFF CLI has the `-l`/`--list` option to fetch URLs from a page and the `--download-list` option to immediately download them.  Plugin version has a similar "Get Story URLs from Web Page" feature.

You do have do to it separately for each page of links.  That part of the code is generally site-agnostic and doesn't know how to follow pages.

And if you do try to download 500 stories at once from ffnet, I expect you _will_ be blocked, judging by what we've seen lately from them.
