### ISSUE TITLE
Xenforo title parsing fails with Calibre 4.23 (python2)

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#791]
Apparently there are regular expression differences between py2 and py3 that cause problems with the changes is #783.  See this [MobileRead post](https://www.mobileread.com/forums/showthread.php?p=4189352#post4189352).

It has to do with handling of grouping being changed between the versions.  [This stackoverflow](https://stackoverflow.com/questions/45691878/python-2-and-3-re-sub-inconsistency) explains.

@hseg - Would you like to take a stab at fixing it for both versions?  

Otherwise, my inclination is to revert 45e5121378ce611790d32e02f1e085da4901aa8a.  It helps with a few stories while breaking all XenForo stories for all pre-Cal5 users.

**Comment by hseg** [comment]
Reproduced the snippet here. A quick fix a la the SO post would be to include
the parens/brackets in the tag (so eg `Abaddon Born(e) - (Worm CYOA)` would be
tagged `(e),(Worm CYOA)` instead of `e,Worm CYOA`). This can be done by a patch
like
```diff
- tagsfromtitle=>^.*?(\[([^\]]+)\]|\(([^\)]+)\)).*?$=>\2\,\3
+ tagsfromtitle=>^.*?(\[[^\]]+\]|\([^\)]+\)).*?$=>\1
```
If this is an acceptable compromise, will open a PR for it.

**Comment by hseg** [comment]
Reproduced the snippet here. A quick fix a la the SO post would be to include
the parens/brackets in the tag (so eg `Abaddon Born(e) - (Worm CYOA)` would be
tagged `(e),(Worm CYOA)` instead of `e,Worm CYOA`). This can be done by a patch
like
```diff
- tagsfromtitle=>^.*?(\[([^\]]+)\]|\(([^\)]+)\)).*?$=>\2\,\3
+ tagsfromtitle=>^.*?(\[[^\]]+\]|\([^\)]+\)).*?$=>\1
```
If this is an acceptable compromise, will move forward with this solution

**Comment by hseg** [comment]
Well, actually there is another, but much uglier, solution that works for both pythons:
```python
re.match(r"^.*?((?P<br>\[)|(?P<pr>\())(?P<tag>(?(br)[^\]]|(?(pr)[^\)]|.))+)(?(br)\]|(?(pr)\))).*?$", title).group('tag')
```
will extract the tag, dropping braces/parens as necessary

**Comment by JimmXinu** [comment]
> A quick fix a la the SO post would be to include
the parens/brackets in the tag (so eg Abaddon Born(e) - (Worm CYOA) would be
tagged (e),(Worm CYOA) instead of e,Worm CYOA). This can be done by a patch
like
> ```diff
> - tagsfromtitle=>^.*?(\[([^\]]+)\]|\(([^\)]+)\)).*?$=>\2\,\3
> + tagsfromtitle=>^.*?(\[[^\]]+\]|\([^\)]+\)).*?$=>\1
> ```
> If this is an acceptable compromise, will move forward with this solution

Unfortunately, I don't think it is.  We would need to add patterns to remove the surrounding paran/bracketes, which isn't a deal breaker.  But it doesn't work properly with this [example](https://forums.spacebattles.com/threads/of-blackguards-and-mercenaries-worm-alt-power-overwatch-crossover.506906/) from #782.  Ends up with `(Alt!Power), Overwatch Crossover]`.

> ` tagsfromtitle=>^.*?((?P<br>\[)|(?P<pr>\())(?P<tag>(?(br)[^\]]|(?(pr)[^\)]))+)(?(br)\]|(?(pr)\))).*?$=>\g<tag>`

This one doesn't work perfectly with the [example](https://forums.spacebattles.com/threads/of-blackguards-and-mercenaries-worm-alt-power-overwatch-crossover.506906/) from #782.  Instead of `Overwatch Crossover, Worm (Alt!Power)`, we get `Alt!Power, Overwatch Crossover`.  And I had to look up the regexp docs to understand it. But so far it seems to be the best option?

`/abaddon-born-e-worm-cyoa.46367` is interesting because it is a case where the author _didn't_ use `(e)` as a tag, but as part of the title: `Abaddon Born(e) - (Worm CYOA)`  All of the regexps we've considered stop at `(e)` and don't pick up `(Worm CYOA)`. Just shows we're probably never going to get it entirely right in all cases.

I have some other things to look at, but I'll come back to this.

**Comment by JimmXinu** [comment]
I am still looking at this.  And despite being the one who wrote it, the intricacies and interactions of the `replace_metadata` system continue to surprise me.

The version you created that worked best (with py3) was:
> `tagsfromtitle=>^.*?(\[([^\]]+)\]|\(([^\)]+)\)).*?$=>\2\,\3`

That works because of the `\,` that splits the output of the line into two entry items instead of one.  Then the recursion prevention code stops that line from being called again on the two items.

Without the `\,` splitter, text like `Worm (Alt!Power)` will go through again during the comma splitting lines (like `tagsfromtitle=>([^,]+),(.+)=>\1\,\2`) and be changed to `Alt!Power`.

So adding a splitter that does nothing helps:

`tagsfromtitle=>^.*?((?P<br>\[)|(?P<pr>\())(?P<tag>(?(br)[^\]]|(?(pr)[^\)]))+)(?(br)\]|(?(pr)\))).*?$=>\g<tag>\,`

That works correctly in py2/py3 for titles such as:
- Of Blackguards and Mercenaries [Worm (Alt!Power) / Overwatch Crossover] -> 'Overwatch Crossover, Worm (Alt!Power)'
- Savage (Worm AU/OOC) -> 'OOC, Worm AU'
- Await the Dawn [Worm/Exalted] -> 'Exalted, Worm'
- Seven Days to Skitter -> ''
- [Pre-canon] The Moon Is Watching -> 'Pre-canon'
- Bob's Story (RoboTrek Crossover / Worm [Alt!Power]) -> 'RoboTrek Crossover, Worm [Alt!Power]'
- The Raven's Nest [Story Snips, One-Shots, Half-Assed Ideas] -> 'Half-Assed Ideas, One-Shots, Story Snips'

It does *not* work well with:
- Abaddon Born(e) - (Worm CYOA) -> 'e'
- Scaling Up [AU][Alt!Power][OP Taylor][Dragons][D&D][Mangled Mythology] -> 'AU'

But then neither did any of our earlier patterns.

While it is *a* solution I want to look at this a bit longer to see if I can find a better solution that doesn't rely on side effects.

FYI, for testing, I'm using the testing.ini (renamed to .txt for github limitations) attached and testing story URLs:
```
http://test1.com?sid=1005
http://test1.com?sid=1006
http://test1.com?sid=1007
http://test1.com?sid=1008
http://test1.com?sid=1009
http://test1.com?sid=1010
http://test1.com?sid=1011
http://test1.com?sid=1012
http://test1.com?sid=1013
```
[testing.ini.txt](https://github.com/JimmXinu/FanFicFare/files/7884101/testing.ini.txt)

**Comment by hseg** [comment]
On 17 January 2022 8:40:58 pm GMT+02:00, Jim Miller ***@***.***> wrote:
>I am still looking at this.  And despite being the one who wrote it, the intricacies and interactions of the `replace_metadata` system continue to surprise me.
>
>The version you created that worked best (with py3) was:
>> `tagsfromtitle=>^.*?(\[([^\]]+)\]|\(([^\)]+)\)).*?$=>\2\,\3`
>
>That works because of the `\,` that splits the output of the line into two entry items instead of one.  Then the recursion prevention code stops that line from being called again on the two items.
I'm surprised it caused problems - the nongreedy match at the start seems like it should match the entire [] in eg "Of Blackguards and Mercenaries [Worm (Alt!Power) / Overwatch Crossover]"

>So adding a splitter that does nothing helps:
>
>`tagsfromtitle=>^.*?((?P<br>\[)|(?P<pr>\())(?P<tag>(?(br)[^\]]|(?(pr)[^\)]))+)(?(br)\]|(?(pr)\))).*?$=>\g<tag>\,`
Because `\,` stops the rewriting?

>It does *not* work well with:
>- Abaddon Born(e) - (Worm CYOA) -> 'e'
We could replace `+` by `{2,}` to avoid too short tags, or replace the `^.*?` at the start with `^(?:.*?[\]) ])?` to require a space or other tag before tags in the middle of the title to avoid this.
>- Scaling Up [AU][Alt!Power][OP Taylor][Dragons][D&D][Mangled Mythology] -> 'AU'
Is the problem here that only one tag extracts? If so, then it's a broken assumption of mine that the tag-extraction regexes would be run on the remaining text. Perhaps this is because the regex matches the entire title? Otherwise, would consider "AU" a perfectly valid tag.

A potential less-hacky solution would be to have the `replace_metadata` engine support `field=>pat=>new_elems=>rewritten field` type rules. Then it suffices to match one tag at a time and erase it out, and the engine will take care of the iteration.

In fact, this sparked an idea for a potential cross-py solution: just split the rule into two:
 ```
tagsfromtitle=>^.*?\[([^\]]+)\].*?$=>\1
tagsfromtitle=>^.*?\(([^\)]+)\).*?$=>\1
```

Have less free time nowadays, will try to give this a look over the weekend.

**Comment by JimmXinu** [comment]
Splitting into two rules causes both to be applied and we end up with only the last matching part:
- Of Blackguards and Mercenaries [Worm (Alt!Power) / Overwatch Crossover] -> 'Alt!Power'
- Bob's Story (RoboTrek Crossover / Worm [Alt!Power]) -> 'Alt!Power'

I'm not that concerned about the "(e)" case.  We're never going to get perfect coverage.

I feel like there should be a way to deal with "Title [X][Y][Z]", "Title (A) (B) (C)" and the like.  Some form of `\][ ]*\[=>,` and same for )(.  Not sure what would happen with "Title [J] (K) [L]".  

I'll see what I can figure out.

**Comment by hseg** [comment]
On 18 January 2022 2:00:08 am GMT+02:00, Jim Miller ***@***.***> wrote:
>Splitting into two rules causes both to be applied and we end up with only the last matching part:
Hrm. So basically the problem with splitting the rule in the current design is that _all_ tags are rewritable by rules at all times, until we stop rewriting. In particular, there's no way to express "this is the literal tag we want, don't touch it further". My "emit tags+rewritten field" proposal above does solve that part, but it breaks a different part of the design - there _are_ some rules we want to be able to fire after tag extraction, eg canonicalizations (pairings, fandoms, …).
One possible design direction is to allow rules of form `field=>pat=>repl=>extr=>out`, which matches `pat` against `field`, replaces `field` with `repl`, and appends `extr` to `out`. Then we can separate rule phases by naming the fields differently, eg `title->tagless_title+tags->clean_title+tagsfromtitle`

**Comment by hseg** [comment]
Fair enough.
Indeed, rerunning arbitrary rules can cause nonobvious infinite loops. There may be a way forward - eg, if you know the substitution is always shorter than the original field - but it's not clear how to design such a system.

**Comment by JimmXinu** [comment]
Test versions posted.
