### ISSUE TITLE
wuxiaworld.com adapter not working after website redesign

### ISSUE THREAD

**Issue by mtsitzer** [JimmXinu/FanFicFare#796]
The adapter for wuxiaworld.com is not working after the recent website redesign

**Comment by JimmXinu** [comment]
This has also been [reported on MobileRead](https://www.mobileread.com/forums/showthread.php?p=4191385&postcount=6837).  

This is want I said about it there:

> I'm not sure that is fixable. The site is now requiring your browser to download and run a sizeable obfuscated javascript file. And another 100+ other JS files??
> 
> FFF doesn't have a javascript engine, and just using FlareSolverr proxy doesn't work either.

**Comment by mtsitzer** [comment]
Roger that. That does indeed sound like a dead end

**Comment by vuonojenmustaturska** [comment]
Wuxiaworld seems to be doing the heavy lifting using some sort of a bespoke binary grpc protocol, for example chapters are fetched by posting a very small struct to api.wuxiaworld.com/wuxiaworld.api.v2.Chapters/GetChapter (content type: application/grpc-web+proto) which returns a struct that contains the chapter title and content html along with other stuff (cover urls etc). At a glance it seems fairly barebones, the problem where I stopped was that browser dev tools (and har files they produce) do not handle binary requests gracefully and doing the capture outside a browser is fairly annoying for https

**Comment by budikesuma** [comment]
@JimmXinu 

**Chapter Content fetch:** 

```
<div class="chapter-content ww
```
```
<div class="fr-view
```

**Chapter Title fetch:** 

```
<h4 class="MuiTypography-root MuiTypography-h4 my-[20px] flex items-center
```

Uploaded file: 

[Wuxiaworld.com Chapters.zip](https://github.com/JimmXinu/FanFicFare/files/7922765/Wuxiaworld.com.Chapters.zip)

Good luck devs...

**Comment by JimmXinu** [comment]
FYI, unless someone steps forward with a PR, this site will be removed in the next version, sometime Mar 2022.

**Comment by Chibba-dev** [comment]
this https://github.com/dipu-bd/lightnovel-crawler
 works on ww.com again
