### ISSUE TITLE
Spacebattles now requires login for all pages, 403's on valid credentials

### ISSUE THREAD

**Issue by hseg** [JimmXinu/FanFicFare#802]
Every SB fic I try requires login now. This isn't a cross-xenforo thing, SV is fine with guests.
Trying to pass credentials, both in `personal.ini` and on the command-line fail with 403.
Credentials are valid -- tested logging to SB with them.

**Comment by JimmXinu** [comment]
I'm not seeing that behavior.  It's working the same as always for me.

It's possible you've been flagged in some fashion, especially if you've been downloading a lot recently.

**Comment by hseg** [comment]
On Sun, Jan 30, 2022 at 04:13:08PM -0800, Jim Miller wrote:
> I'm not seeing that behavior.  It's working the same as always for me.
> 
> It's possible you've been flagged in some fashion, especially if you've been downloading a lot recently.

That's possible -- have been consistently getting captchas from Google and
Cloudflare over here. Perhaps this will vanish when I retry later?
Thanks

**Comment by JimmXinu** [comment]
Still can't duplicate.  Assumed to be user/IP/network specific blocking.

**Comment by hseg** [comment]
OK, finally got my ISP to delist the IP address I was using - apparently a previous user got it on an abuse blacklist. Diagnosed this using the advice from https://docs.chocolatey.org/en-us/troubleshooting#im-getting-a-403-unauthorized-issue-when-attempting-to-use-the-community-package-repository, hopefully the resources there will be useful if someone has a similar problem.
