### ISSUE TITLE
Non interactive switch, debug output.

### ISSUE THREAD

**Issue by nerdguy1338** [JimmXinu/FanFicFare#804]
When I'm using the non-interactive option with a list of links,  can it put the links that need to be logged in into a separate file?

**Comment by JimmXinu** [comment]
That seems very specific.  I will consider code contributions to do something like that, but I'm not interested in doing it myself.

**Comment by nerdguy1338** [comment]
You can go ahead and close this ticket I've actually discovered an AO3
search ability, which I can use to filter those out.

Thanks for the quick reply!

I love this project so much!
