### ISSUE TITLE
Error when downloading from deviantart.com

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#805]
@jcotton42 - 

There's a user asking about deviantart.com on the FFF Google Group.  Could you take a look at it?

https://groups.google.com/g/fanfic-downloader/c/8G3PqxmOt1w

Marq FJA says:
> I'm trying to download a couple of stories from [deviantart.com](http://deviantart.com/), and keep having it fail on me with the same error message:
>
> HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.deviantart.com/users/login'(403)
>
> What does this mean? Am I doing something wrong?

**Comment by sidney** [comment]
I'm not volunteering to fix it, but I can verify that the early login step in line 76 of adapter_deviantartcom.py no longer works as can be verified by:

`curl --head 'https://www.deviantart.com/users/login'`

returning `HTTP/2 403`

**Comment by jcotton42** [comment]
I have no idea how I missed this notification, oops.

I suspect the 403 is from CloudFront, much like what I found in #895.

**Comment by JimmXinu** [comment]
Okay, thanks.

**Comment by jcotton42** [comment]
Closing this seems premature. It may be solvable the same way fanfiction.net was solved, with the browser cache.

Unless you aware offhand of a ClloudFront bypass.

**Comment by JimmXinu** [comment]
The issue can be reopened when needed.
