### ISSUE TITLE
Update date for SOL is not collected and forwarded

### ISSUE THREAD

**Issue by T-Man2000** [JimmXinu/FanFicFare#808]
I'm not sure if it's a setting error or if something about the extension is not working. The issue is SOL. Stories there offer as date "Posted" and "Updated".

Under the Custum Colums I have set it so that the date of "Updated" should be entered in a field. In addition, "Created" and "Published" are offered for the field. "New Only" is not activated.

When I select "Update EPUB if New Chapters" as Update Mode, but also when I select "Overrite Always" or "Update Calibre Metadata from Web Page", the field for the update date is not filled with the corresponding date. It usually says the date for "Posted". 

Since the site offers adult stories, I'm not posting a link here for now, but I can submit them later. But possibly this can also be understood without.

**Comment by T-Man2000** [comment]
I also ran Calibre in debuge mode during an "Update Calibre Metadata from Web Page". I'm happy to provide, but not publicly if it can be avoided.

And I experimented a bit with other stories. I guess it has something to do with the text "inactive" after the date. 

```
Posted: 2014-06-09 Inactive
Updated: 11.3.2020, 18:03:59 (Added Chapter 17)
```

**Comment by JimmXinu** [comment]
The code for `dateUpdated` in [adapter_storiesonlinenet.py is here](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/adapters/adapter_storiesonlinenet.py#L443).  It looks for Posted, Concluded or Updated, with a side order of 'Last Activity'.  

If you have a story it doesn't work with, I'm going to need the story URL to figure anything out.  I don't know what github's policy is, but we haven't had problems before.  If you have a story that shows the issue and is SFW, I would prefer it.

**Comment by T-Man2000** [comment]
I think I have found a story that fits. It is SFW. And shows the problem.

```
Link: https://storiesonline.net/s/59779/the-horseman
Posted: 2009-03-14 Inactive
Updated: 10.2.2018, 17:59:46 (Added Chapter 10)
```
The update date given here by FFF is the date for the post.

**Comment by JimmXinu** [comment]
Test version in the usual place.

**Comment by T-Man2000** [comment]
It works. I have tested it on 5 stories. Thank you very much.

Out of curiosity. Was it the "Inactive" text after the date that caused the error?

**Comment by JimmXinu** [comment]
In a way.  When "Last Activity" was in the status, the date needed to be read from there.  Otherwise, it appears that it's before with an "Updated" label.
