### ISSUE TITLE
Add normalize_chapterurl() and improve internalize_text_links support in royalroad.com

### ISSUE THREAD

**Issue by sidney** [JimmXinu/FanFicFare#813]
RoyalRoad supports various URL formats for chapter URLs that are not recognized by the current adapter. This prevents `internalize_text_links` from working properly on some of the links in at least one story I have seen,
https://www.royalroad.com/fiction/51335/pathogen-forge-your-own-path-reader-interactive
 I'm preparing a PR that fixes that. It leaves the normalized form of chapter URLs as the same format as RR puts on the story ToC page. That format is
 `https://www.royalroad.com/fiction/STORYID/STORYTITLE/chapter/CHAPTERID/CHAPTERTITLE`
where STORYID is a numeric id for the story, STORYTITLE is the text title of the story, CHAPTERID is a numeric id for the chapter that is unique across the entire RR site, and CHAPTERTITLE is the text title of the chapter.

The RR server accepts a chapter URL in the above format or with an optional final '/'. However, it ignores the STORYID as long as it is a numeric string of any value, and ignores the STORYTITLE and CHAPTERTITLE fields as long as they are non-empty strings. All that matters is that CHAPTERID is the numeric id of a chapter on the site.

In addition RR accepts a chapter URL in the format `https://www.royalroad.com/fiction/chapter/CHAPTERID` with optional final '/'. Because CHAPTERID is a unique identifier for a chapter, the URL does not need to include anything about the story or the chapter title.

The PR I am submitting creates a dictionary when the chapter URLs are read from the story's ToC page, keyed by the numeric chapter IDs. It implements normalize_chapterurl() in the royalroad adapter that recognizes all the above forms of URL as long as the story id field is found in that dictionary.

**Comment by JimmXinu** [comment]
Addressed in #814 
Test versions in the usual places.
