### ISSUE TITLE
Royal Road span style goes missing

### ISSUE THREAD

**Issue by ocin4** [JimmXinu/FanFicFare#815]
Hi,
I was downloading a story from royalroad.com. In the HTML source there are `<span style="font-style: italic">`. In the resulting epub there are only `<span>` and the text isn't italic. 
Story I downloaded: https://www.royalroad.com/fiction/15449/quod-olim-erat
It occurred to me in Chapter 5 (https://www.royalroad.com/fiction/15449/quod-olim-erat/chapter/186777/5-twenty-percent-reduction).

**Comment by JimmXinu** [comment]
This is a deliberate feature.  See FAQ [Why doesn't the color / font / special formatting from the story appear in the eBook FanFicFare produces?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-doesnt-the-color--font--special-formatting-from-the-story-appear-in-the-ebook-fanficfare-produces)
