### ISSUE TITLE
a few questions really

### ISSUE THREAD

**Issue by mhussaincov93** [JimmXinu/FanFicFare#816]
hi,
sorry  if this is not the place for this, please forgive me if in error.
update epub in fanficfare cli does the -u option append new chapters to epubs that have allready been downloaded?
and not redownload all chapters?
in other words
I download a story a few days before and there is an update to the story after.
I use fanficfare -d -u story URL 
will fanficfare append new chapters and download only the latest chapters?
if not,
could this be added to fanficfare cli?
I could see this would save bandwith and hitts to the servers.
another question
regarding royalroad and the stub status and my output directory query
here's my output directory layout currently.

output_filename: //home//majid//fics//$site//$author//$status//$category//$title//$title$formatext

now since when a author moves there novel to amazon ku, they have to purge most of there first volume, what will happen in regards the -u flag and fanficfare?
and my output dir layout?
thank you,
Majid Hussain

**Comment by JimmXinu** [comment]
Yes, the `-u`/`--update-epub` option adds new chapters to the epub without downloading existing chapters.

FFF looks at the number of chapters in the epub vs the number on the site to decide whether an update is needed.  

FFF does *not* do update if the number of chapters on the site is less than or equal to the number of chapters in the epub.    FFF will not update if it didn't find any valid chapter URLs in the epub.

Then FFF compares the chapter URLs on the site to those in the existing epub chapters and downloads the ones it doesn't have.

github issues are more for reporting problems than asking questions.  The [Google group/mail list](https://groups.google.com/g/fanfic-downloader) is the most common forum for FFF CLI users.

**Comment by mhussaincov93** [comment]
hi,
thank you for answering.
i'll remember the group in future.
thank you :)

**Comment by famewolf** [comment]
Is there a marker or some text we can search for to jump to the new chapter?  Adding an update seems to reset ebook-viewer to the beginning of the book and it's not always easy to remember where you were in the book if it's been a while since an update.

**Comment by JimmXinu** [comment]
There's a feature for that, but you have to turn it on before updates:
```
## If true, when updating an epub that already has old chapters, new
## chapters will be marked in the TOC and chapter header by using
## chapter_title_new_pattern and chapter_title_addnew_pattern to set
## the chapter title.
## If set to latestonly, only new chapters downloaded this time will
## be marked (new) and existing chapters will have any (new) marks
## removed.
## mark_new_chapters can be true, false or latestonly
mark_new_chapters:false
```

FYI, the [MR plugin forum thread](https://www.mobileread.com/forums/showthread.php?t=259221) is the best place to ask questions for Calibre plugin users.

**Comment by famewolf** [comment]
Thank you.  I'll do so in future!
