### ISSUE TITLE
FanFicFare does not preserve width and height attributes on <img> tags

### ISSUE THREAD

**Issue by jcotton42** [JimmXinu/FanFicFare#817]
When downloading a story with embedded images FanFicFare drops the width and height tags, resulting in images having the incorrect size in a book.

Example story: https://archiveofourown.org/works/34302400/chapters/86055253, Ctrl+F for "Guys you know" to jump to the paragraph with the image. Here's how it looks on AO3
![image](https://user-images.githubusercontent.com/5257450/159195494-8c9722c8-5706-45d9-bbe5-c3124b8a8dd9.png)

And here's the HTML for the image
```html
<img src="https://img3.pillowfort.social/posts/2941a8d66a33f621a151.png" alt="wheeze" width="38" height="36"/>
```

This is how it looks in Calibre's ePub viewer after being downloaded with FanFicFare
![image](https://user-images.githubusercontent.com/5257450/159195542-0316f169-15ad-4da1-b339-4edbf6717e1d.png)

And here's the HTML in the ePub
```html
<img alt="wheeze" longdesc="https://img3.pillowfort.social/posts/2941a8d66a33f621a151.png" src="images/ffdl-0.jpg"/>
```
Note the missing `width` and `height` attrs.

**Comment by JimmXinu** [comment]
Functioning as designed.  

From `defaults.ini`:
```
## Some attributes cause problems for EBook readers.  By default,
## FanFicFare will remove all attributes except the ones specified
## from all tags.  (The only exception is that <img> tags will also
## keep src, alt and longdesc attributes.  data-orighref is used by
## internalize_text_links to preserve links when chapters are
## inserted.)
## Example: To add 'style', 'title' and 'align' to the list to keep,
## in your personal.ini [defaults] put:
## add_to_keep_html_attrs:,style,title,align
keep_html_attrs:href,name,class,id,colspan,rowspan,data-orighref
```

To keep height/width attributes, put `add_to_keep_html_attrs:,height,width` in your `personal.ini` under your choice of `[defaults]` for all downloads, `[archiveofourown.org]` for just AO3 or `[https://archiveofourown.org/works/34302400/]` for just that story.

There is the added wrinkle that FFF, by default, scales larger downloaded images to fit in the `image_max_size` setting.  Attribute processing and image processing occur in different places and FFF has no ability to adjust height/width attributes to match.

It seems kind of weird that the author would include an 860x820 image forceably scaled down to 38x36...

**Comment by jcotton42** [comment]
Ah, completely missed that, thanks for the clarification.

Is there some way to restrict what elements those attrs will be kept for? Like only keep height/width if they're on an <img> tag.

**Comment by JimmXinu** [comment]
There isn't a way right now.  It would add a fair bit of extra processing to break that processing out by tag.  

I'd want to see a fair number of example stories that would benefit before I'd want to add that.
