### ISSUE TITLE
[FR] Number EPUBs downloaded from a list

### ISSUE THREAD

**Issue by NightMachinary** [JimmXinu/FanFicFare#819]
https://github.com/JimmXinu/FanFicFare/issues/253 suggests using `fanficfare --non-interactive  --download-list=https://archiveofourown.org/series/2182653` to download an AO3 series. This loses the order of the parts of the series, which makes merging the EPUBs automatically impossible. If the files can be numbered per their original order, we can easily automate this though.

**Comment by NightMachinary** [comment]
I have also seen this on Reddit:
> If you have the plugin FanFicFare in calibre and you copy and paste the series url from ao3, you can make an anthology epub (which is all of the fics in one epub: an anthology).

But I could not found any such options in the CLI.

**Comment by JimmXinu** [comment]
FFF CLI doesn't have the anthology feature.  I've generally figured anyone using scripts will roll their own to get exactly what they want.

You can put the series into the output file name easily enough:

```
fanficfare --non-interactive --download-list=https://archiveofourown.org/series/2182653 -o output_filename='${series} - ${title}-${siteabbrev}_${storyId}${formatext}'
```
(You'll need " instead of ' for windows.)

**Comment by NightMachinary** [comment]
Thanks, that works! 

I do think having the anthology feature is helpful, as rolling our own is a bit of trouble for not much gain (the primary use case is putting together a series).
