### ISSUE TITLE
Update Cover Image Action?

### ISSUE THREAD

**Issue by foreal26** [JimmXinu/FanFicFare#821]
I looked through the wiki but didn't find an example.

Is it possible to run Calibre + Fanficfare in such a way that it checks for a cover image? Without force updating the entire epubs. For some reason when I'd used WebtoEpub with ffnet, it didn't keep the cover images. I switched to nsapa proxy and get them now  I'm hoping to backfill all the past fics.

**Comment by JimmXinu** [comment]
No, FFF doesn't have such an option--wanting covers for epubs you downloaded with a different tool would be awfully niche.  Most users will have downloaded the story in FFF to begin with.

**Comment by JimmXinu** [comment]
Then you can use 'Update EPUB Always'; it won't replace your existing chapters.  A separate mode for just cover update wouldn't save any network requests.

I would suggest that you test first with only a few books to make sure your cover settings are all as you want them.

Also, be aware that doing lots of updates through a proxy will still cause issues with cloudflare.
