### ISSUE TITLE
author's notes background too light

### ISSUE THREAD

**Issue by Dragonexus** [JimmXinu/FanFicFare#822]
any way to darken the bg for the author's notes section of stories downloaded from fimfiction? i read using dark mode, so the text being white barely contrasts at all with the background.

**Comment by JimmXinu** [comment]
To get a 'dark mode', I assume you already have custom CSS set.

Looking at the code, author notes on fimf are in `<div class='authors-note'>`.  Add something like this to your `output_css` setting:
```
 .authors-note { background-color: black; }
```
...Or whatever your background color is.
