### ISSUE TITLE
Error 403 fanfiction.net

### ISSUE THREAD

**Issue by seba11998** [JimmXinu/FanFicFare#824]
FanFicFare log:
| Status | Title   | Author  | Comment                                                                                                              | URL                                            |
|--------|---------|---------|----------------------------------------------------------------------------------------------------------------------|------------------------------------------------|
| Error  | Unknown | Unknown | Unknown HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/13622324/1/Reborn'(403) | https://www.fanfiction.net/s/13622324/1/Reborn |

**Comment by JimmXinu** [comment]
Most of us have been seeing that for over a year.  See #703 

There are a couple features that can be used to work around it; there are wiki pages for them:
- [BrowserCacheFeature](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature)
- [ProxyFeatures](https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures)
