### ISSUE TITLE
Webnovel - Chapter contents are not being downloaded

### ISSUE THREAD

**Issue by CarelessLazy** [JimmXinu/FanFicFare#825]
As it says in the title FFF stopped downloading contents of the chapters from webnovel. Everything else works perfectly, it gets synopsis/summary, tags, image, update date and so on and creates an epub but when I open the epub what I see is like below:

Usual info about the fic

Chapter 1 Chapter title

[No actual chapter text]

Chapter 2 Chapter title

[No actual chapter text]

Chapter 3 Chapter title

[No actual chapter text]

for however many chapters the fanfic has.
Tried it with few fics randomly some I was already following some new, happened with all of them.

**Comment by JimmXinu** [comment]
The site has started putting the chapter text in javascript data objects instead of HTML.

It may or may not be feasible to parse it out in FFF.  I'm looking into it.

**Comment by JimmXinu** [comment]
I've pushed a first cut fix (ff0a9a73354634343e2666bd504319e1c50fc8f7) and put [test versions in the usual places](https://github.com/JimmXinu/FanFicFare#test-versions).

I've only tested with a few chapters of a few stories. I won't be surprised if there are further issues.

**Comment by CodeyAce95** [comment]
webnovel still not working

**Comment by JimmXinu** [comment]
It appears to be working for me in the test version.  Did you follow the link and install the test version with:

> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

Or from the mobileread forum if you use the plugin.  You didn't mention which you use.

If you are using the test version, please provide a story URL that exhibits the problem--It's working with the ones I'm picking off the front page.

**Comment by CarelessLazy** [comment]
Yep. It's working now. (v4.11.9)
Thank you very much.
Issue is solved so I'm closing it.

**Comment by JimmXinu** [comment]
Reason for reopening issue?

**Comment by JimmXinu** [comment]
I thought there might be more escapes to be found.

Reopening is fine, I just thought you'd mis-clicked or something when there wasn't a new comment.

Test versions up.

**Comment by CodeyAce95** [comment]
i am using the zip file from mobile read on the windows calibre app but maybe i got thr wrong file

**Comment by CodeyAce95** [comment]
this is one thats not working
 https://www.webnovel.com/book/rebirth-of-the-mightiest-disciple-(reboot)_13520985605105905

**Comment by CodeyAce95** [comment]
it works but i have to redownload the story

**Comment by JimmXinu** [comment]
I was able to download the story mentioned [above](https://github.com/JimmXinu/FanFicFare/issues/825#issuecomment-1098450221) without any apparent problems.

If you have specific problems you can point to, you can reopen this issue.
