### ISSUE TITLE
Plugin crashes when trying to download books

### ISSUE THREAD

**Issue by burny2** [JimmXinu/FanFicFare#827]
After updating the Calibre plugin to version 4.11.0 (from some 3.xx version) and trying to download a book, the plugin crashes. Details see attached Calibre debug log. I tracked down the test version 4.1.9 as the first version behaving like this. Previous versions are working fine.

It seems, that the plugin is forced to use the `bs4` module in folder `included_dependencies` since that version; previous versions are using the system installed module instead.

OS: Linux Mint 20.
[calibre-FanFicFare-4.11.0-crash.log](https://github.com/JimmXinu/FanFicFare/files/8501778/calibre-FanFicFare-4.11.0-crash.log)

**Comment by JimmXinu** [comment]
You are running an OS bundled version of Calibre **4**.99.4, which is a radically out-of-date beta.  The current Calibre release is **5**.40.  As a general rule, I only support FFF plugin on the official Calibre releases.

I think you are seeing the same problem as previous issue #685.  You are on an OS that is reporting itself in log as Ubuntu, with Calibre 4.99.4, the same Calibre version as the issue before.  See [this comment](https://github.com/JimmXinu/FanFicFare/issues/685#issuecomment-913692657) in particular.

Short answer: Use the [official Calibre releases](https://calibre-ebook.com/download), not the OS bundled version.

If you are not able to use the official version for some reason, [this comment](https://github.com/JimmXinu/FanFicFare/issues/685#issuecomment-913659360) from the previous issue may help you as a work around.

**Comment by burny2** [comment]
Sorry, i was not aware of that. I should have searched further back through the tickets. Thanks for the hints!
