### ISSUE TITLE
Erroneous Story Does Not Exist When Saving SufficientVelocity Stories Which Require Sign In

### ISSUE THREAD

**Issue by Chirishman** [JimmXinu/FanFicFare#834]
Several stories on Sufficient Velocity which require a sign-in to view are reporting as "Story does not exist" when checking for updates.

I think this is a change on SV's part because when viewed while not signed in they now say `The requested thread could not be found.` instead of prompting for a sign-in to view the thread.

Here are two example threads:
https://forums.sufficientvelocity.com/threads/smash-gal-and-esvanir.92704/
https://forums.sufficientvelocity.com/threads/my-absolutely-incredible-astonishing-super-amazing-life-as-someone-in-another-world-is-absolutely-and-unquestionably-beyond-reproach-it-sucks.68737/

**Comment by JimmXinu** [comment]
That's not new behavior.  FFF can't differentiate between 'thread does not exist' and 'you have to be logged in' because the site doesn't show us any difference.  You have to use `always_login:true` 

Something like:
```
[forums.sufficientvelocity.com]
username:YourName
password:yourpassword

[https://forums.sufficientvelocity.com/threads/smash-gal-and-esvanir.92704/]
# or just under [forums.sufficientvelocity.com]
## XenForo sites require login for some stories, but don't report that
## to FFF.  To download those, set your username, password and set
always_login:true
```

**Comment by Chirishman** [comment]
Honestly I understand the current state of it, but that doesn't explain for me why it WAS working six months or so ago when I first downloaded these stories.

Do you know when they changed this behavior? I couldn't find any closed issues about this when I looked like I would expect to if this was a relatively recent change.

**Comment by JimmXinu** [comment]
My guess would be that the story changed from open to logged in only.
