### ISSUE TITLE
SOL: Structural changes to log in system

### ISSUE THREAD

**Issue by T-Man2000** [JimmXinu/FanFicFare#835]
SOL has made changes to the log in system yesterday. Currently FFF does not work with SOL when trying to log in via FFF.

> Today I implemented some changes to the log in system. The change is huge on the technical level (split the functionality to multiple separate scripts), but the basics are the same with only minimal visual changes.

**Comment by tbaetzler** [comment]
That problem was also reported by somebody else on mobileread.com.

**Comment by JimmXinu** [comment]
Fixed in e9d206bf9b2aa3d393ed89f03cde2fac5ecb2256 - Change cherry-picked from @mvlcek's #836

Test versions up in the usual places.
