### ISSUE TITLE
SufficientVelocity(/XenForo) download by chapter URL doesn't download whole story

### ISSUE THREAD

**Issue by ND-451** [JimmXinu/FanFicFare#837]
https://forums.sufficientvelocity.com 
this site when used with FanFicFare only download direct link to a chapter not the entire thing
am i missing something orit supposed to do that

**Comment by kido5217** [comment]
If story/thread link ends with direction to a specific chapter/post, fff will download only that chapter/post. For example:
```https://forums.sufficientvelocity.com/threads/old-conductor-possessed-anew-fallout-si.88786/#post-19860922```
To download full story you need to specify link to thread or to post with index (for old stories). For example:
```https://forums.sufficientvelocity.com/threads/old-conductor-possessed-anew-fallout-si.88786/```

**Comment by ND-451** [comment]
Ohh thanks 
While on the topics of sites.
Fictionmania.tv doesn't work

**Comment by JimmXinu** [comment]
As @kido5217 explained, that's functioning as designed.  Once upon a time, it was common for story threads to have an index post that wasn't always the first post.

fictionmania.tv is working for me.  Without a story URL and error message, I can't help you.
