### ISSUE TITLE
Lost original files

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#838]
I'm not sure if this is an issue or what but I recently lost my computer and now that I can get a new one I was wondering if I uploaded the fanfiction that's saved on my tablet onto the new Calibre does it transfer the url so I can just update the files or will I have to hunt the links down?

**Comment by JimmXinu** [comment]
This is not an issue with FFF and would be better addressed to the [discussion thread](https://www.mobileread.com/forums/showthread.php?t=259221) for the Calibre plugin.

If you have the epub files FFF generated on your tablet, you can copy them to Calibre, check the 'Search inside ebooks for Story URL' option in FFF config and use FFF's update in 'Update Calibre Metadata from Web Site' mode to get all the metadata again.  The usual warnings about [mass updates](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-shouldnt-i-just-select-my-entire-library-and-use-fanficfare-plugin-to-check-for-updates) and all the ffnet difficulties still  apply.
