### ISSUE TITLE
www.mediaminer.org: URL Parsing Issues

### ISSUE THREAD

**Issue by albyofdoom** [JimmXinu/FanFicFare#845]
## 1st Parsing Issue:
I have FFF set up to check a mailbox for story update notifications, and this works for most sites. For MediaMiner though, the url format they use doesn't parse correctly. It appears that this is because the notifications link directly to the new chapter, not the overall story.

#### Example:
Story url: `https://www.mediaminer.org/fanfic/s/original-stories-fan-fiction/pretty-lady/161297`
Email url: `https://www.mediaminer.org/fanfic/view_ch.php/161297/626395?utm_source=add_chapter&utm_medium=email`

As you can see, the story ID is in the link, so it could theoretically be parsed out. 

## 2nd Issue:
When accessing stories from the author pages, the format used does not get parsed as valid URL by FFF.

#### Example:
Author url: `https://www.mediaminer.org/user_info.php/155950`
Story url: `https://www.mediaminer.org/fanfic/s/harry-potter-series-fan-fiction/-because-she-told-me-to-/145608`
Auther Page Story url: `https://www.mediaminer.org/fanfic/view_st.php?id=145608&submit=View`

It looks like this resembles the old format listed in [adapter_mediaminerorg.py ](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/adapters/adapter_mediaminerorg.py) (line 83), but it is slightly different.

**Comment by JimmXinu** [comment]
Should work now.  Test versions in the usual places.
