### ISSUE TITLE
MCStories.com: Multiple Authors/Anthologies

### ISSUE THREAD

**Issue by albyofdoom** [JimmXinu/FanFicFare#847]
It's uncommon, but some of the stories on this site have multiple authors that don't currently get captured by FFF. 

Examples:
https://mcstories.com/TalesOfBellesBeast/index.html
https://mcstories.com/ViralAnthology/index.html
https://mcstories.com/HotterThanHell/index.html

**Comment by JimmXinu** [comment]
Test versions posted

**Comment by albyofdoom** [comment]
> Test versions posted

Confirmed working with all stories in my library. Thank you!
