### ISSUE TITLE
Crash whilst running in Wayland Calibre

### ISSUE THREAD

**Issue by Victor239** [JimmXinu/FanFicFare#855]
I recently updated to using Wayland and I found that this plugin causes Calibre to crash. When I force Calibre to open in old X11 compatibility mode it doesn't cause a crash however. X11 is on maintenance life support and all Linux distributions are moving to Wayland so this workaround is not a long-term solution unfortunately.

**Comment by JimmXinu** [comment]
First, make sure you aren't using an OS bundled version of Calibre.

I only support FFF on the [official Calibre release](https://calibre-ebook.com/download), not bundled versions as included in various linux distros.  There are just too many different linux variants out there, many of which bundle out dated or broken versions of Calibre.  Search this repo's issues for linux to learn more.

If you have specific error messages, I will investigate. But I can't build a new linux computer to test this.

**Comment by Victor239** [comment]
I'm using the [Flatpak version](https://flathub.org/apps/details/com.calibre_ebook.calibre), since it stays up-to-date with non-Flatpak releases, runs on all distros and allows for automatic updates. 

I can check for error messages, just let me know how I can obtain them.

**Comment by JimmXinu** [comment]
Sorry, that's still not the official Calibre release.  

I don't know how to get error messages on your system for a low level crash.  

Calibre itself can be run in debug mode started from CLI with `calibre-debug -g` or restarted from inside Calibre under Preferences dropdown.

**Comment by JimmXinu** [comment]
Non-supported version.
