### ISSUE TITLE
error download fanfiction.net cache

### ISSUE THREAD

**Issue by tom221-e** [JimmXinu/FanFicFare#856]
Fanficfare gives this error when trying to cache the fics.
mistake:

HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/13969615/1/A-New-Archon'(403)
https://www.fanfiction.net/s/13969615/1/A-New-Archon

**Comment by JimmXinu** [comment]
That indicates that FFF didn't find the page in the cache.  Could be:
- Not configured correctly
- Not cached (ie, you didn't view it recently, used a different browser, etc)
- Problem with the cache itself

For the first two, see the [BrowserCache wiki page](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature).

In the last case, all you can do is clear the cache.  It may need to be manually cleared; see #849.  Back up first, however, in case something goes wrong.  I take no responsibility for broken browsers.

I'll leave this open for the moment, but I doubt it's an issue with FFF itself.

**Comment by JimmXinu** [comment]
FYI, I've added an FAQ for this:

[I've followed all the instructions in Browser Cache Feature and it isn't working / I'm getting errors--help?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#ive-followed-all-the-instructions-in-browser-cache-feature-and-it-isnt-working--im-getting-errors--help)
