### ISSUE TITLE
Tgstorytime.com and fictionamania.tv wont work even though its the same format on the supported site list

### ISSUE THREAD

**Issue by ND-451** [JimmXinu/FanFicFare#861]

**Comment by JimmXinu** [comment]
Both worked for me doing a simple test.

Please provide error messages and story URLs that exhibit the problem.

**Comment by ND-451** [comment]
<img width="836" alt="Screen Shot 2022-06-28 at 9 48 45 AM" src="https://user-images.githubusercontent.com/60086622/176236047-b2230116-ae7c-4506-9b0a-5ad577c41dbd.png">
my machine says otherwise

**Comment by JimmXinu** [comment]
That's a zsh error telling you it's trying to use `?` as a wildcard and not finding any matching files.  Put single quotes around the story URL.

Google zsh wildcards AKA globbing for full details.
