### ISSUE TITLE
storiesonline load more text on single chapter stories.

### ISSUE THREAD

**Issue by cookie-crumb** [JimmXinu/FanFicFare#867]
Code works fine for multi-chapters stories.
However, single chapter stories can be left with a load more text message.
Solution: in adapter_storiesonlinenet.py copy line 499 to 509 after line 194 or 204 or refactor to avoid duplicate code.
Sample url:
https://scifistories.com/s/653/dearest

**Comment by JimmXinu** [comment]
@mvlcek, in April 2022 you contributed #829 to address `There is more of this text...` for storiesonline.net(/finestories.com/scifistories.com).

It appears that it doesn't work with single chapter stories now, at least on scifistories.com.

Do you have the time and interest to look into this?

FYI, while investigating this, I found that adapter_scifistoriescom wasn't working at all for me and needed to more resemble storiesonline.net than finestories.com (99049da5c69325ec0fe4a1073f136bebeb9f4e86).  I also turned on basic caching for finestories.com/scifistories.com (99049da5c69325ec0fe4a1073f136bebeb9f4e86).  While committed, these changes haven't been released.
