### ISSUE TITLE
Can't get colored text or fonts from royal road

### ISSUE THREAD

**Issue by bcikwuagwu** [JimmXinu/FanFicFare#868]
Hello,

I have been trying to update the style for the story memories of the fall (https://www.royalroad.com/fiction/36051/memories-of-the-fall) , but I can't get it to work. I added the  add_to_keep_html_attrs:,style, but that did not seem to work . I then tried to update the style sheet thru calibre editor, but all the formatting is under class=calibre

**Comment by JimmXinu** [comment]
This works:
```
[royalroad.com]
add_to_keep_html_attrs:,style
```
As does this:
```
[https://www.royalroad.com/fiction/36051]
add_to_keep_html_attrs:,style
```
But `[https://www.royalroad.com/fiction/36051/memories-of-the-fall]` doesn't work in personal.ini right now.  I'll add that in the next test version (2482416ea5e7fee6087e114c837a60b8a8b0fd44).

If that isn't your problem, I'll need more information, like what exactly isn't showing up as you expect it to.
