### ISSUE TITLE
Error with Storiesonline - 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by avggeek** [JimmXinu/FanFicFare#871]
Hi,

I'm seeing an issue with downloading stories from storiesonline.net. Getting an error in the job log:

`'NoneType' object has no attribute 'get_text'`

This is with FFF v4.14.3 on calibre 6.2.1

**Comment by JimmXinu** [comment]
I'm not seeing it.  Please provide some story URLs that exhibit the problem and a debug log.

**Comment by avggeek** [comment]
Apologies - it turns out the problem was that my premium membership had expired and so the site was throwing up a warning page after I logged in. Once I fixed that, the problem went away.
