### ISSUE TITLE
Fanficfare can't handle '[' in series title on ao3

### ISSUE THREAD

**Issue by maxsone** [JimmXinu/FanFicFare#875]
AO3 series titles that contain '['  breaks download with ValueError when it tries to find series_index.

To reproduce, try downloading:

 https://archiveofourown.org/works/33701344
or 
 https://archiveofourown.org/works/15727008

I don't understand what 

> if '[' in series:

 at ~436 in writer_epub.py is doing, but perhaps it should check if the content is_numeric?

**Comment by JimmXinu** [comment]
That's only an issue when `calibre_series_meta` is set `true`.

Fixed by changing `index()` to `rindex()` 7558c998df595111ac04e1eb8188567aa2e6910e

CLI test version uploaded.
