### ISSUE TITLE
Issue with error 403 with long stories on QQ

### ISSUE THREAD

**Issue by jeancinq** [JimmXinu/FanFicFare#877]
With fanficfare 4.15.4 on Calibre 6.3.
I have an issue with downloads on QQ. When I download a long story, I get error 403 for this story and all others following in the download queue. In particular, it happens with : https://forum.questionablequesting.com/threads/shadowdices-ideas-and-snippets.7506/
This is a problem I tried to get around by downloading small chunks of the story using slices ("[1-100]"), but after downloading the first two hundred chapter this way, I was unable to download the remainder, either with other slices (doing [201-300] fails because Fanficfare detects the story with the 200 first chapters, and decides that this story is shorter, so it can't download). Or by updating the story file with the first chapters, in this case, I get a error 403.

Here is a an example of a debug log for an attempt at updating the story:
[tmp2wih0ook.txt](https://github.com/JimmXinu/FanFicFare/files/9472222/tmp2wih0ook.txt)

Thanks in advance for any help with this situation.

**Comment by JimmXinu** [comment]
You're bumping into throttling from QQ.  There are a few things you can try, but there isn't anything FFF can do.

1. You might turn up the `slow_down_sleep_time` setting.  Default for QQ (& all XF sites) is 6 secs.
2. To add more 'slices' to the existing story, do [1-100], then do [1-200], later [1-300] etc to add to it.
3. Split into separate books by using 'Add New', first with [1-100], then [101-200] to make 2 books.
