### ISSUE TITLE
browser_cache_age_limit

### ISSUE THREAD

**Issue by nascalsn** [JimmXinu/FanFicFare#879]
Erro: ```HTTP Error in FFF 'Page not found or expired in Browser Cache (see FFF setting browser_cache_age_limit)'(428) URL:'https://www.fanfiction.net/s/14129026/1/Chuck-vs-The-Blacklist-not-a-crosover'```

The error occurs with any link that I have tested from fanfiction.net, even the parameter `browser_cache_age_limit` is set to `-1` having been tested with the cache of Microsoft Edge browsers (Version 105.0.1343.27), Firefox (104.0.1) and Google Chrome (Version 105.0.5195.102).

**Comment by JimmXinu** [comment]
Works fine for me with Firefox 103.0.2.  Updated to 104.0.1, still working fine.

If you're seeing it across multiple browsers and with all story URLs, I suspect you have `browser_cache_path` misconfigured (it's different for each browser), or you are not loading all the story pages correctly in the browser before trying FFF.

I don't think it applies here, but there's an FAQ: [I've followed all the instructions in Browser Cache Feature and it isn't working / I'm getting errors--help?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#ive-followed-all-the-instructions-in-browser-cache-feature-and-it-isnt-working--im-getting-errors--help)

**Comment by nascalsn** [comment]
I tested alternating with the paths below for each browser:
```
browser_cache_path: C:\Users\nasca\AppData\Local\Microsoft\Edge\User Data\Default\Cache\Cache_Data
browser_cache_path: C:\Users\nasca\AppData\Local\Google\Chrome\User Data\Default\Cache\Cache_Data
browser_cache_path: C:\Users\nasca\AppData\Local\Mozilla\Firefox\Profiles\0ogkdy09.nasca-1652934141748\cache2
```
The strange thing is that until a week ago it works without problems.
I've also tried the route of clearing the browser cache as suggested in the FAQ and still not getting success.

**Comment by nascalsn** [comment]
Using NirSoft MZCacheView to check the firefox (v104.0.1) cache on windows 11 (build 22000.918) I noticed that the pages are not being cached. Performing the same test with the Basilisk browser it saves the pages in the cache, allowing the FFF to extract the data from the cache.

**Comment by JimmXinu** [comment]
It's at least possible that the site is sending the pages set to no-cache.  

I know that I have occasionally while doing web development turned off caching on my browser and forgotten to turn it back on.  Seems unlikely you'd do that in three different browsers, though.

Regardless, I don't think there's anything FFF can do about it...

**Comment by KHempel** [comment]
So while I haven't seen this with FFnet links, I've seen it on some Ao3 anthologies and I've found that they're all older anthologies that I originally downloaded before Ao3 switched from http to https - all I have to do to fix the issue is to update the url from http to https in the metadata (it's saved in the entry for id).  While this may not be useful for the original issue with the ffnet urls (assuming that was for new downloads and not updating existing ones) but this might help someone else who stumbles across this issue down the road as the error I was receiving was identical even if the situations weren't.
