### ISSUE TITLE
Latins diacritics on Wattpad

### ISSUE THREAD

**Issue by AhsokaWho** [JimmXinu/FanFicFare#880]
Hello,
First of all, I would like to say that I am just a 15 years old Spanish kid, so I will probably have some grammatical mistakes.

I have been using FanFicFare to download stories from Wattpad, but I have a little problem with accents. I do not have troubles when it comes to English fanfics, but as mostly they are Spanish ones, I have got to use a tool to search and replace characters.

In any case, it would be great if you could fix it. I would do it by myself but a just know a bit of c++ and almost nothing about python, although I belive I have found somewhere that says that you are using an API from other GitHub project. I will add a list with the characters I have been having troubles and how they are downloaded:

Ã - í
Ãº - ú
Ã© - é
Ã¡ - á
Ã³ - ó
Ã± - ñ
Ã¼ - ü 
Â¿ - ¿

I have not found any other problem, but as I am not French or from some other country, I do not have more weird characters.

I thank you for making this plug in. It is amazing and it allows me to reed without needing to use the phone or the laptop (at places such as the school, where they are not allowed). I hope you can fix this.

**Comment by JimmXinu** [comment]
It's probably an issue with encoding.  I need a few story URLs that exhibit the problem before I can help.

**Comment by AhsokaWho** [comment]
[https://www.wattpad.com/story/250073725-%F0%9D%90%85%F0%9D%90%A8%F0%9D%90%AB-%F0%9D%90%84%F0%9D%90%AD%F0%9D%90%9E%F0%9D%90%AB%F0%9D%90%A7%F0%9D%90%A2%F0%9D%90%AD%F0%9D%90%B2-%F0%9D%97%B1%F0%9D%97%BF%F0%9D%97%AE%F0%9D%97%B0%F0%9D%97%BC-%F0%9D%97%BA%F0%9D%97%AE%F0%9D%97%B9%F0%9D%97%B3%F0%9D%97%BC%F0%9D%98%86](url)

This is the link to the last story I have downloaded. I do not have troubles with all the stories, only a few. I will send a few more tomorrow. Thank you.

**Comment by JimmXinu** [comment]
I'm not seeing any problems with diacritics in that story.  I downloaded to epub in both FFF CLI and calibre plugin.

If it's only some stories, that makes it even more likely to be an encoding issue--typically the author uploading a different encoding than the site usually uses.

If you *are* seeing problems with that particular story, perhaps it's the output format?  Are you outputting to epub or something else?

**Comment by AhsokaWho** [comment]
I firstly tried to download it as mobi, as it is what I need for my kindle paperwhite, but I have now tried to download it as epub. It seems to work now.

This is how it seemed to be:
![image](https://user-images.githubusercontent.com/84036833/188880886-18b4ea66-ddd3-420b-a587-d3826948e098.png)

Thanks for everything, I will from now on download the stories on epub format and I will transform them afterwards.

**Comment by JimmXinu** [comment]
FanFicFare's mobi output is poor and unlikely to ever improve.  Amazon has long since moved on to newer formats and FFF story update--one of FFF's key feature, IMO, only works with epub.

Here's a related [FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-doesnt-the-mobi-output-show-chapters-markers-on-the-progress-bar-in-kindle-or-include-images).
