### ISSUE TITLE
Cannot download from adult-fanfiction.org

### ISSUE THREAD

**Issue by aaronmelzak** [JimmXinu/FanFicFare#886]
Trying to download from adult-fanfiction.org you get an error with the attribute 'findAll':

 fanficfare -d "https://hp.adult-fanfiction.org/story.php?no=600100310"
FFF: DEBUG: 2022-09-30 03:21:23,437: cli.py(230):     OS Version:Linux-5.15.0-1017-gcp-x86_64-with-glibc2.29
FFF: DEBUG: 2022-09-30 03:21:23,437: cli.py(231): Python Version:3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
FFF: DEBUG: 2022-09-30 03:21:23,438: cli.py(232):    FFF Version:4.16.0
FFF: DEBUG: 2022-09-30 03:21:23,465: configurable.py(1052): use_browser_cache:
FFF: DEBUG: 2022-09-30 03:21:23,466: configurable.py(1066): use_basic_cache:False
FFF: DEBUG: 2022-09-30 03:21:23,479: adapter_adultfanfictionorg.py(198): URL: https://hp.adult-fanfiction.org/story.php?no=600100310
FFF: DEBUG: 2022-09-30 03:21:23,480: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://hp.adult-fanfiction.org/story.php?no=600100310
FFF: DEBUG: 2022-09-30 03:21:23,777: fetcher.py(492): response code:200
FFF: DEBUG: 2022-09-30 03:21:23,778: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2022-09-30 03:21:24,008: adapter_adultfanfictionorg.py(252): Getting the author page: https://members.adult-fanfiction.org/profile.php?no=1297005865&view=story&zone=hp&page=1
FFF: DEBUG: 2022-09-30 03:21:24,009: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://members.adult-fanfiction.org/profile.php?no=1297005865&view=story&zone=hp&page=1
FFF: DEBUG: 2022-09-30 03:21:24,532: fetcher.py(492): response code:200
FFF: DEBUG: 2022-09-30 03:21:24,533: requestable.py(50): Encoding:utf8
Traceback (most recent call last):
  File "/home/aaronmelzak/.local/bin/fanficfare", line 8, in <module>
    sys.exit(main())
  File "/home/aaronmelzak/.local/lib/python3.8/site-packages/fanficfare/cli.py", line 344, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/home/aaronmelzak/.local/lib/python3.8/site-packages/fanficfare/cli.py", line 320, in dispatch
    do_download(url,
  File "/home/aaronmelzak/.local/lib/python3.8/site-packages/fanficfare/cli.py", line 435, in do_download
    adapter.getStoryMetadataOnly()
  File "/home/aaronmelzak/.local/lib/python3.8/site-packages/fanficfare/adapters/base_adapter.py", line 320, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/home/aaronmelzak/.local/lib/python3.8/site-packages/fanficfare/adapters/adapter_adultfanfictionorg.py", line 262, in doExtractChapterUrlsAndMetadata
    pages=asoup.find('div',{'class' : 'pagination'}).findAll('li')[-1].find('a')
AttributeError: 'NoneType' object has no attribute 'findAll'

**Comment by JimmXinu** [comment]
Fixed in a7ced3d78a1c9db21742bc3f096a96a2886cfd1f.  Test versions are up in the [usual places](https://github.com/JimmXinu/FanFicFare/#test-versions).

**Comment by aaronmelzak** [comment]
Thanks for the quick fix!
