### ISSUE TITLE
Please add www.vansfiction.net

### ISSUE THREAD

**Issue by DartTrapdoor** [JimmXinu/FanFicFare#888]
Story URL examples: 
http://www.vansfiction.net/loft-1.htm
http://www.vansfiction.net/tca10.html
http://www.vansfiction.net/isla-epilogue.html

Thank you for your excellent work.

**Comment by JimmXinu** [comment]
First, see FAQ: [Please add site XYZ to FanFicFare?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#please-add-site-xyz-to-fanficfare)

Second, this site is a poor fit for FFF's paradigm.  There's apparently only one chapter index page for all stories; FFF depends on each story having a chapter list available.

Third, it's a very small site, < 70 stories by only one author spread over more than 25 years.  

I suggest searching for generic tools for making ebooks from web pages.
