### ISSUE TITLE
[Feature Request] Browser Cache Support for fastnovels.net

### ISSUE THREAD

**Issue by albyofdoom** [JimmXinu/FanFicFare#890]
FFF has become just about unusable with fastnovels.net due to their heavy cloudflare usage. Nothing that FFF can solve of course, but as using browser cache for fanfiction.net works so well for bypassing that block, it would be nice to be able to use it for fastnovels as well.

**Comment by JimmXinu** [comment]
I just looked into whether this was possible with the Browser Cache refactor(#905).  

Unfortunately, fastnovels.net needs to do a `POST` request to get the chapter list and Browser Cache can't do `POST`.

**Comment by JimmXinu** [comment]
FYI, I made some fixes for fastnovels.net site changes(22ea1d4a15d730d0009b343a2403209cb06052cf).  Tested using `use_flaresolverr_proxy`.  See [proxy page](https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures).

Test versions posted.

**Comment by albyofdoom** [comment]
@JimmXinu `use_flaresolverr_proxy` Worked perfectly using test version. Thank you!
