### ISSUE TITLE
403 Client Error

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#891]
I keep getting this error since updating two days ago. What am I doing wrong?
Status
Title
Author
Comment
URL
Error
A Shift In GearRound Robin
Introspective Tinkerer
HTTP Error in FFF '403 Client Error: Forbidden for url: https://forums.spacebattles.com/login'(403)
https://forums.spacebattles.com/threads/a-shift-in-gear-battletech-gundam-round-robin.953146/

Status
Title
Author
Comment
URL
Error
Souls Weighed Down
Spear Carrier
HTTP Error in FFF '403 Client Error: Forbidden for url: https://forums.spacebattles.com/login'(403)
https://forums.spacebattles.com/threads/souls-weighed-down-nbsg-gundam.1004072/

**Comment by JimmXinu** [comment]
I'm not seeing it.  However, it did take +40 minutes for the first on alone; ~480 chapters *and* ~480 images.

Based on the error (`403 Client Error`), the number of chapters and images, and it happening for more than one story, I would speculate that you are getting blocked.  Probably for 'excessive' downloads.  

I don't think there's anything FFF can do about it.  You can wait and (probably) get unblocked, or try to change your IP address.

Here's a couple similar previous issues: #877 #802
