### ISSUE TITLE
Frozen while downloading

### ISSUE THREAD

**Issue by flowingblaze** [JimmXinu/FanFicFare#892]
It has been around 3 hours and 38 minutes and Fanficfare appears to be frozen while importing fanfics, only at 45%. Its been like this for a few hours. It might just be the amount I decided to download but the amount of fics isn't that many in my opinion. 
![image](https://user-images.githubusercontent.com/107226733/199336792-15c39cd1-6845-4f3c-b7ae-81dcfc9456f5.png)

**Comment by flowingblaze** [comment]
update: it appears to be now downloading things again after a few hours, I'm assuming it paused to not overload ao3's servers
![image](https://user-images.githubusercontent.com/107226733/199351404-f6b0a884-88df-4806-9063-a7e2c3a078f0.png)

**Comment by JimmXinu** [comment]
See the FAQ: [Why shouldn't I just select my entire library and use FanFicFare plugin to check for updates?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-shouldnt-i-just-select-my-entire-library-and-use-fanficfare-plugin-to-check-for-updates)

Updating or downloading nearly 2000 fics at once is well past what I would consider a reasonable number.  I would not be in the least surprised if AO3's servers noticed and started blocking you.
