### ISSUE TITLE
"BAD books" error

### ISSUE THREAD

**Issue by serenova** [JimmXinu/FanFicFare#897]
Hey there, I know that there's a forum for the Calibre-Plugin version but I couldn't find the answert there (other than a single note to this error from a version update from 2012) so I figured I'd pop in here and ask.

I'm getting a "BAD books" message when trying to update stories downloaded from AO3.

Screenshot:
![image](https://user-images.githubusercontent.com/96950336/202791349-6e129773-272e-456a-8161-cadb2854020a.png)

I'm unsure how to grab the logs on linux to see what's going on (I'm running Kubuntu 22.10), but if it's something I've configured wrong with, say, my AO3 account, I'd very much appreciate someone pointing me in the right direction!

**Comment by JimmXinu** [comment]
Open Calibre's Jobs list (click 'Jobs: 0' in lower right corner of main window), double click "Download X FanFiction Books(s)" job to open the job log.

You can also run Calibre in debug mode (under Calibre Preferences dropdown) and look at the debug log.

**Comment by serenova** [comment]
I ran 1 story through the plugin with Calibre in debug more and got the following:

`
Status
Title
Author
Comment
URL
Skipped
All Vows
flowerfan
Already contains 1 chapters.
https://archiveofourown.org/works/26697157
`

This is one that I know doesn't need an update, but it gave me the same "BAD books" error message.

This is the log from starting Calibre in debug mode (I did remove some references to my phone being attached to my computer as it had identifying information, but other than that this log is a copy/paste):

calibreUsing calibre Qt style: True
FFF: DEBUG: 2022-11-19 16:23:42,075: calibre_plugins.fanficfare_plugin.fff_plugin(216): Plugin FanFicFare macmenuhack file_path:/home/serenova/.config/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 6.3  embedded-python: False
Linux-5.19.0-23-generic-x86_64-with-glibc2.36 Linux ('64bit', 'ELF')
('Linux', '5.19.0-23-generic', '#24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022')
Python 3.10.7
Interface language: None
Successfully initialized third party plugins: FanFicFare (4, 17, 0) && Library Codes (1, 0, 53)
calibre 6.3  embedded-python: False
Linux-5.19.0-23-generic-x86_64-with-glibc2.36 Linux ('64bit', 'ELF')
('Linux', '5.19.0-23-generic', '#24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022')
Python 3.10.7
Interface language: None
Successfully initialized third party plugins: FanFicFare (4, 17, 0) && Library Codes (1, 0, 53)
QPA platform: xcb
devicePixelRatio: 1.125
logicalDpi: 96.0 x 96.0
physicalDpi: 227.53333333333333 x 227.8878504672897
[0.00] Starting up...
[0.00] Showing splash screen...
[0.04] splash screen shown
[0.04] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
[1.22] main UI initialized...
[1.22] Hiding splash screen
Starting QuickView
<removing references to phone for personal information>
Device 0 (VID=04FFF: DEBUG: 2022-11-19 16:26:25,714: calibre_plugins.fanficfare_plugin.fff_plugin(1129): FanFicFare v4.17.0
FFF: INFO: 2022-11-19 16:26:25,820: calibre_plugins.fanficfare_plugin.prefs(215): Using default settings
FFF: DEBUG: 2022-11-19 16:26:25,835: configurable.py(1052): use_browser_cache:
FFF: DEBUG: 2022-11-19 16:26:25,836: configurable.py(1066): use_basic_cache:true
FFF: INFO: 2022-11-19 16:26:25,836: adapter_archiveofourownorg.py(163): url: https://archiveofourown.org/works/26697157/navigate?view_adult=true
FFF: INFO: 2022-11-19 16:26:25,836: adapter_archiveofourownorg.py(164): metaurl: https://archiveofourown.org/works/26697157?view_adult=true
FFF: DEBUG: 2022-11-19 16:26:25,837: fetcher.py(234): 
========== MISS (GET) BasicCache
https://archiveofourown.org/works/26697157/navigate?view_adult=true
FFF: DEBUG: 2022-11-19 16:26:25,837: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://archiveofourown.org/works/26697157/navigate?view_adult=true
FFF: DEBUG: 2022-11-19 16:26:26,036: fetcher.py(492): response code:200
FFF: DEBUG: 2022-11-19 16:26:26,037: fetcher.py(156): random sleep(2.50-7.50):2.55
FFF: DEBUG: 2022-11-19 16:26:28,586: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2022-11-19 16:26:28,586: fetcher.py(234): 
========== MISS (GET) BasicCache
https://archiveofourown.org/works/26697157?view_adult=true
FFF: DEBUG: 2022-11-19 16:26:28,587: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://archiveofourown.org/works/26697157?view_adult=true
FFF: DEBUG: 2022-11-19 16:26:28,857: fetcher.py(492): response code:200
FFF: DEBUG: 2022-11-19 16:26:28,858: fetcher.py(156): random sleep(2.50-7.50):3.46
FFF: DEBUG: 2022-11-19 16:26:32,318: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2022-11-19 16:26:32,319: fetcher.py(234): 
========== MISS (GET) BasicCache
https://archiveofourown.org/token_dispenser.json
FFF: DEBUG: 2022-11-19 16:26:32,319: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://archiveofourown.org/token_dispenser.json
FFF: DEBUG: 2022-11-19 16:26:32,458: fetcher.py(492): response code:200
FFF: DEBUG: 2022-11-19 16:26:32,458: fetcher.py(156): random sleep(2.50-7.50):7.14
FFF: DEBUG: 2022-11-19 16:26:39,602: requestable.py(50): Encoding:utf8
FFF: INFO: 2022-11-19 16:26:39,602: adapter_archiveofourownorg.py(140): Will now login to URL (https://archiveofourown.org/users/login) as (kaidaserenova@gmail.com)
FFF: DEBUG: 2022-11-19 16:26:39,602: fetcher.py(234): 
========== MISS (POST) BasicCache
https://archiveofourown.org/users/login
FFF: DEBUG: 2022-11-19 16:26:39,603: fetcher.py(479): 
---------- REQ (POST) RequestsFetcher
https://archiveofourown.org/users/login
FFF: DEBUG: 2022-11-19 16:26:41,448: fetcher.py(492): response code:200
FFF: DEBUG: 2022-11-19 16:26:41,449: fetcher.py(156): random sleep(2.50-7.50):4.33
FFF: DEBUG: 2022-11-19 16:26:45,782: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2022-11-19 16:26:45,782: fetcher.py(234): 
========== MISS (GET) BasicCache
https://archiveofourown.org/works/26697157/navigate?view_adult=true
FFF: DEBUG: 2022-11-19 16:26:45,783: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://archiveofourown.org/works/26697157/navigate?view_adult=true
FFF: DEBUG: 2022-11-19 16:26:45,988: fetcher.py(492): response code:200
FFF: DEBUG: 2022-11-19 16:26:45,989: fetcher.py(156): random sleep(2.50-7.50):3.27
FFF: DEBUG: 2022-11-19 16:26:49,258: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2022-11-19 16:26:49,259: fetcher.py(234): 
========== MISS (GET) BasicCache
https://archiveofourown.org/works/26697157?view_adult=true
FFF: DEBUG: 2022-11-19 16:26:49,259: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://archiveofourown.org/works/26697157?view_adult=true
FFF: DEBUG: 2022-11-19 16:26:49,578: fetcher.py(492): response code:200
FFF: DEBUG: 2022-11-19 16:26:49,578: fetcher.py(156): random sleep(2.50-7.50):5.77
FFF: DEBUG: 2022-11-19 16:26:55,356: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2022-11-19 16:26:55,649: adapter_archiveofourownorg.py(264): numChapters: (1)
FFF: DEBUG: 2022-11-19 16:26:55,796: calibre_plugins.fanficfare_plugin.fff_plugin(1447): update existing id:7493
/usr/lib/python3/dist-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
<removed reference to my phone as it contains personal information here>
calibre_plugins.fanficfare_plugin.fff_plugin(1892): set_marked_ids:{7493: 'fff_failed_0000'}
FFF: DEBUG: 2022-11-19 16:27:38,060: calibre_plugins.fanficfare_plugin.fff_plugin(1901): Finished Adding/Updating 0 books.
FFF: DEBUG: 2022-11-19 16:27:38,060: calibre_plugins.fanficfare_plugin.fff_plugin(1904): removed tdir
[11.16] splash screen hidden
[11.16] Started up in 11.16 seconds with 4322 books
Worker Launch took: 0.00 seconds
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
kf.sonnet.clients.hspell: HSpellDict::HSpellDict: Init failed

**Comment by JimmXinu** [comment]
FFF is functioning as designed.  Those messages are supposed to appear briefly in the Calibre status bar when you have FFF configured to save error messages for 'failed' downloads.  Which does technically include not updating for no new chapters.

I assume that being more intrusive is part of your OS / window manager.

I will consider if they should be removed.
