### ISSUE TITLE
Xenforo threadmarks-by-date has bad validation

### ISSUE THREAD

**Issue by WovenTales** [JimmXinu/FanFicFare#902]
While I really appreciate the separation of Xenforo apocrypha from the rest of the story, I think it would be nice to have most of the other categories intermixed.  The `order_threadmarks_by_date_categories` option seems like it's exactly the solution I'm looking for.  However, even the default (commented) value of `Threadmarks,Sidestory` pops up with "not a valid value" and while the dialog does allow me to "save anyway" the message repeats every time I edit the personal.ini and the minor annoyance is enough for me to not even leave it in long enough to see if the setting works despite the warning or not (I'm perfectly fine leaving all the categories separate as well, so I've not wanted to deal with the extra hassle).

**Comment by JimmXinu** [comment]
Sorry about that, the edit check code was wrong.  New [test version posted](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2)
