### ISSUE TITLE
Getting an error when fetching URLs from email

### ISSUE THREAD

**Issue by M3We** [JimmXinu/FanFicFare#904]
I have been using this feature for a while to update releant fics. But after updating to latest version, I recieved the following error:

> calibre, version 6.11.0
> ERROR: Unhandled exception: <b>TypeError</b>:QBoxLayout.addWidget(): argument 3 has unexpected type 'int'
> calibre 6.11  embedded-python: True
> macOS-12.4-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64')
> Python 3.10.1
> OSX: ('12.4', ('', '', ''), 'x86_64')
> Interface language: None
> Successfully initialized third party plugins: DeDRM (7, 2, 1) && Count Pages (1, 12, 0) && EpubMerge (2, 15, 0) && FanFicFare (4, 19, 0) && Manage Series (1, 5, 0) && Reading List (1, 14, 0)
> Traceback (most recent call last):
>   File "calibre_plugins.fanficfare_plugin.fff_plugin", line 556, in get_urls_from_imap_menu
>     d = EmailPassDialog(self.gui,prefs['imapuser'])
>   File "calibre_plugins.fanficfare_plugin.dialogs", line 1607, in __init__
>     horz.addWidget(self.ok_button,2,0)
> TypeError: QBoxLayout.addWidget(): argument 3 has unexpected type 'int'

**Comment by JimmXinu** [comment]
Fixed in the [current test version](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2). 56da4a285009aabf7c0fb719ff14989465adb597
