### ISSUE TITLE
[Feature Request] Set the "Date" or "Modified" field based on the time of the last fic update instead of time of retrieval

### ISSUE THREAD

**Issue by KridOCaign** [JimmXinu/FanFicFare#915]
Currently, the "Date" and "Modified" field both show when you retrieved the fic.
Would it be possible to use one of these to show when the last update to the fic was posted as of the time of retrieval?
I believe this would do a much better job of providing pertinent information to the user.

**Comment by JimmXinu** [comment]
I assume you're talking about in Calibre.  

Create a custom column of type 'Date', then in FFF's Config > Custom Columns tab, assign that column to be populated with 'Updated'.
