### ISSUE TITLE
Weird issue in AO3 Chapter

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#917]
I found a weird issue on this chapter:

> https://archiveofourown.org/works/5953125/chapters/112928932

It is chapter 53 so you can download it as `https://archiveofourown.org/works/5953125/chapters/112928932[53-]`
It looks like it is some kind of formating error on the text:

- The resulting epub is completely in italics
- On the website it looks normal
- _However_ when I look on the source code for the page (ctrl+U) it looks like every line in the text is _actually in italics_.
- So, it looks like there is some kind of weird formatting that, while the text is inside `<i></i>` it is not recognised as italics on AO3... some times, since the first sentence is in italics
- The only theory I have looking at the source code is that double italics (`<i><i></i></i>`) cancel eachother out (so triple italics like in the first sentence is like normal italics)

Similar kind of thing happens here `https://archiveofourown.org/works/43987488/chapters/112720393` (chapter 5) were halfway through after a `<em>` another` <em>` opens and everything afterwards is in italics (after `Booth clearly hated this particular part of the case.`)
In that one there is another `<em>` opening later (after `You can call me Skye if you want, I prefer Daisy`) were the 2nd `not`  _looks_  like should be in italics but isn't on the site either

The above looks like a bug in AO3 and not in FFF, but maybe it can be dealt with in download so that the end result maches the site.

I don't know if that's possible, or even if you are interested in doing it, but since I found it (and I think I figured out why) I figured I might as well open a issue here so that you can at least check it out to see

**Comment by JimmXinu** [comment]
For that first one, there's a CSS rule(in [here](https://archiveofourown.org/stylesheets/skins/skin_1_default/1_site_screen_.css)) that overrides the `<i>` tags.  If you want, you can copy that into your `output_css` settings for AO3 or that specific story.

Other than that, this is the authors' issue.

**Comment by Twilight666** [comment]
1st of all the link is a massive text. Which part should I add
2nd of all, does that mean that it deactivates _all_ italics? In that case is it possible to do it for specific chapters (since the rest of the chapters are fine)

**Comment by JimmXinu** [comment]
Browser Inspection shows this is the CSS line:
```
cite em, em cite, cite i, i cite, i em, em i, em em, i i, cite cite {
  font-style: normal;
}
```
It only effects doubled up `i` or `em`, etc.  This is clearly a work around for exactly this sort of situation.  Because WYSWIG editors in general are kind of crap.

Interestingly, AO3 doesn't include that CSS in their own EPUB download.
