### ISSUE TITLE
Scribblehub shows 'HTTP Error in FFF '403 Client Error: Forbidden for url:'

### ISSUE THREAD

**Issue by Chibba-dev** [JimmXinu/FanFicFare#920]

**Comment by Edocsil** [comment]
That's because it's using cloudfare. There's nothing you can do.

**Comment by JimmXinu** [comment]
Agreed.  I believe one of [Proxy services](https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures) is the only way to use FFF with Scribblehub now.
