### ISSUE TITLE
[Feature Request] Browser Cache Support for ScribbleHub

### ISSUE THREAD

**Issue by dastrdly6585** [JimmXinu/FanFicFare#921]
Given the recent implementation of stronger Cloudflare protection for ScribbleHub (#920), is it possible to utilize the browser cache to get stories from that website?

Currently when attempting to use the browser cache, it appears that FFF fails because the chapter list population is done via a POST request that is returning the 403 error and cannot be cached.  Presumably this request is done because the chapter list on the series page is limited.  However, there appear to be at least two ways to get a complete chapter list displayed in-browser:

1. There is a button to the top right of the chapter list on the series page that reveals all the chapters.
2. Inside each chapter, there is a button that opens a drop-down menu that has a list of all the chapters (similar to FF.net).

**Comment by JimmXinu** [comment]
As you've already noted, the POST req for chapter list isn't cached and therefore can't be gotten through reading browser cache on disk.

But from everything I can tell, both of the buttons you mention also invoke the same POST request.
