### ISSUE TITLE
[Bug] Unknown 'NoneType' object has no attribute 'text' on royalroad.com downloads/updates

### ISSUE THREAD

**Issue by Spy6137** [JimmXinu/FanFicFare#929]
I never had an issue before, but now downloads/updates from royalroad fail and result in Unknown 'NoneType' object has no attribute 'text'.

A scraper issue, perhaps?

Any ideas for what I can do?

**Comment by Edocsil** [comment]
I'm guessing this is a duplicate of #923.

**Comment by JimmXinu** [comment]
Dup of #923.  And #925 and #926. #929
