### ISSUE TITLE
fictionmania.tv returning 'In Progress' status for completed stories

### ISSUE THREAD

**Issue by albyofdoom** [JimmXinu/FanFicFare#931]
I've only recently discovered this site (fictionmania.tv), so I'm not sure how long this issue has been present. This appears to happen with all stories, but I've included a couple of confirmed examples below. 

Examples of stories downloaded with incorrect status:
https://www.fictionmania.tv/stories/readtextstory.html?storyID=29885223281041398
https://www.fictionmania.tv/stories/readtextstory.html?storyID=29762109503333676

I am using FFF v4.21.0, and have no custom settings for this site in personal.ini

**Comment by JimmXinu** [comment]
Test versions up.
