### ISSUE TITLE
Suggestion: Add fanfiction.ws

### ISSUE THREAD

**Issue by lightningHoneypot** [JimmXinu/FanFicFare#934]
Greetings to whom reads this message,

I am planning to move from [FanFictionReader](https://github.com/genious7/FanFictionReade) to this software, because the dev has struggled and hasn't update their app due to Cloudflare screwing up most of the app (and other apps too, something that you guys know already). 

However, there are some fics that are not able to be downloaded to regular means due to them being wiped off of fanfiction.net, one of which is this: [https://www.fanfiction.ws/s/10299022/1/Watching-the-Future-with-Memories](https://www.fanfiction.ws/s/10299022/1/Watching-the-Future-with-Memories)

This fic is dear to me, and as far as I know, the author is not going to revisit that fic again, or even upload them for everyone to see (from the last time I communicated with them, still in their server). When I put in that fanfiction.ws link, FanFicFare does not like to download it from there.

So, is there a way to add support on this website? Or are there any other ways to get that fic? 

(P.S. If you guys could able to do it, help out [genious7](https://github.com/genious7) on solving their Cloudflare issue, it seems that you guys got the Cloudflare thing under control)

**Comment by JimmXinu** [comment]
fanfiction.ws has been brought up before (#747) and I judged the site too unreliable at the time.  

It doesn't look any better now -- it only took 3 clicks from your link to find a [missing chapter](https://www.fanfiction.ws/s/13510603/2/Uzu-s-Resolve).  I don't want to add a site when I'll be having users asking about missing chapters immediately.

I wouldn't say we have CloudFlare solved or under control; we have a couple of kludgey and somewhat fragile work arounds.  

I honestly suggest that new users consider other tools for ffnet downloads like the WebToEpub browser plugin or FanFictionDownloader.

Or, since you are looking for a replacement for a mobile app, ffnet's own app.

**Comment by jcotton42** [comment]
@lightningHoneypot I've used https://fichub.net/ for that site before.

**Comment by lightningHoneypot** [comment]
> @lightningHoneypot I've used https://fichub.net/ for that site before.

Thank you so much @jcotton42, I manage to download the fic from that site! :)

**Comment by lightningHoneypot** [comment]
> fanfiction.ws has been brought up before (#747) and I judged the site too unreliable at the time.
> 
> It doesn't look any better now -- it only took 3 clicks from your link to find a [missing chapter](https://www.fanfiction.ws/s/13510603/2/Uzu-s-Resolve). I don't want to add a site when I'll be having users asking about missing chapters immediately.

I see, thanks for bringing this up. I am a bit recent on this git @JimmXinu. The fic that I am referencing is lucky to have all of the chapters intact, but I can understand why you guys don't want to implement fanfiction.ws as it may not have all of the chapters.


> I wouldn't say we have CloudFlare solved or under control; we have a couple of kludgey and somewhat fragile work arounds.
> 
> I honestly suggest that new users consider other tools for ffnet downloads like the WebToEpub browser plugin or FanFictionDownloader.

Do you know why Fanfiction decided to implement a Cloudflare DDoS checker? It seems to me that it is a bit odd that they decided to implement Cloudflare DDoS recently considering that they have a lot of time to implement it given the history of the site. 

I have use flaresolverr to get around Cloudflare. But as for WebToEpub browser plugin it is simple but lacks the "check for new updates" downloader. And FanFictionDownloader... (man that is a name I haven't heard for a long time since early 2010s) can it do the "check for new updates" too?

> Or, since you are looking for a replacement for a mobile app, ffnet's own app.

That's the thing that I have been avoiding for a long time right now, the app *requires an account*. Since I don't plan to do any fanfic writing at this point, creating an account is just another way for..... collecting data? Or forcing people to create another account. I just hate services that just forces you to create an account, just check the recent examples of today's tech forcing you to create an account just to do simple things.
