### ISSUE TITLE
Question: how to get front cover images

### ISSUE THREAD

**Issue by lightningHoneypot** [JimmXinu/FanFicFare#939]
Sorry for posting this here, but the title says it all.

**Comment by JimmXinu** [comment]
Does the [Cover Images wiki page](https://github.com/JimmXinu/FanFicFare/wiki/Cover-Settings-Calibre-Plugin) address your question?

For questions, as opposed to bug reports, please ask in the [FanFicFare maillist] for the CLI or the MobileRead forum [discussion thread] for the Calibre plugin.

[FanFicFare maillist]: https://groups.google.com/group/fanfic-downloader
[discussion thread]: https://www.mobileread.com/forums/showthread.php?t=259221
