### ISSUE TITLE
[Suggestion] Add an option to download AO3's EPUB format 

### ISSUE THREAD

**Issue by lightningHoneypot** [JimmXinu/FanFicFare#943]
The title says it all, AO3 does has its download links for these different formats when you click on the download button: AZW3, EPUB, MOBI, PDF, and HTML.

What I am suggesting is that have the option to either FanFicFare download the stories into a format like what AO3 outputs as if you are downloading from AO3, or have it fetch the AO3 download link and download it from there. Downloading from AO3 and then putting it into calibre does not give the full metadata.

The differences between FanFicFare and AO3 versions are just slightly different from one another. The only difference is the format of the title page/preface, and _maybe_ the slightly different "page numbers" on the EPUB.

But again, that is a suggestion, if you guys think that it is too redundant or unnecessary, then please disregard this suggestion and close the issue.

Thank you, and I hope you guys can consider what I purpose.

**Comment by JimmXinu** [comment]
This has been suggested before, but I don't see any advantage it.

AO3's epub file is actually more limited than FFF's.  AO3 doesn't include images in the story text or styles or even html attributes for formatting.

If you want, you can download AO3's epubs and still use FFF's 'Update Calibre Metadata Only' to pull metadata with FFF's "Search inside ebooks for Story URL" option checked.

FYI, the FFF AO3 adapter already uses the 'Entire Work' page to download from.

**Comment by lightningHoneypot** [comment]
thanks, have a nice day :)

**Comment by lightningHoneypot** [comment]
Thanks! Have a nice day! :)
> AO3's epub file is actually more limited than FFF's. AO3 doesn't include images in the story text or styles or even html attributes for formatting.

I think I have download a story with images before, both of them show up regardless if you download it via AO3 or FFF.


> If you want, you can download AO3's epubs and still use FFF's 'Update Calibre Metadata Only' to pull metadata with FFF's "Search inside ebooks for Story URL" option checked.
> 
> FYI, the FFF AO3 adapter already uses the 'Entire Work' page to download from.

I see, thank you.

**Comment by JimmXinu** [comment]
I've thought about it, but at best all it does is replace the 'Entire Work' request with a 'download epub' request, which is still coming from the same site.  Perhaps if the AO3 epubs were pre-generated it would help, but internal timestamp shows they are created on demand.

And all the same limitations noted above still apply.
