### ISSUE TITLE
Flaresolverr Windows

### ISSUE THREAD

**Issue by Tornhelm** [JimmXinu/FanFicFare#944]
See this issue on the Flaresolverr repo.

https://github.com/FlareSolverr/FlareSolverr/issues/761

I tested this with a novelfull link.

When using the standalone bundle on Windows, it'll work normally when grabbing the index pages, but as soon as FFF starts scraping the individual chapters, it causes FlareSolverr to create extra chromium processes, pegging the CPU to 100% usage and eventually crashing, with the only way to resolve it being restarting Windows. Posting it here as I'm not sure if the issue is on the Flaresolverr or FFF end of things.

**Comment by Tornhelm** [comment]
Probably should have mentioned OP tested it with a fanfiction.net link, so it isn't specific to a particular host.

**Comment by JimmXinu** [comment]
I'm not seeing this using an ffnet story on Win10 with Flaresolverr 3.1.2 also in Win10(localhost) and FFF's default `slow_down_sleep_time:12` setting.  I only have Microsoft's builtin AV.

What I see is flaresolverr keeping 3 chromium procs open, then surging by 8-9 more when a request is made, then falling back to 3 after the request.

It's possible you may need to set `slow_down_sleep_time` higher than the default `2` seconds for novelfull.

I'm inclined to say it's not FFF.  Have you tried ilike2burnthing's suggestion of disabling AV?
