### ISSUE TITLE
Check to make sure story isn't deleted

### ISSUE THREAD

**Issue by kolbdog3333** [JimmXinu/FanFicFare#945]
Can you make it so it checks urls in your fanficfare library so if the story is deleted by authour it will tell you instead of clicking each story manually to check. Since i have some from fanfiction.net in it as well.

**Comment by JimmXinu** [comment]
If you attempt to update a story that isn't there anymore, you will get an error.  

Assuming you are using the Calibre plugin, you can use the Update/Error Custom column feature towards the bottom of the Custom Column FFF config tab to record the error.

Trying to detect 'removed by author' is especially problematic on ffnet now--the `Story Not Found` page is flagged `no-cache` so it can't been seen at all when using browser cache..
