### ISSUE TITLE
Cannot delete a story

### ISSUE THREAD

**Issue by inanimatexgirl** [JimmXinu/FanFicFare#946]
Using FanFicFare v4.22.1 (on PC Windows 11) to download/update AO3 fics. When I try to delete a fic from Calibre, it gives me an error message - "ERROR: Permission denied".

![image](https://user-images.githubusercontent.com/89869221/234659887-51e7deed-5797-43ab-8ec0-415f420c0f88.png)
Show Details says:
> Traceback (most recent call last):
>   File "calibre\db\backend.py", line 425, in rmtree_with_retry
>   File "shutil.py", line 739, in rmtree
>   File "shutil.py", line 621, in _rmtree_unsafe
>   File "shutil.py", line 619, in _rmtree_unsafe
> PermissionError: [WinError 5] Access is denied: 'C:\\Users\\gryff\\Desktop\\Calibre Library - SW-AD-DR Fanfiction\\.caltrash\\b\\16975'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "calibre\gui2\actions\delete.py", line 459, in do_library_delete
>   File "calibre\gui2\library\models.py", line 462, in delete_books_by_id
>   File "calibre\db\cache.py", line 77, in call_func_with_lock
>   File "calibre\db\cache.py", line 2058, in remove_books
>   File "calibre\db\backend.py", line 2124, in remove_books
>   File "calibre\db\backend.py", line 2024, in move_book_to_trash
>   File "calibre\db\backend.py", line 432, in rmtree_with_retry
>   File "shutil.py", line 739, in rmtree
>   File "shutil.py", line 621, in _rmtree_unsafe
>   File "shutil.py", line 619, in _rmtree_unsafe
> PermissionError: [WinError 5] Access is denied: 'C:\\Users\\gryff\\Desktop\\Calibre Library - SW-AD-DR Fanfiction\\.caltrash\\b\\16975'

I can only delete the story if I change the library (from where the story is originally in) and then delete it manually from the Calibre folder. Then when I return back to the library, it's gone. It wasn't like this before the recent update.

**Comment by JimmXinu** [comment]
That's nothing to do with FanFicFare.  

There's an MR thread recently: [PermissionError: [WinError 5] Access is denied when updating Metadata](https://www.mobileread.com/forums/showthread.php?t=353570).  Kovid says anti-virus interference, some others mention other esoteric Windows issues.  

Regardless, I can't help you with it.

**Comment by JimmXinu** [comment]
You might quote your error trace into the MR thread--it's a bit different than the one that's there, referring to `.caltrash`.
