### ISSUE TITLE
NoneType error with AO3 after needing login

### ISSUE THREAD

**Issue by Lagicrus** [JimmXinu/FanFicFare#948]
When AO3 prompts for login, the first linked AO3 story fails, whilst the rest pass.
The first linked will fail with `'NoneType' object has no attribute 'get_text'`, and the rest will be fine.
This was tested by moving the second linked story which passed to the top of the input list, and causing the prompt to occur on that story instead of the second. Causing the second (now first) to fail, but allowing the first (now second) to pass

**Comment by JimmXinu** [comment]
Story URLs?  I don't know any login AO3 stories off hand.

**Comment by Lagicrus** [comment]
`https://archiveofourown.org/works/18862240` and `https://archiveofourown.org/works/15684198`, two random ones I just found on AO3 with the search

**Comment by JimmXinu** [comment]
I'm not seeing it happen.  

Which version of FFF are you using (CLI or plugin and version number)?

Do you have `username`/`password` in personal.ini?  `always_login:true`?

Can you run in debug mode and capture the debug log?
