### ISSUE TITLE
Book updates based on last chapter url

### ISSUE THREAD

**Issue by mightyheretic** [JimmXinu/FanFicFare#949]
I love FanFicFare it has been great for archiving my favorite stories that might otherwise disappear.  I have however noticed that many titles on royalroad will not update because of bad updates.  I presume that is because the authors remove old chapters which throws off the chapter count with FanFicFare.  Would it be possible to store the url for the last chapter with the ebook such that FanFicFare can just attempt to resume where it was last updated from in order to just append the new chapters to the pre-existing ebook without getting the full ebook and then merging which seems like a lot of server calls for very large web novels.

**Comment by JimmXinu** [comment]
Short answer is no.  You can use 'Update Always' mode to get new chapters and discard deleted chapters.

Somebody asked something similar last week in #942.  Part of my response was:

> FFF's fundamental paradigm doesn't have a way to keep chapters that aren't in the TOC.

> A nontechnical issue is the FanFicFare is meant for fanfiction. If an author has removed their content to make money on it, I'm not interested in helping work around that.
