### ISSUE TITLE
Make epubs with  images

### ISSUE THREAD

**Issue by PHBN2021** [JimmXinu/FanFicFare#951]
Could you make so fanfics with images like of AO3 or Wattpad have images on their epubs?

**Comment by JimmXinu** [comment]
FanFicFare can already do that, but it's off by default in the CLI for historical reasons.

Add to your `personal.ini` under section `[epub]`:
`include_images:true`

In the Calibre plugin version of FFF, that setting is on by default.

Be aware that some image sites require additional special settings (see [here](https://github.com/JimmXinu/FanFicFare/issues/941#issuecomment-1527686407)) and some are hosted in such a way that FFF cannot download them at all.  I would need to see story URLs to comment specifically.
