### ISSUE TITLE
Change wuxiaworld.co to wuxiaworld.xyz?

### ISSUE THREAD

**Issue by buzzbros2002** [JimmXinu/FanFicFare#953]
Wuxiaworld.co redirects to wuxiaworld.xyz. Also maybe wuxiaworld.eu?

**Comment by JimmXinu** [comment]
I don't read this site, so I don't have a stable of unusual stories to test with.  Let me know if there are problems.

Also fixes `adapter_novelupdatescc` which shares code.

FYI, wuxiaworld.eu does not redirect to wuxiaworld.xyz

[Test versions in the usual places.](https://github.com/JimmXinu/FanFicFare#test-versions)

**Comment by JimmXinu** [comment]
Assumed fixed.
