### ISSUE TITLE
None of the fics are either updating or downloading. please help

### ISSUE THREAD

**Issue by randomgithubber87** [JimmXinu/FanFicFare#954]
Hey,

I have tried updating and downloading fics, but get forbidden 403 error every time and nothing works.... i am beyond frustrated.

please help... here is my log:

`Status Title Author Comment URL Error Harry gets Motivated BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3427377/1/'(403) https://www.fanfiction.net/s/3427377/1/ Bad URL Bits and Pieces a collection of sorts BajaB URL is not a valid story URL. http://:/ Bad URL Dark Marauder BajaB URL is not a valid story URL. http://:/ Error Death Eater BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2769927/1/'(403) https://www.fanfiction.net/s/2769927/1/ Error Death of a Nobody BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/4106581/1/'(403) https://www.fanfiction.net/s/4106581/1/ Error First Task BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3421497/1/'(403) https://www.fanfiction.net/s/3421497/1/ Error Dudders' Adventure BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2766206/1/'(403) https://www.fanfiction.net/s/2766206/1/ Error Fair Trade BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/4818951/1/'(403) https://www.fanfiction.net/s/4818951/1/ Error Forgotten BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2930853/1/'(403) https://www.fanfiction.net/s/2930853/1/ Bad URL Fugitives of Azkaban BajaB URL is not a valid story URL. http://:/ Error For Love of Hate BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/6363333/1/'(403) https://www.fanfiction.net/s/6363333/1/ Error Grawp's Big Tale BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3048204/1/'(403) https://www.fanfiction.net/s/3048204/1/ Add Harry gets Motivated BajaB Same story already included. https://www.fanfiction.net/s/3427377/1/ Error Harry the Hufflepuff BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/6466185/1/'(403) https://www.fanfiction.net/s/6466185/1/ Error Harry Potter and the Mary Sue BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2767791/1/'(403) https://www.fanfiction.net/s/2767791/1/ Error Harry the Hufflepuff 2 BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/7330591/1/'(403) https://www.fanfiction.net/s/7330591/1/ Error Harry the Hufflepuff 3 - Harry's Year off BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/10843543/1/'(403) https://www.fanfiction.net/s/10843543/1/ Error Harry The HufflePuff 4 BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/12863701/1/'(403) https://www.fanfiction.net/s/12863701/1/ Error Helpful Hints for First Years BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3170097/1/'(403) https://www.fanfiction.net/s/3170097/1/ Error Homework Excuses BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2970377/1/'(403) https://www.fanfiction.net/s/2970377/1/ Error Last Day BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/4611189/1/'(403) https://www.fanfiction.net/s/4611189/1/ Error Magic is useless BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/4414284/1/'(403) https://www.fanfiction.net/s/4414284/1/ Error Mistaken Identity BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/4554301/1/'(403) https://www.fanfiction.net/s/4554301/1/ Error Not Noteworthy BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/4439933/1/'(403) https://www.fanfiction.net/s/4439933/1/ Error Position Vacant 1 The DADA Interviews BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2747474/1/'(403) https://www.fanfiction.net/s/2747474/1/ Error Position Vacant 2 The First Day BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2759860/1/'(403) https://www.fanfiction.net/s/2759860/1/ Error Relive BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3430006/1/'(403) https://www.fanfiction.net/s/3430006/1/ Error Secrets of Severus BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3121102/1/'(403) https://www.fanfiction.net/s/3121102/1/ Error Sweet Dream Sweets BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3015951/1/'(403) https://www.fanfiction.net/s/3015951/1/ Error The Greatest Minister of Magic BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/4487319/1/'(403) https://www.fanfiction.net/s/4487319/1/ Bad URL The Memory Chest BajaB URL is not a valid story URL. http://:/ Error The Phoenixandrsquo;s Choice BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3237834/1/'(403) https://www.fanfiction.net/s/3237834/1/ Error The Price of Knowledge BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3209463/1/'(403) https://www.fanfiction.net/s/3209463/1/ Error The Return BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2761695/1/'(403) https://www.fanfiction.net/s/2761695/1/ Error The Substitute BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/4641394/1/'(403) https://www.fanfiction.net/s/4641394/1/ Bad URL The Substitute Omakes, Epilogues, and Alt Endings BajaB URL is not a valid story URL. http://:/ Not Found Two Weeks in the Alley BajaB No story URL found. Error Weasley's Wearables BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2739228/1/'(403) https://www.fanfiction.net/s/2739228/1/ Bad URL Veritas Oracle BajaB URL is not a valid story URL. http://:/ Error WunderWand BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2792057/1/'(403) https://www.fanfiction.net/s/2792057/1/ Error A Robbery to remember BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2769327/1/'(403) https://www.fanfiction.net/s/2769327/1/ Error Almost a Squib BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/3885086/1/'(403) https://www.fanfiction.net/s/3885086/1/ Error A new Fountain of Magical Brethren BajaB HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/2740718/1/'(403) https://www.fanfiction.net/s/2740718/1/`

**Comment by randomgithubber87** [comment]
instead of updating, I tried to simply download a new fic using url. got this error:

url is: [https://www.fanfiction.net/s/13833982/1/Fixing-the-Wizarding-World](https://www.fanfiction.net/s/13833982/1/Fixing-the-Wizarding-World)

`
Status
Title
Author
Comment
URL
Error
Unknown
Unknown
HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/13833982/1/Fixing-the-Wizarding-World'(403)
https://www.fanfiction.net/s/13833982/1/Fixing-the-Wizarding-World
`

**Comment by mhussaincov93** [comment]
make sure in personal.ini,

you have the folowing enabled.



use_browser_cache:true
use_browser_cache_only:true
open_pages_in_browser:true

**Comment by JimmXinu** [comment]
This has been happening to most of us for a few years now.  

FAQ: [Why am I having errors downloading from fanfiction.net? / Why am I getting 'Cloudflare' errors downloading from fanfiction.net?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-am-i-having-errors-downloading-from-fanfictionnet--why-am-i-getting-cloudflare-errors-downloading-from-fanfictionnet).  

The two workarounds the FAQ mention are:
[BrowserCacheFeature](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature)
[ProxyFeatures](https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures)

To use mhussaincov93's suggestion, you also need a `browser_cache_path` setting pointing to your default browser's cache directory.  See the [BrowserCacheFeature](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature) page.

Also see FAQ: [Why shouldn't I just select my entire library and use FanFicFare plugin to check for updates?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-shouldnt-i-just-select-my-entire-library-and-use-fanficfare-plugin-to-check-for-updates)
