### ISSUE TITLE
[Enhancement] 'Add to existing value' in Custom Column tab

### ISSUE THREAD

**Issue by chocolatechipcats** [JimmXinu/FanFicFare#955]
Currently, using the Custom Columns tab to assign an entry seems to use the default 'replace'.

Enhancement: For consistency and also because it would be helpful, have an additional 'Add' checkbox that instead appends it similar to the custom_column_settings flag. Ideally this would only be available for tag-like columns.

Thank you.

**Comment by JimmXinu** [comment]
Already exists as `personal.ini` settings, I don't see a lot of value in making it GUI.
