### ISSUE TITLE
Some stories on ao3 don't save the chapter end notes.

### ISSUE THREAD

**Issue by HowardJeng** [JimmXinu/FanFicFare#956]
FanFicFare 4.23.0 Calibre plugin. 

Today I updated a few stories on ao3 with "Overwrite if Newer" and the chapter end notes are missing. For example, the downloaded epubs for these URLs are missing the chapter end notes:
https://archiveofourown.org/works/47055061
https://archiveofourown.org/works/24231487
https://archiveofourown.org/works/25256101
https://archiveofourown.org/works/46947646

One story I updated today, did save the chapter end notes, however:
https://archiveofourown.org/works/23723560

**Comment by JimmXinu** [comment]
Looks like they tweaked the HTML slightly to remove a `role` attribute on chapter end notes.  

Test versions in the [usual places](https://github.com/JimmXinu/FanFicFare#test-versions).
