### ISSUE TITLE
[Enhancement] Add support for https://re-library.com/

### ISSUE THREAD

**Issue by KridOCaign** [JimmXinu/FanFicFare#957]
https://re-library.com/ is not currently supported.

**Comment by TheOne320** [comment]
Is there any progress on this? I read a lot on there and I dislike the site layout and want to read on my Kindle.

**Comment by JimmXinu** [comment]
Site is not fanfiction and according to their [recruitment page](https://re-library.com/recruitment/) their are paid for views.

While I'm not planning to take away currently supported sites, I'm not currently adding new sites where it may take money away from authors.
