### ISSUE TITLE
How to add new sites on fanficfare to supoort?

### ISSUE THREAD

**Issue by PHBN2021** [JimmXinu/FanFicFare#965]

**Comment by JimmXinu** [comment]
From #885:
> There isn't a guide or document. Probably best is to start with an adapter for a similar site, if there is one in [adapters](https://github.com/JimmXinu/FanFicFare/tree/main/fanficfare/adapters).
> 
> I'd also look at past PRs for new sites, such as #801.

Here's another relevant quote from #[440](https://github.com/JimmXinu/FanFicFare/issues/440#issuecomment-545589619):
> FYI: I'm personally not interested in adding new sites these days. Nor have other developers been very active lately.
> 
> I'm also not convinced that all of these translation sites should be in FanFicFare at all. I haven't made a detailed study of the legalities, but I worry about the copyright issues of distributing translations of works from other languages. Looking into it again briefly, it looks like it's mostly a matter of the Chinese/other source copyright holders not knowing or not caring about enforcement.
> 
> That said, I have [rejected](https://github.com/JimmXinu/FanFicFare/issues/221) [some](https://github.com/JimmXinu/FanFicFare/issues/223) [sites](https://github.com/JimmXinu/FanFicFare/issues/359) before for hosting content I'm reasonably sure should be considered copyrighted in my country, at least.
> 
> If someone wants to contribute code to add a new site, I'm usually happy to accept it. But I reserve the right to reject (or even remove after inclusion) support for sites that might cause me problems.
