### ISSUE TITLE
[Feature Request] Update Epub with New Chapters when Some Old Chapters have been Removed

### ISSUE THREAD

**Issue by deepbhattacharya** [JimmXinu/FanFicFare#968]
A lot of original content authors are removing their initial chapters of a story from the public site once they move to Kindle (as an example). As a result you suddenly chapter 80 follow chapter1, like this: https://www.royalroad.com/fiction/20568

An existing epub of this story (from before when the chapters were nuked can't be updated anymore, only overwritten - which will remove those missing chapters.

Can we have:

(1) an option to match the last retrieved chapter in the ebook and retrieve only the newer chapters
(2) or an option to manually edit the epub with Sigil or a similar tool to mark those nuked chapters somehow so FFF will ignore them for the purposes of chapter count etc, and keep them as-is when adding new chapters?

**Comment by JimmXinu** [comment]
Prior issue #950 covers the same topic.
