### ISSUE TITLE
Add the Option to automatically create a Table of contents file

### ISSUE THREAD

**Issue by Tjerbor** [JimmXinu/FanFicFare#970]
Hello, I would like to request the option to automatically have Fanficefare create a Table of Contents within the Ebook. So far there already is a table of contents but not as its own page. I have to always add them myself to the ebooks.
The reason why I'm asking is because of the nature of web novels and how big they can become. So to have a page where all the chapters are sorted in chronological order with a direct link to them would be very helpful.
The best place for that HTML file would be after the title or cover page IMO.
![grafik](https://github.com/JimmXinu/FanFicFare/assets/44727916/3e627885-7f88-4e97-a8c0-f03452fb2c8d)
![grafik](https://github.com/JimmXinu/FanFicFare/assets/44727916/4cbcd017-47c7-44fb-8200-8a244ff90b7b)

**Comment by JimmXinu** [comment]
FFF has always had that--it's just off by default for EPUBs.  

In `personal.ini`, add `include_tocpage: true` under `[epub]`.
```
[epub]
include_tocpage: true
```

**Comment by Tjerbor** [comment]
Okay thank you, sorry for bothering you.
