### ISSUE TITLE
Fanfiction.net 403 Forbidden Error

### ISSUE THREAD

**Issue by Shanakthra** [JimmXinu/FanFicFare#971]
Hi JimmXinu

Tried to download and make an epub of Harry Potter: Honour thy blood on URL: 
https://www.fanfiction.net/s/13290222/1/Honour-Thy-Blood-Remastered
from fanfiction.net

Saw it was in your supported sites, but the Calibre plugin gave a '403 Client Error: Forbidden for URL' for the above URL

Please advise and assist. 

The below is a copy of the log

Status
Title
Author
Comment
URL
Error
Unknown
Unknown
HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fanfiction.net/s/13290222/1/Honour-Thy-Blood-Remastered'(403)
https://www.fanfiction.net/s/13290222/1/Honour-Thy-Blood-Remastered

**Comment by jcotton42** [comment]
Make sure you've set up the browser cache feature https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature and try again.

**Comment by Shanakthra** [comment]
Thanks, just tested and working great. 

Is it possible to add this information to the supported sites page so that future users know how to use fanfiction.net with FFF?

Thanks a ton again for this amazing piece of software

**Comment by JimmXinu** [comment]
[Limited Support Sites](https://github.com/JimmXinu/FanFicFare/wiki/SupportedSites#limited-support-sites) section added to wiki page.
