### ISSUE TITLE
Works less and less often with ffn, producing 'chapter errors'

### ISSUE THREAD

**Issue by Batchman17** [JimmXinu/FanFicFare#972]
Don't know what is going on. A month ago, one story out of every few I tried to download from ffn didn't work because it said it picked up chapter errors in one chapter. A couple of weeks ago, it was more like 1 out of every 2. Today it is every story I have tried to download from ffn so far.

I'm doing the same thing I've done ever since problems started with ffn a year or two ago ... right before I try to download, I view every chapter in my web browser, so they are all in memory, so it doesn't have to try and get them from the actual site, but it still comes up with chapter errors.

**Comment by JimmXinu** [comment]
Honestly, getting ffnet to work has become a bit hit or miss and varies by individual.  All I can really do is give you some general advice.

The problem I see the most is that the site has a bad habit of sending out notification emails before the new chapters are fully propagated to their servers.  I routinely have to wait an hour or two before all the new metadata (word count, updated date, new chapter) shows up on all chapters.

Also see the existing documentation:
- [Why am I having errors downloading from fanfiction.net?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-am-i-having-errors-downloading-from-fanfictionnet--why-am-i-getting-cloudflare-errors-downloading-from-fanfictionnet)
- [I've followed all the instructions in Browser Cache Feature and it isn't working / I'm getting errors--help? 
](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#ive-followed-all-the-instructions-in-browser-cache-feature-and-it-isnt-working--im-getting-errors--help)
- [Browser Cache Feature](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature)

**Comment by Batchman17** [comment]
The timing issue isn't involved, because I tend to save up 7 or 8 stories that have been completed, then do them all (one at a time) at once, every two or three weeks. So I'm not trying to do them minutes or hours after they are posted, but days and weeks.

You produced a tool that I quite love, it just mildly sucks that ffn puts so much work into trying to prevent it from working! Anyway, don't know if I have ever said it before, so wanted to say thank you for the tool! Even if it works less and less often on ffn, it does the job without problems on all the other sites I visit!

Will double-check the cache documentation to see if I am missing anything.

**Comment by chocolatechipcats** [comment]
If you haven't done this already, it might be worth checking whether your stories are cross-posted on other sites. If they are, you can just change the link in the Calibre identifiers field and it should work -- assuming that the number of chapters isn't different for whatever reason.

**Comment by JimmXinu** [comment]
No further follow up.
