### ISSUE TITLE
how to make the calibre plugin not ask for adult confirmation?

### ISSUE THREAD

**Issue by rezad1393** [JimmXinu/FanFicFare#974]
how can I make the calibre plugin not ask for adult confirmation everytime?

**Comment by JimmXinu** [comment]
FAQ: [How can I keep FanFicFare from asking me if I am an adult all the time?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#how-can-i-keep-fanficfare-from-asking-me-if-i-am-an-adult-all-the-time)
