### ISSUE TITLE
A03 HTTP Error

### ISSUE THREAD

**Issue by thatguy4114** [JimmXinu/FanFicFare#976]
I'm getting -HTTP Error in FFF '403 Client Error: Forbidden for url: "random fic"- whenever I try to update or download anything, probably cause of the recent issue's that happened :(

**Comment by Edocsil** [comment]
https://github.com/JimmXinu/FanFicFare/issues/975

They have enabled cloudfare protection.

You should always check if there's an issue already open before creating a new one.

**Comment by JimmXinu** [comment]
#975 dup
