### ISSUE TITLE
FanFicFare doesn't recognize chapters in existing epub

### ISSUE THREAD

**Issue by klreeher** [JimmXinu/FanFicFare#983]
I've run into this a few times when importing a previously established Calibre library to a new install of Calibre. When I set up the FanficFare Calibre plugin and check for updates to a fic that was downloaded (using fanficfare) on the previous install of Calibre, I get that there is an update to the fic, but that FanFicFare cannot download it. The log message shows

```FanFicFare doesn't recognize chapters in existing epub, epub is probably from a different source. Use Overwrite to force update.```

I've played around with the "always update" settings, but none of them appear to be the force update setting referenced here. Is this a CLI only option? If not, how can I configure FanFicFare Calibre Plugin to update the epub regardless?

**Comment by JimmXinu** [comment]
I'd have to see one of these epubs, but I suspect you modified them with some other tool that changed the structure or internal file names.  

The obvious answer is do what it says and use `Overwrite Always` mode for those.
