### ISSUE TITLE
Lush story URL doesn't work

### ISSUE THREAD

**Issue by Aces-and-Jacks** [JimmXinu/FanFicFare#988]
I tried it with a random story to test but the URL doesn't work. And since the website is on the list of supported sites I figured it'd be fine to ask about it

**Comment by JimmXinu** [comment]
My notes show that site last working about a year ago due to major site redesign/replacement.  I didn't look into any deeper because no one was complaining.  I'll look into it more next week.

**Comment by JimmXinu** [comment]
This site doesn't even have a category for fanfiction anymore.  It appears to be all original fiction.  And authors can upload ebooks if they want?

All in all, I'm not terribly interested in fixing it myself.

**Comment by Aces-and-Jacks** [comment]
ok then. So would this issue be closed as not planned?
