### ISSUE TITLE
scribblehub example url not working

### ISSUE THREAD

**Issue by FireDemon290304** [JimmXinu/FanFicFare#989]
Tried to add a scribblehub.com story, but none of the URLs I tried worked, even the example URL didn't work

403 error:
"line 149, in request
    raise exceptions.HTTPErrorFFF(
fanficfare.exceptions.HTTPErrorFFF: HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.scribblehub.com/series/133207/wait-theres-another-wayne/'(403)"

**Comment by Edocsil** [comment]
"403 Client Error: Forbidden" this means you're not allowed to see the
page, if you can see it on a browser without problems then it usually means
fanficfare is being blocked by cloudfare. There's nothing you can do.

**Comment by JimmXinu** [comment]
Cloudflare.  See [prior scribblehub issues](https://github.com/JimmXinu/FanFicFare/issues?q=is%3Aissue+scribblehub).
