### ISSUE TITLE
forums.spacebattles.com returns (403) error

### ISSUE THREAD

**Issue by mokunonet** [JimmXinu/FanFicFare#991]
attempting to download stories from forums.spacebattles.com results in the following error message:

> HTTP Error in FFF '403 Client Error: Forbidden for url: https://forums.spacebattles.com/login'(403)

tested on:
-Win10Pro v 22H2
-calibre 6.25
-FanFicFare v4.26.0

**Comment by idiotcommerce** [comment]
i think it is downloading for me. 
https://forums.spacebattles.com/threads/psa-fanficfare-can-download-stories-on-sb-sv-for-offline-reading.350081/
![image](https://github.com/JimmXinu/FanFicFare/assets/121589808/0f280a30-690c-4e7c-a40c-3b8c240e39b7)
then i reached here

![image](https://github.com/JimmXinu/FanFicFare/assets/121589808/fdeaf009-a63c-4a5a-aef5-ec00557b110b)

then this page i reached 
![image](https://github.com/JimmXinu/FanFicFare/assets/121589808/8546c49f-d26f-4559-967a-378805db2659)

i clicked this it is downloading

**Comment by mokunonet** [comment]
there must be something strange with my local config, I tried that and got this instead:
`
Status
`
`
Title
`
`
Author
`
`
Comment
`
`
URL
`
`
Error
`
`
Unknown
`
`
Unknown
`
`
HTTP Error in FFF '403 Client Error: Forbidden for url: https://forums.spacebattles.com/login'(403)
`
`
https://forums.spacebattles.com/threads/psa-fanficfare-can-download-stories-on-sb-sv-for-offline-reading.350081/
`

**Comment by JimmXinu** [comment]
I'm not seeing any problems with SB using a similar set up.

FFF will only try to login on SB for member-only stories or if you have `always_login:true`.  If you have a bad user/pass, you should be prompted to enter user/pass.

With a 403 error, I suspect you are using a VPN that doesn't work correctly, or being blocked by the site.

**Comment by idiotcommerce** [comment]
i did not even login. i just searched on google with yout provided site and tried. i share the images.

**Comment by JimmXinu** [comment]
I was answering @mokunonet.

**Comment by mokunonet** [comment]
I didn't even consider turning VPN off b/c I had no problem getting to the site via browser, that fixed it.

thank you so much

**Comment by mokunonet** [comment]
P.S. if you are willing, I'd be really curious to know why the VPN caused trouble for FFF but not via browser

**Comment by idiotcommerce** [comment]
@mokunonet sorry for mis understanding. thank you

**Comment by JimmXinu** [comment]
I don't know for sure--it's happened many times now, but nobody ever mentions what VPN they are using--at least not that I remember.

I speculate that you are using something I would not consider a 'real' VPN.

A real VPN does network address translation and should be completely invisible to everything in the OS above the network level.  Ideally, it should happen in the networking hardware, like routers.

I believe some things like browser plugins, etc call themselves VPNs while really being web proxies or just hijacking web requests in the browser.  These do not appear to be complete implementations in many cases, especially not working correctly with HTTP POST requests.

**Comment by mokunonet** [comment]
I use surfshark, it has some options which implement how you're describing, but I thought I had those off. It appears as a separate ethernet adaptor under "Network Connections" if that means anything?

**Comment by idiotcommerce** [comment]
bro , i am not that as you talented. i did not use any vpt till now. because of any malware or insecurity. normally websites are running. my self i created 3 websites using wordpress. and some plugines and used tmd hosting. but u coded entire website it is very herd for me
