### ISSUE TITLE
Storiesonline.net getting words as html tags when it this tool saves textContent in xhtml files.

### ISSUE THREAD

**Issue by confident-hate** [JimmXinu/FanFicFare#996]
Hello,
I just want to point out a little bug.
When this tool parse text from storiesonline(on some chapters), it inserts non-html tags as html, which leads it to display error in epub file.

Website URL:
https://storiesonline.net/s/57098:79310/deja-vu-ascendancy-chapter-2

Error text:
`This page contains the following errors:
error on line 43 at column 40: error parsing attribute name
Below is a rendering of the page up to the first error.`

Error image:
![ScreenshotMiXplorer](https://github.com/JimmXinu/FanFicFare/assets/66160911/7cb2cca9-14f5-4088-8a83-9e73fae8aff7)

xhtml file image with words as html tags:
![Screenshot_MiXplorer](https://github.com/JimmXinu/FanFicFare/assets/66160911/24222b79-eefc-4861-bb23-be3e526efe7b)

**Comment by JimmXinu** [comment]
You'd have to take that up with the author.  That's in the source material HTML:

```<p>I followed up on the mouthless <What?> that I'd 'heard' back at the beginning, ...</p>```

Although the closing `</what?>` was added by the HTML parser.  It assumes tags it doesn't know need matching close tags.

Personally, I would just edit the epub manually.  I don't plan to add special code for this source error.
