### ISSUE TITLE
Very Large Images Not Being Resized to Max Image Size

### ISSUE THREAD

**Issue by dastrdly6585** [JimmXinu/FanFicFare#997]
The following book has in many of its chapters included very large resolution images:
[https://www.royalroad.com/fiction/51893/the-heart-grows](https://www.royalroad.com/fiction/51893/the-heart-grows)

There seems to be a problem, however, where the largest of these images are not being resized as specified by the `image_max_size` setting.  The current max size I've set is 3000 x 3000.  For images which are only slightly larger than the max size (4000+ pixel dimensions), I'm seeing that they are correctly resized preserving their aspect ratio.  For the largest images (6000+ pixel dimensions), however, it looks like no resizing is done and they are inserted into the epub at their original resolution.

**Comment by JimmXinu** [comment]
That story has 100+ chapters.  Can you narrow it down to some specific chapters?

**Comment by dastrdly6585** [comment]
I believe at least chapters 85-105 all have one or two images at the end of them which are not getting resized properly.

**Comment by JimmXinu** [comment]
I see the same thing in chapter 105 I did in 85.  4 large images, all resized as expected.

**Comment by dastrdly6585** [comment]
Plugin version of FFF on Windows 10.  I just attempted a fresh download of the story after deleting the epub entirely, and once again images with the highest resolution are not being resized.  Here is the debug output:
[FFF-debug_Large-Images.txt](https://github.com/JimmXinu/FanFicFare/files/12516873/FFF-debug_Large-Images.txt)

In the epub output from this, Chapter 105 has four images, two of which were not resized (the first and third image in the chapter).

**Comment by JimmXinu** [comment]
I don't see anything unusual in the debug output.  If image conversion fails, FFF logs it and doesn't include the image.  I added `never_make_cover:true` to make my setup match yours more, but it made no difference.

What version of Calibre are you using?  Are you sure you don't have `no_image_processing:true` set somewhere?  And that `image_max_size` is set to what you think it is?  

It might help if I see the 'safe' version of your personal.ini.

**Comment by dastrdly6585** [comment]
I'm using Calibre 6.25 and I am sure that `no_image_processing` has not been set to true.  Here is my safe version of the personal.ini:

[safe_personal.txt](https://github.com/JimmXinu/FanFicFare/files/12516989/safe_personal.txt)

**Comment by dastrdly6585** [comment]
Update: I just tried the latest CLI version and it looks like it resized all the images correctly for the test chapter (Chapter 105).  Whatever is causing the largest images to not be resized correctly seems to be limited either to the plugin or Calibre version.

**Comment by JimmXinu** [comment]
I know what's going on now.  It's both Calibre specific and requires `never_make_cover:true`--for this story, at least.

### 0x0 Image?
FanFicFare plugin calls Calibre's `calibre.utils.img.image_and_format_from_data()` to get the size of images for `image_max_size`.  For the images in question, it's returning 0x0, which FFF is accepting as less than max size.

When calling that code directly (using `calibre-debug -e`) I get the same 0x0 but with a further error printout: 
`qt.gui.imageio: QImageIOHandler: Rejecting image as it exceeds the current allocation limit of 128 megabytes`

### Exceeds Limit??
But the 8904x6651 image is >9MB?  And a 12MB 6000x4000 picture jpg does *not* cause it to happen.  So I speculate it's the size of the internal uncompressed image buffer, not the size of the file. 

Yep.  [This doc](https://doc.qt.io/qt-6/qimagereader.html#setAllocationLimit) says 32bit per pixel, so the default 128MB is good up to 32 megapixel images; and 8904x6651 needs > 226MB.

### Raise the Limit?
Googling finds other apps/users having the same issue.  This [stackoverflow](https://stackoverflow.com/questions/71458968/pyqt6-how-to-set-allocation-limit-in-qimagereader) has a work around setting environment variable `QT_IMAGEIO_MAXALLOC` to a larger value.  Others involve explicitly calling [setAllocationLimit](https://doc.qt.io/qt-6/qimagereader.html#setAllocationLimit).

`QT_IMAGEIO_MAXALLOC` works for me, both set before running and using `os.environ` in code.

### But Why Only With `never_make_cover:true`?
I speculate that getting the size for the set cover image (the-heart-grows-aadawryoire.jpg in this case) 'primes' the image system somehow.  But I can't make it work in minimalist testing using `calibre-debug -e`.

### Immediate Solutions - What can be done without code changes:
#### Don't use `never_make_cover:true` 
*Seems* to work, but I don't know *why*.  And other stories without a specific cover may still have the same problem.  Setting a `default_cover_image` or `force_cover_image` doesn't have the same affect.  Cannot recommend as a general solution.

#### Set environment variable `QT_IMAGEIO_MAXALLOC` to a larger value.
The pros and cons for this are the same: 
1. You get to / have to set it in your environment yourself, and; 
2. You get to / have to decide what value to set yourself.  Image X * Y * 32 / 8 = necessary megabytes.

### What to Change?
What should be changed in FFF to address this?  (This section is more for me to look at tomorrow.)
1. Should recognize 0x0 as 'failed to parse image' and report it.  
    1. But should it be a 'leave out the image' failure?  
    1. Currently, as long as it's named a jpg, it will included as is (mostly).  
    1. Make an optional setting?
1. Should the environment variable `QT_IMAGEIO_MAXALLOC` be settable from FFF's personal.ini?  
    1. Offends my sense of code propriety.
    1. Would be much easier for users.
    1. Would save explaining as much to users.
1. Figure out what Calibre does and copy it--see below.

### Report as a Calibre Issue?
I don't think this should be reported as an issue in Calibre--it's a limitation of the underlying library.  

I should, however, spend a bit more time looking at how Calibre itself handles large images as it's perfectly happy getting oversized images given as covers and silently resizes them without issue.

**Comment by dastrdly6585** [comment]
I think I've worked out the specific chain for why getting the cover primes the image system so that it has a higher allocation limit:

1. When FFF gets the cover image, it calls `check_cover_min_size` ([src](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/story.py#L1692))
2. In this function it calls `get_image_size` ([src](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/story.py#L64))
3. This in turn calls Calibre's `image_from_data` ([src](https://github.com/kovidgoyal/calibre/blob/master/src/calibre/utils/img.py#L124))
4. You then have a call to `set_image_allocation_limit` ([src](https://github.com/kovidgoyal/calibre/blob/master/src/calibre/utils/img.py#L111)) with no arguments which sets the the allocation limit to _1024 MB_ via `setAllocationLimit` in `QProgressIndicator` ([src](https://github.com/kovidgoyal/calibre/blob/master/src/calibre/gui2/progress_indicator/QProgressIndicator.cpp#L128))

Perhaps the general fix would be to have an explicit call to `set_image_allocation_limit` at the start of image processing of any kind.  The question then would be whether to give users the option to set it or just use Calibre's 1024 MB (as far as I can tell Calibre's front-end doesn't give you the option to actually change this).

**Comment by JimmXinu** [comment]
I think you're exactly right.  

It does raise the question of why it isn't already applied when Calibre sets it, but adding an explicit call to `set_image_allocation_limit()` fixes it.  1024MB is enough for 256 megapixels.  

I'll add that call somewhere, but I also want to at least log the 0x0 if it happens.
