### ISSUE TITLE
Dead/Defunct Site: noveltrove.com

### ISSUE THREAD

**Issue by albyofdoom** [JimmXinu/FanFicFare#998]
Per the site forum [here](https://noveltrove.com/t/4145), the owner of the site has been missing/non-responsive since June 2020, and links to stories broke sometime in 2021.

**Comment by JimmXinu** [comment]
Yeah, I tend to give broken sites a year or before removing them.  I've seen sites resurrected after removing them before.
My test library shows last successful download there May 03 2022.

This one's probably had long enough.
